import type { Cafe } from '@/types';
import { calculateScore } from './scoring';

const rawCafes: Omit<Cafe, 'id' | 'created_at' | 'third_wave_score' | 'overall_rating' | 'review_count' | 'permanently_closed'>[] = [
  // TOKYO (3 cafes)
  {
    name: "Fuglen Tokyo",
    slug: "fuglen-tokyo",
    lat: 35.6696,
    lng: 139.6916,
    city: "Tokyo",
    country: "Japan",
    address: "1-16-11 Tomigaya, Shibuya-ku, Tokyo",
    roaster: "Fuglen Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "no-laptop"],
    google_place_id: "ChIJN1-WT_KLGGARzMPs8sI9WBc",
    instagram_handle: "fuglentokyo",
    website: "https://www.fuglen.com/",
    editorial_blurb: "Oslo's cult café landed in Tokyo and raised the bar for the entire city — order the pour-over and stay for the vintage furniture.",
    featured_in: ["sprudge", "monocle"],
    verified: true,
    last_verified_at: "2024-11-01",
    verification_source: "admin",
  },
  {
    name: "Koffee Mameya",
    slug: "koffee-mameya",
    lat: 35.6654,
    lng: 139.7104,
    city: "Tokyo",
    country: "Japan",
    address: "4-15-3 Jingumae, Shibuya-ku, Tokyo",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso"],
    vibe_tags: ["standing-bar", "minimalist"],
    instagram_handle: "koffee_mameya",
    website: "https://koffee-mameya.com/",
    editorial_blurb: "No menu, no seating — just a barista asking what you want and delivering the precise cup you didn't know you needed.",
    featured_in: ["sprudge", "ny_times"],
    verified: true,
    last_verified_at: "2024-10-15",
    verification_source: "admin",
  },
  {
    name: "Switch Coffee Tokyo",
    slug: "switch-coffee-tokyo",
    lat: 35.6952,
    lng: 139.7049,
    city: "Tokyo",
    country: "Japan",
    address: "Minami-Aoyama 6-6-22, Minato-ku, Tokyo",
    roaster: "Switch Coffee",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "switchcoffeetokyo",
    editorial_blurb: "A quietly confident roastery café in Aoyama where single-origins rotate weekly and the staff genuinely wants to talk about terroir.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-20",
    verification_source: "admin",
  },
  // COPENHAGEN (3 cafes)
  {
    name: "The Coffee Collective",
    slug: "the-coffee-collective-copenhagen",
    lat: 55.6867,
    lng: 12.5611,
    city: "Copenhagen",
    country: "Denmark",
    address: "Jægersborggade 10, 2200 Copenhagen",
    roaster: "The Coffee Collective",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "coffeecollective",
    website: "https://coffeecollective.dk/",
    editorial_blurb: "Copenhagen's gold standard for specialty — their direct-trade relationships and obsessive roasting set the benchmark for Northern Europe.",
    featured_in: ["sprudge", "standart", "monocle"],
    verified: true,
    last_verified_at: "2024-11-10",
    verification_source: "admin",
  },
  {
    name: "Prolog Coffee Bar",
    slug: "prolog-coffee-bar",
    lat: 55.6761,
    lng: 12.5572,
    city: "Copenhagen",
    country: "Denmark",
    address: "Vesterbrogade 76, 1620 Copenhagen",
    roaster: "Prolog",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "standing-bar"],
    instagram_handle: "prologcoffee",
    editorial_blurb: "Vespa and concrete, espresso and natural wine — Prolog made the Copenhagen café look louder and the coffee just as good.",
    featured_in: ["sprudge", "guardian"],
    verified: true,
    last_verified_at: "2024-10-01",
    verification_source: "admin",
  },
  {
    name: "Original Coffee",
    slug: "original-coffee-copenhagen",
    lat: 55.6894,
    lng: 12.5529,
    city: "Copenhagen",
    country: "Denmark",
    address: "Nørrebrogade 23, 2200 Copenhagen",
    roaster: "Original Coffee",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "originalcoffeedk",
    editorial_blurb: "Relaxed, unpretentious, consistently excellent — the kind of neighborhood spot Copenhagen does better than anywhere.",
    featured_in: ["timeout"],
    verified: true,
    last_verified_at: "2024-08-15",
    verification_source: "community",
  },
  // MELBOURNE (3 cafes)
  {
    name: "St Ali",
    slug: "st-ali-melbourne",
    lat: -37.8067,
    lng: 144.9580,
    city: "Melbourne",
    country: "Australia",
    address: "12-18 Yarra Place, South Melbourne VIC 3205",
    roaster: "St Ali",
    brew_methods: ["espresso", "pour-over", "syphon", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "stalicoffee",
    website: "https://stali.com.au/",
    editorial_blurb: "The roastery that helped define Melbourne's coffee identity — still the best introduction to why this city takes coffee so seriously.",
    featured_in: ["sprudge", "guardian", "eater"],
    verified: true,
    last_verified_at: "2024-11-05",
    verification_source: "admin",
  },
  {
    name: "Patricia Coffee Brewers",
    slug: "patricia-coffee-brewers",
    lat: -37.8150,
    lng: 144.9608,
    city: "Melbourne",
    country: "Australia",
    address: "493-495 Little Bourke St, Melbourne VIC 3000",
    roaster: "Multiple roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["standing-bar", "no-laptop"],
    instagram_handle: "patriciacoffeebrewers",
    editorial_blurb: "Standing room only, zero compromise — Patricia runs the tightest espresso program in the CBD and everyone knows it.",
    featured_in: ["sprudge", "timeout"],
    verified: true,
    last_verified_at: "2024-10-20",
    verification_source: "admin",
  },
  {
    name: "Market Lane Coffee",
    slug: "market-lane-coffee",
    lat: -37.8083,
    lng: 144.9702,
    city: "Melbourne",
    country: "Australia",
    address: "Prahran Market, 163 Commercial Rd, Prahran VIC 3181",
    roaster: "Market Lane",
    brew_methods: ["pour-over", "espresso", "aeropress", "french-press"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "marketlanecoffee",
    website: "https://marketlane.com.au/",
    editorial_blurb: "Market-stall origins, world-class roasting — their seasonal single-origins are worth building a Melbourne morning around.",
    featured_in: ["sprudge", "standart"],
    verified: true,
    last_verified_at: "2024-09-30",
    verification_source: "admin",
  },
  // NEW YORK CITY (3 cafes)
  {
    name: "Devoción",
    slug: "devocion-nyc",
    lat: 40.7134,
    lng: -73.9634,
    city: "New York City",
    country: "United States",
    address: "69 Grand St, Brooklyn, NY 11249",
    roaster: "Devoción",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "laptop-friendly"],
    instagram_handle: "devocion",
    website: "https://www.devocion.com/",
    editorial_blurb: "Colombian-owned, Williamsburg-roasted — they ship beans from farm to cup in 10 days, and you can taste the difference.",
    featured_in: ["sprudge", "ny_times", "infatuation"],
    verified: true,
    last_verified_at: "2024-11-08",
    verification_source: "admin",
  },
  {
    name: "Onyx Coffee Lab NYC",
    slug: "onyx-coffee-lab-nyc",
    lat: 40.7282,
    lng: -73.9942,
    city: "New York City",
    country: "United States",
    address: "85 Attorney St, New York, NY 10002",
    roaster: "Onyx Coffee Lab",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "onyxcoffeelab",
    website: "https://onyxcoffeelab.com/",
    editorial_blurb: "Arkansas roasters who conquered NYC — their competition-level pours are approachable enough for a Tuesday morning.",
    featured_in: ["sprudge", "eater"],
    verified: true,
    last_verified_at: "2024-10-12",
    verification_source: "admin",
  },
  {
    name: "Parlor Coffee",
    slug: "parlor-coffee-brooklyn",
    lat: 40.6950,
    lng: -73.9909,
    city: "New York City",
    country: "United States",
    address: "135 Atlantic Ave, Brooklyn, NY 11201",
    roaster: "Parlor Coffee",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "parlorcoffee",
    editorial_blurb: "Tucked inside a Boerum Hill barbershop, Parlor's espresso is worth the detour and the wait for a stool.",
    featured_in: ["sprudge", "ny_times"],
    verified: true,
    last_verified_at: "2024-09-15",
    verification_source: "admin",
  },
  // LONDON (2 cafes)
  {
    name: "Monmouth Coffee",
    slug: "monmouth-coffee-london",
    lat: 51.5125,
    lng: -0.1237,
    city: "London",
    country: "United Kingdom",
    address: "27 Monmouth St, London WC2H 9EU",
    roaster: "Monmouth Coffee",
    brew_methods: ["pour-over", "espresso", "french-press"],
    vibe_tags: ["no-laptop", "outdoor-seating"],
    instagram_handle: "monmouthcoffee",
    website: "https://www.monmouthcoffee.co.uk/",
    editorial_blurb: "London's original specialty institution — the queue outside Borough Market moves fast and the cup at the end is always worth it.",
    featured_in: ["guardian", "timeout", "sprudge"],
    verified: true,
    last_verified_at: "2024-10-30",
    verification_source: "admin",
  },
  {
    name: "Square Mile Coffee Roasters",
    slug: "square-mile-london",
    lat: 51.5224,
    lng: -0.0864,
    city: "London",
    country: "United Kingdom",
    address: "Unit 4.1, The Tea Building, 56 Shoreditch High St, London E1 6JJ",
    roaster: "Square Mile Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "squaremilecoffee",
    website: "https://shop.squaremilecoffee.com/",
    editorial_blurb: "The roastery that trained a generation of London baristas — their Red Brick blend is a daily ritual for good reason.",
    featured_in: ["sprudge", "standart", "guardian"],
    verified: true,
    last_verified_at: "2024-11-02",
    verification_source: "admin",
  },
  // MONTREAL (2 cafes)
  {
    name: "Café Myriade",
    slug: "cafe-myriade-montreal",
    lat: 45.4972,
    lng: -73.5773,
    city: "Montreal",
    country: "Canada",
    address: "1432 Rue Mackay, Montréal, QC H3G 2H7",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "cafemyriade",
    website: "https://cafemyriade.com/",
    editorial_blurb: "Montreal's specialty anchor — consistently excellent espresso and a rotating guest roaster program that keeps regulars coming back.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-05",
    verification_source: "admin",
  },
  {
    name: "Dispatch Coffee",
    slug: "dispatch-coffee-montreal",
    lat: 45.5231,
    lng: -73.5790,
    city: "Montreal",
    country: "Canada",
    address: "4231 Rue Saint-Denis, Montréal, QC H2J 2K9",
    roaster: "Dispatch Coffee",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "dispatchcoffee",
    editorial_blurb: "Plateau neighbourhood staple with a serious roasting operation — the natural-process Ethiopians here are among Canada's best.",
    featured_in: ["sprudge", "timeout"],
    verified: true,
    last_verified_at: "2024-09-10",
    verification_source: "community",
  },
  // BERLIN (2 cafes)
  {
    name: "The Barn",
    slug: "the-barn-berlin",
    lat: 52.5289,
    lng: 13.3859,
    city: "Berlin",
    country: "Germany",
    address: "Auguststraße 58, 10119 Berlin",
    roaster: "The Barn",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "thebarnberlin",
    website: "https://thebarn.de/",
    editorial_blurb: "Berlin's most opinionated roaster — they'll tell you which brew method suits your chosen bean, and they'll be right.",
    featured_in: ["sprudge", "monocle", "standart"],
    verified: true,
    last_verified_at: "2024-10-25",
    verification_source: "admin",
  },
  {
    name: "Five Elephant",
    slug: "five-elephant-berlin",
    lat: 52.4994,
    lng: 13.4283,
    city: "Berlin",
    country: "Germany",
    address: "Reichenberger Str. 101, 10999 Berlin",
    roaster: "Five Elephant",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "fiveelephant",
    website: "https://www.fiveelephant.com/",
    editorial_blurb: "Kreuzberg coffee institution — the cheesecake has its own fanbase but the roasting is what put them on the world map.",
    featured_in: ["sprudge", "guardian"],
    verified: true,
    last_verified_at: "2024-10-18",
    verification_source: "admin",
  },
  // MEXICO CITY (2 cafes)
  {
    name: "Café Nil",
    slug: "cafe-nil-mexico-city",
    lat: 19.4326,
    lng: -99.1676,
    city: "Mexico City",
    country: "Mexico",
    address: "Orizaba 101, Roma Norte, 06700 Ciudad de México",
    roaster: "Café Nil",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["outdoor-seating", "minimalist"],
    instagram_handle: "cafenilmx",
    editorial_blurb: "Roma Norte's best-kept secret — Mexican single-origins from Oaxaca and Veracruz brewed with the care they deserve.",
    featured_in: ["sprudge", "infatuation"],
    verified: true,
    last_verified_at: "2024-09-25",
    verification_source: "admin",
  },
  {
    name: "Buna Coffee",
    slug: "buna-coffee-mexico-city",
    lat: 19.4284,
    lng: -99.1607,
    city: "Mexico City",
    country: "Mexico",
    address: "Tonalá 10, Roma Norte, 06700 Ciudad de México",
    roaster: "Buna",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "bunacoffee",
    editorial_blurb: "Ethiopian coffee expertise meets CDMX warmth — the natural processes here taste like nowhere else in the city.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-08-30",
    verification_source: "community",
  },
  // SEOUL (2 cafes)
  {
    name: "Fritz Coffee Company",
    slug: "fritz-coffee-seoul",
    lat: 37.5139,
    lng: 126.9931,
    city: "Seoul",
    country: "South Korea",
    address: "11-5 Mapo-daero 18-gil, Mapo-gu, Seoul",
    roaster: "Fritz Coffee",
    brew_methods: ["pour-over", "espresso", "syphon"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "fritzcoffeecompany",
    website: "https://www.fritzcoffee.co.kr/",
    editorial_blurb: "Seoul's most beloved roastery café — the Saturday morning queue is a pilgrimage and the single-origins justify every minute of it.",
    featured_in: ["sprudge", "standart"],
    verified: true,
    last_verified_at: "2024-11-06",
    verification_source: "admin",
  },
  {
    name: "Namusairo",
    slug: "namusairo-seoul",
    lat: 37.5796,
    lng: 126.9770,
    city: "Seoul",
    country: "South Korea",
    address: "21 Jahamun-ro 5-gil, Jongno-gu, Seoul",
    roaster: "Namusairo",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "namusairo",
    editorial_blurb: "Tucked in Bukchon Hanok Village, Namusairo pairs traditional architecture with technically immaculate pour-overs — a rare combination.",
    featured_in: ["sprudge", "monocle"],
    verified: true,
    last_verified_at: "2024-10-08",
    verification_source: "admin",
  },
  // CAPE TOWN (2 cafes)
  {
    name: "Truth Coffee Roasting",
    slug: "truth-coffee-cape-town",
    lat: -33.9249,
    lng: 18.4241,
    city: "Cape Town",
    country: "South Africa",
    address: "36 Buitenkant St, Cape Town City Centre, 8001",
    roaster: "Truth Coffee",
    brew_methods: ["espresso", "pour-over", "syphon", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "truthcoffee",
    website: "https://www.truthcoffee.com/",
    editorial_blurb: "Steampunk décor, serious roasting — Truth earned 'world's best coffee shop' headlines and still delivers on the hype.",
    featured_in: ["sprudge", "guardian", "timeout"],
    verified: true,
    last_verified_at: "2024-10-22",
    verification_source: "admin",
  },
  {
    name: "Origin Coffee Roasting",
    slug: "origin-coffee-cape-town",
    lat: -33.9173,
    lng: 18.4234,
    city: "Cape Town",
    country: "South Africa",
    address: "28 Hudson St, De Waterkant, Cape Town, 8001",
    roaster: "Origin Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "origincoffeeroasting",
    editorial_blurb: "Pan-African sourcing done right — Origin's direct relationships with East African farmers show up in every cup.",
    featured_in: ["sprudge", "standart"],
    verified: true,
    last_verified_at: "2024-09-18",
    verification_source: "admin",
  },
  // BUENOS AIRES (2 cafes)
  {
    name: "Café Registrado",
    slug: "cafe-registrado-buenos-aires",
    lat: -34.5884,
    lng: -58.4161,
    city: "Buenos Aires",
    country: "Argentina",
    address: "Humboldt 1542, C1414 CABA, Buenos Aires",
    roaster: "Café Registrado",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "caferegistrado",
    editorial_blurb: "The café that changed what Buenos Aires understood about coffee — their training program shaped the city's entire specialty scene.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-05",
    verification_source: "admin",
  },
  {
    name: "LAB Tostadores de Café",
    slug: "lab-tostadores-buenos-aires",
    lat: -34.5961,
    lng: -58.3928,
    city: "Buenos Aires",
    country: "Argentina",
    address: "Thames 1885, C1414 CABA, Buenos Aires",
    roaster: "LAB Tostadores",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "labtostadores",
    editorial_blurb: "Palermo's most focused roastery café — an ever-changing Colombian single-origin menu and baristas who love to explain the difference.",
    featured_in: ["sprudge", "infatuation"],
    verified: true,
    last_verified_at: "2024-08-20",
    verification_source: "community",
  },
  // SAN FRANCISCO (3 cafes)
  {
    name: "Sightglass Coffee",
    slug: "sightglass-coffee-sf",
    lat: 37.7749,
    lng: -122.4066,
    city: "San Francisco",
    country: "United States",
    address: "7th St & Folsom St, San Francisco, CA 94103",
    roaster: "Sightglass Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "sightglasscoffee",
    website: "https://sightglasscoffee.com/",
    editorial_blurb: "SOMA roastery flagship with soaring ceilings and a sourcing program that earns every inch of the hype.",
    featured_in: ["sprudge", "eater"],
    verified: true,
    last_verified_at: "2024-11-01",
    verification_source: "admin",
  },
  {
    name: "Ritual Coffee Roasters",
    slug: "ritual-coffee-hayes-valley",
    lat: 37.7762,
    lng: -122.4245,
    city: "San Francisco",
    country: "United States",
    address: "432B Octavia Blvd, San Francisco, CA 94102",
    roaster: "Ritual Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "ritualcoffee",
    website: "https://www.ritualroasters.com/",
    editorial_blurb: "The roastery that pioneered SF specialty — Hayes Valley flagship still serves as the city's benchmark for direct-trade espresso.",
    featured_in: ["sprudge", "ny_times"],
    verified: true,
    last_verified_at: "2024-10-15",
    verification_source: "admin",
  },
  {
    name: "Linea Caffe",
    slug: "linea-caffe-sf",
    lat: 37.7599,
    lng: -122.4148,
    city: "San Francisco",
    country: "United States",
    address: "18th St, Mission District, San Francisco, CA 94110",
    roaster: "Linea Caffe",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["standing-bar", "no-laptop", "minimalist"],
    instagram_handle: "lineacaffe",
    editorial_blurb: "Standing bar, no wifi, zero distraction — the serious espresso program here is reason enough to make the Mission pilgrimage.",
    featured_in: ["sprudge", "infatuation"],
    verified: true,
    last_verified_at: "2024-10-20",
    verification_source: "admin",
  },
  // CHICAGO (3 cafes)
  {
    name: "Intelligentsia Coffee",
    slug: "intelligentsia-millennium-park",
    lat: 41.8820,
    lng: -87.6244,
    city: "Chicago",
    country: "United States",
    address: "53 W Jackson Blvd, Chicago, IL 60604",
    roaster: "Intelligentsia Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "intelligentsiacoffee",
    website: "https://www.intelligentsiacoffee.com/",
    editorial_blurb: "The seminal US third-wave roaster that redefined direct trade — every cup carries twenty-five years of hard-won sourcing relationships.",
    featured_in: ["sprudge", "ny_times"],
    verified: true,
    last_verified_at: "2024-11-01",
    verification_source: "admin",
  },
  {
    name: "Dark Matter Coffee",
    slug: "dark-matter-coffee-wicker-park",
    lat: 41.9086,
    lng: -87.6788,
    city: "Chicago",
    country: "United States",
    address: "738 N Western Ave, Chicago, IL 60622",
    roaster: "Dark Matter Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "darkmattercoffee",
    website: "https://www.darkmattercoffee.com/",
    editorial_blurb: "Punk-aesthetic roastery in Wicker Park that proves world-class beans and a loud personality are not mutually exclusive.",
    featured_in: ["sprudge", "eater"],
    verified: true,
    last_verified_at: "2024-10-18",
    verification_source: "admin",
  },
  {
    name: "Sawada Coffee",
    slug: "sawada-coffee-chicago",
    lat: 41.8834,
    lng: -87.6479,
    city: "Chicago",
    country: "United States",
    address: "112 N Green St, Chicago, IL 60607",
    roaster: "Intelligentsia Coffee",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["minimalist", "no-laptop", "standing-bar"],
    instagram_handle: "sawadacoffee",
    editorial_blurb: "Japanese precision in the West Loop — Hiroshi Sawada's military latte and immaculate espresso pull make this a non-negotiable Chicago stop.",
    featured_in: ["sprudge", "infatuation"],
    verified: true,
    last_verified_at: "2024-10-10",
    verification_source: "admin",
  },
  // PARIS (3 cafes)
  {
    name: "Café Lomi",
    slug: "cafe-lomi-paris",
    lat: 48.8894,
    lng: 2.3483,
    city: "Paris",
    country: "France",
    address: "3ter Rue Marcadet, 75018 Paris",
    roaster: "Café Lomi",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "cafelomi",
    website: "https://www.cafelomi.com/",
    editorial_blurb: "Montmartre warehouse roastery that proved Paris could take specialty as seriously as Scandinavia — the filter menu changes weekly.",
    featured_in: ["sprudge", "guardian"],
    verified: true,
    last_verified_at: "2024-10-25",
    verification_source: "admin",
  },
  {
    name: "Coutume Café",
    slug: "coutume-cafe-paris",
    lat: 48.8558,
    lng: 2.3167,
    city: "Paris",
    country: "France",
    address: "47 Rue de Babylone, 75007 Paris",
    roaster: "Coutume",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "coutumecafe",
    website: "https://coutumecafe.com/",
    editorial_blurb: "The café that brought Australian coffee culture to the 7th arrondissement — flat whites and serious filter in equal measure.",
    featured_in: ["sprudge", "monocle"],
    verified: true,
    last_verified_at: "2024-10-08",
    verification_source: "admin",
  },
  {
    name: "Ten Belles",
    slug: "ten-belles-paris",
    lat: 48.8701,
    lng: 2.3625,
    city: "Paris",
    country: "France",
    address: "10 Rue de la Grange aux Belles, 75010 Paris",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "tenbelles",
    editorial_blurb: "Canal Saint-Martin institution pairing natural wines with pour-overs — the terrace is Paris specialty at its most atmospheric.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-20",
    verification_source: "admin",
  },
  // AMSTERDAM (3 cafes)
  {
    name: "Lot Sixty One Coffee Roasters",
    slug: "lot-sixty-one-amsterdam",
    lat: 52.3737,
    lng: 4.8741,
    city: "Amsterdam",
    country: "Netherlands",
    address: "Kinkerstraat 112, 1053 EG Amsterdam",
    roaster: "Lot Sixty One",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "lotsixtyone",
    website: "https://www.lotsixtyone.com/",
    editorial_blurb: "Flagship of Dutch specialty coffee — the Jordaan roastery's seasonal menu is the best introduction to serious Amsterdam beans.",
    featured_in: ["sprudge", "monocle"],
    verified: true,
    last_verified_at: "2024-11-02",
    verification_source: "admin",
  },
  {
    name: "White Label Coffee",
    slug: "white-label-coffee-amsterdam",
    lat: 52.3712,
    lng: 4.8674,
    city: "Amsterdam",
    country: "Netherlands",
    address: "Jan Evertsenstraat 136, 1057 BK Amsterdam",
    roaster: "White Label Coffee",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "whitelabelcoffeeams",
    editorial_blurb: "Stripped-back Amsterdam West space with a serious filter focus — no distractions, just excellent beans brewed with precision.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-14",
    verification_source: "admin",
  },
  {
    name: "Bocca Coffee",
    slug: "bocca-coffee-amsterdam",
    lat: 52.3798,
    lng: 4.8837,
    city: "Amsterdam",
    country: "Netherlands",
    address: "Westerstraat 33, 1015 LR Amsterdam",
    roaster: "Bocca Coffee",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "boccacoffee",
    website: "https://www.boccacoffee.nl/",
    editorial_blurb: "One of Europe's most respected sourcing programs lives in this Westerstraat roastery — the traceability details go further than almost anyone.",
    featured_in: ["sprudge", "standart"],
    verified: true,
    last_verified_at: "2024-10-05",
    verification_source: "admin",
  },
  // SYDNEY (3 cafes)
  {
    name: "Single O",
    slug: "single-o-surry-hills",
    lat: -33.8896,
    lng: 151.2094,
    city: "Sydney",
    country: "Australia",
    address: "60-64 Reservoir St, Surry Hills NSW 2010",
    roaster: "Single O",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "laptop-friendly"],
    instagram_handle: "singleocoffee",
    website: "https://www.singleo.com.au/",
    editorial_blurb: "The Surry Hills roastery that defined Sydney specialty — their taps of batch brew and cold brew changed how the city drinks coffee.",
    featured_in: ["sprudge", "guardian"],
    verified: true,
    last_verified_at: "2024-11-03",
    verification_source: "admin",
  },
  {
    name: "Sample Coffee",
    slug: "sample-coffee-sydney",
    lat: -33.8923,
    lng: 151.2077,
    city: "Sydney",
    country: "Australia",
    address: "118 Devonshire St, Surry Hills NSW 2010",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "samplecoffeesydney",
    editorial_blurb: "Rotating guest roasters and genuinely serious pour-overs make Sample the best place in Sydney to discover what's new in specialty.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-12",
    verification_source: "admin",
  },
  {
    name: "Reuben Hills",
    slug: "reuben-hills-sydney",
    lat: -33.8910,
    lng: 151.2060,
    city: "Sydney",
    country: "Australia",
    address: "61 Albion St, Surry Hills NSW 2010",
    roaster: "Reuben Hills",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "reubenhills",
    website: "https://reubenhills.com.au/",
    editorial_blurb: "South American bean focus and a roastery café that doubles as a proper brunch destination — the espresso program is the real reason to visit.",
    featured_in: ["sprudge", "timeout"],
    verified: true,
    last_verified_at: "2024-10-22",
    verification_source: "admin",
  },
  // VIENNA (3 cafes)
  {
    name: "Kaffeefabrik",
    slug: "kaffeefabrik-vienna",
    lat: 48.1967,
    lng: 16.3686,
    city: "Vienna",
    country: "Austria",
    address: "Favoritenstraße 4-6, 1040 Vienna",
    roaster: "Kaffeefabrik",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "kaffeefabrik",
    website: "https://kaffeefabrik.at/",
    editorial_blurb: "4th district roastery with an uncompromising single-origin focus — the most technically rigorous coffee in a city famous for café tradition.",
    featured_in: ["sprudge", "standart"],
    verified: true,
    last_verified_at: "2024-10-28",
    verification_source: "admin",
  },
  {
    name: "Café Phil",
    slug: "cafe-phil-vienna",
    lat: 48.1988,
    lng: 16.3571,
    city: "Vienna",
    country: "Austria",
    address: "Gumpendorfer Str. 10-12, 1060 Vienna",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "cafephilvienna",
    website: "https://www.cafephil.at/",
    editorial_blurb: "Books, vinyl, and specialty espresso in Vienna's 6th district — the most atmospheric café in a city built on atmosphere.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-15",
    verification_source: "admin",
  },
  {
    name: "Seven",
    slug: "seven-vienna",
    lat: 48.2089,
    lng: 16.3703,
    city: "Vienna",
    country: "Austria",
    address: "Siebensterngasse 7, 1070 Vienna",
    roaster: "Seven",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["minimalist", "standing-bar"],
    instagram_handle: "sevencoffeebar",
    editorial_blurb: "Third-wave sensibility meets Viennese café tradition in the 1st district — the espresso here bridges two centuries of coffee culture.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-28",
    verification_source: "admin",
  },
  // STOCKHOLM (3 cafes)
  {
    name: "Drop Coffee Roasters",
    slug: "drop-coffee-stockholm",
    lat: 59.3151,
    lng: 18.0611,
    city: "Stockholm",
    country: "Sweden",
    address: "Wollmar Yxkullsgatan 10, 118 50 Stockholm",
    roaster: "Drop Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "dropcoffeeroasters",
    website: "https://dropcoffee.se/",
    editorial_blurb: "World competition winners roasting in Södermalm — the precision and restraint in every cup explains every trophy on the shelf.",
    featured_in: ["sprudge", "standart"],
    verified: true,
    last_verified_at: "2024-11-04",
    verification_source: "admin",
  },
  {
    name: "Johan & Nyström",
    slug: "johan-nystrom-stockholm",
    lat: 59.3169,
    lng: 18.0744,
    city: "Stockholm",
    country: "Sweden",
    address: "Swedenborgsgatan 7, 118 48 Stockholm",
    roaster: "Johan & Nyström",
    brew_methods: ["pour-over", "espresso", "cold-brew", "chemex"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "johanochnystrm",
    website: "https://johanochnystrm.se/",
    editorial_blurb: "The Scandinavian specialty pioneer that opened Sweden's eyes to origin coffee — still the city's most essential roastery café.",
    featured_in: ["sprudge", "monocle"],
    verified: true,
    last_verified_at: "2024-10-30",
    verification_source: "admin",
  },
  {
    name: "Café Pascal",
    slug: "cafe-pascal-stockholm",
    lat: 59.3414,
    lng: 18.0436,
    city: "Stockholm",
    country: "Sweden",
    address: "Norrtullsgatan 4, 113 29 Stockholm",
    roaster: "Café Pascal",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "cafepascal",
    website: "https://cafepascal.se/",
    editorial_blurb: "Vasastan neighborhood roastery with a loyal local following — the rotating single-origins and relaxed setting make it hard to leave.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-10",
    verification_source: "admin",
  },
  // LISBON (3 cafes)
  {
    name: "Fábrica Coffee Roasters",
    slug: "fabrica-coffee-lisbon",
    lat: 38.7111,
    lng: -9.1421,
    city: "Lisbon",
    country: "Portugal",
    address: "Rua Nova do Carvalho 10, 1200-291 Lisbon",
    roaster: "Fábrica Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "fabricacoffeeroasters",
    website: "https://www.fabricacoffeeroasters.com/",
    editorial_blurb: "Lisbon's first specialty roastery set the standard the rest of the city is still catching up to — the Chiado flagship remains unmissable.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-11-01",
    verification_source: "admin",
  },
  {
    name: "Copenhagen Coffee Lab Lisbon",
    slug: "copenhagen-coffee-lab-lisbon",
    lat: 38.7178,
    lng: -9.1470,
    city: "Lisbon",
    country: "Portugal",
    address: "Rua Nova da Piedade 10, 1200-298 Lisbon",
    roaster: "Copenhagen Coffee Lab",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "copenhagencoffeelab",
    editorial_blurb: "Danish precision transplanted to Príncipe Real — Scandinavian sourcing and technique in one of Lisbon's best-looking cafés.",
    featured_in: ["sprudge", "monocle"],
    verified: true,
    last_verified_at: "2024-10-18",
    verification_source: "admin",
  },
  {
    name: "Hello, Kristof",
    slug: "hello-kristof-lisbon",
    lat: 38.7230,
    lng: -9.1342,
    city: "Lisbon",
    country: "Portugal",
    address: "Largo do Intendente Pina Manique 1, 1100-285 Lisbon",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "hellokristof",
    editorial_blurb: "Natural wines and natural-process coffees at Intendente — the most exciting pairing in Lisbon's rapidly evolving drinks scene.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-25",
    verification_source: "admin",
  },
  // BARCELONA (3 cafes)
  {
    name: "Nomad Coffee",
    slug: "nomad-coffee-barcelona",
    lat: 41.4037,
    lng: 2.1972,
    city: "Barcelona",
    country: "Spain",
    address: "Passatge Sert 12, 08003 Barcelona",
    roaster: "Nomad Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "nomadcoffee",
    website: "https://nomadcoffee.es/",
    editorial_blurb: "Competition pedigree meets Poblenou industrial — the roastery behind Spain's most decorated specialty program is worth crossing Barcelona for.",
    featured_in: ["sprudge", "standart"],
    verified: true,
    last_verified_at: "2024-11-05",
    verification_source: "admin",
  },
  {
    name: "Syra Coffee",
    slug: "syra-coffee-barcelona",
    lat: 41.3930,
    lng: 2.1570,
    city: "Barcelona",
    country: "Spain",
    address: "Carrer de Enric Granados 36, 08008 Barcelona",
    roaster: "Syra Coffee",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "syracoffee",
    website: "https://syracoffee.com/",
    editorial_blurb: "Eixample minimalism done right — clean design and excellent filter coffee make Syra the neighborhood anchor Barcelona needed.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-20",
    verification_source: "admin",
  },
  {
    name: "Right Side Coffee Bar",
    slug: "right-side-coffee-barcelona",
    lat: 41.3853,
    lng: 2.1822,
    city: "Barcelona",
    country: "Spain",
    address: "Carrer del Parlament 33, 08015 Barcelona",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "rightsidecoffee",
    editorial_blurb: "Aussie-influenced El Born bar with a strong espresso program and the kind of relaxed confidence Barcelona's specialty scene needed.",
    featured_in: ["sprudge", "timeout"],
    verified: true,
    last_verified_at: "2024-10-08",
    verification_source: "admin",
  },
  // SINGAPORE (3 cafes)
  {
    name: "Nylon Coffee Roasters",
    slug: "nylon-coffee-singapore",
    lat: 1.2796,
    lng: 103.8390,
    city: "Singapore",
    country: "Singapore",
    address: "4 Everton Park #01-40, Singapore 080004",
    roaster: "Nylon Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "nyloncoffee",
    website: "https://www.nyloncoffee.sg/",
    editorial_blurb: "Tanjong Pagar institution that defined Singapore specialty — Everton Park HDB block setting is as iconic as the coffee itself.",
    featured_in: ["sprudge", "monocle"],
    verified: true,
    last_verified_at: "2024-11-06",
    verification_source: "admin",
  },
  {
    name: "Cata",
    slug: "cata-singapore",
    lat: 1.2772,
    lng: 103.8424,
    city: "Singapore",
    country: "Singapore",
    address: "1 Tanjong Pagar Plaza #01-01, Singapore 082001",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "cata_sg",
    editorial_blurb: "Where Singapore's wine bar scene meets specialty coffee — the curated pairing menu makes Cata one of the city's most original concepts.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-15",
    verification_source: "admin",
  },
  {
    name: "Chye Seng Huat Hardware",
    slug: "chye-seng-huat-singapore",
    lat: 1.3127,
    lng: 103.8644,
    city: "Singapore",
    country: "Singapore",
    address: "150 Tyrwhitt Rd, Singapore 207563",
    roaster: "Papa Palheta",
    brew_methods: ["pour-over", "espresso", "syphon", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "laptop-friendly"],
    instagram_handle: "cshhardware",
    website: "https://www.cshhardware.com/",
    editorial_blurb: "Converted hardware shop turned roastery flagship — the courtyard, the pour-overs, and the industrial bones are all reasons to visit.",
    featured_in: ["sprudge", "guardian"],
    verified: true,
    last_verified_at: "2024-10-28",
    verification_source: "admin",
  },
  // TAIPEI (3 cafes)
  {
    name: "Fika Fika Café",
    slug: "fika-fika-taipei",
    lat: 25.0611,
    lng: 121.5237,
    city: "Taipei",
    country: "Taiwan",
    address: "No. 33, Yitong St, Zhongshan District, Taipei 104",
    roaster: "Fika Fika",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "fikafika_cafe",
    website: "https://www.fikafika.com.tw/",
    editorial_blurb: "Taiwan's first Scandinavian-style roastery brought light-roast competition culture to Taipei — and the city never looked back.",
    featured_in: ["sprudge", "standart"],
    verified: true,
    last_verified_at: "2024-11-02",
    verification_source: "admin",
  },
  {
    name: "Simple Kaffa",
    slug: "simple-kaffa-taipei",
    lat: 25.0290,
    lng: 121.5434,
    city: "Taipei",
    country: "Taiwan",
    address: "No. 54, Lane 243, Sec 1, Dunhua S Rd, Da'an, Taipei",
    roaster: "Simple Kaffa",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "simplekaffa",
    website: "https://simplekaffa.com/",
    editorial_blurb: "World barista champion Berg Wu's Da'an flagship — technically flawless espresso from a café that's earned every accolade it carries.",
    featured_in: ["sprudge", "monocle"],
    verified: true,
    last_verified_at: "2024-11-08",
    verification_source: "admin",
  },
  {
    name: "Rufous Coffee",
    slug: "rufous-coffee-taipei",
    lat: 25.0585,
    lng: 121.5224,
    city: "Taipei",
    country: "Taiwan",
    address: "No. 1, Lane 40, Xinsheng N Rd, Zhongshan, Taipei",
    roaster: "Rufous Coffee",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "rufous_coffee",
    editorial_blurb: "Zhongshan's serious single-origin program draws the kind of crowd that wants to talk about altitude and processing — and the baristas are ready.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-05",
    verification_source: "admin",
  },
  // SÃO PAULO (3 cafes)
  {
    name: "Guilhotina Coffee",
    slug: "guilhotina-coffee-sao-paulo",
    lat: -23.5630,
    lng: -46.6920,
    city: "São Paulo",
    country: "Brazil",
    address: "Rua Harmonia 354, Vila Madalena, São Paulo, SP 05435-000",
    roaster: "Guilhotina Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "guilhotinacoffee",
    editorial_blurb: "Vila Madalena roastery championing Brazilian single-origins — the best argument for why the world should drink more coffee from São Paulo's backyard.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-20",
    verification_source: "admin",
  },
  {
    name: "Suplicy Cafés Especiais",
    slug: "suplicy-cafes-sao-paulo",
    lat: -23.5715,
    lng: -46.6628,
    city: "São Paulo",
    country: "Brazil",
    address: "Al. Lorena 1430, Jardins, São Paulo, SP 01424-001",
    roaster: "Suplicy Cafés Especiais",
    brew_methods: ["espresso", "pour-over", "chemex", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "suplicycafes",
    website: "https://www.suplicycafes.com.br/",
    editorial_blurb: "Premium Brazilian specialty done with Jardins elegance — the micro-lot menu showcases what makes this country the world's most interesting origin.",
    featured_in: ["sprudge", "infatuation"],
    verified: true,
    last_verified_at: "2024-10-30",
    verification_source: "admin",
  },
  {
    name: "Café Três",
    slug: "cafe-tres-sao-paulo",
    lat: -23.5604,
    lng: -46.6762,
    city: "São Paulo",
    country: "Brazil",
    address: "Rua Aspicuelta 474, Pinheiros, São Paulo, SP 05433-012",
    roaster: "Café Três",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "cafetres",
    editorial_blurb: "Pinheiros natural-process specialists who source from farms within driving distance — this is Brazilian coffee at its most transparent.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-18",
    verification_source: "admin",
  },
  // ISTANBUL (3 cafes)
  {
    name: "Kronotrop",
    slug: "kronotrop-istanbul",
    lat: 41.0326,
    lng: 28.9828,
    city: "Istanbul",
    country: "Turkey",
    address: "Sıraselviler Cad. 69, Cihangir, 34433 Istanbul",
    roaster: "Kronotrop",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "kronotrop",
    website: "https://kronotrop.com.tr/",
    editorial_blurb: "Istanbul's most respected specialty roaster set in Cihangir's creative hub — the filter coffee here challenges everything you thought you knew about Turkish coffee.",
    featured_in: ["sprudge", "monocle"],
    verified: true,
    last_verified_at: "2024-11-04",
    verification_source: "admin",
  },
  {
    name: "Petra Roasting Co.",
    slug: "petra-roasting-istanbul",
    lat: 41.0233,
    lng: 28.9748,
    city: "Istanbul",
    country: "Turkey",
    address: "Kemankeş Karamustafa Paşa Mah., Karaköy, Istanbul",
    roaster: "Petra Roasting Co.",
    brew_methods: ["espresso", "pour-over", "chemex"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "petraroasting",
    editorial_blurb: "Karaköy roastery with Bosphorus views and a bean program worth navigating Istanbul's hills for — specialty coffee with an unmissable setting.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-15",
    verification_source: "admin",
  },
  {
    name: "MOC Coffee",
    slug: "moc-coffee-istanbul",
    lat: 41.0472,
    lng: 28.9944,
    city: "Istanbul",
    country: "Turkey",
    address: "Abdi İpekçi Cad., Nişantaşı, Istanbul",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "moccoffeetr",
    editorial_blurb: "Japanese-influenced minimalism in Nişantaşı — the focused pour-over menu and quiet interior are the antidote to Istanbul's sensory overload.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-30",
    verification_source: "admin",
  },
  // NAIROBI (3 cafes)
  {
    name: "Nairobi Coffee Exchange",
    slug: "nairobi-coffee-exchange",
    lat: -1.2836,
    lng: 36.8214,
    city: "Nairobi",
    country: "Kenya",
    address: "Mama Ngina St, Nairobi CBD, Nairobi",
    roaster: "Nairobi Coffee Exchange",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "nairobicoffeeexchange",
    editorial_blurb: "Origin-focused CBD café serving single-farm Kenyan lots you simply cannot find anywhere else — drinking here is a direct line to the source.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-11-01",
    verification_source: "admin",
  },
  {
    name: "Kikao Coffee",
    slug: "kikao-coffee-nairobi",
    lat: -1.2636,
    lng: 36.8008,
    city: "Nairobi",
    country: "Kenya",
    address: "Westlands, Nairobi",
    roaster: "Kikao Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "kikaocoffee",
    editorial_blurb: "East Africa's specialty pioneer with a Westlands roastery proving that great Kenyan coffee belongs in the cup, not the export container.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-12",
    verification_source: "admin",
  },
  {
    name: "Dormans Coffee",
    slug: "dormans-coffee-nairobi",
    lat: -1.3244,
    lng: 36.7139,
    city: "Nairobi",
    country: "Kenya",
    address: "Karen Shopping Centre, Karen, Nairobi",
    roaster: "Dormans Coffee",
    brew_methods: ["espresso", "pour-over", "french-press"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "dormanscoffee",
    website: "https://www.dormanscoffee.co.ke/",
    editorial_blurb: "Kenya's historic roaster reborn as a specialty champion — Karen flagship is the most reliable place in the city for traceable Kenyan lots.",
    featured_in: ["sprudge", "guardian"],
    verified: true,
    last_verified_at: "2024-10-05",
    verification_source: "admin",
  },
  // HO CHI MINH CITY (3 cafes)
  {
    name: "The Workshop Coffee",
    slug: "the-workshop-coffee-hcmc",
    lat: 10.7769,
    lng: 106.7009,
    city: "Ho Chi Minh City",
    country: "Vietnam",
    address: "27 Ngo Duc Ke, District 1, Ho Chi Minh City",
    roaster: "The Workshop Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "theworkshop_coffee",
    website: "https://www.theworkshop.coffee/",
    editorial_blurb: "Rooftop industrial space in District 1 that reimagined what a Vietnamese café could be — the specialty program here sets the city's benchmark.",
    featured_in: ["sprudge", "monocle"],
    verified: true,
    last_verified_at: "2024-11-03",
    verification_source: "admin",
  },
  {
    name: "Shin Coffee",
    slug: "shin-coffee-hcmc",
    lat: 10.7793,
    lng: 106.6866,
    city: "Ho Chi Minh City",
    country: "Vietnam",
    address: "4/2 Nguyen Thi Minh Khai, District 3, Ho Chi Minh City",
    roaster: "Shin Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "shincoffee",
    editorial_blurb: "Vietnamese robusta meets specialty arabica in District 3 — Shin bridges the country's coffee heritage with third-wave technique in a single menu.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-18",
    verification_source: "admin",
  },
  {
    name: "L'Usine",
    slug: "lusine-hcmc",
    lat: 10.7760,
    lng: 106.7005,
    city: "Ho Chi Minh City",
    country: "Vietnam",
    address: "151/5 Dong Khoi, District 1, Ho Chi Minh City",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "lusinespace",
    website: "https://www.lusinespace.com/",
    editorial_blurb: "French colonial architecture meets third-wave coffee in the heart of District 1 — the design alone is reason to linger over a second cup.",
    featured_in: ["sprudge", "timeout"],
    verified: true,
    last_verified_at: "2024-10-25",
    verification_source: "admin",
  },
  // OSAKA (3 cafes)
  {
    name: "% Arabica Osaka",
    slug: "arabica-osaka-kitahama",
    lat: 34.6898,
    lng: 135.5101,
    city: "Osaka",
    country: "Japan",
    address: "1-1-1 Kitahama, Chuo-ku, Osaka",
    roaster: "% Arabica",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "outdoor-seating", "no-laptop"],
    instagram_handle: "arabica.osaka",
    website: "https://www.arabica.coffee/",
    editorial_blurb: "Iconic river-facing minimalist space where Kitahama's beauty meets specialty precision — the best Instagram backdrop in Osaka that actually earns it.",
    featured_in: ["sprudge", "monocle"],
    verified: true,
    last_verified_at: "2024-11-07",
    verification_source: "admin",
  },
  {
    name: "Kurasu Osaka",
    slug: "kurasu-osaka-shinsaibashi",
    lat: 34.6724,
    lng: 135.5011,
    city: "Osaka",
    country: "Japan",
    address: "1-7-1 Shinsaibashisuji, Chuo-ku, Osaka",
    roaster: "Kurasu",
    brew_methods: ["pour-over", "espresso", "aeropress", "chemex"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "kurasucoffee",
    website: "https://kurasu.kyoto/",
    editorial_blurb: "Kyoto roastery's Osaka flagship bringing direct-trade beans and Shinsaibashi foot traffic together — the pour-over menu rewards the extra walk.",
    featured_in: ["sprudge", "standart"],
    verified: true,
    last_verified_at: "2024-10-22",
    verification_source: "admin",
  },
  {
    name: "Mel Coffee Roasters",
    slug: "mel-coffee-roasters-osaka",
    lat: 34.6654,
    lng: 135.5032,
    city: "Osaka",
    country: "Japan",
    address: "Namba, Chuo-ku, Osaka",
    roaster: "Mel Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "melcoffeeroasters",
    editorial_blurb: "Namba roastery with a natural-process focus that stands apart from Osaka's lighter-roast mainstream — complex and worth seeking out.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-08",
    verification_source: "admin",
  },
  // PORTLAND, OR (2 cafes)
  {
    name: "Stumptown Coffee Roasters",
    slug: "stumptown-portland",
    lat: 45.5143,
    lng: -122.6545,
    city: "Portland",
    country: "United States",
    address: "4525 SE Division St, Portland, OR 97206",
    roaster: "Stumptown Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "french-press", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "stumptowncoffee",
    website: "https://www.stumptowncoffee.com/",
    editorial_blurb: "The roastery that launched Portland's coffee revolution — the original Division location still feels like the center of something important.",
    featured_in: ["sprudge", "ny_times", "eater"],
    verified: true,
    last_verified_at: "2024-10-28",
    verification_source: "admin",
  },
  {
    name: "Water Avenue Coffee",
    slug: "water-avenue-coffee-portland",
    lat: 45.5168,
    lng: -122.6649,
    city: "Portland",
    country: "United States",
    address: "1028 SE Water Ave, Portland, OR 97214",
    roaster: "Water Avenue Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "wateravenuecoffee",
    website: "https://wateravenuecoffee.com/",
    editorial_blurb: "Eastside Portland's precision roastery — their long extraction pour-overs and obsessive sourcing make the Hawthorne Bridge detour worthwhile.",
    featured_in: ["sprudge", "guardian"],
    verified: true,
    last_verified_at: "2024-10-10",
    verification_source: "admin",
  },
  {
    name: "Coava Coffee Roasters",
    slug: "coava-coffee-portland",
    lat: 45.5170,
    lng: -122.6604,
    city: "Portland",
    country: "United States",
    address: "1300 SE Grand Ave, Portland, OR 97214",
    roaster: "Coava Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "coavacoffee",
    website: "https://coava.coffee/",
    editorial_blurb: "Roastery inside a repurposed basketball court on Grand Ave — the scale of the space matches the ambition of the single-origin sourcing program.",
    featured_in: ["sprudge", "eater"],
    verified: true,
    last_verified_at: "2024-10-28",
    verification_source: "admin",
  },
  // MEXICO CITY addition
  {
    name: "Quentin Café",
    slug: "quentin-cafe-mexico-city",
    lat: 19.4017,
    lng: -99.1696,
    city: "Mexico City",
    country: "Mexico",
    address: "Insurgentes Sur 811, Colonia Nápoles, 03810 Ciudad de México",
    roaster: "Quentin Café",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "quentincafe",
    editorial_blurb: "Veracruz single-origins served from a serious pour-over bar in Nápoles — the best argument for CDMX's homegrown specialty beans.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-15",
    verification_source: "admin",
  },
];

export const SEED_CAFES: Cafe[] = rawCafes.map((cafe, index) => {
  const scoreBreakdown = calculateScore({
    roaster: cafe.roaster,
    brew_methods: cafe.brew_methods,
    vibe_tags: cafe.vibe_tags,
    featured_in: cafe.featured_in,
    community_upvotes: Math.floor(Math.random() * 8),
  });
  return {
    ...cafe,
    id: `cafe-${index + 1}`,
    created_at: new Date().toISOString(),
    third_wave_score: scoreBreakdown.total,
    overall_rating: 4.2 + Math.random() * 0.7,
    review_count: 50 + Math.floor(Math.random() * 200),
    permanently_closed: false,
    flagged: false,
    sponsored: false,
  };
});

export const SEED_CITIES = [
  { id: 'city-1', name: 'Tokyo', country: 'Japan', lat: 35.6762, lng: 139.6503, slug: 'tokyo', cafe_count: 3, city_blurb: 'Tokyo has elevated coffee into an art form — precision brewing, flawless service, and a density of world-class cafés that rivals any city on earth.' },
  { id: 'city-2', name: 'Copenhagen', country: 'Denmark', lat: 55.6761, lng: 12.5683, slug: 'copenhagen', cafe_count: 3, city_blurb: 'Scandinavia\'s coffee capital leads Europe on sourcing ethics and light-roast technique — every cup here feels considered.' },
  { id: 'city-3', name: 'Melbourne', country: 'Australia', lat: -37.8136, lng: 144.9631, slug: 'melbourne', cafe_count: 3, city_blurb: 'Melbourne\'s café culture is a civic institution — world-class flat whites and a roasting scene that exports talent globally.' },
  { id: 'city-4', name: 'New York City', country: 'United States', lat: 40.7128, lng: -74.0060, slug: 'new-york-city', cafe_count: 3, city_blurb: 'New York\'s specialty coffee scene is borough-by-borough diverse — Brooklyn leads on craft, Manhattan on volume, and the competition makes everyone better.' },
  { id: 'city-5', name: 'London', country: 'United Kingdom', lat: 51.5074, lng: -0.1278, slug: 'london', cafe_count: 2, city_blurb: 'London transformed from espresso-resistant to one of the world\'s most exciting coffee cities in a single decade — the east side is still the epicenter.' },
  { id: 'city-6', name: 'Montreal', country: 'Canada', lat: 45.5017, lng: -73.5673, slug: 'montreal', cafe_count: 2, city_blurb: 'Montreal\'s bilingual café culture and Québécois identity produce some of North America\'s most distinctive specialty shops.' },
  { id: 'city-7', name: 'Berlin', country: 'Germany', lat: 52.5200, lng: 13.4050, slug: 'berlin', cafe_count: 2, city_blurb: 'Berlin\'s third wave arrived with characteristic intensity — precise roasting, opinionated baristas, and spaces that double as cultural institutions.' },
  { id: 'city-8', name: 'Mexico City', country: 'Mexico', lat: 19.4326, lng: -99.1332, slug: 'mexico-city', cafe_count: 3, city_blurb: 'CDMX is rewriting what Mexican coffee means — local Oaxacan and Veracruz single-origins are finally getting the treatment they deserve.' },
  { id: 'city-9', name: 'Seoul', country: 'South Korea', lat: 37.5665, lng: 126.9780, slug: 'seoul', cafe_count: 2, city_blurb: 'Seoul\'s café density is unmatched anywhere — specialty coffee thrives alongside traditional tea culture and the aesthetics are always exceptional.' },
  { id: 'city-10', name: 'Cape Town', country: 'South Africa', lat: -33.9249, lng: 18.4241, slug: 'cape-town', cafe_count: 2, city_blurb: 'Cape Town\'s proximity to East African origins gives it an unfair advantage — roasters here work with some of the freshest beans on earth.' },
  { id: 'city-11', name: 'Buenos Aires', country: 'Argentina', lat: -34.6037, lng: -58.3816, slug: 'buenos-aires', cafe_count: 2, city_blurb: 'Buenos Aires is in the middle of a specialty coffee awakening — Palermo\'s independent roasteries are making the city\'s traditional café culture look again.' },
  { id: 'city-12', name: 'Portland', country: 'United States', lat: 45.5051, lng: -122.6750, slug: 'portland', cafe_count: 3, city_blurb: 'Portland\'s coffee heritage runs deep — this is where the American third wave started, and the roasting culture it built still sets global standards.' },
  { id: 'city-13', name: 'San Francisco', country: 'United States', lat: 37.7749, lng: -122.4194, slug: 'san-francisco', cafe_count: 3, city_blurb: 'San Francisco\'s specialty scene is as opinionated as the city itself — SOMA roasteries and Mission standing bars set the West Coast benchmark.' },
  { id: 'city-14', name: 'Chicago', country: 'United States', lat: 41.8781, lng: -87.6298, slug: 'chicago', cafe_count: 3, city_blurb: 'Chicago\'s third-wave story starts with Intelligentsia and keeps getting better — the West Loop and Wicker Park are now among America\'s most exciting coffee corridors.' },
  { id: 'city-15', name: 'Paris', country: 'France', lat: 48.8566, lng: 2.3522, slug: 'paris', cafe_count: 3, city_blurb: 'Paris resisted specialty coffee and then embraced it completely — the 10th and 18th arrondissements are now home to some of Europe\'s most exciting new roasters.' },
  { id: 'city-16', name: 'Amsterdam', country: 'Netherlands', lat: 52.3676, lng: 4.9041, slug: 'amsterdam', cafe_count: 3, city_blurb: 'Amsterdam\'s canal-side café culture found a new gear when specialty roasters arrived — the Jordaan and Amsterdam West are the places to start.' },
  { id: 'city-17', name: 'Sydney', country: 'Australia', lat: -33.8688, lng: 151.2093, slug: 'sydney', cafe_count: 3, city_blurb: 'Sydney\'s Surry Hills is Australia\'s most concentrated specialty coffee district — three world-class roasteries within walking distance of each other.' },
  { id: 'city-18', name: 'Vienna', country: 'Austria', lat: 48.2082, lng: 16.3738, slug: 'vienna', cafe_count: 3, city_blurb: 'Vienna perfected café culture centuries ago and is now adding specialty precision to the tradition — the combination is unlike anywhere else in Europe.' },
  { id: 'city-19', name: 'Stockholm', country: 'Sweden', lat: 59.3293, lng: 18.0686, slug: 'stockholm', cafe_count: 3, city_blurb: 'Stockholm\'s Södermalm roasteries have shaped how all of Scandinavia thinks about light roasting and ethical sourcing — the world is still catching up.' },
  { id: 'city-20', name: 'Lisbon', country: 'Portugal', lat: 38.7169, lng: -9.1399, slug: 'lisbon', cafe_count: 3, city_blurb: 'Lisbon\'s specialty scene arrived late but moved fast — Chiado and Príncipe Real are now home to some of the most interesting cafés in southern Europe.' },
  { id: 'city-21', name: 'Barcelona', country: 'Spain', lat: 41.3851, lng: 2.1734, slug: 'barcelona', cafe_count: 3, city_blurb: 'Barcelona\'s specialty coffee scene is as design-conscious as the city itself — Poblenou\'s roasteries and El Born\'s bars are raising the bar for all of Spain.' },
  { id: 'city-22', name: 'Singapore', country: 'Singapore', lat: 1.3521, lng: 103.8198, slug: 'singapore', cafe_count: 3, city_blurb: 'Singapore\'s coffee culture runs from hawker-centre kopi to competition-level pour-overs — the specialty scene here is among Asia\'s most sophisticated.' },
  { id: 'city-23', name: 'Taipei', country: 'Taiwan', lat: 25.0330, lng: 121.5654, slug: 'taipei', cafe_count: 3, city_blurb: 'Taipei\'s barista talent and roasting culture are world-class — world competition champions run cafés here and the density of quality is quietly remarkable.' },
  { id: 'city-24', name: 'São Paulo', country: 'Brazil', lat: -23.5505, lng: -46.6333, slug: 'sao-paulo', cafe_count: 3, city_blurb: 'The world\'s largest coffee-producing country is finally drinking its own best beans — São Paulo\'s Vila Madalena and Pinheiros lead that transformation.' },
  { id: 'city-25', name: 'Istanbul', country: 'Turkey', lat: 41.0082, lng: 28.9784, slug: 'istanbul', cafe_count: 3, city_blurb: 'Istanbul\'s specialty scene sits at the crossroads of coffee history — Cihangir and Karaköy roasters are building something entirely new on ancient grounds.' },
  { id: 'city-26', name: 'Nairobi', country: 'Kenya', lat: -1.2921, lng: 36.8219, slug: 'nairobi', cafe_count: 3, city_blurb: 'Nairobi is the world\'s most exciting origin city for coffee — drinking single-farm Kenyan lots here, where they\'re grown and roasted, is irreplaceable.' },
  { id: 'city-27', name: 'Ho Chi Minh City', country: 'Vietnam', lat: 10.8231, lng: 106.6297, slug: 'ho-chi-minh-city', cafe_count: 3, city_blurb: 'Ho Chi Minh City has one of the world\'s oldest café cultures and is now adding specialty precision to it — District 1\'s third-wave scene is worth the trip alone.' },
  { id: 'city-28', name: 'Osaka', country: 'Japan', lat: 34.6937, lng: 135.5023, slug: 'osaka', cafe_count: 3, city_blurb: 'Osaka\'s coffee scene is Tokyo\'s more relaxed sibling — Kitahama and Namba have quietly built a specialty culture that rewards the traveler who looks beyond ramen.' },
];
