import type { Cafe } from '@/types';

export const ASIA_RAW_CAFES: Omit<Cafe, 'id' | 'created_at' | 'third_wave_score' | 'overall_rating' | 'review_count' | 'permanently_closed'>[] = [
  // ── TOKYO (20) ───────────────────────────────────────────────────────────────
  {
    name: "Fuglen Tokyo",
    slug: "fuglen-tokyo",
    lat: 35.6696, lng: 139.6916,
    city: "Tokyo", country: "Japan",
    address: "1-16-11 Tomigaya, Shibuya-ku, Tokyo",
    roaster: "Fuglen Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "fuglentokyo",
    website: "https://www.fuglen.com/",
    editorial_blurb: "Oslo's cult café landed in Tokyo and raised the bar for the entire city — order the pour-over and stay for the vintage furniture.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2024-11-01", verification_source: "admin",
  },
  {
    name: "Koffee Mameya",
    slug: "koffee-mameya",
    lat: 35.6654, lng: 139.7104,
    city: "Tokyo", country: "Japan",
    address: "4-15-3 Jingumae, Shibuya-ku, Tokyo",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso"],
    vibe_tags: ["standing-bar", "minimalist"],
    instagram_handle: "koffee_mameya",
    website: "https://koffee-mameya.com/",
    editorial_blurb: "No menu, no seating — just a barista asking what you want and delivering the precise cup you didn't know you needed.",
    featured_in: ["sprudge", "ny_times"],
    verified: true, last_verified_at: "2024-10-15", verification_source: "admin",
  },
  {
    name: "Switch Coffee Tokyo",
    slug: "switch-coffee-tokyo",
    lat: 35.6952, lng: 139.7049,
    city: "Tokyo", country: "Japan",
    address: "Minami-Aoyama 6-6-22, Minato-ku, Tokyo",
    roaster: "Switch Coffee",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "switchcoffeetokyo",
    editorial_blurb: "A quietly confident roastery café in Aoyama where single-origins rotate weekly and the staff genuinely wants to talk about terroir.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-20", verification_source: "admin",
  },
  {
    name: "% Arabica Tokyo",
    slug: "arabica-tokyo-aoyama",
    lat: 35.6640, lng: 139.7099,
    city: "Tokyo", country: "Japan",
    address: "5-17-13 Minami-Aoyama, Minato-ku, Tokyo",
    roaster: "% Arabica",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "arabica.tokyo",
    website: "https://www.arabica.coffee/",
    editorial_blurb: "The Kyoto minimalist icon's Aoyama home — a white cube where the espresso is as considered as the architecture.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2024-11-08", verification_source: "admin",
  },
  {
    name: "Glitch Coffee & Roasters",
    slug: "glitch-coffee-tokyo",
    lat: 35.6963, lng: 139.7590,
    city: "Tokyo", country: "Japan",
    address: "3-16 Kanda Nishikicho, Chiyoda-ku, Tokyo",
    roaster: "Glitch Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "glitch_coffee",
    website: "https://glitchcoffee.com/",
    editorial_blurb: "Jimbocho roastery with a world-competition record and a filter menu that changes based on what's peaking — the most technically serious café in Tokyo.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2024-10-28", verification_source: "admin",
  },
  {
    name: "Onibus Coffee",
    slug: "onibus-coffee-nakameguro",
    lat: 35.6401, lng: 139.7004,
    city: "Tokyo", country: "Japan",
    address: "2-14-1 Kamimeguro, Meguro-ku, Tokyo",
    roaster: "Onibus Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "onibuscoffee",
    website: "https://onibuscoffee.com/",
    editorial_blurb: "Nakameguro roastery tucked off the canal — the Portuguese name (bus) fits a café built on movement, sourcing, and sharing.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2024-11-03", verification_source: "admin",
  },
  {
    name: "Woodberry Coffee Roasters",
    slug: "woodberry-coffee-tokyo",
    lat: 35.7122, lng: 139.7744,
    city: "Tokyo", country: "Japan",
    address: "1-19-8 Yanaka, Taito-ku, Tokyo",
    roaster: "Woodberry Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "laptop-friendly"],
    instagram_handle: "woodberrycoffee",
    website: "https://woodberrycoffee.com/",
    editorial_blurb: "Yanaka roastery in Tokyo's most atmospheric old neighborhood — Ethiopian and Central American lots roasted with uncommon clarity.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-18", verification_source: "admin",
  },
  {
    name: "Sarutahiko Coffee",
    slug: "sarutahiko-coffee-ebisu",
    lat: 35.6468, lng: 139.7099,
    city: "Tokyo", country: "Japan",
    address: "1-6-6 Ebisu, Shibuya-ku, Tokyo",
    roaster: "Sarutahiko Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["standing-bar", "minimalist"],
    instagram_handle: "sarutahiko_coffee",
    editorial_blurb: "Ebisu standing bar with an obsessive drip culture and a compact menu that never wastes your time or your palate.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-10", verification_source: "admin",
  },
  {
    name: "About Life Coffee Brewers",
    slug: "about-life-coffee-shibuya",
    lat: 35.6587, lng: 139.6979,
    city: "Tokyo", country: "Japan",
    address: "1-19-8 Dogenzaka, Shibuya-ku, Tokyo",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["standing-bar", "minimalist"],
    instagram_handle: "aboutlifecoffee",
    editorial_blurb: "Shibuya standing counter with a rotating guest-roaster program — the name is a provocation, the coffee makes good on it.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-05", verification_source: "admin",
  },
  {
    name: "Blue Bottle Coffee Kiyosumi",
    slug: "blue-bottle-kiyosumi-tokyo",
    lat: 35.6778, lng: 139.8052,
    city: "Tokyo", country: "Japan",
    address: "4-7-2 Hirano, Koto-ku, Tokyo",
    roaster: "Blue Bottle Coffee",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "bluebottlejpn",
    website: "https://bluebottlecoffee.com/",
    editorial_blurb: "Blue Bottle's Tokyo flagship in a converted Kiyosumi warehouse — the roastery that announced specialty coffee's arrival in Japan to a global audience.",
    featured_in: ["sprudge", "ny_times", "monocle"],
    verified: true, last_verified_at: "2024-11-02", verification_source: "admin",
  },
  {
    name: "Arise Coffee Entangle",
    slug: "arise-coffee-tokyo",
    lat: 35.6781, lng: 139.8044,
    city: "Tokyo", country: "Japan",
    address: "3-16-3 Shirakawa, Koto-ku, Tokyo",
    roaster: "Arise Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "arisecoffeeentangle",
    editorial_blurb: "Blue Bottle's neighbor in Kiyosumi-Shirakawa doing equally serious work in a fraction of the space — a local institution with a cult following.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-20", verification_source: "admin",
  },
  {
    name: "Bear Pond Espresso",
    slug: "bear-pond-espresso-tokyo",
    lat: 35.6615, lng: 139.6673,
    city: "Tokyo", country: "Japan",
    address: "2-36-12 Kitazawa, Setagaya-ku, Tokyo",
    roaster: "Bear Pond Espresso",
    brew_methods: ["espresso"],
    vibe_tags: ["standing-bar", "no-laptop"],
    instagram_handle: "bearpondespresso",
    editorial_blurb: "Shimokitazawa espresso purist — a single counter, a single focus, and the most intensely discussed shot in Tokyo. Cash only, always worth it.",
    featured_in: ["sprudge", "guardian"],
    verified: true, last_verified_at: "2024-10-08", verification_source: "admin",
  },
  {
    name: "Streamer Coffee Company",
    slug: "streamer-coffee-shibuya",
    lat: 35.6597, lng: 139.6977,
    city: "Tokyo", country: "Japan",
    address: "1-20-28 Shibuya, Shibuya-ku, Tokyo",
    roaster: "Streamer Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "streamercoffee",
    website: "https://streamer.coffee/",
    editorial_blurb: "Streamer's latte art championship roots are on the walls; the espresso program that won those titles is in the cup.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-25", verification_source: "admin",
  },
  {
    name: "Nozy Coffee",
    slug: "nozy-coffee-sangenjaya",
    lat: 35.6439, lng: 139.6708,
    city: "Tokyo", country: "Japan",
    address: "5-17-13 Sangenjaya, Setagaya-ku, Tokyo",
    roaster: "Nozy Coffee",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "nozycoffee",
    editorial_blurb: "Sangenjaya roastery that helped define Tokyo's third-wave generation — the outdoor bench and a single-origin V60 are all you need here.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-15", verification_source: "admin",
  },
  {
    name: "Coffee Supreme Tokyo",
    slug: "coffee-supreme-tokyo",
    lat: 35.6690, lng: 139.7079,
    city: "Tokyo", country: "Japan",
    address: "6-12-6 Jingumae, Shibuya-ku, Tokyo",
    roaster: "Coffee Supreme",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "coffeesupreme",
    website: "https://coffeesupreme.com/",
    editorial_blurb: "New Zealand's most revered roastery in the heart of Harajuku — the Antipodean irreverence and the technical precision are both very real.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2024-10-22", verification_source: "admin",
  },
  {
    name: "Passage Coffee",
    slug: "passage-coffee-tokyo",
    lat: 35.6788, lng: 139.7215,
    city: "Tokyo", country: "Japan",
    address: "3-7 Sendagaya, Shibuya-ku, Tokyo",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "passagecoffee",
    editorial_blurb: "Sendagaya narrow-front café where the guest-roaster list reads like a Tokyo specialty map — a reliable stop before or after a Meiji Shrine morning.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-28", verification_source: "admin",
  },
  {
    name: "Eagle Coffee",
    slug: "eagle-coffee-tokyo",
    lat: 35.6416, lng: 139.7026,
    city: "Tokyo", country: "Japan",
    address: "1-3-19 Nakameguro, Meguro-ku, Tokyo",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["outdoor-seating", "minimalist"],
    instagram_handle: "eaglecoffee_tokyo",
    editorial_blurb: "Canal-side Nakameguro perch where the cherry blossoms are seasonal but the single-origin pour-overs are year-round excellent.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-01", verification_source: "community",
  },
  {
    name: "Paul Bassett",
    slug: "paul-bassett-shinjuku",
    lat: 35.6917, lng: 139.7033,
    city: "Tokyo", country: "Japan",
    address: "3-38-1 Shinjuku, Shinjuku-ku, Tokyo",
    roaster: "Paul Bassett",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "paulbassettcoffee",
    website: "https://www.paulbassett.com/",
    editorial_blurb: "World barista champion Paul Bassett's Shinjuku flagship — the espresso-as-craft philosophy translates into one of Tokyo's most quietly excellent menus.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-15", verification_source: "admin",
  },
  {
    name: "Café Kitsuné Aoyama",
    slug: "cafe-kitsune-aoyama-tokyo",
    lat: 35.6641, lng: 139.7121,
    city: "Tokyo", country: "Japan",
    address: "3-17-1 Minami-Aoyama, Minato-ku, Tokyo",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "cafekitsune",
    website: "https://cafekitsune.com/",
    editorial_blurb: "Fashion house garden café in Aoyama where the design is exceptional and the specialty espresso is serious — both are reasons to visit.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2024-11-06", verification_source: "admin",
  },
  {
    name: "Coffee Wrights Sendagaya",
    slug: "coffee-wrights-sendagaya",
    lat: 35.6810, lng: 139.7092,
    city: "Tokyo", country: "Japan",
    address: "4-3-4 Sendagaya, Shibuya-ku, Tokyo",
    roaster: "Coffee Wrights",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "outdoor-seating"],
    instagram_handle: "coffee_wrights",
    editorial_blurb: "Yoyogi Park-adjacent coffee stand that captures what Tokyo neighbourhood specialty does best — a small menu, rotating origins, and no fuss.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-18", verification_source: "community",
  },

  // ── SEOUL (15) ───────────────────────────────────────────────────────────────
  {
    name: "Fritz Coffee Company",
    slug: "fritz-coffee-seoul",
    lat: 37.5139, lng: 126.9931,
    city: "Seoul", country: "South Korea",
    address: "11-5 Mapo-daero 18-gil, Mapo-gu, Seoul",
    roaster: "Fritz Coffee",
    brew_methods: ["pour-over", "espresso", "syphon"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "fritzcoffeecompany",
    website: "https://www.fritzcoffee.co.kr/",
    editorial_blurb: "Seoul's most beloved roastery café — the Saturday morning queue is a pilgrimage and the single-origins justify every minute of it.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2024-11-06", verification_source: "admin",
  },
  {
    name: "Namusairo",
    slug: "namusairo-seoul",
    lat: 37.5796, lng: 126.9770,
    city: "Seoul", country: "South Korea",
    address: "21 Jahamun-ro 5-gil, Jongno-gu, Seoul",
    roaster: "Namusairo",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "namusairo",
    editorial_blurb: "Tucked in Bukchon Hanok Village, Namusairo pairs traditional architecture with technically immaculate pour-overs — a rare combination.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2024-10-08", verification_source: "admin",
  },
  {
    name: "% Arabica Seoul",
    slug: "arabica-seoul-apgujeong",
    lat: 37.5270, lng: 127.0012,
    city: "Seoul", country: "South Korea",
    address: "Apgujeong-ro, Gangnam-gu, Seoul",
    roaster: "% Arabica",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "arabica.seoul",
    website: "https://www.arabica.coffee/",
    editorial_blurb: "Kyoto's global minimalist icon in Apgujeong — the same quiet precision, the same exceptional espresso, the same insistence on doing one thing right.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-25", verification_source: "admin",
  },
  {
    name: "Onion Anguk",
    slug: "onion-anguk-seoul",
    lat: 37.5790, lng: 126.9869,
    city: "Seoul", country: "South Korea",
    address: "102 Gyedong-gil, Jongno-gu, Seoul",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["no-laptop", "outdoor-seating"],
    instagram_handle: "onion.anguk",
    editorial_blurb: "Bukchon heritage building turned brutalist bakery-café — the concrete interior and the cardamom croissants are both reasons to queue.",
    featured_in: ["sprudge", "guardian"],
    verified: true, last_verified_at: "2024-10-30", verification_source: "admin",
  },
  {
    name: "Coffee Libre",
    slug: "coffee-libre-seoul",
    lat: 37.5578, lng: 126.9266,
    city: "Seoul", country: "South Korea",
    address: "Yeonnam-dong, Mapo-gu, Seoul",
    roaster: "Coffee Libre",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "coffeelibre",
    website: "https://coffeelibre.kr/",
    editorial_blurb: "Yeonnam-dong roastery that built the Seoul specialty movement before it had a name — their Latin American sourcing program is still the city's best.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2024-10-18", verification_source: "admin",
  },
  {
    name: "Anthracite Coffee Roasters",
    slug: "anthracite-coffee-seoul",
    lat: 37.5435, lng: 126.9908,
    city: "Seoul", country: "South Korea",
    address: "131 Itaewon-ro, Yongsan-gu, Seoul",
    roaster: "Anthracite Coffee",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "anthracitecoffee",
    website: "https://www.anthracitecoffee.com/",
    editorial_blurb: "Itaewon industrial roastery in a converted shoe factory — the space is as compelling as the light-roast single-origins brewed inside it.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2024-11-01", verification_source: "admin",
  },
  {
    name: "Meter Coffee",
    slug: "meter-coffee-seoul",
    lat: 37.5440, lng: 127.0605,
    city: "Seoul", country: "South Korea",
    address: "Seongsu-dong 2-ga, Seongdong-gu, Seoul",
    roaster: "Meter Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "outdoor-seating"],
    instagram_handle: "meter_coffee",
    editorial_blurb: "Seongsu industrial café where the espresso dialing is taken as seriously as the concrete design — Seoul's coolest neighbourhood finally has its anchor.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-20", verification_source: "admin",
  },
  {
    name: "Manufact Coffee Roasters",
    slug: "manufact-coffee-seoul",
    lat: 37.5453, lng: 127.0579,
    city: "Seoul", country: "South Korea",
    address: "Seongsu-dong, Seongdong-gu, Seoul",
    roaster: "Manufact Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "manufact_coffee",
    editorial_blurb: "Seongsu roastery café with a serious light-roast commitment and a filter program that's been shaping Seoul palates for years.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-12", verification_source: "admin",
  },
  {
    name: "Raw Sugar",
    slug: "raw-sugar-seochon-seoul",
    lat: 37.5795, lng: 126.9735,
    city: "Seoul", country: "South Korea",
    address: "Seochon, Jongno-gu, Seoul",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso"],
    vibe_tags: ["no-laptop", "outdoor-seating"],
    instagram_handle: "rawsugar_official",
    editorial_blurb: "Seochon village café where the hanok streetscape and the natural-process pour-overs produce a combination that feels specific to Seoul.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-22", verification_source: "community",
  },
  {
    name: "Terarosa Coffee Seoul",
    slug: "terarosa-coffee-seoul",
    lat: 37.5186, lng: 127.0262,
    city: "Seoul", country: "South Korea",
    address: "Cheongdam-dong, Gangnam-gu, Seoul",
    roaster: "Terarosa Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "terarosacoffee",
    website: "https://www.terarosa.com/",
    editorial_blurb: "Gangneung's legendary roastery in Seoul — Terarosa's Gangnam outpost brings the same obsessive sourcing and light-roast conviction to the capital.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2024-11-04", verification_source: "admin",
  },
  {
    name: "Lowkey Coffee",
    slug: "lowkey-coffee-itaewon",
    lat: 37.5434, lng: 126.9880,
    city: "Seoul", country: "South Korea",
    address: "Itaewon-ro, Yongsan-gu, Seoul",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "lowkeycoffee",
    editorial_blurb: "Itaewon specialty bar where the name is the ethos — no flashy design, just excellent espresso and a rotating filter menu worth returning for.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-18", verification_source: "community",
  },
  {
    name: "Felt Coffee",
    slug: "felt-coffee-seoul",
    lat: 37.5512, lng: 126.9118,
    city: "Seoul", country: "South Korea",
    address: "Mangwon-dong, Mapo-gu, Seoul",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "felt_espresso",
    editorial_blurb: "Mangwon neighborhood café with a warm atmosphere and a filter menu that changes more often than you'd expect — always worth the detour.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-10", verification_source: "community",
  },
  {
    name: "Zagmachi",
    slug: "zagmachi-seoul",
    lat: 37.5832, lng: 126.9871,
    city: "Seoul", country: "South Korea",
    address: "Gahoe-dong, Jongno-gu, Seoul",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "zagmachi",
    editorial_blurb: "Bukchon alley café where the hanok setting and the precise pour-over make a strong case for slowing down in the city's fastest neighborhood.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-05", verification_source: "community",
  },
  {
    name: "Onion Ahyeon",
    slug: "onion-ahyeon-seoul",
    lat: 37.5590, lng: 126.9574,
    city: "Seoul", country: "South Korea",
    address: "Ahyeon-dong, Mapo-gu, Seoul",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["no-laptop", "outdoor-seating"],
    instagram_handle: "onion.ahyeon",
    editorial_blurb: "Brutalist Mapo-gu powerhouse with a rooftop terrace and a café program that punches well above most bakery-coffee hybrids.",
    featured_in: ["sprudge", "guardian"],
    verified: true, last_verified_at: "2024-10-22", verification_source: "admin",
  },
  {
    name: "Café Layered",
    slug: "cafe-layered-seochon",
    lat: 37.5775, lng: 126.9694,
    city: "Seoul", country: "South Korea",
    address: "Seochon, Jongno-gu, Seoul",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "cafe_layered",
    editorial_blurb: "Seochon multi-floor café where the specialty coffee is as considered as the layered Korean desserts — a neighborhood institution with staying power.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-15", verification_source: "community",
  },

  // ── SINGAPORE (12) ───────────────────────────────────────────────────────────
  {
    name: "Nylon Coffee Roasters",
    slug: "nylon-coffee-singapore",
    lat: 1.2796, lng: 103.8390,
    city: "Singapore", country: "Singapore",
    address: "4 Everton Park #01-40, Singapore 080004",
    roaster: "Nylon Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "nyloncoffee",
    website: "https://www.nyloncoffee.sg/",
    editorial_blurb: "Tanjong Pagar institution that defined Singapore specialty — Everton Park HDB block setting is as iconic as the coffee itself.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2024-11-06", verification_source: "admin",
  },
  {
    name: "Cata",
    slug: "cata-singapore",
    lat: 1.2772, lng: 103.8424,
    city: "Singapore", country: "Singapore",
    address: "1 Tanjong Pagar Plaza #01-01, Singapore 082001",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "cata_sg",
    editorial_blurb: "Where Singapore's wine bar scene meets specialty coffee — the curated pairing menu makes Cata one of the city's most original concepts.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-15", verification_source: "admin",
  },
  {
    name: "Chye Seng Huat Hardware",
    slug: "chye-seng-huat-singapore",
    lat: 1.3127, lng: 103.8644,
    city: "Singapore", country: "Singapore",
    address: "150 Tyrwhitt Rd, Singapore 207563",
    roaster: "Papa Palheta",
    brew_methods: ["pour-over", "espresso", "syphon", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "laptop-friendly"],
    instagram_handle: "cshhardware",
    website: "https://www.cshhardware.com/",
    editorial_blurb: "Converted hardware shop turned roastery flagship — the courtyard, the pour-overs, and the industrial bones are all reasons to visit.",
    featured_in: ["sprudge", "guardian"],
    verified: true, last_verified_at: "2024-10-28", verification_source: "admin",
  },
  {
    name: "Common Man Coffee Roasters",
    slug: "common-man-coffee-singapore",
    lat: 1.2888, lng: 103.8400,
    city: "Singapore", country: "Singapore",
    address: "22 Martin Rd, Singapore 239058",
    roaster: "Common Man Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "commonmancoffeeroasters",
    website: "https://www.commonmancoffeeroasters.com/",
    editorial_blurb: "Robertson Quay roastery that made specialty coffee accessible without dumbing it down — the training academy and the café are both world-class.",
    featured_in: ["sprudge", "standart", "monocle"],
    verified: true, last_verified_at: "2024-11-05", verification_source: "admin",
  },
  {
    name: "Sarnies",
    slug: "sarnies-singapore",
    lat: 1.2815, lng: 103.8480,
    city: "Singapore", country: "Singapore",
    address: "136 Telok Ayer St, Singapore 068601",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["no-laptop", "outdoor-seating"],
    instagram_handle: "sarniessg",
    editorial_blurb: "Telok Ayer shophouse café where the Antipodean sandwich and the flat white are equally non-negotiable — CBD specialty coffee done right.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2024-10-20", verification_source: "admin",
  },
  {
    name: "PPP Coffee",
    slug: "ppp-coffee-singapore",
    lat: 1.2852, lng: 103.8300,
    city: "Singapore", country: "Singapore",
    address: "Tiong Bahru, Singapore",
    roaster: "PPP Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "pppcoffee",
    website: "https://www.pppcoffee.com/",
    editorial_blurb: "Tiong Bahru roastery that started as a delivery service and became one of Singapore's most progressive specialty programs — the subscriptions built the café.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-10", verification_source: "admin",
  },
  {
    name: "Jewel Coffee",
    slug: "jewel-coffee-singapore",
    lat: 1.2905, lng: 103.8550,
    city: "Singapore", country: "Singapore",
    address: "Near Raffles Place, Singapore",
    roaster: "Jewel Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "jewel_coffee",
    editorial_blurb: "CBD specialty café serving some of the city's most consistent espresso to Singapore's finance district — the after-work filter crowd is loyal for a reason.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-25", verification_source: "admin",
  },
  {
    name: "Ronin",
    slug: "ronin-singapore",
    lat: 1.2804, lng: 103.8490,
    city: "Singapore", country: "Singapore",
    address: "Telok Ayer St, Singapore",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "roninsg",
    editorial_blurb: "Telok Ayer specialty bar where the focused menu and the stripped-back aesthetic let the coffee do the talking — and it always has something interesting to say.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-15", verification_source: "community",
  },
  {
    name: "Columbus Coffee Co.",
    slug: "columbus-coffee-singapore",
    lat: 1.3112, lng: 103.7956,
    city: "Singapore", country: "Singapore",
    address: "Holland Village, Singapore",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "columbuscoffeeco",
    editorial_blurb: "Holland Village neighborhood anchor with a breezy terrace and a reliable specialty program — the kind of café that keeps a neighborhood grounded.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-10", verification_source: "community",
  },
  {
    name: "Assembly Coffee",
    slug: "assembly-coffee-singapore",
    lat: 1.2752, lng: 103.8004,
    city: "Singapore", country: "Singapore",
    address: "Pasir Panjang Rd, Singapore",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "assemblycoffee",
    editorial_blurb: "Singapore specialty café with a clean aesthetic and a filter menu that changes more often than most — always worth checking what's on the bar.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-05", verification_source: "community",
  },
  {
    name: "Tiong Hoe Specialty Coffee",
    slug: "tiong-hoe-coffee-singapore",
    lat: 1.2840, lng: 103.8261,
    city: "Singapore", country: "Singapore",
    address: "Tiong Bahru, Singapore",
    roaster: "Tiong Hoe",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "tionghoecoffee",
    editorial_blurb: "Tiong Bahru roastery that's been quietly excellent for longer than most — the house roasts and the barista knowledge both reward the regular.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-08", verification_source: "admin",
  },
  {
    name: "Kafe Utu",
    slug: "kafe-utu-singapore",
    lat: 1.2786, lng: 103.8391,
    city: "Singapore", country: "Singapore",
    address: "12 Jiak Chuan Rd, Singapore 089265",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "kafeutu",
    editorial_blurb: "Pan-African specialty café in Duxton with East African sourcing focus — drinking single-farm Ethiopian or Kenyan here, surrounded by the continent's art, is something else.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2024-10-22", verification_source: "admin",
  },

  // ── TAIPEI (11) ──────────────────────────────────────────────────────────────
  {
    name: "Fika Fika Café",
    slug: "fika-fika-taipei",
    lat: 25.0611, lng: 121.5237,
    city: "Taipei", country: "Taiwan",
    address: "No. 33, Yitong St, Zhongshan District, Taipei 104",
    roaster: "Fika Fika",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "fikafika_cafe",
    website: "https://www.fikafika.com.tw/",
    editorial_blurb: "Taiwan's first Scandinavian-style roastery brought light-roast competition culture to Taipei — and the city never looked back.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2024-11-02", verification_source: "admin",
  },
  {
    name: "Simple Kaffa",
    slug: "simple-kaffa-taipei",
    lat: 25.0290, lng: 121.5434,
    city: "Taipei", country: "Taiwan",
    address: "No. 54, Lane 243, Sec 1, Dunhua S Rd, Da'an, Taipei",
    roaster: "Simple Kaffa",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "simplekaffa",
    website: "https://simplekaffa.com/",
    editorial_blurb: "World barista champion Berg Wu's Da'an flagship — technically flawless espresso from a café that's earned every accolade it carries.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2024-11-08", verification_source: "admin",
  },
  {
    name: "Rufous Coffee",
    slug: "rufous-coffee-taipei",
    lat: 25.0585, lng: 121.5224,
    city: "Taipei", country: "Taiwan",
    address: "No. 1, Lane 40, Xinsheng N Rd, Zhongshan, Taipei",
    roaster: "Rufous Coffee",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "rufous_coffee",
    editorial_blurb: "Zhongshan's serious single-origin program draws the kind of crowd that wants to talk about altitude and processing — and the baristas are ready.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-05", verification_source: "admin",
  },
  {
    name: "% Arabica Taipei",
    slug: "arabica-taipei",
    lat: 25.0534, lng: 121.5249,
    city: "Taipei", country: "Taiwan",
    address: "Zhongshan District, Taipei",
    roaster: "% Arabica",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "arabica.taipei",
    website: "https://www.arabica.coffee/",
    editorial_blurb: "The Kyoto minimalist icon in Zhongshan — the same precision pour-over, the same calm intention, the same reason to stay for a second cup.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-20", verification_source: "admin",
  },
  {
    name: "Gabee Coffee",
    slug: "gabee-coffee-taipei",
    lat: 25.0546, lng: 121.5311,
    city: "Taipei", country: "Taiwan",
    address: "No. 8, Lane 96, Zhongshan N Rd, Zhongshan, Taipei",
    roaster: "Gabee",
    brew_methods: ["espresso", "pour-over", "syphon"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "gabeecoffee",
    website: "https://www.gabee.com.tw/",
    editorial_blurb: "Zhongshan latte art pioneer that helped build Taiwan's barista culture — still one of Taipei's most essential café-roastery experiences.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2024-10-28", verification_source: "admin",
  },
  {
    name: "MJCOFFEE",
    slug: "mjcoffee-taipei",
    lat: 25.0503, lng: 121.5268,
    city: "Taipei", country: "Taiwan",
    address: "Zhongshan District, Taipei",
    roaster: "MJCOFFEE",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "mjcoffee.tw",
    editorial_blurb: "Progressive Zhongshan specialty café with one of Taipei's most forward-thinking filter programs — the sourcing notes are always worth reading.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-10", verification_source: "admin",
  },
  {
    name: "15g Specialty Coffee",
    slug: "15g-specialty-taipei",
    lat: 25.0307, lng: 121.5411,
    city: "Taipei", country: "Taiwan",
    address: "Da'an District, Taipei",
    roaster: "15g",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "15g_coffee",
    editorial_blurb: "Da'an roastery built on competition-level sourcing and a belief that every gram matters — the filter menu rewards the curious.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-28", verification_source: "community",
  },
  {
    name: "Goodman Roaster",
    slug: "goodman-roaster-taipei",
    lat: 25.0328, lng: 121.5659,
    city: "Taipei", country: "Taiwan",
    address: "Xinyi District, Taipei",
    roaster: "Goodman Roaster",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "goodmanroaster",
    editorial_blurb: "Xinyi roastery café doing serious filter work in the shadow of Taipei 101 — the setting is dramatic, the coffee is the reason to come back.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-05", verification_source: "community",
  },
  {
    name: "WA Living Coffee",
    slug: "wa-living-taipei",
    lat: 25.0540, lng: 121.5299,
    city: "Taipei", country: "Taiwan",
    address: "Zhongshan District, Taipei",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "wa_living",
    editorial_blurb: "Japanese-influenced lifestyle café in Zhongshan where the ceramics, the coffee, and the calm are equally worth your time.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-15", verification_source: "community",
  },
  {
    name: "Zhi Xin Coffee",
    slug: "zhi-xin-coffee-taipei",
    lat: 25.0499, lng: 121.5316,
    city: "Taipei", country: "Taiwan",
    address: "Zhongshan District, Taipei",
    roaster: "Zhi Xin Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "zhixincoffee",
    editorial_blurb: "Zhongshan roastery focused on Taiwanese-adjacent origins from Southeast Asia — a sourcing philosophy that makes the filter menu distinctly different.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-10", verification_source: "community",
  },
  {
    name: "Hiyori Coffee",
    slug: "hiyori-coffee-taipei",
    lat: 25.0434, lng: 121.5432,
    city: "Taipei", country: "Taiwan",
    address: "Da'an District, Taipei",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "hiyori_coffee_tw",
    editorial_blurb: "Da'an specialty café where the Japanese-minimalist aesthetic and the rotating pour-over menu both reward multiple visits.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-05", verification_source: "community",
  },

  // ── OSAKA (10) ───────────────────────────────────────────────────────────────
  {
    name: "% Arabica Osaka Kitahama",
    slug: "arabica-osaka-kitahama",
    lat: 34.6898, lng: 135.5101,
    city: "Osaka", country: "Japan",
    address: "1-1-1 Kitahama, Chuo-ku, Osaka",
    roaster: "% Arabica",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "outdoor-seating", "no-laptop"],
    instagram_handle: "arabica.osaka",
    website: "https://www.arabica.coffee/",
    editorial_blurb: "Iconic river-facing minimalist space where Kitahama's beauty meets specialty precision — the best Instagram backdrop in Osaka that actually earns it.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2024-11-07", verification_source: "admin",
  },
  {
    name: "Kurasu Osaka",
    slug: "kurasu-osaka-shinsaibashi",
    lat: 34.6724, lng: 135.5011,
    city: "Osaka", country: "Japan",
    address: "1-7-1 Shinsaibashisuji, Chuo-ku, Osaka",
    roaster: "Kurasu",
    brew_methods: ["pour-over", "espresso", "aeropress", "chemex"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "kurasucoffee",
    website: "https://kurasu.kyoto/",
    editorial_blurb: "Kyoto roastery's Osaka flagship bringing direct-trade beans and Shinsaibashi foot traffic together — the pour-over menu rewards the extra walk.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2024-10-22", verification_source: "admin",
  },
  {
    name: "Mel Coffee Roasters",
    slug: "mel-coffee-roasters-osaka",
    lat: 34.6654, lng: 135.5032,
    city: "Osaka", country: "Japan",
    address: "Namba, Chuo-ku, Osaka",
    roaster: "Mel Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "melcoffeeroasters",
    editorial_blurb: "Namba roastery with a natural-process focus that stands apart from Osaka's lighter-roast mainstream — complex and worth seeking out.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-08", verification_source: "admin",
  },
  {
    name: "LiLo Coffee Roasters",
    slug: "lilo-coffee-osaka",
    lat: 34.6715, lng: 135.4993,
    city: "Osaka", country: "Japan",
    address: "1-7-19 Minamisenba, Chuo-ku, Osaka",
    roaster: "LiLo Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "lilocoffeeroasters",
    website: "https://lilocoffee.jp/",
    editorial_blurb: "Minamisenba roastery that's quietly become one of the Kansai region's most respected — the African-origin filter program has no equal in Osaka.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2024-11-04", verification_source: "admin",
  },
  {
    name: "Takamura Wine & Coffee Roasters",
    slug: "takamura-coffee-osaka",
    lat: 34.6853, lng: 135.4908,
    city: "Osaka", country: "Japan",
    address: "1-1-35 Nishi-ku, Osaka",
    roaster: "Takamura",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "takamura_coffee",
    website: "https://www.takamura.co.jp/",
    editorial_blurb: "Utsubo Park-adjacent roastery that pairs natural wine sourcing sensibility with serious coffee — the best of two obsessive worlds under one roof.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2024-11-02", verification_source: "admin",
  },
  {
    name: "Graph Coffee",
    slug: "graph-coffee-osaka",
    lat: 34.6748, lng: 135.5018,
    city: "Osaka", country: "Japan",
    address: "Shinsaibashi, Chuo-ku, Osaka",
    roaster: "Graph Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "standing-bar"],
    instagram_handle: "graphcoffee",
    editorial_blurb: "Shinsaibashi standing bar with an analytical approach to extraction and a pour-over program that changes based on what's at peak — Osaka's most precise coffee stop.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-15", verification_source: "admin",
  },
  {
    name: "Fuglen Osaka",
    slug: "fuglen-osaka",
    lat: 34.6699, lng: 135.5007,
    city: "Osaka", country: "Japan",
    address: "Namba, Chuo-ku, Osaka",
    roaster: "Fuglen Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "outdoor-seating"],
    instagram_handle: "fuglenOsaka",
    website: "https://www.fuglen.com/",
    editorial_blurb: "Oslo's vintage-furniture café in Namba — the same precision Nordic pour-overs that made Tokyo's Fuglen famous, now with Osaka's energy.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-25", verification_source: "admin",
  },
  {
    name: "Coffee Base Nashinoki",
    slug: "coffee-base-nashinoki-osaka",
    lat: 34.6630, lng: 135.5009,
    city: "Osaka", country: "Japan",
    address: "Nipponbashi, Naniwa-ku, Osaka",
    roaster: "Coffee Base Nashinoki",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "coffeebase_nashinoki",
    editorial_blurb: "Nipponbashi specialty bar with a focused menu and the kind of filter-first conviction that makes every cup feel deliberate.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-05", verification_source: "community",
  },
  {
    name: "% Arabica Osaka Nakanoshima",
    slug: "arabica-osaka-nakanoshima",
    lat: 34.6905, lng: 135.4975,
    city: "Osaka", country: "Japan",
    address: "Nakanoshima, Kita-ku, Osaka",
    roaster: "% Arabica",
    brew_methods: ["pour-over", "espresso"],
    vibe_tags: ["minimalist", "outdoor-seating", "no-laptop"],
    instagram_handle: "arabica.nakanoshima",
    website: "https://www.arabica.coffee/",
    editorial_blurb: "Island location on the Dojima River — the Nakanoshima setting for % Arabica's second Osaka outpost may be their most beautiful globally.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-18", verification_source: "admin",
  },
  {
    name: "Maruyama Coffee Osaka",
    slug: "maruyama-coffee-osaka",
    lat: 34.6760, lng: 135.5025,
    city: "Osaka", country: "Japan",
    address: "Shinsaibashi, Chuo-ku, Osaka",
    roaster: "Maruyama Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "maruyamacoffee",
    website: "https://www.maruyamacoffee.com/",
    editorial_blurb: "Matsumoto legend's Osaka outpost bringing their COE-trophy sourcing program and immaculate pour-over technique to Kansai's biggest city.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2024-11-03", verification_source: "admin",
  },

  // ── HO CHI MINH CITY (9) ─────────────────────────────────────────────────────
  {
    name: "The Workshop Coffee",
    slug: "the-workshop-coffee-hcmc",
    lat: 10.7769, lng: 106.7009,
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "27 Ngo Duc Ke, District 1, Ho Chi Minh City",
    roaster: "The Workshop Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "theworkshop_coffee",
    website: "https://www.theworkshop.coffee/",
    editorial_blurb: "Rooftop industrial space in District 1 that reimagined what a Vietnamese café could be — the specialty program here sets the city's benchmark.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2024-11-03", verification_source: "admin",
  },
  {
    name: "Shin Coffee",
    slug: "shin-coffee-hcmc",
    lat: 10.7793, lng: 106.6866,
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "4/2 Nguyen Thi Minh Khai, District 3, Ho Chi Minh City",
    roaster: "Shin Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "shincoffee",
    editorial_blurb: "Vietnamese robusta meets specialty arabica in District 3 — Shin bridges the country's coffee heritage with third-wave technique in a single menu.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-18", verification_source: "admin",
  },
  {
    name: "L'Usine",
    slug: "lusine-hcmc",
    lat: 10.7760, lng: 106.7005,
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "151/5 Dong Khoi, District 1, Ho Chi Minh City",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "lusinespace",
    website: "https://www.lusinespace.com/",
    editorial_blurb: "French colonial architecture meets third-wave coffee in the heart of District 1 — the design alone is reason to linger over a second cup.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2024-10-25", verification_source: "admin",
  },
  {
    name: "Bosgaurus Coffee Roasters",
    slug: "bosgaurus-coffee-hcmc",
    lat: 10.7788, lng: 106.6881,
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "District 3, Ho Chi Minh City",
    roaster: "Bosgaurus Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "bosgaurus",
    editorial_blurb: "District 3 roastery building Vietnam's most ambitious specialty program — the sourcing stories and the extraction quality are both exceptional.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-12", verification_source: "admin",
  },
  {
    name: "Windmills Coffee Roasters",
    slug: "windmills-coffee-hcmc",
    lat: 10.8024, lng: 106.7155,
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "Bình Thạnh District, Ho Chi Minh City",
    roaster: "Windmills Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "windmillscoffee",
    editorial_blurb: "Bình Thạnh roastery café with a pour-over focus and a bean program that leans heavily on Vietnam's own highland growing regions.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-05", verification_source: "community",
  },
  {
    name: "Kairo Coffee",
    slug: "kairo-coffee-hcmc",
    lat: 10.7740, lng: 106.7012,
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "District 1, Ho Chi Minh City",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "kairocoffee",
    editorial_blurb: "District 1 specialty bar with a stripped-back aesthetic and a filter menu that makes a clear argument for why Ho Chi Minh City is becoming a serious coffee city.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-25", verification_source: "community",
  },
  {
    name: "Hola Coffee",
    slug: "hola-coffee-hcmc",
    lat: 10.7805, lng: 106.6895,
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "District 3, Ho Chi Minh City",
    roaster: "Hola Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "holacoffeevn",
    editorial_blurb: "District 3 specialty café doing careful pour-overs and well-sourced espresso in a space that feels more neighborhood gem than urban showcase.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-18", verification_source: "community",
  },
  {
    name: "Gemma",
    slug: "gemma-hcmc",
    lat: 10.8091, lng: 106.7399,
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "Thảo Điền, District 2, Ho Chi Minh City",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "gemma_saigon",
    editorial_blurb: "Thảo Điền expat neighborhood café with a specialty espresso program that holds its own globally — the riverside setting doesn't hurt.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-10", verification_source: "community",
  },
  {
    name: "Yoko Coffee",
    slug: "yoko-coffee-hcmc",
    lat: 10.7810, lng: 106.6902,
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "District 3, Ho Chi Minh City",
    roaster: "Yoko Coffee",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "yokocoffeevn",
    editorial_blurb: "Japanese-influenced specialty café in District 3 where the pour-over menu and the clean aesthetic signal what the next chapter of HCMC coffee looks like.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-05", verification_source: "community",
  },
];
