import type { Cafe } from '@/types';

export const AFRICA_RAW_CAFES: Omit<Cafe, 'id' | 'created_at' | 'third_wave_score' | 'overall_rating' | 'review_count' | 'permanently_closed'>[] = [

  // ── CAPE TOWN (12) ────────────────────────────────────────────────────────────
  {
    name: "Truth Coffee Roasting",
    slug: "truth-coffee-cape-town",
    lat: -33.9249, lng: 18.4241,
    city: "Cape Town", country: "South Africa",
    address: "36 Buitenkant St, Cape Town City Centre, 8001",
    roaster: "Truth Coffee",
    brew_methods: ["espresso", "pour-over", "syphon", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "truthcoffee",
    website: "https://www.truthcoffee.com/",
    editorial_blurb: "Steampunk décor, serious roasting — Truth earned 'world's best coffee shop' headlines and still delivers on the hype.",
    featured_in: ["sprudge", "guardian", "timeout"],
    verified: true, last_verified_at: "2025-10-22", verification_source: "admin",
  },
  {
    name: "Origin Coffee Roasting",
    slug: "origin-coffee-cape-town",
    lat: -33.9173, lng: 18.4234,
    city: "Cape Town", country: "South Africa",
    address: "28 Hudson St, De Waterkant, Cape Town, 8001",
    roaster: "Origin Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "origincoffeeroasting",
    editorial_blurb: "Pan-African sourcing done right — Origin's direct relationships with East African farmers show up in every cup.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-09-18", verification_source: "admin",
  },
  {
    name: "Rosetta Roastery",
    slug: "rosetta-roastery-cape-town",
    lat: -33.9361, lng: 18.4148,
    city: "Cape Town", country: "South Africa",
    address: "8 Kloof Nek Rd, Gardens, Cape Town, 8001",
    roaster: "Rosetta Roastery",
    brew_methods: ["espresso", "pour-over", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "rosettaroastery",
    website: "https://www.rosettaroastery.com/",
    editorial_blurb: "Cape Town's most beloved neighbourhood roastery — Kloof Street locals and travelling coffee professionals queue side by side for the same exceptional cup.",
    featured_in: ["sprudge", "standart", "guardian"],
    verified: true, last_verified_at: "2025-10-30", verification_source: "admin",
  },
  {
    name: "Deluxe Coffeeworks",
    slug: "deluxe-coffeeworks-cape-town",
    lat: -33.9240, lng: 18.4212,
    city: "Cape Town", country: "South Africa",
    address: "19 Church Square, Cape Town City Centre, 8001",
    roaster: "Deluxe Coffeeworks",
    brew_methods: ["espresso", "pour-over", "chemex"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "deluxecoffeeworks",
    website: "https://www.deluxecoffeeworks.com/",
    editorial_blurb: "Church Square CBD institution — Deluxe introduced Cape Town's office crowd to what espresso was supposed to taste like and never let standards slip.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2025-10-12", verification_source: "admin",
  },
  {
    name: "Espresso Lab Microroasters",
    slug: "espresso-lab-cape-town",
    lat: -33.9282, lng: 18.4411,
    city: "Cape Town", country: "South Africa",
    address: "Old Biscuit Mill, 373-375 Albert Rd, Woodstock, 7915",
    roaster: "Espresso Lab",
    brew_methods: ["espresso", "pour-over", "syphon", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "espressolabza",
    website: "https://www.espressolab.co.za/",
    editorial_blurb: "Woodstock's Old Biscuit Mill showpiece — the Saturday market crowd and the serious coffee traveller find equal satisfaction in the same roastery space.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-25", verification_source: "admin",
  },
  {
    name: "Tribe Coffee",
    slug: "tribe-coffee-cape-town",
    lat: -33.9274, lng: 18.4437,
    city: "Cape Town", country: "South Africa",
    address: "Woodstock Exchange, 66 Albert Rd, Woodstock, 7925",
    roaster: "Tribe Coffee",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "tribecoffeeroasters",
    website: "https://www.tribecoffee.co.za/",
    editorial_blurb: "Woodstock roastery run by barista champions who turned competition technique into everyday practice — the most technically consistent cup in Cape Town.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-08", verification_source: "admin",
  },
  {
    name: "Father Coffee",
    slug: "father-coffee-cape-town",
    lat: -33.9152, lng: 18.4148,
    city: "Cape Town", country: "South Africa",
    address: "133 Bree St, Cape Town City Centre, 8001",
    roaster: "Father Coffee",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "fathercoffee",
    editorial_blurb: "Bree Street's most focused espresso bar — stripped back to just the coffee, served by people who know exactly what they're doing.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2025-09-28", verification_source: "admin",
  },
  {
    name: "Bootlegger Coffee Company",
    slug: "bootlegger-coffee-cape-town",
    lat: -33.9112, lng: 18.4056,
    city: "Cape Town", country: "South Africa",
    address: "Regent Rd, Sea Point, Cape Town, 8060",
    roaster: "Bootlegger Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "bootleggercoffee",
    website: "https://www.bootleggercoffee.com/",
    editorial_blurb: "Sea Point fixture with a loyal neighbourhood following — not the purist destination but the most reliably enjoyable daily coffee stop on the Atlantic Seaboard.",
    featured_in: ["timeout"],
    verified: true, last_verified_at: "2025-09-15", verification_source: "admin",
  },
  {
    name: "TriBeCa Coffee",
    slug: "tribeca-coffee-cape-town",
    lat: -33.9348, lng: 18.4139,
    city: "Cape Town", country: "South Africa",
    address: "11 Kloof St, Gardens, Cape Town, 8001",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "tribecacoffeect",
    editorial_blurb: "Kloof Street all-day café that works harder than most — the pour-over programme rotates monthly and the patio is Cape Town's best working terrace.",
    featured_in: ["timeout"],
    verified: false, last_verified_at: "2025-09-10", verification_source: "community",
  },
  {
    name: "Haas Coffee Collective",
    slug: "haas-coffee-cape-town",
    lat: -33.9200, lng: 18.4183,
    city: "Cape Town", country: "South Africa",
    address: "38 Wale St, Cape Town City Centre, 8001",
    roaster: "Haas Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "haascoffee",
    editorial_blurb: "City Bowl specialty collective with a rotating guest roster and a loyal following of baristas, designers, and coffee professionals — one of Cape Town's best-kept secrets.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2025-09-05", verification_source: "community",
  },
  {
    name: "Honest Chocolate Café",
    slug: "honest-chocolate-cape-town",
    lat: -33.9233, lng: 18.4170,
    city: "Cape Town", country: "South Africa",
    address: "64A Wale St, Cape Town City Centre, 8001",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "honestchocolate",
    website: "https://www.honestchocolate.co.za/",
    editorial_blurb: "Bean-to-bar chocolate meets third-wave coffee on Wale Street — a pairing Cape Town made look effortless, with espresso that holds its own against the famous product.",
    featured_in: ["guardian", "timeout"],
    verified: true, last_verified_at: "2025-10-18", verification_source: "admin",
  },
  {
    name: "HQ Coffee",
    slug: "hq-coffee-cape-town",
    lat: -33.9252, lng: 18.4248,
    city: "Cape Town", country: "South Africa",
    address: "55 Church St, Cape Town City Centre, 8001",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "chemex"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "hqcoffeect",
    editorial_blurb: "Central Church Street café built for the serious coffee drinker — rotating guest roasters, methodical extraction, no shortcuts.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2025-08-28", verification_source: "community",
  },

  {
    name: "Jason Bakery",
    slug: "jason-bakery-cape-town",
    lat: -33.9213, lng: 18.4183,
    city: "Cape Town", country: "South Africa",
    address: "185 Bree St, Cape Town City Centre, 8001",
    roaster: "Truth Coffee",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["no-laptop", "outdoor-seating"],
    instagram_handle: "jasonbakerysa",
    website: "https://www.jasonbakery.com/",
    editorial_blurb: "Bree Street institution where the doughnut queues distract from a genuinely serious espresso programme — Truth Coffee in a bakery setting is exactly as good as it sounds.",
    featured_in: ["guardian", "timeout"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Artem Coffee",
    slug: "artem-coffee-cape-town",
    lat: -33.9345, lng: 18.4125,
    city: "Cape Town", country: "South Africa",
    address: "73 Kloof St, Gardens, Cape Town, 8001",
    roaster: "Artem Coffee",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "artemcoffeect",
    editorial_blurb: "Gardens specialty bar with an Eastern European coffee philosophy applied to African beans — the precision here is quiet and the results are consistently exceptional.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Crows Nest Coffee",
    slug: "crows-nest-coffee-cape-town",
    lat: -33.9137, lng: 18.4183,
    city: "Cape Town", country: "South Africa",
    address: "53 Bree St, Cape Town City Centre, 8001",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "crowsnestcoffee",
    editorial_blurb: "Bree Street rooftop-adjacent specialty bar with the city's best rotating African-origin pour-over menu — an essential stop for anyone serious about coffee from the continent.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Origin Coffee Roasting V&A",
    slug: "origin-coffee-va-waterfront",
    lat: -33.9023, lng: 18.4183,
    city: "Cape Town", country: "South Africa",
    address: "Watershed, V&A Waterfront, Cape Town, 8001",
    roaster: "Origin Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "origincoffeeroasting",
    editorial_blurb: "Origin's Waterfront outpost brings the same exceptional East African sourcing to Cape Town's most visited tourist precinct — the quality never compromises for the foot traffic.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Woodstock Bakery Coffee",
    slug: "woodstock-bakery-coffee-cape-town",
    lat: -33.9268, lng: 18.4402,
    city: "Cape Town", country: "South Africa",
    address: "30 Albert Rd, Woodstock, Cape Town, 7925",
    roaster: "Espresso Lab",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "woodstockbakery",
    editorial_blurb: "Woodstock heritage bakery café pouring Espresso Lab in a sourdough-scented space where the morning ritual involves both bread and single-origin pour-overs.",
    featured_in: ["timeout"],
    verified: false, last_verified_at: "2025-09-01", verification_source: "community",
  },
  {
    name: "Neighbour Coffee",
    slug: "neighbour-coffee-cape-town",
    lat: -33.9252, lng: 18.4143,
    city: "Cape Town", country: "South Africa",
    address: "31 Buitenkant St, Cape Town City Centre, 8001",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "neighbourcoffee",
    editorial_blurb: "Buitenkant Street neighbourhood bar that lives up to its name — the hospitality here is as carefully considered as the rotating South African roaster programme.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2025-09-01", verification_source: "community",
  },
  {
    name: "Black Coffee Roasting",
    slug: "black-coffee-roasting-cape-town",
    lat: -33.9291, lng: 18.4455,
    city: "Cape Town", country: "South Africa",
    address: "Woodstock Exchange, Albert Rd, Woodstock, Cape Town, 7925",
    roaster: "Black Coffee Roasting",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "blackcoffeeroasting",
    editorial_blurb: "Woodstock micro-roastery sourcing from smallholder farms across Ethiopia, Kenya, and Rwanda — the most geographically adventurous cup in Cape Town.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2025-09-01", verification_source: "community",
  },
  {
    name: "Café Ganesh",
    slug: "cafe-ganesh-cape-town",
    lat: -33.9162, lng: 18.4252,
    city: "Cape Town", country: "South Africa",
    address: "Bree St, Cape Town City Centre, 8001",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "cafeganeshct",
    editorial_blurb: "Bree Street all-day café with a loyal creative-industry following — the espresso is reliably excellent and the pavement tables are the best people-watching in the CBD.",
    featured_in: ["timeout"],
    verified: false, last_verified_at: "2025-09-01", verification_source: "community",
  },
  {
    name: "Roodebloem Road Café",
    slug: "roodebloem-road-cafe-cape-town",
    lat: -33.9222, lng: 18.4518,
    city: "Cape Town", country: "South Africa",
    address: "Roodebloem Rd, Woodstock, Cape Town, 7925",
    roaster: "Origin Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "dog-friendly"],
    instagram_handle: "roodebloem_cafe",
    editorial_blurb: "Woodstock residential street café with a loyal local following and Origin Coffee on the bar — the Sunday morning crowd cycles here and nobody is in a rush to leave.",
    featured_in: ["timeout"],
    verified: false, last_verified_at: "2025-09-01", verification_source: "community",
  },
  {
    name: "Loading Bay",
    slug: "loading-bay-cape-town",
    lat: -33.9168, lng: 18.4174,
    city: "Cape Town", country: "South Africa",
    address: "30 Hudson St, De Waterkant, Cape Town, 8001",
    roaster: "Rosetta Roastery",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "loadingbayct",
    editorial_blurb: "De Waterkant design-district café pouring Rosetta in a converted loading bay — the industrial interior and the Kloof Street-adjacent crowd make this Cape Town's most effortlessly stylish all-day stop.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Quarta Caffè",
    slug: "quarta-caffe-cape-town",
    lat: -33.9230, lng: 18.4213,
    city: "Cape Town", country: "South Africa",
    address: "76 Shortmarket St, Cape Town City Centre, 8001",
    roaster: "Quarta Caffè",
    brew_methods: ["espresso", "pour-over", "syphon"],
    vibe_tags: ["minimalist", "standing-bar"],
    instagram_handle: "quartacaffe",
    editorial_blurb: "Italian-South African specialty bar in the CBD where the espresso recipe was developed over three generations and the extraction is timed to the second.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2025-09-01", verification_source: "community",
  },
  {
    name: "Hazz Coffee",
    slug: "hazz-coffee-cape-town",
    lat: -33.9310, lng: 18.4093,
    city: "Cape Town", country: "South Africa",
    address: "Gardens Centre, Mill St, Gardens, Cape Town, 8001",
    roaster: "Hazz Coffee",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "hazzcoffee",
    editorial_blurb: "Gardens specialty roastery with a loyal neighbourhood following and a sourcing programme that reaches from Malawi to Ethiopia — Cape Town's most underrated roastery café.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2025-09-01", verification_source: "community",
  },

  // ── NAIROBI (11) ──────────────────────────────────────────────────────────────
  {
    name: "Nairobi Coffee Exchange",
    slug: "nairobi-coffee-exchange",
    lat: -1.2836, lng: 36.8214,
    city: "Nairobi", country: "Kenya",
    address: "Mama Ngina St, Nairobi CBD, Nairobi",
    roaster: "Nairobi Coffee Exchange",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "nairobicoffeeexchange",
    editorial_blurb: "Origin-focused CBD café serving single-farm Kenyan lots you simply cannot find anywhere else — drinking here is a direct line to the source.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-11-01", verification_source: "admin",
  },
  {
    name: "Kikao Coffee",
    slug: "kikao-coffee-nairobi",
    lat: -1.2636, lng: 36.8008,
    city: "Nairobi", country: "Kenya",
    address: "Westlands, Nairobi",
    roaster: "Kikao Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "kikaocoffee",
    editorial_blurb: "East Africa's specialty pioneer with a Westlands roastery proving that great Kenyan coffee belongs in the cup, not the export container.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-12", verification_source: "admin",
  },
  {
    name: "Dormans Coffee",
    slug: "dormans-coffee-nairobi",
    lat: -1.3244, lng: 36.7139,
    city: "Nairobi", country: "Kenya",
    address: "Karen Shopping Centre, Karen, Nairobi",
    roaster: "Dormans Coffee",
    brew_methods: ["espresso", "pour-over", "french-press"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "dormanscoffee",
    website: "https://www.dormanscoffee.co.ke/",
    editorial_blurb: "Kenya's historic roaster reborn as a specialty champion — Karen flagship is the most reliable place in the city for traceable Kenyan lots.",
    featured_in: ["sprudge", "guardian"],
    verified: true, last_verified_at: "2025-10-05", verification_source: "admin",
  },
  {
    name: "42 Degrees Coffee",
    slug: "42-degrees-nairobi",
    lat: -1.2658, lng: 36.8022,
    city: "Nairobi", country: "Kenya",
    address: "Westlands, Nairobi",
    roaster: "42 Degrees Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "42degreescoffee",
    editorial_blurb: "Westlands specialty roastery named for coffee's ideal bloom temperature — the single-origin Kenyan programme is the most precise in the city.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-20", verification_source: "admin",
  },
  {
    name: "Brew Bistro & Lounge",
    slug: "brew-bistro-nairobi",
    lat: -1.2908, lng: 36.7826,
    city: "Nairobi", country: "Kenya",
    address: "Kilimani, Nairobi",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "brewbistro_ke",
    editorial_blurb: "Kilimani's specialty coffee anchor doubling as a craft cocktail bar — the daytime pour-over programme is every bit as serious as the evening menu.",
    featured_in: ["timeout"],
    verified: true, last_verified_at: "2025-10-08", verification_source: "admin",
  },
  {
    name: "Karo Coffee",
    slug: "karo-coffee-nairobi",
    lat: -1.2844, lng: 36.7847,
    city: "Nairobi", country: "Kenya",
    address: "Kilimani Rd, Kilimani, Nairobi",
    roaster: "Karo Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "karocoffee",
    editorial_blurb: "Small-batch Kilimani roastery sourcing exclusively from farms within 200 km — the traceability here is unmatched in East Africa's café scene.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-09-25", verification_source: "admin",
  },
  {
    name: "Cultured Roots Coffee",
    slug: "cultured-roots-nairobi",
    lat: -1.2628, lng: 36.7993,
    city: "Nairobi", country: "Kenya",
    address: "Westlands Ave, Westlands, Nairobi",
    roaster: "Cultured Roots Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "culturedrootscoffee",
    editorial_blurb: "Westlands roastery championing smallholder Kenyan farmers by name — the most compelling proof that traceability and great flavour travel together.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2025-09-18", verification_source: "community",
  },
  {
    name: "Jiko Coffee",
    slug: "jiko-coffee-nairobi",
    lat: -1.2780, lng: 36.8156,
    city: "Nairobi", country: "Kenya",
    address: "Upper Hill, Nairobi",
    roaster: "Jiko Coffee",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "jikocoffee",
    editorial_blurb: "Upper Hill specialty bar where Nairobi's finance crowd discovered what single-origin Kenyan AA really tastes like — and converted almost immediately.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2025-09-12", verification_source: "community",
  },
  {
    name: "Turaco Coffee Bar",
    slug: "turaco-coffee-bar-nairobi",
    lat: -1.2670, lng: 36.8035,
    city: "Nairobi", country: "Kenya",
    address: "Westlands Rd, Westlands, Nairobi",
    roaster: "Turaco Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "turacocoffee",
    editorial_blurb: "Named for Kenya's most vibrant bird, Turaco roasts exclusively Kenyan AA and SL-28 lots — the most terroir-focused specialty bar in the Westlands corridor.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "The Artisan Coffee",
    slug: "the-artisan-coffee-nairobi",
    lat: -1.2892, lng: 36.7821,
    city: "Nairobi", country: "Kenya",
    address: "Yaya Centre, Argwings Kodhek Rd, Kilimani, Nairobi",
    roaster: "The Artisan Coffee",
    brew_methods: ["espresso", "pour-over", "chemex", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "theartisancoffeeke",
    editorial_blurb: "Kilimani shopping-centre specialty bar that refuses to let the retail context compromise quality — the Kenyan single-origin pour-over programme is the neighbourhood's best.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "About Coffee",
    slug: "about-coffee-nairobi",
    lat: -1.2714, lng: 36.8096,
    city: "Nairobi", country: "Kenya",
    address: "ABC Place, Waiyaki Way, Westlands, Nairobi",
    roaster: "About Coffee",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "aboutcoffeeke",
    editorial_blurb: "Waiyaki Way specialty bar that takes its direct sourcing seriously enough to publish farm visit notes on the menu — Nairobi's most transparent coffee experience.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Cultivar Coffee Bar",
    slug: "cultivar-coffee-bar-nairobi",
    lat: -1.2842, lng: 36.7986,
    city: "Nairobi", country: "Kenya",
    address: "Galana Plaza, Galana Rd, Kilimani, Nairobi",
    roaster: "Cultivar Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "minimalist", "laptop-friendly"],
    instagram_handle: "cultivarcoffee",
    editorial_blurb: "Kilimani roastery café built around heirloom varietal exploration — the Ruiru 11 and Batian single-variety lots prove that Kenya's coffee genetics are as interesting as its geography.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Kaldi's Coffee",
    slug: "kaldis-coffee-nairobi",
    lat: -1.2798, lng: 36.8072,
    city: "Nairobi", country: "Kenya",
    address: "Kencom House, Moi Ave, Nairobi CBD, Nairobi",
    roaster: "Kaldi's Coffee",
    brew_methods: ["espresso", "pour-over", "french-press"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "kaldiscoffeeke",
    editorial_blurb: "CBD specialty institution honouring the Ethiopian goatherder myth with Kenyan execution — the morning espresso queue is Nairobi's most reliable indicator of neighbourhood coffee culture.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Nairobi Roasters",
    slug: "nairobi-roasters-westlands",
    lat: -1.2648, lng: 36.8012,
    city: "Nairobi", country: "Kenya",
    address: "The Mall, Westlands, Nairobi",
    roaster: "Nairobi Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "nairobicoasters",
    editorial_blurb: "Westlands roastery sourcing from Kenya's Central and Nyeri counties — the weekly cupping sessions are open to the public and genuinely educational.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2025-09-01", verification_source: "community",
  },
  {
    name: "Kahawa Collective",
    slug: "kahawa-collective-nairobi",
    lat: -1.2730, lng: 36.8108,
    city: "Nairobi", country: "Kenya",
    address: "Parklands, Nairobi",
    roaster: "Kahawa Collective",
    brew_methods: ["espresso", "pour-over", "chemex"],
    vibe_tags: ["minimalist", "coworking"],
    instagram_handle: "kahawacollective",
    editorial_blurb: "Parklands co-working café where the single-origin Kenyan programme is as deliberate as the co-working ethos — the most intellectually engaged room in Nairobi's specialty scene.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2025-09-01", verification_source: "community",
  },

];
