import type { Cafe } from '@/types';

export const OCEANIA_RAW_CAFES: Omit<Cafe, 'id' | 'created_at' | 'third_wave_score' | 'overall_rating' | 'review_count' | 'permanently_closed'>[] = [

  // ── MELBOURNE (25) ────────────────────────────────────────────────────────────
  {
    name: "St Ali",
    slug: "st-ali-melbourne",
    lat: -37.8067, lng: 144.9580,
    city: "Melbourne", country: "Australia",
    address: "12-18 Yarra Place, South Melbourne VIC 3205",
    roaster: "St Ali",
    brew_methods: ["espresso", "pour-over", "syphon", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "stalicoffee",
    website: "https://stali.com.au/",
    editorial_blurb: "The roastery that helped define Melbourne's coffee identity — still the best introduction to why this city takes coffee so seriously.",
    featured_in: ["sprudge", "guardian", "eater"],
    verified: true, last_verified_at: "2025-11-05", verification_source: "admin",
  },
  {
    name: "Patricia Coffee Brewers",
    slug: "patricia-coffee-brewers",
    lat: -37.8150, lng: 144.9608,
    city: "Melbourne", country: "Australia",
    address: "493-495 Little Bourke St, Melbourne VIC 3000",
    roaster: "Multiple roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["standing-bar", "no-laptop"],
    instagram_handle: "patriciacoffeebrewers",
    editorial_blurb: "Standing room only, zero compromise — Patricia runs the tightest espresso programme in the CBD and everyone knows it.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2025-10-20", verification_source: "admin",
  },
  {
    name: "Market Lane Coffee",
    slug: "market-lane-coffee",
    lat: -37.8083, lng: 144.9702,
    city: "Melbourne", country: "Australia",
    address: "Prahran Market, 163 Commercial Rd, Prahran VIC 3181",
    roaster: "Market Lane",
    brew_methods: ["pour-over", "espresso", "aeropress", "french-press"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "marketlanecoffee",
    website: "https://marketlane.com.au/",
    editorial_blurb: "Market-stall origins, world-class roasting — their seasonal single-origins are worth building a Melbourne morning around.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-09-30", verification_source: "admin",
  },
  {
    name: "Proud Mary",
    slug: "proud-mary-melbourne",
    lat: -37.8031, lng: 144.9874,
    city: "Melbourne", country: "Australia",
    address: "172 Oxford St, Collingwood VIC 3066",
    roaster: "Proud Mary",
    brew_methods: ["espresso", "pour-over", "cold-brew", "aeropress"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "proudmarycoffee",
    website: "https://www.proudmarycoffee.com.au/",
    editorial_blurb: "Collingwood institution that exported Melbourne's coffee gospel to Portland and Tokyo — the brunch-hour pour-over queue is a pilgrimage Melbourne locals earn the right to skip.",
    featured_in: ["sprudge", "standart", "guardian"],
    verified: true, last_verified_at: "2025-11-08", verification_source: "admin",
  },
  {
    name: "Seven Seeds",
    slug: "seven-seeds-melbourne",
    lat: -37.8041, lng: 144.9599,
    city: "Melbourne", country: "Australia",
    address: "114 Berkeley St, Carlton VIC 3053",
    roaster: "Seven Seeds",
    brew_methods: ["espresso", "pour-over", "chemex", "syphon", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "sevenseedscoffee",
    website: "https://sevenseeds.com.au/",
    editorial_blurb: "Carlton warehouse roastery that rewired Melbourne's palate for light roasts — the Saturday cupping table and the long communal bench are both still essential.",
    featured_in: ["sprudge", "standart", "guardian"],
    verified: true, last_verified_at: "2025-11-01", verification_source: "admin",
  },
  {
    name: "Dukes Coffee Roasters",
    slug: "dukes-coffee-melbourne",
    lat: -37.8188, lng: 144.9634,
    city: "Melbourne", country: "Australia",
    address: "247 Flinders Lane, Melbourne VIC 3000",
    roaster: "Dukes Coffee Roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "dukescoffeeroasters",
    website: "https://www.dukescoffee.com.au/",
    editorial_blurb: "Flinders Lane basement bar that turns the CBD lunch rush into an exercise in precision — the espresso programme here runs at a different pace to everywhere else.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2025-10-28", verification_source: "admin",
  },
  {
    name: "Axil Coffee Roasters",
    slug: "axil-coffee-roasters-melbourne",
    lat: -37.8226, lng: 145.0369,
    city: "Melbourne", country: "Australia",
    address: "322 Burwood Rd, Hawthorn VIC 3122",
    roaster: "Axil Coffee Roasters",
    brew_methods: ["espresso", "pour-over", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "axilcoffeeroasters",
    website: "https://axilcoffee.com.au/",
    editorial_blurb: "World Barista Championship pedigree translated into Hawthorn's best local — David Makin's roastery sets Melbourne's eastern suburbs standard for what direct trade looks like.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-22", verification_source: "admin",
  },
  {
    name: "Sensory Lab",
    slug: "sensory-lab-melbourne",
    lat: -37.8148, lng: 144.9633,
    city: "Melbourne", country: "Australia",
    address: "297 Little Collins St, Melbourne VIC 3000",
    roaster: "Sensory Lab",
    brew_methods: ["pour-over", "espresso", "syphon", "aeropress"],
    vibe_tags: ["minimalist", "no-laptop", "standing-bar"],
    instagram_handle: "sensorylabcoffee",
    editorial_blurb: "David Jones' CBD ground-floor espresso bar that punches above its retail setting — the rotating single-origin pour-over flight is Melbourne's best corporate-hour coffee.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-15", verification_source: "admin",
  },
  {
    name: "Brother Baba Budan",
    slug: "brother-baba-budan-melbourne",
    lat: -37.8133, lng: 144.9634,
    city: "Melbourne", country: "Australia",
    address: "359 Little Bourke St, Melbourne VIC 3000",
    roaster: "Seven Seeds",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["standing-bar", "no-laptop", "minimalist"],
    instagram_handle: "brotherbababudan",
    editorial_blurb: "Seven Seeds' CBD sibling — chairs suspended from the ceiling, zero pretension, and the same exacting espresso in a space the size of a hallway.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2025-10-10", verification_source: "admin",
  },
  {
    name: "Wide Open Road",
    slug: "wide-open-road-brunswick",
    lat: -37.7698, lng: 144.9584,
    city: "Melbourne", country: "Australia",
    address: "274 Blyth St, Brunswick VIC 3056",
    roaster: "Wide Open Road",
    brew_methods: ["espresso", "pour-over", "cold-brew", "chemex"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "wideopenroadcoffee",
    website: "https://www.wideopenroadcoffee.com.au/",
    editorial_blurb: "Brunswick roastery that feels like it was designed for long weekend mornings — exceptional natural-process lots and a courtyard that earns the walk north of the city.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2025-10-25", verification_source: "admin",
  },
  {
    name: "Higher Ground",
    slug: "higher-ground-melbourne",
    lat: -37.8133, lng: 144.9584,
    city: "Melbourne", country: "Australia",
    address: "650 Little Bourke St, Melbourne VIC 3000",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "highergroundmelb",
    editorial_blurb: "Converted power station with soaring ceilings and a coffee programme that matches the architecture — Melbourne's most spectacular all-day café.",
    featured_in: ["sprudge", "eater", "timeout"],
    verified: true, last_verified_at: "2025-11-03", verification_source: "admin",
  },
  {
    name: "Top Paddock",
    slug: "top-paddock-richmond",
    lat: -37.8237, lng: 145.0072,
    city: "Melbourne", country: "Australia",
    address: "658 Church St, Richmond VIC 3121",
    roaster: "Market Lane",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "toppaddockmelbourne",
    editorial_blurb: "Richmond's neighbourhood café elevated by Market Lane's roasting — the weekend brunch crowd and the flat white devotees share the same excellent cup.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2025-10-18", verification_source: "admin",
  },
  {
    name: "Allpress Espresso Melbourne",
    slug: "allpress-espresso-melbourne",
    lat: -37.8028, lng: 144.9858,
    city: "Melbourne", country: "Australia",
    address: "150 Johnston St, Collingwood VIC 3066",
    roaster: "Allpress Espresso",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "allpressespresso",
    website: "https://allpressespresso.com/",
    editorial_blurb: "Trans-Tasman roastery institution's Collingwood headquarters — the open roastery and the espresso bar run in parallel, and the breakfast crowd arrives before the doors open.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-11-06", verification_source: "admin",
  },
  {
    name: "Padre Coffee",
    slug: "padre-coffee-brunswick",
    lat: -37.7734, lng: 144.9598,
    city: "Melbourne", country: "Australia",
    address: "438 Sydney Rd, Brunswick VIC 3056",
    roaster: "Padre Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "padrecoffee",
    website: "https://www.padrecoffee.com.au/",
    editorial_blurb: "Sydney Road's defining specialty address — Padre's direct-trade sourcing and in-house roasting have made Brunswick's main strip a genuine coffee destination.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-20", verification_source: "admin",
  },
  {
    name: "Monk Bodhi Dharma",
    slug: "monk-bodhi-dharma-melbourne",
    lat: -37.8648, lng: 144.9958,
    city: "Melbourne", country: "Australia",
    address: "202 Carlisle St, Balaclava VIC 3183",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "monkbodhi",
    website: "https://www.monkbodhidharma.com.au/",
    editorial_blurb: "Balaclava's most curious café — a plant-based menu, a rotating single-origin filter programme, and the kind of regulars who've come every morning for a decade.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2025-10-12", verification_source: "admin",
  },
  {
    name: "Hardware Société",
    slug: "hardware-societe-melbourne",
    lat: -37.8118, lng: 144.9625,
    city: "Melbourne", country: "Australia",
    address: "120 Hardware St, Melbourne VIC 3000",
    roaster: "Market Lane",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "hardwaresociete",
    website: "https://www.hardwaresociete.com/",
    editorial_blurb: "Hardware Lane institution with French leanings and Melbourne coffee values — the soufflé pancakes and the Market Lane espresso coexist without compromise.",
    featured_in: ["sprudge", "eater", "timeout"],
    verified: true, last_verified_at: "2025-10-28", verification_source: "admin",
  },
  {
    name: "Aunty Peg's",
    slug: "aunty-pegs-collingwood",
    lat: -37.8028, lng: 144.9876,
    city: "Melbourne", country: "Australia",
    address: "172 Oxford St, Collingwood VIC 3066",
    roaster: "Proud Mary",
    brew_methods: ["pour-over", "espresso", "syphon", "chemex"],
    vibe_tags: ["roastery-on-site", "minimalist", "no-laptop"],
    instagram_handle: "auntypegsbar",
    editorial_blurb: "Proud Mary's upstairs cupping and filter bar — a quieter, more focused counterpoint to the bustling café below, where the pour-over menu goes deeper.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-30", verification_source: "admin",
  },
  {
    name: "Everyday Coffee",
    slug: "everyday-coffee-fitzroy",
    lat: -37.7995, lng: 144.9790,
    city: "Melbourne", country: "Australia",
    address: "334 Smith St, Fitzroy VIC 3065",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "everydaycoffee",
    editorial_blurb: "Smith Street neighbourhood café that takes its name seriously — reliable, honest specialty in one of Fitzroy's best people-watching spots.",
    featured_in: ["timeout"],
    verified: true, last_verified_at: "2025-10-05", verification_source: "admin",
  },
  {
    name: "Code Black Coffee",
    slug: "code-black-coffee-brunswick",
    lat: -37.7703, lng: 144.9604,
    city: "Melbourne", country: "Australia",
    address: "Albert St, Brunswick VIC 3056",
    roaster: "Code Black Coffee",
    brew_methods: ["espresso", "pour-over", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "codeblackcoffee",
    website: "https://www.codeblackcoffee.com.au/",
    editorial_blurb: "Brunswick roastery whose intense sourcing philosophy and in-house roasting make it the suburb's most serious specialty address — the origin flights reward the curious.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-15", verification_source: "admin",
  },
  {
    name: "Auction Rooms",
    slug: "auction-rooms-north-melbourne",
    lat: -37.7986, lng: 144.9440,
    city: "Melbourne", country: "Australia",
    address: "103-107 Errol St, North Melbourne VIC 3051",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "auctionroomsmelbourne",
    editorial_blurb: "North Melbourne's destination café in a former auction house — the industrial space, serious brunch menu, and rotating single-origins have built a following that crosses city lines.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2025-10-22", verification_source: "admin",
  },
  {
    name: "Workshop Espresso",
    slug: "workshop-espresso-melbourne",
    lat: -37.8185, lng: 144.9691,
    city: "Melbourne", country: "Australia",
    address: "413 Collins St, Melbourne VIC 3000",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["standing-bar", "no-laptop", "minimalist"],
    instagram_handle: "workshopespresso",
    editorial_blurb: "Collins Street express bar where Melbourne's CBD coffee culture runs at its sharpest — in and out in five minutes with the best flat white in the legal district.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-08", verification_source: "admin",
  },
  {
    name: "Stagger Lee's",
    slug: "stagger-lees-fitzroy",
    lat: -37.7977, lng: 144.9784,
    city: "Melbourne", country: "Australia",
    address: "276 Smith St, Fitzroy VIC 3065",
    roaster: "Seven Seeds",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "stagga_lees",
    editorial_blurb: "Smith Street character café with no pretension and every reason to return — the Seven Seeds espresso hits differently in a room with this much neighbourhood warmth.",
    featured_in: ["timeout"],
    verified: true, last_verified_at: "2025-09-28", verification_source: "admin",
  },

  {
    name: "Industry Beans Fitzroy",
    slug: "industry-beans-fitzroy",
    lat: -37.7994, lng: 144.9810,
    city: "Melbourne", country: "Australia",
    address: "3/62 Rose St, Fitzroy VIC 3065",
    roaster: "Industry Beans",
    brew_methods: ["espresso", "pour-over", "cold-brew", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "industrybeans",
    website: "https://industrybeans.com/",
    editorial_blurb: "Fitzroy's converted warehouse roastery where the tasting flight is practically mandatory — Industry Beans' seasonal menu treats Melbourne's palate like a classroom.",
    featured_in: ["sprudge", "standart", "timeout"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Industry Beans CBD",
    slug: "industry-beans-cbd",
    lat: -37.8165, lng: 144.9657,
    city: "Melbourne", country: "Australia",
    address: "270 Flinders Lane, Melbourne VIC 3000",
    roaster: "Industry Beans",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "standing-bar"],
    instagram_handle: "industrybeans",
    website: "https://industrybeans.com/",
    editorial_blurb: "Industry Beans' CBD format distilled to its essence — the same seasonal roast programme in a standing bar that makes Flinders Lane's lunch break worthwhile.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Mecca Espresso Melbourne",
    slug: "mecca-espresso-melbourne",
    lat: -37.8148, lng: 144.9671,
    city: "Melbourne", country: "Australia",
    address: "335 Little Collins St, Melbourne VIC 3000",
    roaster: "Mecca Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "standing-bar", "no-laptop"],
    instagram_handle: "meccacoffee",
    website: "https://meccacoffee.com.au/",
    editorial_blurb: "Sydney's Mecca brings its benchmark espresso programme to Melbourne's CBD — two cities, one standard, and a rivalry that only improves both cups.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Market Lane Collins Street",
    slug: "market-lane-collins-st",
    lat: -37.8183, lng: 144.9692,
    city: "Melbourne", country: "Australia",
    address: "Emporium Melbourne, 287 Lonsdale St, Melbourne VIC 3000",
    roaster: "Market Lane",
    brew_methods: ["pour-over", "espresso", "aeropress", "chemex"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "marketlanecoffee",
    website: "https://marketlane.com.au/",
    editorial_blurb: "Market Lane's Emporium location applies the same seasonal sourcing rigour to the CBD lunch crowd — the filter menu rotates twice weekly and is always worth reading first.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Commonfolk Coffee",
    slug: "commonfolk-coffee-mornington",
    lat: -38.2228, lng: 145.0373,
    city: "Melbourne", country: "Australia",
    address: "7/31 Barkly St, Mornington VIC 3931",
    roaster: "Commonfolk Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew", "chemex"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "dog-friendly"],
    instagram_handle: "commonfolkcoffee",
    website: "https://www.commonfolkcoffee.com.au/",
    editorial_blurb: "Peninsula roastery worth the drive from the city — Commonfolk's direct-trade programme and open-air roasting shed have built a following that spans the entire Mornington Peninsula.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Axil Coffee Roasters CBD",
    slug: "axil-coffee-roasters-cbd",
    lat: -37.8175, lng: 144.9638,
    city: "Melbourne", country: "Australia",
    address: "291 Flinders Lane, Melbourne VIC 3000",
    roaster: "Axil Coffee Roasters",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["minimalist", "standing-bar"],
    instagram_handle: "axilcoffeeroasters",
    website: "https://axilcoffee.com.au/",
    editorial_blurb: "Axil's Flinders Lane outpost brings Hawthorn's World Barista Championship pedigree to the CBD — the espresso is calibrated to the same impossible standard.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Ona Coffee Melbourne",
    slug: "ona-coffee-melbourne",
    lat: -37.8022, lng: 144.9875,
    city: "Melbourne", country: "Australia",
    address: "169 Oxford St, Collingwood VIC 3066",
    roaster: "ONA Coffee",
    brew_methods: ["espresso", "pour-over", "chemex", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "minimalist", "no-laptop"],
    instagram_handle: "onacoffee",
    website: "https://onacoffee.com.au/",
    editorial_blurb: "Collingwood outpost from Australia's most competition-decorated roastery — the seasonal filter menu and the espresso are both poured with World Barista Championship precision.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Pope Joan",
    slug: "pope-joan-melbourne",
    lat: -37.7862, lng: 144.9780,
    city: "Melbourne", country: "Australia",
    address: "77-79 Ferguson St, North Fitzroy VIC 3068",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "dog-friendly", "laptop-friendly"],
    instagram_handle: "popejoanmelbourne",
    editorial_blurb: "North Fitzroy's beloved neighbourhood café with a shaded garden and the kind of unhurried weekend pace Melbourne's inner suburbs do best — the filter coffee is a bonus.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Little Mule Coffee",
    slug: "little-mule-coffee-melbourne",
    lat: -37.8108, lng: 144.9761,
    city: "Melbourne", country: "Australia",
    address: "232 Smith St, Collingwood VIC 3066",
    roaster: "Little Mule Coffee",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "littlemulecoffee",
    editorial_blurb: "Smith Street specialty roastery with the quiet confidence of a place that doesn't need to advertise — the rotating washed-process pour-over is consistently Collingwood's best.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Padre Coffee Fitzroy",
    slug: "padre-coffee-fitzroy",
    lat: -37.7991, lng: 144.9782,
    city: "Melbourne", country: "Australia",
    address: "312 Smith St, Fitzroy VIC 3065",
    roaster: "Padre Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "padrecoffee",
    website: "https://www.padrecoffee.com.au/",
    editorial_blurb: "Padre's Fitzroy location extends the Brunswick roastery's direct-trade ethos into Melbourne's most coffee-literate neighbourhood — the seasonal lot rotations land here first.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Doctor Doctor Coffee",
    slug: "doctor-doctor-coffee-melbourne",
    lat: -37.8041, lng: 144.9623,
    city: "Melbourne", country: "Australia",
    address: "20 Rose St, Fitzroy VIC 3065",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "doctordoctorcoffee",
    editorial_blurb: "Fitzroy specialty bar operating like a prescription service — the tasting menu tells you what you need, and the barista team diagnoses your palate with genuine accuracy.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Cafenated Coffee Co.",
    slug: "cafenated-coffee-cbd",
    lat: -37.8157, lng: 144.9650,
    city: "Melbourne", country: "Australia",
    address: "91 Collins St, Melbourne VIC 3000",
    roaster: "Cafenated Coffee Co.",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["standing-bar", "no-laptop", "minimalist"],
    instagram_handle: "cafenatedcoffeeco",
    editorial_blurb: "Collins Street espresso bar that turns Melbourne's busiest professional corridor into a precision coffee moment — the flat white here is the CBD benchmark.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Penny Coffee",
    slug: "penny-coffee-collingwood",
    lat: -37.8043, lng: 144.9880,
    city: "Melbourne", country: "Australia",
    address: "87 Oxford St, Collingwood VIC 3066",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["minimalist", "outdoor-seating"],
    instagram_handle: "pennycoffee_melb",
    editorial_blurb: "Collingwood corner bar that keeps it effortlessly simple — rotating guest roasters, single-origin filter, and a streetside counter that works in all Melbourne weather.",
    featured_in: ["timeout"],
    verified: false, last_verified_at: "2025-09-01", verification_source: "community",
  },
  {
    name: "Navi Coffee",
    slug: "navi-coffee-hawthorn",
    lat: -37.8222, lng: 145.0340,
    city: "Melbourne", country: "Australia",
    address: "44 Burwood Rd, Hawthorn VIC 3122",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "navicoffeemelb",
    editorial_blurb: "Hawthorn specialty bar that navigates Melbourne's eastern suburbs away from mediocrity — the considered filter programme and precise espresso make this the suburb's most reliable address.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2025-09-01", verification_source: "community",
  },
  {
    name: "The Exchange Coffee",
    slug: "the-exchange-coffee-melbourne",
    lat: -37.8014, lng: 144.9588,
    city: "Melbourne", country: "Australia",
    address: "74 Errol St, North Melbourne VIC 3051",
    roaster: "Market Lane",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "theexchangecoffee",
    editorial_blurb: "North Melbourne neighbourhood café with Market Lane on the bar and a community-minded crowd at the tables — the most welcoming specialty address north of the CBD.",
    featured_in: ["timeout"],
    verified: false, last_verified_at: "2025-09-01", verification_source: "community",
  },
  {
    name: "Traveller Coffee",
    slug: "traveller-coffee-melbourne",
    lat: -37.8218, lng: 144.9615,
    city: "Melbourne", country: "Australia",
    address: "438 Little Bourke St, Melbourne VIC 3000",
    roaster: "Seven Seeds",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["standing-bar", "no-laptop", "minimalist"],
    instagram_handle: "travellercoffee",
    editorial_blurb: "Express CBD bar for the Melbourne commuter who will not compromise on quality — Seven Seeds espresso delivered through a window with the precision of a proper specialty bar.",
    featured_in: ["timeout"],
    verified: false, last_verified_at: "2025-09-01", verification_source: "community",
  },
  {
    name: "Kettle Black",
    slug: "kettle-black-south-melbourne",
    lat: -37.8318, lng: 144.9612,
    city: "Melbourne", country: "Australia",
    address: "50 Albert Rd, South Melbourne VIC 3205",
    roaster: "Market Lane",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "thekettleblack",
    editorial_blurb: "Albert Road Instagram favourite that earns every frame — the ricotta hotcakes are famous, the Market Lane espresso is quietly impeccable, and the terrace is Melbourne at its best.",
    featured_in: ["eater", "timeout"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Lune Croissanterie",
    slug: "lune-croissanterie-fitzroy",
    lat: -37.7974, lng: 144.9762,
    city: "Melbourne", country: "Australia",
    address: "119 Rose St, Fitzroy VIC 3065",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["no-laptop", "minimalist"],
    instagram_handle: "lunecroissanterie",
    website: "https://lunecroissanterie.com/",
    editorial_blurb: "Kate Reid's world-famous pastry atelier pairs its croissants with an equally serious coffee programme — the morning queue in the glass cube is a Melbourne ritual worth the wait.",
    featured_in: ["sprudge", "guardian", "eater", "ny_times"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Tall Timber",
    slug: "tall-timber-fitzroy",
    lat: -37.8005, lng: 144.9818,
    city: "Melbourne", country: "Australia",
    address: "30 Gellie Lane, Fitzroy VIC 3065",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "dog-friendly", "laptop-friendly"],
    instagram_handle: "talltimbercafe",
    editorial_blurb: "Fitzroy laneway café with the kind of timber-beamed interior that makes a neighbourhood feel like itself — the rotating filter and the all-day brunch draw a loyal Saturday crowd.",
    featured_in: ["timeout"],
    verified: false, last_verified_at: "2025-09-01", verification_source: "community",
  },
  {
    name: "St Ali North",
    slug: "st-ali-north-brunswick",
    lat: -37.7713, lng: 144.9589,
    city: "Melbourne", country: "Australia",
    address: "395 Sydney Rd, Brunswick VIC 3056",
    roaster: "St Ali",
    brew_methods: ["espresso", "pour-over", "syphon", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "laptop-friendly"],
    instagram_handle: "stalicoffee",
    website: "https://stali.com.au/",
    editorial_blurb: "St Ali's northern outpost brings South Melbourne's coffee gospel to Brunswick's Sydney Road — the brewing programme matches the original and the neighbourhood crowd is even more devoted.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Anchor Coffee",
    slug: "anchor-coffee-clifton-hill",
    lat: -37.7907, lng: 144.9958,
    city: "Melbourne", country: "Australia",
    address: "155 Queens Parade, Clifton Hill VIC 3068",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "anchorcoffeemelb",
    editorial_blurb: "Queens Parade neighbourhood café that holds the Clifton Hill standard for specialty — rotating Australian roasters and a morning patio worth navigating the tram for.",
    featured_in: ["timeout"],
    verified: false, last_verified_at: "2025-09-01", verification_source: "community",
  },
  {
    name: "Gideon's Coffee",
    slug: "gideons-coffee-port-melbourne",
    lat: -37.8380, lng: 144.9518,
    city: "Melbourne", country: "Australia",
    address: "219 Bay St, Port Melbourne VIC 3207",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "gideonscoffee",
    editorial_blurb: "Port Melbourne specialty café on the beach side of the city — the flat white here and the Bay Street foot traffic make this Melbourne's most relaxed quality coffee stop.",
    featured_in: ["timeout"],
    verified: false, last_verified_at: "2025-09-01", verification_source: "community",
  },
  {
    name: "Market Lane Carlton",
    slug: "market-lane-carlton",
    lat: -37.8031, lng: 144.9672,
    city: "Melbourne", country: "Australia",
    address: "Argyle Square, 138 Faraday St, Carlton VIC 3053",
    roaster: "Market Lane",
    brew_methods: ["pour-over", "espresso", "aeropress", "chemex"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "laptop-friendly"],
    instagram_handle: "marketlanecoffee",
    website: "https://marketlane.com.au/",
    editorial_blurb: "Market Lane's Carlton café sits inside a heritage market hall two blocks from Seven Seeds — Argyle Square gets a second world-class address and neither apologises for it.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Proud Mary Northcote",
    slug: "proud-mary-northcote",
    lat: -37.7816, lng: 144.9967,
    city: "Melbourne", country: "Australia",
    address: "195 High St, Northcote VIC 3070",
    roaster: "Proud Mary",
    brew_methods: ["espresso", "pour-over", "cold-brew", "aeropress"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "proudmarycoffee",
    website: "https://www.proudmarycoffee.com.au/",
    editorial_blurb: "Proud Mary's Northcote extension carries the Collingwood roastery's direct-trade pedigree to the High Street corridor — the single-origin filter menu lands here at the same time as the flagship.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Dukes Coffee Hawksburn",
    slug: "dukes-coffee-hawksburn",
    lat: -37.8435, lng: 144.9938,
    city: "Melbourne", country: "Australia",
    address: "106 Malvern Rd, Hawksburn VIC 3142",
    roaster: "Dukes Coffee Roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "dukescoffeeroasters",
    website: "https://www.dukescoffee.com.au/",
    editorial_blurb: "Dukes' Hawksburn village format applies Flinders Lane precision to a gentler neighbourhood pace — the espresso programme is identical and the setting is considerably more forgiving.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Seven Seeds Carlton North",
    slug: "seven-seeds-carlton-north",
    lat: -37.7917, lng: 144.9707,
    city: "Melbourne", country: "Australia",
    address: "71 Nicholson St, Carlton North VIC 3054",
    roaster: "Seven Seeds",
    brew_methods: ["espresso", "pour-over", "chemex"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "sevenseedscoffee",
    website: "https://sevenseeds.com.au/",
    editorial_blurb: "Seven Seeds' Carlton North neighbourhood café brings the Berkeley Street roastery's light-roast philosophy to a quieter postcode — the Nicholson Street terrace is Melbourne's most underrated outdoor coffee spot.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },

  // ── SYDNEY (18) ───────────────────────────────────────────────────────────────
  {
    name: "Single O",
    slug: "single-o-surry-hills",
    lat: -33.8896, lng: 151.2094,
    city: "Sydney", country: "Australia",
    address: "60-64 Reservoir St, Surry Hills NSW 2010",
    roaster: "Single O",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "laptop-friendly"],
    instagram_handle: "singleocoffee",
    website: "https://www.singleo.com.au/",
    editorial_blurb: "The Surry Hills roastery that defined Sydney specialty — their taps of batch brew and cold brew changed how the city drinks coffee.",
    featured_in: ["sprudge", "guardian"],
    verified: true, last_verified_at: "2025-11-03", verification_source: "admin",
  },
  {
    name: "Sample Coffee",
    slug: "sample-coffee-sydney",
    lat: -33.8923, lng: 151.2077,
    city: "Sydney", country: "Australia",
    address: "118 Devonshire St, Surry Hills NSW 2010",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "samplecoffeesydney",
    editorial_blurb: "Rotating guest roasters and genuinely serious pour-overs make Sample the best place in Sydney to discover what's new in specialty.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-12", verification_source: "admin",
  },
  {
    name: "Reuben Hills",
    slug: "reuben-hills-sydney",
    lat: -33.8910, lng: 151.2060,
    city: "Sydney", country: "Australia",
    address: "61 Albion St, Surry Hills NSW 2010",
    roaster: "Reuben Hills",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "reubenhills",
    website: "https://reubenhills.com.au/",
    editorial_blurb: "South American bean focus and a roastery café that doubles as a proper brunch destination — the espresso programme is the real reason to visit.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2025-10-22", verification_source: "admin",
  },
  {
    name: "Mecca Coffee",
    slug: "mecca-coffee-surry-hills",
    lat: -33.8882, lng: 151.2108,
    city: "Sydney", country: "Australia",
    address: "46 Myrtle St, Chippendale NSW 2008",
    roaster: "Mecca Coffee",
    brew_methods: ["espresso", "pour-over", "syphon", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "meccacoffee",
    website: "https://meccacoffee.com.au/",
    editorial_blurb: "Sydney's benchmark specialty roastery — for two decades Mecca has been the standard other cafés are judged by and the roastery café earns that reputation daily.",
    featured_in: ["sprudge", "standart", "guardian"],
    verified: true, last_verified_at: "2025-11-06", verification_source: "admin",
  },
  {
    name: "Artificer Coffee",
    slug: "artificer-coffee-sydney",
    lat: -33.8898, lng: 151.2081,
    city: "Sydney", country: "Australia",
    address: "547 Crown St, Surry Hills NSW 2010",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress", "chemex"],
    vibe_tags: ["standing-bar", "minimalist", "no-laptop"],
    instagram_handle: "artificercoffee",
    editorial_blurb: "Surry Hills espresso bar at the competitive edge of the city's craft — the rotating guest roaster programme and rigorous extraction standards attract baristas on days off.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-28", verification_source: "admin",
  },
  {
    name: "Paramount Coffee Project",
    slug: "paramount-coffee-project-sydney",
    lat: -33.8876, lng: 151.2073,
    city: "Sydney", country: "Australia",
    address: "80 Commonwealth St, Surry Hills NSW 2010",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "pcpmelbourne",
    website: "https://paramountcoffeeproject.com.au/",
    editorial_blurb: "Japanese-Australian collaboration café in Surry Hills that proved Sydney could hold its own — the wagyu sando and the pour-over are both non-negotiable.",
    featured_in: ["sprudge", "eater", "timeout"],
    verified: true, last_verified_at: "2025-11-01", verification_source: "admin",
  },
  {
    name: "Brewtown Newtown",
    slug: "brewtown-newtown-sydney",
    lat: -33.8965, lng: 151.1795,
    city: "Sydney", country: "Australia",
    address: "6-8 O'Connell St, Newtown NSW 2042",
    roaster: "Single O",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "brewtownnewtown",
    website: "https://www.brewtown.com.au/",
    editorial_blurb: "Newtown's specialty anchor in a converted warehouse — Single O beans, an open roastery floor, and the easy pace of Sydney's most interesting neighbourhood.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2025-10-25", verification_source: "admin",
  },
  {
    name: "Toby's Estate",
    slug: "tobys-estate-sydney",
    lat: -33.8867, lng: 151.2053,
    city: "Sydney", country: "Australia",
    address: "129 Devonshire St, Surry Hills NSW 2010",
    roaster: "Toby's Estate",
    brew_methods: ["espresso", "pour-over", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "tobysestate",
    website: "https://tobysestate.com.au/",
    editorial_blurb: "Sydney's most exported roastery — Toby's Estate trained half of Singapore and New York's barista talent while maintaining a benchmark Surry Hills café.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-18", verification_source: "admin",
  },
  {
    name: "Pablo & Rusty's",
    slug: "pablo-rustys-sydney",
    lat: -33.8672, lng: 151.2083,
    city: "Sydney", country: "Australia",
    address: "161 Castlereagh St, Sydney NSW 2000",
    roaster: "Pablo & Rusty's",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "standing-bar"],
    instagram_handle: "pabloandrustyss",
    website: "https://www.pabloandrustyss.com.au/",
    editorial_blurb: "CBD roastery café that brought Surry Hills standards to the financial district — the office-hour espresso programme holds up to anything in the city.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2025-10-15", verification_source: "admin",
  },
  {
    name: "Gumption Coffee",
    slug: "gumption-coffee-sydney",
    lat: -33.8694, lng: 151.2082,
    city: "Sydney", country: "Australia",
    address: "The Strand Arcade, 412 George St, Sydney NSW 2000",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["standing-bar", "no-laptop", "minimalist"],
    instagram_handle: "gumptioncoffee",
    editorial_blurb: "Strand Arcade heritage shopfront turned specialty espresso bar — Sydney's most theatrical coffee address, where the marble counter and the precision are equally impressive.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2025-10-20", verification_source: "admin",
  },
  {
    name: "Coffee Alchemy",
    slug: "coffee-alchemy-marrickville",
    lat: -33.9091, lng: 151.1636,
    city: "Sydney", country: "Australia",
    address: "100 Marrickville Rd, Marrickville NSW 2204",
    roaster: "Coffee Alchemy",
    brew_methods: ["pour-over", "espresso", "syphon", "chemex", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "coffeealchemy",
    website: "https://www.coffeealchemy.com.au/",
    editorial_blurb: "Marrickville single-origin laboratory that rewards the trip west — the most comprehensive brew method menu in the city, served by people who teach it.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-11-04", verification_source: "admin",
  },
  {
    name: "Rumble Coffee Roasters",
    slug: "rumble-coffee-rozelle",
    lat: -33.8628, lng: 151.1689,
    city: "Sydney", country: "Australia",
    address: "241 Darling St, Balmain NSW 2041",
    roaster: "Rumble Coffee Roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "rumblecoffeeroasters",
    editorial_blurb: "Balmain roastery with an unhurried inner-west pace and a sourcing programme that traces every bean back to the producer — exactly what specialty coffee is supposed to be.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-08", verification_source: "admin",
  },
  {
    name: "Edition Coffee Roasters",
    slug: "edition-coffee-roasters-sydney",
    lat: -33.8905, lng: 151.2069,
    city: "Sydney", country: "Australia",
    address: "33 Foveaux St, Surry Hills NSW 2010",
    roaster: "Edition Coffee Roasters",
    brew_methods: ["espresso", "pour-over", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "edition_coffee",
    website: "https://editioncoffee.com.au/",
    editorial_blurb: "Surry Hills micro-roastery built on the premise that small batches roasted close to service is the only way to work — every cup proves the point.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-12", verification_source: "admin",
  },
  {
    name: "Will & Co",
    slug: "will-and-co-sydney",
    lat: -33.8608, lng: 151.2107,
    city: "Sydney", country: "Australia",
    address: "72 Pitt St, Sydney NSW 2000",
    roaster: "Will & Co",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "willandco",
    website: "https://www.willandco.com.au/",
    editorial_blurb: "CBD specialty brand that scaled without compromising — the espresso is exacting and the cold brew tap makes every Sydney office worker's afternoon easier.",
    featured_in: ["timeout"],
    verified: true, last_verified_at: "2025-10-18", verification_source: "admin",
  },
  {
    name: "The Grounds of Alexandria",
    slug: "the-grounds-of-alexandria-sydney",
    lat: -33.9041, lng: 151.1955,
    city: "Sydney", country: "Australia",
    address: "7A/2 Huntley St, Alexandria NSW 2015",
    roaster: "The Grounds Roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "roastery-on-site"],
    instagram_handle: "thegroundsofale",
    website: "https://thegrounds.com.au/",
    editorial_blurb: "Sydney's most visited café destination and still genuinely good — the on-site roastery, market garden, and weekend crowds are all real, the coffee holds its own.",
    featured_in: ["eater", "timeout", "guardian"],
    verified: true, last_verified_at: "2025-10-30", verification_source: "admin",
  },

  {
    name: "Single O Haberfield",
    slug: "single-o-haberfield",
    lat: -33.8833, lng: 151.1478,
    city: "Sydney", country: "Australia",
    address: "241 Ramsay St, Haberfield NSW 2045",
    roaster: "Single O",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "singleocoffee",
    website: "https://www.singleo.com.au/",
    editorial_blurb: "Single O's inner-west café in an Italian neighbourhood that has always known how to drink coffee — the espresso programme earns respectful nods from both demographics.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Toby's Estate Potts Point",
    slug: "tobys-estate-potts-point",
    lat: -33.8720, lng: 151.2213,
    city: "Sydney", country: "Australia",
    address: "104 New South Head Rd, Edgecliff NSW 2027",
    roaster: "Toby's Estate",
    brew_methods: ["espresso", "pour-over", "aeropress", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "tobysestate",
    website: "https://tobysestate.com.au/",
    editorial_blurb: "Toby's Estate east-side café serving the Double Bay and Edgecliff crowd — the same benchmark roasting programme, now in Sydney's most residential specialty setting.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Workshop Espresso Sydney",
    slug: "workshop-espresso-sydney",
    lat: -33.8712, lng: 151.2063,
    city: "Sydney", country: "Australia",
    address: "Darlinghurst Rd, Darlinghurst NSW 2010",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["standing-bar", "minimalist", "no-laptop"],
    instagram_handle: "workshopespresso",
    editorial_blurb: "Darlinghurst express bar where the espresso is dialled in before the neighbourhood has woken up — Sydney's most efficient specialty coffee ritual.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Reformatory Caffeine Lab",
    slug: "reformatory-caffeine-lab-sydney",
    lat: -33.8828, lng: 151.2070,
    city: "Sydney", country: "Australia",
    address: "22-28 Eddy Ave, Haymarket NSW 2000",
    roaster: "Reformatory Caffeine Lab",
    brew_methods: ["pour-over", "espresso", "syphon", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "minimalist", "standing-bar"],
    instagram_handle: "reformatorycaffeinelab",
    editorial_blurb: "Central Station specialty laboratory treating espresso and filter as equal sciences — the brew method menu is the most academically rigorous in Sydney.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Skittle Lane",
    slug: "skittle-lane-sydney",
    lat: -33.8688, lng: 151.2048,
    city: "Sydney", country: "Australia",
    address: "14 Wilmot St, Sydney NSW 2000",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["standing-bar", "minimalist", "no-laptop"],
    instagram_handle: "skittlelane",
    editorial_blurb: "CBD laneway bar hidden in plain sight — the morning single-origin espresso here is the best-kept secret in Sydney's George Street precinct.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Ona Coffee Sydney",
    slug: "ona-coffee-sydney",
    lat: -33.8888, lng: 151.2059,
    city: "Sydney", country: "Australia",
    address: "9 Foster St, Surry Hills NSW 2010",
    roaster: "ONA Coffee",
    brew_methods: ["espresso", "pour-over", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "onacoffee",
    website: "https://onacoffee.com.au/",
    editorial_blurb: "Australia's most competition-decorated roastery opens in Surry Hills — the seasonal lot programme and the World Barista Championship pedigree raise Sydney's ceiling considerably.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "The Commons",
    slug: "the-commons-surry-hills",
    lat: -33.8852, lng: 151.2095,
    city: "Sydney", country: "Australia",
    address: "32 Burton St, Darlinghurst NSW 2010",
    roaster: "Single O",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "thecommonssydney",
    editorial_blurb: "Burton Street neighbourhood café with a Burton Street community — Single O on the bar, a rooftop vegetable garden overhead, and the unhurried pace that makes Darlinghurst worth visiting.",
    featured_in: ["timeout"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Single O Pyrmont",
    slug: "single-o-pyrmont",
    lat: -33.8706, lng: 151.1944,
    city: "Sydney", country: "Australia",
    address: "60 Union St, Pyrmont NSW 2009",
    roaster: "Single O",
    brew_methods: ["espresso", "cold-brew", "pour-over"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "singleocoffee",
    website: "https://www.singleo.com.au/",
    editorial_blurb: "Single O's roastery HQ and the source of the taps system that changed how Sydney thinks about batch brew — visiting is partly café, partly coffee pilgrimage.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Cali Press Newtown",
    slug: "cali-press-newtown",
    lat: -33.8960, lng: 151.1825,
    city: "Sydney", country: "Australia",
    address: "400 King St, Newtown NSW 2042",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "cold-brew", "pour-over"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "calipresscafes",
    website: "https://www.calipress.com.au/",
    editorial_blurb: "Newtown health-café brand with a specialty coffee programme that earns the patronage on its own merits — the cold brew tap and the King Street terrace are both daily habits for the neighbourhood.",
    featured_in: ["timeout"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Axil Coffee Sydney",
    slug: "axil-coffee-sydney",
    lat: -33.8671, lng: 151.2051,
    city: "Sydney", country: "Australia",
    address: "30 Bond St, Sydney NSW 2000",
    roaster: "Axil Coffee Roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["standing-bar", "minimalist"],
    instagram_handle: "axilcoffeeroasters",
    website: "https://axilcoffee.com.au/",
    editorial_blurb: "Melbourne's World Barista Championship roastery opens in Sydney's CBD — the espresso programme doesn't soften for the harbour city and both cities are better for it.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Five Senses Coffee Sydney",
    slug: "five-senses-coffee-sydney",
    lat: -33.8902, lng: 151.2071,
    city: "Sydney", country: "Australia",
    address: "77a Foveaux St, Surry Hills NSW 2010",
    roaster: "Five Senses Coffee",
    brew_methods: ["espresso", "pour-over", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "fivesensescoffee",
    website: "https://www.fivesenses.com.au/",
    editorial_blurb: "Perth-born specialty giant opens a Surry Hills café that makes the cross-continental roasting conversation visible — the WA and PNG single-origins are the most geographically distant in Sydney.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Black Star Pastry",
    slug: "black-star-pastry-newtown",
    lat: -33.8983, lng: 151.1785,
    city: "Sydney", country: "Australia",
    address: "277 Australia St, Newtown NSW 2042",
    roaster: "Single O",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "blackstarpastry",
    website: "https://www.blackstarpastry.com.au/",
    editorial_blurb: "The watermelon cake made it famous, but Single O on the bar makes it essential — Newtown's most-photographed café earns its reputation in both the food and the coffee.",
    featured_in: ["eater", "timeout", "guardian"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Double Roasters",
    slug: "double-roasters-sydney",
    lat: -33.8921, lng: 151.1825,
    city: "Sydney", country: "Australia",
    address: "166 Enmore Rd, Enmore NSW 2042",
    roaster: "Double Roasters",
    brew_methods: ["espresso", "pour-over", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "doubleroasters",
    editorial_blurb: "Enmore micro-roastery operating with the directness the name implies — two roasters, one mission, and some of Sydney's most interesting natural-process lots.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2025-09-01", verification_source: "community",
  },
  {
    name: "Sash Coffee",
    slug: "sash-coffee-surry-hills",
    lat: -33.8870, lng: 151.2102,
    city: "Sydney", country: "Australia",
    address: "25 Reservoir St, Surry Hills NSW 2010",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "sashcoffee",
    editorial_blurb: "Reservoir Street specialty bar in Sydney's most concentrated coffee neighbourhood — the rotating Australasian roaster programme is the area's most geographically adventurous.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2025-09-01", verification_source: "community",
  },
  {
    name: "Myrtle Coffee",
    slug: "myrtle-coffee-chippendale",
    lat: -33.8892, lng: 151.2055,
    city: "Sydney", country: "Australia",
    address: "75 Myrtle St, Chippendale NSW 2008",
    roaster: "Mecca Coffee",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["minimalist", "outdoor-seating"],
    instagram_handle: "myrtlecoffee",
    editorial_blurb: "Chippendale neighbourhood bar pouring Mecca with the quiet confidence of a café that knows its street well — the early-morning espresso here is Chippendale's best kept secret.",
    featured_in: ["timeout"],
    verified: false, last_verified_at: "2025-09-01", verification_source: "community",
  },
  {
    name: "Boon Café",
    slug: "boon-cafe-sydney",
    lat: -33.8854, lng: 151.2073,
    city: "Sydney", country: "Australia",
    address: "49 Albion St, Surry Hills NSW 2010",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew", "aeropress"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "booncafesydney",
    editorial_blurb: "Surry Hills Thai-Australian café where the cooking and the coffee programme compete for your loyalty in equal measure — the natural-process pour-over complements the northern Thai menu perfectly.",
    featured_in: ["timeout", "eater"],
    verified: false, last_verified_at: "2025-09-01", verification_source: "community",
  },
  {
    name: "Bare Espresso",
    slug: "bare-espresso-manly",
    lat: -33.7968, lng: 151.2880,
    city: "Sydney", country: "Australia",
    address: "Wentworth St, Manly NSW 2095",
    roaster: "Single O",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "bareespresso",
    editorial_blurb: "Manly's best specialty address serving the northern beaches crowd who refuse to compromise on coffee when they're this close to the ocean — Single O, naturally.",
    featured_in: ["timeout"],
    verified: false, last_verified_at: "2025-09-01", verification_source: "community",
  },
  {
    name: "Paramount Coffee Project Bondi",
    slug: "paramount-coffee-project-bondi",
    lat: -33.8908, lng: 151.2742,
    city: "Sydney", country: "Australia",
    address: "84 Campbell Parade, Bondi Beach NSW 2026",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "pcpmelbourne",
    website: "https://paramountcoffeeproject.com.au/",
    editorial_blurb: "Paramount's Bondi outpost applies Surry Hills precision to the most competitive café strip in Sydney — the ocean view and the pour-over compete equally for your attention.",
    featured_in: ["eater", "timeout"],
    verified: false, last_verified_at: "2025-09-01", verification_source: "community",
  },
  {
    name: "Bunker Coffee",
    slug: "bunker-coffee-sydney",
    lat: -33.8845, lng: 151.2080,
    city: "Sydney", country: "Australia",
    address: "22 McLachlan Ave, Rushcutters Bay NSW 2011",
    roaster: "Toby's Estate",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["outdoor-seating", "dog-friendly"],
    instagram_handle: "bunkercoffee_sydney",
    editorial_blurb: "Rushcutters Bay park-adjacent café with a view of the marina and Toby's Estate on the bar — Sydney's most pleasant morning espresso ritual, twelve months of the year.",
    featured_in: ["timeout"],
    verified: false, last_verified_at: "2025-09-01", verification_source: "community",
  },
  {
    name: "Room 10",
    slug: "room-10-potts-point",
    lat: -33.8744, lng: 151.2197,
    city: "Sydney", country: "Australia",
    address: "10 Llankelly Place, Potts Point NSW 2011",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["no-laptop", "minimalist"],
    instagram_handle: "room10espresso",
    editorial_blurb: "Potts Point laneway institution that has been pouring exceptional espresso in a room barely wider than the bar for over a decade — Sydney minimalism at its most principled.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Campos Coffee Newtown",
    slug: "campos-coffee-newtown",
    lat: -33.8956, lng: 151.1792,
    city: "Sydney", country: "Australia",
    address: "193 Missenden Rd, Newtown NSW 2042",
    roaster: "Campos Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "laptop-friendly"],
    instagram_handle: "camposcoffee",
    website: "https://www.camposcoffee.com/",
    editorial_blurb: "The Missenden Road roastery that gave Sydney a language for specialty — Campos pioneered direct trade in Australia and the Newtown café still pours the most consequential espresso in the city.",
    featured_in: ["sprudge", "standart", "guardian"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Mecca Coffee Rosebery",
    slug: "mecca-coffee-rosebery",
    lat: -33.9106, lng: 151.2025,
    city: "Sydney", country: "Australia",
    address: "64 Mentmore Ave, Rosebery NSW 2018",
    roaster: "Mecca Coffee",
    brew_methods: ["espresso", "pour-over", "chemex", "syphon"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "meccacoffee",
    website: "https://meccacoffee.com.au/",
    editorial_blurb: "Mecca's Rosebery roastery and training centre — the origin of everything the brand stands for, and the only place in Sydney you can watch the roasting while drinking the result.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Artificer Coffee Lane Cove",
    slug: "artificer-coffee-lane-cove",
    lat: -33.8181, lng: 151.1706,
    city: "Sydney", country: "Australia",
    address: "38 Burns Bay Rd, Lane Cove NSW 2066",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "artificercoffee",
    editorial_blurb: "Artificer's North Shore outpost applies the same Surry Hills extraction rigour to a quieter postcode — Lane Cove gets its first genuinely competition-grade specialty bar.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2025-09-01", verification_source: "community",
  },
  {
    name: "Rosebery Common",
    slug: "rosebery-common-sydney",
    lat: -33.9098, lng: 151.2041,
    city: "Sydney", country: "Australia",
    address: "27 Dunning Ave, Rosebery NSW 2018",
    roaster: "Sample Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "roseberycommon",
    editorial_blurb: "Dunning Avenue café serving Rosebery's design precinct with Sample Coffee on the bar — the warehouse-district crowd and the morning filter drinkers share the same reliable excellence.",
    featured_in: ["timeout"],
    verified: false, last_verified_at: "2025-09-01", verification_source: "community",
  },

  // ── AUCKLAND (8) ──────────────────────────────────────────────────────────────
  {
    name: "Kokako",
    slug: "kokako-auckland",
    lat: -36.8642, lng: 174.7341,
    city: "Auckland", country: "New Zealand",
    address: "537 Great North Rd, Grey Lynn, Auckland 1021",
    roaster: "Kokako",
    brew_methods: ["espresso", "pour-over", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "kokako_organic",
    website: "https://www.kokako.co.nz/",
    editorial_blurb: "Grey Lynn's organic specialty roastery is New Zealand's most principled coffee business — fair-trade, bird-friendly, and still producing the city's most interesting single-origins.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-11-05", verification_source: "admin",
  },
  {
    name: "Eighthirty Coffee Roasters",
    slug: "eighthirty-auckland",
    lat: -36.8487, lng: 174.7633,
    city: "Auckland", country: "New Zealand",
    address: "34 Wyndham St, Auckland CBD, Auckland 1010",
    roaster: "Eighthirty Coffee Roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "eighthirty",
    website: "https://eighthirty.co.nz/",
    editorial_blurb: "Auckland CBD roastery that supplies half the city's best cafés and runs a flagship bar that demonstrates exactly why — the espresso programme is as good as it gets.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-22", verification_source: "admin",
  },
  {
    name: "Allpress Espresso Auckland",
    slug: "allpress-espresso-auckland",
    lat: -36.8612, lng: 174.7479,
    city: "Auckland", country: "New Zealand",
    address: "8 Drake St, Freemans Bay, Auckland 1011",
    roaster: "Allpress Espresso",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "laptop-friendly"],
    instagram_handle: "allpressespresso",
    website: "https://allpressespresso.com/",
    editorial_blurb: "The origin story — Allpress started in this building before taking their espresso gospel to Sydney, Melbourne, Tokyo, and London, and the Auckland roastery still earns the pilgrimage.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2025-11-02", verification_source: "admin",
  },
  {
    name: "Atomic Coffee Roasters",
    slug: "atomic-coffee-auckland",
    lat: -36.8542, lng: 174.7452,
    city: "Auckland", country: "New Zealand",
    address: "3 Sale St, Freemans Bay, Auckland 1011",
    roaster: "Atomic Coffee Roasters",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "atomiccoffeeroasters",
    website: "https://www.atomiccoffee.co.nz/",
    editorial_blurb: "Auckland roastery institution with a decades-long direct-trade programme — their Ethiopia and Kenya lots remain benchmarks for what New Zealand expects from specialty.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-18", verification_source: "admin",
  },
  {
    name: "Paper Crane Coffee",
    slug: "paper-crane-auckland",
    lat: -36.8553, lng: 174.7609,
    city: "Auckland", country: "New Zealand",
    address: "90 Federal St, Auckland CBD, Auckland 1010",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "papercraneauckland",
    editorial_blurb: "CBD specialty bar with Japanese-influenced precision and an Auckland neighbourhood spirit — the rotating origin filter is the most considered in the city.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2025-09-20", verification_source: "community",
  },
  {
    name: "Coffee Supreme Auckland",
    slug: "coffee-supreme-auckland",
    lat: -36.8498, lng: 174.7605,
    city: "Auckland", country: "New Zealand",
    address: "376 Karangahape Rd, Newton, Auckland 1010",
    roaster: "Coffee Supreme",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "coffeesupreme",
    website: "https://coffeesupreme.com/",
    editorial_blurb: "K Road's coffee institution from the Wellington roastery that helped shape how Australasia thinks about specialty — the K Rd location has the energy the brand was built on.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2025-10-10", verification_source: "admin",
  },
  {
    name: "One Ton Coffee",
    slug: "one-ton-coffee-auckland",
    lat: -36.8559, lng: 174.7622,
    city: "Auckland", country: "New Zealand",
    address: "Commercial Bay, Auckland CBD, Auckland 1010",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["standing-bar", "minimalist"],
    instagram_handle: "onetoncoffee",
    editorial_blurb: "Commercial Bay's most focused espresso stop — the rotating micro-lot programme and the fast counter service make it Auckland CBD's best daily coffee ritual.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2025-09-15", verification_source: "community",
  },
  {
    name: "Morning Ritual",
    slug: "morning-ritual-auckland",
    lat: -36.8622, lng: 174.7508,
    city: "Auckland", country: "New Zealand",
    address: "Ponsonby Rd, Ponsonby, Auckland 1011",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "morningritualauckland",
    editorial_blurb: "Ponsonby's favourite daytime café — the guest roaster programme and the sunlit terrace make this Auckland's most pleasant way to start a morning.",
    featured_in: ["timeout"],
    verified: false, last_verified_at: "2025-09-10", verification_source: "community",
  },

  {
    name: "Mojo Coffee Queen Street",
    slug: "mojo-coffee-queen-street",
    lat: -36.8480, lng: 174.7637,
    city: "Auckland", country: "New Zealand",
    address: "29 Queen St, Auckland CBD, Auckland 1010",
    roaster: "Mojo Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "mojocoffee",
    website: "https://www.mojocoffee.co.nz/",
    editorial_blurb: "Wellington's most consistent specialty brand brings its South Pacific sourcing programme to Auckland's main commercial street — the CBD's most reliable flat white.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Ima Boutique Restaurant & Café",
    slug: "ima-boutique-auckland",
    lat: -36.8502, lng: 174.7614,
    city: "Auckland", country: "New Zealand",
    address: "53 Fort St, Auckland CBD, Auckland 1010",
    roaster: "Kokako",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "imaboutique",
    editorial_blurb: "Fort Street Middle-Eastern café where Kokako organic espresso accompanies brunch platters designed for sharing — the most civilised morning stop in Auckland's CBD.",
    featured_in: ["timeout"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Flight Coffee Auckland",
    slug: "flight-coffee-auckland",
    lat: -36.8511, lng: 174.7601,
    city: "Auckland", country: "New Zealand",
    address: "O'Connell St, Auckland CBD, Auckland 1010",
    roaster: "Flight Coffee",
    brew_methods: ["espresso", "pour-over", "aeropress", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "flightcoffee",
    website: "https://flightcoffee.co.nz/",
    editorial_blurb: "Wellington's defining roastery extends its direct-trade East African programme to Auckland's CBD — the single-origin pour-over board changes with each Wellington roast release.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Caffeine Laboratory",
    slug: "caffeine-laboratory-auckland",
    lat: -36.8530, lng: 174.7559,
    city: "Auckland", country: "New Zealand",
    address: "21 Britomart Place, Britomart, Auckland 1010",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "syphon", "aeropress"],
    vibe_tags: ["minimalist", "standing-bar", "no-laptop"],
    instagram_handle: "caffeinelaboratory",
    editorial_blurb: "Britomart lab-format specialty bar where the white-coat aesthetic is earned — rotating international roasters and a syphon menu that Auckland's coffee professionals visit on days off.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Mojo Coffee Britomart",
    slug: "mojo-coffee-britomart",
    lat: -36.8445, lng: 174.7688,
    city: "Auckland", country: "New Zealand",
    address: "29 Galway St, Britomart, Auckland 1010",
    roaster: "Mojo Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "mojocoffee",
    website: "https://www.mojocoffee.co.nz/",
    editorial_blurb: "Mojo's Britomart terrace café is the prettiest place to drink specialty coffee in Auckland — the Galway Street cobblestones and the Kokako-sourcing-level espresso are both worth the detour.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Kokako CBD",
    slug: "kokako-cbd-auckland",
    lat: -36.8495, lng: 174.7625,
    city: "Auckland", country: "New Zealand",
    address: "Fortieth Sq, 23 Fort Lane, Auckland CBD, Auckland 1010",
    roaster: "Kokako",
    brew_methods: ["espresso", "pour-over", "cold-brew", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "kokako_organic",
    website: "https://www.kokako.co.nz/",
    editorial_blurb: "Kokako's city-centre outpost delivers Grey Lynn's organic specialty pedigree to the corporate precinct — the Fairtrade sourcing and the filter menu are both identically principled.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Noble Espresso",
    slug: "noble-espresso-auckland",
    lat: -36.8472, lng: 174.7652,
    city: "Auckland", country: "New Zealand",
    address: "10 Durham Lane East, Auckland CBD, Auckland 1010",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["standing-bar", "minimalist", "no-laptop"],
    instagram_handle: "nobleespresso",
    editorial_blurb: "CBD laneway espresso bar that earns its name — the queue of bankers, architects, and baristas on days off tells you everything about the coffee before you taste it.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2025-09-01", verification_source: "community",
  },
  {
    name: "Eighthirty Ponsonby",
    slug: "eighthirty-ponsonby",
    lat: -36.8572, lng: 174.7479,
    city: "Auckland", country: "New Zealand",
    address: "Ponsonby Rd, Ponsonby, Auckland 1011",
    roaster: "Eighthirty Coffee Roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "eighthirty",
    website: "https://eighthirty.co.nz/",
    editorial_blurb: "Eighthirty extends its CBD roastery programme to Ponsonby's main retail strip — the espresso is calibrated to the same impossible standard and the neighbourhood is considerably more relaxed.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2025-09-01", verification_source: "community",
  },

  // ── WELLINGTON (7) ────────────────────────────────────────────────────────────
  {
    name: "Flight Coffee",
    slug: "flight-coffee-wellington",
    lat: -41.2934, lng: 174.7744,
    city: "Wellington", country: "New Zealand",
    address: "112 Dixon St, Te Aro, Wellington 6011",
    roaster: "Flight Coffee",
    brew_methods: ["espresso", "pour-over", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "flightcoffee",
    website: "https://flightcoffee.co.nz/",
    editorial_blurb: "Wellington's defining specialty roastery — Flight's direct-trade Kenyan and Ethiopian lots set the standard for what New Zealand expects from filter coffee.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-11-03", verification_source: "admin",
  },
  {
    name: "People's Coffee",
    slug: "peoples-coffee-wellington",
    lat: -41.3098, lng: 174.7841,
    city: "Wellington", country: "New Zealand",
    address: "4 Constable St, Newtown, Wellington 6021",
    roaster: "People's Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "peoplescoffee",
    website: "https://www.peoplescoffee.co.nz/",
    editorial_blurb: "Newtown worker-owned roastery that proved ethical trading and exceptional espresso belong in the same cup — Wellington's most principled and most beloved coffee business.",
    featured_in: ["sprudge", "standart", "guardian"],
    verified: true, last_verified_at: "2025-11-06", verification_source: "admin",
  },
  {
    name: "Caffe L'affare",
    slug: "caffe-laffare-wellington",
    lat: -41.2952, lng: 174.7758,
    city: "Wellington", country: "New Zealand",
    address: "27 College St, Te Aro, Wellington 6011",
    roaster: "L'affare",
    brew_methods: ["espresso", "pour-over", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "laptop-friendly"],
    instagram_handle: "caffelaffare",
    website: "https://www.laffare.co.nz/",
    editorial_blurb: "Wellington's oldest specialty roastery and still one of its best — three decades of direct-trade relationships and a Cuba Street-adjacent courtyard that anchors the city's café culture.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2025-10-28", verification_source: "admin",
  },
  {
    name: "Customs Brew Bar",
    slug: "customs-brew-bar-wellington",
    lat: -41.2856, lng: 174.7763,
    city: "Wellington", country: "New Zealand",
    address: "39 Customhouse Quay, Wellington 6011",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress", "chemex"],
    vibe_tags: ["minimalist", "standing-bar"],
    instagram_handle: "customsbrewbar",
    website: "https://customsbrewbar.com/",
    editorial_blurb: "Lambton Quay specialty bar that serves Wellington's government and legal district a proper alternative to mediocrity — the rotating single-origin pour-over is the reason people walk past the chains.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-18", verification_source: "admin",
  },
  {
    name: "Coffee Supreme Wellington",
    slug: "coffee-supreme-wellington",
    lat: -41.2928, lng: 174.7746,
    city: "Wellington", country: "New Zealand",
    address: "45 Dixon St, Te Aro, Wellington 6011",
    roaster: "Coffee Supreme",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "coffeesupreme",
    website: "https://coffeesupreme.com/",
    editorial_blurb: "The Wellington mothership of Australasia's most influential roastery — this is where Coffee Supreme's ethos was formed, and it still pours the most consistent flat white in the city.",
    featured_in: ["sprudge", "standart", "monocle"],
    verified: true, last_verified_at: "2025-11-01", verification_source: "admin",
  },
  {
    name: "Golding's Free Dive",
    slug: "goldings-free-dive-wellington",
    lat: -41.2944, lng: 174.7744,
    city: "Wellington", country: "New Zealand",
    address: "14 Leeds St, Te Aro, Wellington 6011",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "goldingsfreedive",
    editorial_blurb: "Wellington's most beloved low-key haunt — the daytime coffee is serious, the beer list is legendary, and the Cuba Quarter terrace is where the whole city eventually ends up.",
    featured_in: ["guardian", "timeout"],
    verified: true, last_verified_at: "2025-10-10", verification_source: "admin",
  },
  {
    name: "Midnight Espresso",
    slug: "midnight-espresso-wellington",
    lat: -41.2963, lng: 174.7745,
    city: "Wellington", country: "New Zealand",
    address: "178 Cuba St, Te Aro, Wellington 6011",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "midnightespresso",
    editorial_blurb: "Cuba Street's 24-hour institution that has served Wellington's musicians, students, and insomniacs a proper espresso since 1989 — the city's most unconditional coffee.",
    featured_in: ["guardian", "monocle"],
    verified: true, last_verified_at: "2025-10-22", verification_source: "admin",
  },
  {
    name: "Havana Coffee Works",
    slug: "havana-coffee-works-wellington",
    lat: -41.2967, lng: 174.7759,
    city: "Wellington", country: "New Zealand",
    address: "163 Tory St, Te Aro, Wellington 6011",
    roaster: "Havana Coffee Works",
    brew_methods: ["espresso", "pour-over", "french-press", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "laptop-friendly"],
    instagram_handle: "havanacoffeeworks",
    website: "https://www.havana.co.nz/",
    editorial_blurb: "Wellington's most storied independent roastery — Havana has been sourcing Central American lots directly since before direct trade had a name, and Tory Street smells like it.",
    featured_in: ["sprudge", "standart", "monocle"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Karaka Espresso",
    slug: "karaka-espresso-wellington",
    lat: -41.2840, lng: 174.7778,
    city: "Wellington", country: "New Zealand",
    address: "13 Grey St, Wellington 6011",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["minimalist", "standing-bar"],
    instagram_handle: "karakaespresso",
    editorial_blurb: "Lambton Quarter espresso bar built for Wellington's parliamentary precinct — the rotating New Zealand roaster programme and the zero-fuss service make this the government district's best coffee stop.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Prefab Eatery",
    slug: "prefab-eatery-wellington",
    lat: -41.2910, lng: 174.7790,
    city: "Wellington", country: "New Zealand",
    address: "14 Jessie St, Te Aro, Wellington 6011",
    roaster: "Coffee Supreme",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "prefabwellington",
    website: "https://prefab.co.nz/",
    editorial_blurb: "Wellington's most celebrated all-day café with Coffee Supreme on the bar and a brunch programme that has earned its own tourist following — the espresso and the house-baked bread are both essential.",
    featured_in: ["sprudge", "guardian", "timeout"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Fix & Fogg Coffee Bar",
    slug: "fix-and-fogg-coffee-wellington",
    lat: -41.2925, lng: 174.7749,
    city: "Wellington", country: "New Zealand",
    address: "52 Ghuznee St, Te Aro, Wellington 6011",
    roaster: "People's Coffee",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["no-laptop", "outdoor-seating"],
    instagram_handle: "fixandfogg",
    website: "https://fixandfogg.com/",
    editorial_blurb: "Wellington's world-famous nut butter maker runs a café bar where People's Coffee and toast piled with peanut butter are both, somehow, the specialty — the city's most honest combination.",
    featured_in: ["guardian", "timeout"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Mojo Coffee Wellington",
    slug: "mojo-coffee-wellington",
    lat: -41.2870, lng: 174.7766,
    city: "Wellington", country: "New Zealand",
    address: "14 Brandon St, Wellington 6011",
    roaster: "Mojo Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "mojocoffee",
    website: "https://www.mojocoffee.co.nz/",
    editorial_blurb: "Mojo's Wellington home base — the city that built the brand and still pours it best, with a Brandon Street location that serves the lunchtime legal district at proper specialty standard.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Espresso Workshop",
    slug: "espresso-workshop-wellington",
    lat: -41.2952, lng: 174.7764,
    city: "Wellington", country: "New Zealand",
    address: "61 Abel Smith St, Te Aro, Wellington 6011",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress", "chemex"],
    vibe_tags: ["minimalist", "laptop-friendly", "coworking"],
    instagram_handle: "espressoworkshopwgtn",
    editorial_blurb: "Abel Smith Street specialty bar running New Zealand's most considered guest roaster programme — the bi-monthly origin changeovers and the whiteboard tasting notes are worth planning your visit around.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2025-09-01", verification_source: "community",
  },
];
