import type { Cafe } from '@/types';

export const EU_RAW_CAFES: Omit<Cafe, 'id' | 'created_at' | 'third_wave_score' | 'overall_rating' | 'review_count' | 'permanently_closed'>[] = [
  // ── LONDON (18) ──────────────────────────────────────────────────────────────
  {
    name: "Monmouth Coffee",
    slug: "monmouth-coffee-london",
    lat: 51.5125,
    lng: -0.1237,
    city: "London",
    country: "United Kingdom",
    address: "27 Monmouth St, London WC2H 9EU",
    roaster: "Monmouth Coffee",
    brew_methods: ["pour-over", "espresso", "french-press"],
    vibe_tags: ["no-laptop", "outdoor-seating"],
    instagram_handle: "monmouthcoffee",
    website: "https://www.monmouthcoffee.co.uk/",
    editorial_blurb: "London's original specialty institution — the queue outside Borough Market moves fast and the cup at the end is always worth it.",
    featured_in: ["guardian", "timeout", "sprudge"],
    verified: true,
    last_verified_at: "2024-10-30",
    verification_source: "admin",
  },
  {
    name: "Square Mile Coffee Roasters",
    slug: "square-mile-london",
    lat: 51.5224,
    lng: -0.0864,
    city: "London",
    country: "United Kingdom",
    address: "Unit 4.1, The Tea Building, 56 Shoreditch High St, London E1 6JJ",
    roaster: "Square Mile Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "squaremilecoffee",
    website: "https://shop.squaremilecoffee.com/",
    editorial_blurb: "The roastery that trained a generation of London baristas — their Red Brick blend is a daily ritual for good reason.",
    featured_in: ["sprudge", "standart", "guardian"],
    verified: true,
    last_verified_at: "2024-11-02",
    verification_source: "admin",
  },
  {
    name: "Workshop Coffee",
    slug: "workshop-coffee-london",
    lat: 51.5181,
    lng: -0.1388,
    city: "London",
    country: "United Kingdom",
    address: "27 Mortimer St, London W1T 3BL",
    roaster: "Workshop Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "workshopcoffee",
    website: "https://www.workshopcoffee.com/",
    editorial_blurb: "Fitzrovia's most precise pour-over bar — their seasonal single-origins rotate fast and the staff can tell you exactly why each one tastes the way it does.",
    featured_in: ["sprudge", "standart", "guardian"],
    verified: true,
    last_verified_at: "2024-10-15",
    verification_source: "admin",
  },
  {
    name: "Caravan Coffee Roasters",
    slug: "caravan-coffee-london",
    lat: 51.5384,
    lng: -0.1236,
    city: "London",
    country: "United Kingdom",
    address: "Granary Building, 1 Granary Square, London N1C 4AA",
    roaster: "Caravan Coffee Roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "laptop-friendly"],
    instagram_handle: "caravancoffeeroasters",
    website: "https://www.caravanrestaurants.co.uk/",
    editorial_blurb: "King's Cross canalside roastery where the weekend brunch crowd and the filter-curious meet — the Granary Square setting is one of London's best.",
    featured_in: ["sprudge", "guardian", "timeout"],
    verified: true,
    last_verified_at: "2024-10-18",
    verification_source: "admin",
  },
  {
    name: "Climpson & Sons",
    slug: "climpson-sons-london",
    lat: 51.5390,
    lng: -0.0572,
    city: "London",
    country: "United Kingdom",
    address: "67 Broadway Market, London E8 4PH",
    roaster: "Climpson & Sons",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "climpsonandsons",
    editorial_blurb: "Broadway Market institution that helped put East London on the specialty map — the roastery above the café and the Saturday market energy are both essential.",
    featured_in: ["sprudge", "guardian"],
    verified: true,
    last_verified_at: "2024-09-20",
    verification_source: "admin",
  },
  {
    name: "Allpress Espresso",
    slug: "allpress-espresso-london",
    lat: 51.5478,
    lng: -0.0660,
    city: "London",
    country: "United Kingdom",
    address: "55 Dalston Lane, London E8 2NG",
    roaster: "Allpress Espresso",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "allpressespresso",
    website: "https://uk.allpressespresso.com/",
    editorial_blurb: "New Zealand's most exported coffee culture landed in Dalston with a roastery that makes some of East London's cleanest espresso.",
    featured_in: ["sprudge", "monocle"],
    verified: true,
    last_verified_at: "2024-10-05",
    verification_source: "admin",
  },
  {
    name: "Prufrock Coffee",
    slug: "prufrock-coffee-london",
    lat: 51.5193,
    lng: -0.1082,
    city: "London",
    country: "United Kingdom",
    address: "23-25 Leather Lane, London EC1N 7TE",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress", "chemex"],
    vibe_tags: ["laptop-friendly", "standing-bar"],
    instagram_handle: "prufrockuk",
    website: "https://www.prufrockuk.com/",
    editorial_blurb: "Leather Lane training ground and café where more London baristas have learned their craft than anywhere else — the technical depth is unmatched.",
    featured_in: ["sprudge", "standart", "guardian"],
    verified: true,
    last_verified_at: "2024-10-22",
    verification_source: "admin",
  },
  {
    name: "Dark Arts Coffee",
    slug: "dark-arts-coffee-london",
    lat: 51.5278,
    lng: -0.0601,
    city: "London",
    country: "United Kingdom",
    address: "286 Cambridge Heath Rd, London E2 9DA",
    roaster: "Dark Arts Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "darkartscoffee",
    website: "https://www.darkartscoffee.co.uk/",
    editorial_blurb: "Heavy-metal aesthetics and obsessively sourced beans — the Bethnal Green roastery is proof that great coffee doesn't need to look polite.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-28",
    verification_source: "admin",
  },
  {
    name: "Kaffeine",
    slug: "kaffeine-london",
    lat: 51.5181,
    lng: -0.1399,
    city: "London",
    country: "United Kingdom",
    address: "66 Great Titchfield St, London W1W 7QJ",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["no-laptop", "outdoor-seating"],
    instagram_handle: "kaffeineuk",
    website: "https://www.kaffeine.co.uk/",
    editorial_blurb: "Australian-founded Fitzrovia bar that helped define London's flat white era — still one of the best espresso programs in the West End.",
    featured_in: ["sprudge", "guardian", "timeout"],
    verified: true,
    last_verified_at: "2024-10-10",
    verification_source: "admin",
  },
  {
    name: "Notes Coffee Roasters",
    slug: "notes-coffee-london",
    lat: 51.5096,
    lng: -0.1257,
    city: "London",
    country: "United Kingdom",
    address: "31 St Martin's Lane, London WC2N 4ER",
    roaster: "Notes Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "notescoffee",
    website: "https://www.notescoffee.com/",
    editorial_blurb: "Trafalgar Square location with a roastery program that punches well above its tourist-adjacent address — the filter menu is genuinely excellent.",
    featured_in: ["sprudge", "timeout"],
    verified: true,
    last_verified_at: "2024-10-25",
    verification_source: "admin",
  },
  {
    name: "Curators Coffee Gallery",
    slug: "curators-coffee-london",
    lat: 51.5118,
    lng: -0.0855,
    city: "London",
    country: "United Kingdom",
    address: "9 Cullum St, London EC3M 7JJ",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "curatorscoffee",
    editorial_blurb: "City of London's best specialty bar — a calm, precise counter where the Square Mile's suited workers and the coffee-obsessed share the same bench.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-08",
    verification_source: "admin",
  },
  {
    name: "Association Coffee",
    slug: "association-coffee-london",
    lat: 51.5135,
    lng: -0.0787,
    city: "London",
    country: "United Kingdom",
    address: "10-12 Creechurch Lane, London EC3A 5AY",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "associationcoffee",
    editorial_blurb: "Creechurch Lane's understated gem — a rotating roster of the UK's best roasters and baristas who know how to talk terroir without the attitude.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-01",
    verification_source: "admin",
  },
  {
    name: "Nude Espresso",
    slug: "nude-espresso-london",
    lat: 51.5188,
    lng: -0.0733,
    city: "London",
    country: "United Kingdom",
    address: "26 Hanbury St, London E1 6QR",
    roaster: "Nude Espresso",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["outdoor-seating", "minimalist"],
    instagram_handle: "nudeespresso",
    website: "https://www.nudeespresso.com/",
    editorial_blurb: "Spitalfields institution that quietly outlasted every wave of Shoreditch trend — the espresso has always been the point, and it still is.",
    featured_in: ["sprudge", "guardian"],
    verified: true,
    last_verified_at: "2024-09-15",
    verification_source: "admin",
  },
  {
    name: "Taylor Street Baristas",
    slug: "taylor-street-baristas-london",
    lat: 51.5149,
    lng: -0.0882,
    city: "London",
    country: "United Kingdom",
    address: "125 Old Broad St, London EC2N 1AR",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["standing-bar", "no-laptop"],
    instagram_handle: "taylorstreetcoffee",
    website: "https://www.taylor-st.com/",
    editorial_blurb: "Australian-founded City coffee bar running fast espresso with Australian warmth — the Bank location handles morning rush without ever losing quality.",
    featured_in: ["sprudge", "timeout"],
    verified: true,
    last_verified_at: "2024-09-30",
    verification_source: "admin",
  },
  {
    name: "Redemption Roasters",
    slug: "redemption-roasters-london",
    lat: 51.5379,
    lng: -0.1027,
    city: "London",
    country: "United Kingdom",
    address: "Upper Street, London N1 (Islington)",
    roaster: "Redemption Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "redemptionroasters",
    website: "https://www.redemptionroasters.com/",
    editorial_blurb: "Social enterprise roastery training baristas in prisons — the coffee is seriously good and the mission behind every cup makes it taste better.",
    featured_in: ["sprudge", "guardian"],
    verified: true,
    last_verified_at: "2024-10-12",
    verification_source: "admin",
  },
  {
    name: "Ozone Coffee Roasters",
    slug: "ozone-coffee-london",
    lat: 51.5242,
    lng: -0.0865,
    city: "London",
    country: "United Kingdom",
    address: "11 Leonard St, London EC2A 4AQ",
    roaster: "Ozone Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "ozonecoffee",
    website: "https://ozonecoffee.co.uk/",
    editorial_blurb: "New Zealand roastery's London flagship on Leonard Street — open kitchen, roastery visible from the bar, and some of the best breakfast in Shoreditch.",
    featured_in: ["sprudge", "monocle"],
    verified: true,
    last_verified_at: "2024-11-01",
    verification_source: "admin",
  },
  {
    name: "The Espresso Room",
    slug: "the-espresso-room-london",
    lat: 51.5219,
    lng: -0.1195,
    city: "London",
    country: "United Kingdom",
    address: "31-35 Great Ormond St, London WC1N 3HZ",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["standing-bar", "minimalist"],
    instagram_handle: "theespressoroom",
    editorial_blurb: "Bloomsbury standing bar with a ruthlessly edited menu and perfectly calibrated espresso — everything here is intentional, nothing is wasted.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-10",
    verification_source: "admin",
  },
  {
    name: "Dose Espresso",
    slug: "dose-espresso-london",
    lat: 51.5197,
    lng: -0.0979,
    city: "London",
    country: "United Kingdom",
    address: "70 Long Lane, London EC1A 9EJ",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "doseespresso",
    editorial_blurb: "Long Lane strip-back counter where the focus is entirely on the shot — a City/EC1 institution that helped prove London could do espresso as well as Sydney.",
    featured_in: ["sprudge", "guardian"],
    verified: true,
    last_verified_at: "2024-09-25",
    verification_source: "admin",
  },

  // ── COPENHAGEN (11) ──────────────────────────────────────────────────────────
  {
    name: "The Coffee Collective",
    slug: "the-coffee-collective-copenhagen",
    lat: 55.6867,
    lng: 12.5611,
    city: "Copenhagen",
    country: "Denmark",
    address: "Jægersborggade 10, 2200 Copenhagen",
    roaster: "The Coffee Collective",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "coffeecollective",
    website: "https://coffeecollective.dk/",
    editorial_blurb: "Copenhagen's gold standard for specialty — their direct-trade relationships and obsessive roasting set the benchmark for Northern Europe.",
    featured_in: ["sprudge", "standart", "monocle"],
    verified: true,
    last_verified_at: "2024-11-10",
    verification_source: "admin",
  },
  {
    name: "Prolog Coffee Bar",
    slug: "prolog-coffee-bar",
    lat: 55.6761,
    lng: 12.5572,
    city: "Copenhagen",
    country: "Denmark",
    address: "Vesterbrogade 76, 1620 Copenhagen",
    roaster: "Prolog",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "standing-bar"],
    instagram_handle: "prologcoffee",
    editorial_blurb: "Vespa and concrete, espresso and natural wine — Prolog made the Copenhagen café look louder and the coffee just as good.",
    featured_in: ["sprudge", "guardian"],
    verified: true,
    last_verified_at: "2024-10-01",
    verification_source: "admin",
  },
  {
    name: "Original Coffee",
    slug: "original-coffee-copenhagen",
    lat: 55.6894,
    lng: 12.5529,
    city: "Copenhagen",
    country: "Denmark",
    address: "Nørrebrogade 23, 2200 Copenhagen",
    roaster: "Original Coffee",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "originalcoffeedk",
    editorial_blurb: "Relaxed, unpretentious, consistently excellent — the kind of neighborhood spot Copenhagen does better than anywhere.",
    featured_in: ["timeout"],
    verified: true,
    last_verified_at: "2024-08-15",
    verification_source: "community",
  },
  {
    name: "La Cabra Coffee",
    slug: "la-cabra-copenhagen",
    lat: 55.6783,
    lng: 12.5742,
    city: "Copenhagen",
    country: "Denmark",
    address: "Admiralgade 26, 1066 Copenhagen K",
    roaster: "La Cabra",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "lacabracoffee",
    website: "https://www.lacabracoffee.com/",
    editorial_blurb: "Aarhus roastery's Copenhagen outpost brings their competition-pedigree light roasts to the capital — the pour-over menu rewards patience.",
    featured_in: ["sprudge", "standart"],
    verified: true,
    last_verified_at: "2024-10-20",
    verification_source: "admin",
  },
  {
    name: "Democratic Coffee",
    slug: "democratic-coffee-copenhagen",
    lat: 55.6738,
    lng: 12.5729,
    city: "Copenhagen",
    country: "Denmark",
    address: "Bernstorffsgade 6, 1577 Copenhagen V",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "democraticcoffee",
    editorial_blurb: "City Hall neighbor serving the kind of filter coffee that makes you stay for a second — relaxed, democratic, and quietly excellent.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-05",
    verification_source: "admin",
  },
  {
    name: "Risteriet",
    slug: "risteriet-copenhagen",
    lat: 55.6751,
    lng: 12.5388,
    city: "Copenhagen",
    country: "Denmark",
    address: "Gammel Kongevej 1, 1610 Copenhagen V",
    roaster: "Risteriet",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "risteriet",
    editorial_blurb: "Frederiksberg roastery café with a small-batch focus and a regulars crowd that knows exactly what they're ordering — a neighborhood gem.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-10",
    verification_source: "community",
  },
  {
    name: "Darcy's Kaffe",
    slug: "darcys-kaffe-copenhagen",
    lat: 55.6906,
    lng: 12.5476,
    city: "Copenhagen",
    country: "Denmark",
    address: "Fælledvej 2, 2200 Copenhagen N",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "darcyskaffe",
    editorial_blurb: "Nørrebro corner café where the Fælledparken crowd fuels up before the park — unpretentious specialty coffee done exactly right.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-18",
    verification_source: "community",
  },
  {
    name: "Talormade",
    slug: "talormade-copenhagen",
    lat: 55.6695,
    lng: 12.5551,
    city: "Copenhagen",
    country: "Denmark",
    address: "Dybbølsgade 20A, 1721 Copenhagen V",
    roaster: "Talormade",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "talormade_coffee",
    editorial_blurb: "Vesterbro's most precise pour-over bar — a tiny footprint, a focused menu, and the kind of attention to extraction that earns its own following.",
    featured_in: ["sprudge", "standart"],
    verified: true,
    last_verified_at: "2024-10-28",
    verification_source: "admin",
  },
  {
    name: "Juno the Bakery",
    slug: "juno-bakery-copenhagen",
    lat: 55.6831,
    lng: 12.5838,
    city: "Copenhagen",
    country: "Denmark",
    address: "Gothersgade 28, 1123 Copenhagen K",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["no-laptop", "outdoor-seating"],
    instagram_handle: "juno_the_bakery",
    editorial_blurb: "The cardamom bun queue is real, and so is the coffee — Juno pairs Copenhagen's best pastry with seriously sourced espresso.",
    featured_in: ["sprudge", "guardian"],
    verified: true,
    last_verified_at: "2024-10-15",
    verification_source: "admin",
  },
  {
    name: "Ricco's Kaffebar",
    slug: "riccos-kaffebar-copenhagen",
    lat: 55.6731,
    lng: 12.5506,
    city: "Copenhagen",
    country: "Denmark",
    address: "Istedgade 119, 1650 Copenhagen V",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "riccoskaffebar",
    editorial_blurb: "Istedgade institution that rode every wave of Copenhagen coffee and emerged as a neighborhood anchor — knowledgeable staff and a welcoming atmosphere.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-05",
    verification_source: "community",
  },
  {
    name: "Sort Kaffe & Vinyl",
    slug: "sort-kaffe-vinyl-copenhagen",
    lat: 55.6744,
    lng: 12.5491,
    city: "Copenhagen",
    country: "Denmark",
    address: "Skydebanegade 4, 1709 Copenhagen V",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "sortkaffe",
    editorial_blurb: "Vinyl plays, filter pours, Vesterbro hums — Sort Kaffe is as Copenhagen as it gets, stripped back to two things done well.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-22",
    verification_source: "community",
  },

  // ── BERLIN (11) ──────────────────────────────────────────────────────────────
  {
    name: "The Barn",
    slug: "the-barn-berlin",
    lat: 52.5289,
    lng: 13.3859,
    city: "Berlin",
    country: "Germany",
    address: "Auguststraße 58, 10119 Berlin",
    roaster: "The Barn",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "thebarnberlin",
    website: "https://thebarn.de/",
    editorial_blurb: "Berlin's most opinionated roaster — they'll tell you which brew method suits your chosen bean, and they'll be right.",
    featured_in: ["sprudge", "monocle", "standart"],
    verified: true,
    last_verified_at: "2024-10-25",
    verification_source: "admin",
  },
  {
    name: "Five Elephant",
    slug: "five-elephant-berlin",
    lat: 52.4994,
    lng: 13.4283,
    city: "Berlin",
    country: "Germany",
    address: "Reichenberger Str. 101, 10999 Berlin",
    roaster: "Five Elephant",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "fiveelephant",
    website: "https://www.fiveelephant.com/",
    editorial_blurb: "Kreuzberg coffee institution — the cheesecake has its own fanbase but the roasting is what put them on the world map.",
    featured_in: ["sprudge", "guardian"],
    verified: true,
    last_verified_at: "2024-10-18",
    verification_source: "admin",
  },
  {
    name: "Bonanza Coffee Roasters",
    slug: "bonanza-coffee-berlin",
    lat: 52.5399,
    lng: 13.4055,
    city: "Berlin",
    country: "Germany",
    address: "Oderberger Str. 35, 10435 Berlin",
    roaster: "Bonanza Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "bonanzacoffee",
    website: "https://www.bonanzacoffee.de/",
    editorial_blurb: "Prenzlauer Berg's original specialty anchor with a sun-drenched roastery courtyard — the light-roast filter menu and the garden are both worth the trip.",
    featured_in: ["sprudge", "standart", "guardian"],
    verified: true,
    last_verified_at: "2024-11-05",
    verification_source: "admin",
  },
  {
    name: "Father Carpenter",
    slug: "father-carpenter-berlin",
    lat: 52.5261,
    lng: 13.4023,
    city: "Berlin",
    country: "Germany",
    address: "Münzstraße 21, 10178 Berlin",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "fathercarpenter",
    website: "https://www.fathercarpenter.com/",
    editorial_blurb: "Mitte all-day café that nailed the specialty-meets-brunch formula before it was fashionable — the espresso program has always been the backbone.",
    featured_in: ["sprudge", "monocle"],
    verified: true,
    last_verified_at: "2024-10-20",
    verification_source: "admin",
  },
  {
    name: "Silo Coffee",
    slug: "silo-coffee-berlin",
    lat: 52.5094,
    lng: 13.4534,
    city: "Berlin",
    country: "Germany",
    address: "Gabriel-Max-Str. 4, 10245 Berlin",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "silocoffeeberlin",
    editorial_blurb: "Friedrichshain's most consistent pour-over bar — an ever-rotating guest list of Europe's best roasters in a stripped-back Kiez setting.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-08",
    verification_source: "admin",
  },
  {
    name: "Café Oliv",
    slug: "cafe-oliv-berlin",
    lat: 52.5258,
    lng: 13.4012,
    city: "Berlin",
    country: "Germany",
    address: "Mulackstraße 17, 10119 Berlin",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "cafe_oliv",
    editorial_blurb: "Mitte gem on Mulackstraße where the coffee is as considered as the interior — small, focused, and beloved by the people who know Berlin well.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-15",
    verification_source: "community",
  },
  {
    name: "Commonground Coffee",
    slug: "commonground-coffee-berlin",
    lat: 52.5244,
    lng: 13.4005,
    city: "Berlin",
    country: "Germany",
    address: "Neue Schönhauser Str. 13, 10178 Berlin",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "commongroundberlin",
    editorial_blurb: "Neue Schönhauser corner café that bridges Mitte's tourist-facing streets with a genuinely local specialty scene — the terrace fills fast.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-28",
    verification_source: "community",
  },
  {
    name: "Concierge Coffee",
    slug: "concierge-coffee-berlin",
    lat: 52.5272,
    lng: 13.4107,
    city: "Berlin",
    country: "Germany",
    address: "Rosa-Luxemburg-Str. 2, 10178 Berlin",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["standing-bar", "minimalist"],
    instagram_handle: "concierge_coffee",
    editorial_blurb: "Tucked into the Volkspark entrance, Concierge runs a standing bar where the espresso is always on point and the vibe is always Berlin.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-02",
    verification_source: "community",
  },
  {
    name: "ISLA Coffee",
    slug: "isla-coffee-berlin",
    lat: 52.4892,
    lng: 13.3882,
    city: "Berlin",
    country: "Germany",
    address: "Willibald-Alexis-Str. 9, 10965 Berlin",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "outdoor-seating"],
    instagram_handle: "isla_coffee_berlin",
    editorial_blurb: "Kreuzberg's sunlit corner spot where a rotating guest roaster program keeps the pour-over menu perpetually worth exploring.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-20",
    verification_source: "community",
  },
  {
    name: "Companion Coffee",
    slug: "companion-coffee-berlin",
    lat: 52.5498,
    lng: 13.3603,
    city: "Berlin",
    country: "Germany",
    address: "Sprengelstraße 2, 13353 Berlin",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "companion_coffee_berlin",
    editorial_blurb: "Wedding neighborhood café that brought serious specialty north of the ring — unpretentious, consistent, and worth the detour from Mitte.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-05",
    verification_source: "community",
  },
  {
    name: "Roamers",
    slug: "roamers-berlin",
    lat: 52.4856,
    lng: 13.4379,
    city: "Berlin",
    country: "Germany",
    address: "Pannierstraße 64, 12047 Berlin",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "laptop-friendly"],
    instagram_handle: "roamers_berlin",
    editorial_blurb: "Neukölln all-day café with an Antipodean ethos and a back courtyard that becomes the best garden in Berlin when the sun is out.",
    featured_in: ["sprudge", "guardian"],
    verified: true,
    last_verified_at: "2024-10-12",
    verification_source: "admin",
  },

  // ── PARIS (15) ───────────────────────────────────────────────────────────────
  {
    name: "Café Lomi",
    slug: "cafe-lomi-paris",
    lat: 48.8894,
    lng: 2.3483,
    city: "Paris",
    country: "France",
    address: "3ter Rue Marcadet, 75018 Paris",
    roaster: "Café Lomi",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "cafelomi",
    website: "https://www.cafelomi.com/",
    editorial_blurb: "Montmartre warehouse roastery that proved Paris could take specialty as seriously as Scandinavia — the filter menu changes weekly.",
    featured_in: ["sprudge", "guardian"],
    verified: true,
    last_verified_at: "2024-10-25",
    verification_source: "admin",
  },
  {
    name: "Coutume Café",
    slug: "coutume-cafe-paris",
    lat: 48.8558,
    lng: 2.3167,
    city: "Paris",
    country: "France",
    address: "47 Rue de Babylone, 75007 Paris",
    roaster: "Coutume",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "coutumecafe",
    website: "https://coutumecafe.com/",
    editorial_blurb: "The café that brought Australian coffee culture to the 7th arrondissement — flat whites and serious filter in equal measure.",
    featured_in: ["sprudge", "monocle"],
    verified: true,
    last_verified_at: "2024-10-08",
    verification_source: "admin",
  },
  {
    name: "Ten Belles",
    slug: "ten-belles-paris",
    lat: 48.8701,
    lng: 2.3625,
    city: "Paris",
    country: "France",
    address: "10 Rue de la Grange aux Belles, 75010 Paris",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "tenbelles",
    editorial_blurb: "Canal Saint-Martin institution pairing natural wines with pour-overs — the terrace is Paris specialty at its most atmospheric.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-20",
    verification_source: "admin",
  },
  {
    name: "Café Oberkampf",
    slug: "cafe-oberkampf-paris",
    lat: 48.8650,
    lng: 2.3728,
    city: "Paris",
    country: "France",
    address: "3 Rue de la Folie Méricourt, 75011 Paris",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "cafeoberkampf",
    editorial_blurb: "11th arrondissement all-day bar where the specialty espresso is as serious as the natural wine list — a neighborhood essential for the Oberkampf crowd.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-10",
    verification_source: "admin",
  },
  {
    name: "Belleville Brûlerie",
    slug: "belleville-brulerie-paris",
    lat: 48.8755,
    lng: 2.3803,
    city: "Paris",
    country: "France",
    address: "10 Rue de Pradier, 75019 Paris",
    roaster: "Belleville Brûlerie",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "bellevillebrulerie",
    website: "https://www.bellevillebrulerie.com/",
    editorial_blurb: "19th arrondissement roastery that co-founded the Paris specialty movement with Lomi — light-roast filter coffee and a dog-friendly roasting floor.",
    featured_in: ["sprudge", "standart"],
    verified: true,
    last_verified_at: "2024-11-05",
    verification_source: "admin",
  },
  {
    name: "Café Loustic",
    slug: "cafe-loustic-paris",
    lat: 48.8616,
    lng: 2.3557,
    city: "Paris",
    country: "France",
    address: "40 Rue Chapon, 75003 Paris",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "cafeloustic",
    editorial_blurb: "Marais charmer with a precise pour-over focus and one of Paris's most considered guest roaster programs — small room, big coffee.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-05",
    verification_source: "admin",
  },
  {
    name: "Honor Café",
    slug: "honor-cafe-paris",
    lat: 48.8655,
    lng: 2.3404,
    city: "Paris",
    country: "France",
    address: "Galerie Vivienne, 6 Rue des Petits Champs, 75001 Paris",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "honorcafe",
    editorial_blurb: "Hidden inside the Galerie Vivienne arcade — Honor is Paris's most atmospheric specialty bar, where 19th-century glass ceilings frame a 21st-century espresso.",
    featured_in: ["sprudge", "monocle"],
    verified: true,
    last_verified_at: "2024-10-28",
    verification_source: "admin",
  },
  {
    name: "KB CaféShop",
    slug: "kb-cafeshop-paris",
    lat: 48.8793,
    lng: 2.3463,
    city: "Paris",
    country: "France",
    address: "53 Avenue Trudaine, 75009 Paris",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "kbcafeshop",
    editorial_blurb: "South Pigalle institution that anchored the neighborhood's café boom — the terrace and the batch brew are both non-negotiable.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-15",
    verification_source: "admin",
  },
  {
    name: "Fragments Paris",
    slug: "fragments-paris",
    lat: 48.8571,
    lng: 2.3617,
    city: "Paris",
    country: "France",
    address: "76 Rue des Tournelles, 75003 Paris",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "fragmentsparis",
    editorial_blurb: "Marais gallery-café where the coffee curation is as deliberate as the design — a rotating cast of Europe's finest roasters on a quiet Rue des Tournelles.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-12",
    verification_source: "admin",
  },
  {
    name: "Telescope Café",
    slug: "telescope-cafe-paris",
    lat: 48.8647,
    lng: 2.3379,
    city: "Paris",
    country: "France",
    address: "5 Rue Villedo, 75001 Paris",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["minimalist", "standing-bar"],
    instagram_handle: "telescopecafe",
    editorial_blurb: "1st arrondissement micro-café where the espresso is calibrated daily and the space forces a pleasant intimacy with the coffee and the barista.",
    featured_in: ["sprudge", "guardian"],
    verified: true,
    last_verified_at: "2024-10-20",
    verification_source: "admin",
  },
  {
    name: "Boot Café",
    slug: "boot-cafe-paris",
    lat: 48.8604,
    lng: 2.3571,
    city: "Paris",
    country: "France",
    address: "19 Rue du Pont aux Choux, 75003 Paris",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "bootcafe",
    editorial_blurb: "Paris's smallest specialty bar — converted from a shoe repair shop, now serving some of the city's best espresso from a room barely bigger than the machine.",
    featured_in: ["sprudge", "monocle"],
    verified: true,
    last_verified_at: "2024-10-18",
    verification_source: "admin",
  },
  {
    name: "Hexagone Café",
    slug: "hexagone-cafe-paris",
    lat: 48.8453,
    lng: 2.3207,
    city: "Paris",
    country: "France",
    address: "121 Rue du Cherche-Midi, 75006 Paris",
    roaster: "Hexagone",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "hexagone_cafe",
    website: "https://hexagonecafe.fr/",
    editorial_blurb: "6th arrondissement roastery with a French sourcing pride — their program champions West African and Caribbean origins alongside the usual suspects.",
    featured_in: ["sprudge", "standart"],
    verified: true,
    last_verified_at: "2024-11-08",
    verification_source: "admin",
  },
  {
    name: "Café Méricourt",
    slug: "cafe-mericourt-paris",
    lat: 48.8636,
    lng: 2.3726,
    city: "Paris",
    country: "France",
    address: "22 Rue de la Folie Méricourt, 75011 Paris",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "cafe_mericourt",
    editorial_blurb: "All-day 11th arrondissement café that proved Paris's Oberkampf quarter could do proper third-wave coffee alongside a full menu — both are good.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-25",
    verification_source: "admin",
  },
  {
    name: "La Caféothèque",
    slug: "la-cafeotheque-paris",
    lat: 48.8535,
    lng: 2.3554,
    city: "Paris",
    country: "France",
    address: "52 Rue de l'Hôtel-de-Ville, 75004 Paris",
    roaster: "La Caféothèque",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress", "french-press"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "lacafeotheque",
    website: "https://www.lacafeotheque.com/",
    editorial_blurb: "The grandmother of Paris specialty — Gloria Montenegro opened this Marais institution before the city knew what third-wave meant, and it remains essential.",
    featured_in: ["sprudge", "standart", "guardian"],
    verified: true,
    last_verified_at: "2024-11-02",
    verification_source: "admin",
  },
  {
    name: "Dose – Dealer de Café",
    slug: "dose-dealer-paris",
    lat: 48.8456,
    lng: 2.3509,
    city: "Paris",
    country: "France",
    address: "73 Rue Mouffetard, 75005 Paris",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "dose_caffe",
    editorial_blurb: "Rue Mouffetard market street espresso bar — the outdoor counter and the well-priced specialty shots make this the Latin Quarter's best coffee stop.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-10",
    verification_source: "community",
  },

  // ── AMSTERDAM (10) ───────────────────────────────────────────────────────────
  {
    name: "Lot Sixty One Coffee Roasters",
    slug: "lot-sixty-one-amsterdam",
    lat: 52.3737,
    lng: 4.8741,
    city: "Amsterdam",
    country: "Netherlands",
    address: "Kinkerstraat 112, 1053 EG Amsterdam",
    roaster: "Lot Sixty One",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "lotsixtyone",
    website: "https://www.lotsixtyone.com/",
    editorial_blurb: "Flagship of Dutch specialty coffee — the Jordaan roastery's seasonal menu is the best introduction to serious Amsterdam beans.",
    featured_in: ["sprudge", "monocle"],
    verified: true,
    last_verified_at: "2024-11-02",
    verification_source: "admin",
  },
  {
    name: "White Label Coffee",
    slug: "white-label-coffee-amsterdam",
    lat: 52.3712,
    lng: 4.8674,
    city: "Amsterdam",
    country: "Netherlands",
    address: "Jan Evertsenstraat 136, 1057 BK Amsterdam",
    roaster: "White Label Coffee",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "whitelabelcoffeeams",
    editorial_blurb: "Stripped-back Amsterdam West space with a serious filter focus — no distractions, just excellent beans brewed with precision.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-14",
    verification_source: "admin",
  },
  {
    name: "Bocca Coffee",
    slug: "bocca-coffee-amsterdam",
    lat: 52.3798,
    lng: 4.8837,
    city: "Amsterdam",
    country: "Netherlands",
    address: "Westerstraat 33, 1015 LR Amsterdam",
    roaster: "Bocca Coffee",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "boccacoffee",
    website: "https://www.boccacoffee.nl/",
    editorial_blurb: "One of Europe's most respected sourcing programs lives in this Westerstraat roastery — the traceability details go further than almost anyone.",
    featured_in: ["sprudge", "standart"],
    verified: true,
    last_verified_at: "2024-10-05",
    verification_source: "admin",
  },
  {
    name: "Scandinavian Embassy",
    slug: "scandinavian-embassy-amsterdam",
    lat: 52.3552,
    lng: 4.8964,
    city: "Amsterdam",
    country: "Netherlands",
    address: "Sarphatipark 34, 1073 CZ Amsterdam",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["minimalist", "outdoor-seating"],
    instagram_handle: "scandinavianembassy",
    website: "https://www.scandinavianembassy.nl/",
    editorial_blurb: "De Pijp's Nordic outpost — Sarphatipark views, Scandinavian sourcing sensibility, and a pour-over menu that makes the neighborhood even harder to leave.",
    featured_in: ["sprudge", "monocle"],
    verified: true,
    last_verified_at: "2024-11-05",
    verification_source: "admin",
  },
  {
    name: "Friedhats",
    slug: "friedhats-amsterdam",
    lat: 52.3614,
    lng: 4.9301,
    city: "Amsterdam",
    country: "Netherlands",
    address: "Pontanusstraat 6, 1094 GC Amsterdam",
    roaster: "Friedhats",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "friedhats",
    website: "https://friedhats.com/",
    editorial_blurb: "East Amsterdam roastery with a filter-first philosophy and an educational bent — the tasting menus here are among the city's most rewarding coffee experiences.",
    featured_in: ["sprudge", "standart"],
    verified: true,
    last_verified_at: "2024-10-22",
    verification_source: "admin",
  },
  {
    name: "Back to Black Coffee",
    slug: "back-to-black-amsterdam",
    lat: 52.3516,
    lng: 4.8986,
    city: "Amsterdam",
    country: "Netherlands",
    address: "Ferdinand Bolstraat 98, 1072 LM Amsterdam",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["no-laptop", "outdoor-seating"],
    instagram_handle: "backtoblackamsterdam",
    editorial_blurb: "De Pijp neighborhood anchor where the espresso is always on and the terrace always buzzing — simple, warm, and genuinely excellent.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-10",
    verification_source: "community",
  },
  {
    name: "Espressofabriek",
    slug: "espressofabriek-amsterdam",
    lat: 52.3846,
    lng: 4.8690,
    city: "Amsterdam",
    country: "Netherlands",
    address: "Gosschalklaan 7, 1013 AT Amsterdam",
    roaster: "Espressofabriek",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "laptop-friendly"],
    instagram_handle: "espressofabriek",
    website: "https://www.espressofabriek.nl/",
    editorial_blurb: "Westerpark industrial roastery in a former gas works — the cavernous space and the quality espresso program are both bigger than they look from outside.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-18",
    verification_source: "admin",
  },
  {
    name: "Man Met Bril Koffie",
    slug: "man-met-bril-amsterdam",
    lat: 52.3655,
    lng: 4.8650,
    city: "Amsterdam",
    country: "Netherlands",
    address: "Jan Pieter Heijestraat 21, 1054 VB Amsterdam",
    roaster: "Man Met Bril Koffie",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "manmetbrilkoffie",
    editorial_blurb: "Oud-West roastery café where the glasses-wearing man on the bag matches the attention to detail inside — a reliable neighborhood institution.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-25",
    verification_source: "community",
  },
  {
    name: "Headfirst Coffee Roasters",
    slug: "headfirst-coffee-amsterdam",
    lat: 52.3702,
    lng: 4.9006,
    city: "Amsterdam",
    country: "Netherlands",
    address: "Jodenbreestraat 29, 1011 NJ Amsterdam",
    roaster: "Headfirst Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "headfirstcoffee",
    editorial_blurb: "Nieuwmarkt roastery café with a filter-first menu and the kind of single-origin depth that makes each visit different — Amsterdam's most educational coffee stop.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-15",
    verification_source: "admin",
  },
  {
    name: "Coffee District",
    slug: "coffee-district-amsterdam",
    lat: 52.3721,
    lng: 4.8781,
    city: "Amsterdam",
    country: "Netherlands",
    address: "Elandsgracht 62, 1016 TX Amsterdam",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "coffeedistrictams",
    editorial_blurb: "Jordaan canal-side café where the relaxed setting and consistent espresso keep a loyal neighborhood crowd returning daily.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-12",
    verification_source: "community",
  },

  // ── VIENNA (9) ───────────────────────────────────────────────────────────────
  {
    name: "Kaffeefabrik",
    slug: "kaffeefabrik-vienna",
    lat: 48.1967,
    lng: 16.3686,
    city: "Vienna",
    country: "Austria",
    address: "Favoritenstraße 4-6, 1040 Vienna",
    roaster: "Kaffeefabrik",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "kaffeefabrik",
    website: "https://kaffeefabrik.at/",
    editorial_blurb: "4th district roastery with an uncompromising single-origin focus — the most technically rigorous coffee in a city famous for café tradition.",
    featured_in: ["sprudge", "standart"],
    verified: true,
    last_verified_at: "2024-10-28",
    verification_source: "admin",
  },
  {
    name: "Café Phil",
    slug: "cafe-phil-vienna",
    lat: 48.1988,
    lng: 16.3571,
    city: "Vienna",
    country: "Austria",
    address: "Gumpendorfer Str. 10-12, 1060 Vienna",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "cafephilvienna",
    website: "https://www.cafephil.at/",
    editorial_blurb: "Books, vinyl, and specialty espresso in Vienna's 6th district — the most atmospheric café in a city built on atmosphere.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-15",
    verification_source: "admin",
  },
  {
    name: "Seven",
    slug: "seven-vienna",
    lat: 48.2089,
    lng: 16.3703,
    city: "Vienna",
    country: "Austria",
    address: "Siebensterngasse 7, 1070 Vienna",
    roaster: "Seven",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["minimalist", "standing-bar"],
    instagram_handle: "sevencoffeebar",
    editorial_blurb: "Third-wave sensibility meets Viennese café tradition in the 1st district — the espresso here bridges two centuries of coffee culture.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-28",
    verification_source: "admin",
  },
  {
    name: "MOK",
    slug: "mok-kaffee-vienna",
    lat: 48.2088,
    lng: 16.3660,
    city: "Vienna",
    country: "Austria",
    address: "Schauflergasse 6, 1010 Vienna",
    roaster: "MOK",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "mok_wien",
    editorial_blurb: "Inner-city Vienna's most focused specialty bar — a tiny 1st district shop where the pour-over is always worth pausing for.",
    featured_in: ["sprudge", "monocle"],
    verified: true,
    last_verified_at: "2024-11-01",
    verification_source: "admin",
  },
  {
    name: "Supersense",
    slug: "supersense-vienna",
    lat: 48.2034,
    lng: 16.3521,
    city: "Vienna",
    country: "Austria",
    address: "Burggasse 19-21, 1070 Vienna",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "supersense_hq",
    website: "https://supersense.com/",
    editorial_blurb: "Analog lifestyle emporium in the 7th with a coffee bar that matches the obsessive precision of the cameras, film, and records sold alongside it.",
    featured_in: ["sprudge", "monocle"],
    verified: true,
    last_verified_at: "2024-10-20",
    verification_source: "admin",
  },
  {
    name: "Mokuya Coffee",
    slug: "mokuya-coffee-vienna",
    lat: 48.1985,
    lng: 16.3851,
    city: "Vienna",
    country: "Austria",
    address: "Ungargasse 60, 1030 Vienna",
    roaster: "Mokuya Coffee",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "mokuya_coffee",
    editorial_blurb: "3rd district specialty café with a Japanese-influenced minimalism and a filter menu that makes Landstraße worth the walk.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-22",
    verification_source: "community",
  },
  {
    name: "Coffee Pirates",
    slug: "coffee-pirates-vienna",
    lat: 48.2274,
    lng: 16.3543,
    city: "Vienna",
    country: "Austria",
    address: "Nußdorfer Str. 2, 1090 Vienna",
    roaster: "Coffee Pirates",
    brew_methods: ["espresso", "pour-over", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "coffeepirates_vienna",
    editorial_blurb: "9th district roastery with a loyal Alsergrund following and a house-roasted menu that favors clarity and origin transparency.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-05",
    verification_source: "community",
  },
  {
    name: "BKK1",
    slug: "bkk1-vienna",
    lat: 48.2036,
    lng: 16.3558,
    city: "Vienna",
    country: "Austria",
    address: "Theobaldgasse 16, 1060 Vienna",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "bkk1coffee",
    editorial_blurb: "Mariahilf specialty café with an ever-changing bean roster and a terrace that feels definitively Viennese even when the coffee is Kenyan.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-30",
    verification_source: "community",
  },
  {
    name: "Hamet Coffee Bar",
    slug: "hamet-coffee-vienna",
    lat: 48.2022,
    lng: 16.3546,
    city: "Vienna",
    country: "Austria",
    address: "Kirchengasse 10, 1070 Vienna",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["minimalist", "standing-bar"],
    instagram_handle: "hamet_coffee",
    editorial_blurb: "7th district standing bar doing exactly what a great neighborhood coffee stop should — fast, precise, and completely unpretentious.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-08",
    verification_source: "community",
  },

  // ── STOCKHOLM (9) ────────────────────────────────────────────────────────────
  {
    name: "Drop Coffee Roasters",
    slug: "drop-coffee-stockholm",
    lat: 59.3151,
    lng: 18.0611,
    city: "Stockholm",
    country: "Sweden",
    address: "Wollmar Yxkullsgatan 10, 118 50 Stockholm",
    roaster: "Drop Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "dropcoffeeroasters",
    website: "https://dropcoffee.se/",
    editorial_blurb: "World competition winners roasting in Södermalm — the precision and restraint in every cup explains every trophy on the shelf.",
    featured_in: ["sprudge", "standart"],
    verified: true,
    last_verified_at: "2024-11-04",
    verification_source: "admin",
  },
  {
    name: "Johan & Nyström",
    slug: "johan-nystrom-stockholm",
    lat: 59.3169,
    lng: 18.0744,
    city: "Stockholm",
    country: "Sweden",
    address: "Swedenborgsgatan 7, 118 48 Stockholm",
    roaster: "Johan & Nyström",
    brew_methods: ["pour-over", "espresso", "cold-brew", "chemex"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "johanochnystrm",
    website: "https://johanochnystrm.se/",
    editorial_blurb: "The Scandinavian specialty pioneer that opened Sweden's eyes to origin coffee — still the city's most essential roastery café.",
    featured_in: ["sprudge", "monocle"],
    verified: true,
    last_verified_at: "2024-10-30",
    verification_source: "admin",
  },
  {
    name: "Café Pascal",
    slug: "cafe-pascal-stockholm",
    lat: 59.3414,
    lng: 18.0436,
    city: "Stockholm",
    country: "Sweden",
    address: "Norrtullsgatan 4, 113 29 Stockholm",
    roaster: "Café Pascal",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "cafepascal",
    website: "https://cafepascal.se/",
    editorial_blurb: "Vasastan neighborhood roastery with a loyal local following — the rotating single-origins and relaxed setting make it hard to leave.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-10",
    verification_source: "admin",
  },
  {
    name: "Morgon Coffee Roasters",
    slug: "morgon-coffee-stockholm",
    lat: 59.3132,
    lng: 18.0375,
    city: "Stockholm",
    country: "Sweden",
    address: "Hornstulls Strand 4, 117 39 Stockholm",
    roaster: "Morgon Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "morgoncoffee",
    website: "https://morgoncoffeeroasters.se/",
    editorial_blurb: "Hornstull waterfront roastery where the view and the single-origins compete for attention — the light-roast filter program is among Stockholm's finest.",
    featured_in: ["sprudge", "standart"],
    verified: true,
    last_verified_at: "2024-11-06",
    verification_source: "admin",
  },
  {
    name: "Mellqvist Kaffebar",
    slug: "mellqvist-kaffebar-stockholm",
    lat: 59.3392,
    lng: 18.0469,
    city: "Stockholm",
    country: "Sweden",
    address: "Rörstrandsgatan 4, 113 40 Stockholm",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "mellqvistkaffebar",
    editorial_blurb: "Vasastan neighborhood institution where the morning queue tells you everything you need to know — reliable, warm, and consistently excellent espresso.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-15",
    verification_source: "admin",
  },
  {
    name: "Café Saturnus",
    slug: "cafe-saturnus-stockholm",
    lat: 59.3384,
    lng: 18.0862,
    city: "Stockholm",
    country: "Sweden",
    address: "Erik Dahlbergsgatan 4, 114 26 Stockholm",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "cafesaturnus",
    editorial_blurb: "Östermalm institution famous for Sweden's best cardamom bun — the coffee is equally serious, just slightly less photographed.",
    featured_in: ["sprudge", "guardian"],
    verified: true,
    last_verified_at: "2024-10-08",
    verification_source: "admin",
  },
  {
    name: "Solde Kaffebar",
    slug: "solde-kaffebar-stockholm",
    lat: 59.3119,
    lng: 18.0272,
    city: "Stockholm",
    country: "Sweden",
    address: "Hornsgatan 150, 117 36 Stockholm",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "soldekaffebar",
    editorial_blurb: "Hornstull end of Södermalm's main drag — Solde does clean filter coffee and good espresso without any of the fuss that Södermalm sometimes attracts.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-20",
    verification_source: "community",
  },
  {
    name: "Pom & Flora",
    slug: "pom-flora-stockholm",
    lat: 59.3352,
    lng: 18.0663,
    city: "Stockholm",
    country: "Sweden",
    address: "Hamngatan 37, 111 47 Stockholm",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "pom_flora",
    editorial_blurb: "City center café where brunch and specialty espresso overlap in the best possible way — the light-filled interior and Nordic menu make it a city-centre refuge.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-12",
    verification_source: "community",
  },
  {
    name: "Kalf & Hansen",
    slug: "kalf-hansen-stockholm",
    lat: 59.3155,
    lng: 18.0785,
    city: "Stockholm",
    country: "Sweden",
    address: "Katarina Bangata 4, 116 39 Stockholm",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "kalfhansen",
    editorial_blurb: "Södermalm deli-café that takes the coffee as seriously as the cheese and charcuterie — a neighborhood anchor with a reliable specialty program.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-05",
    verification_source: "community",
  },

  // ── LISBON (10) ──────────────────────────────────────────────────────────────
  {
    name: "Fábrica Coffee Roasters",
    slug: "fabrica-coffee-lisbon",
    lat: 38.7111,
    lng: -9.1421,
    city: "Lisbon",
    country: "Portugal",
    address: "Rua Nova do Carvalho 10, 1200-291 Lisbon",
    roaster: "Fábrica Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "fabricacoffeeroasters",
    website: "https://www.fabricacoffeeroasters.com/",
    editorial_blurb: "Lisbon's first specialty roastery set the standard the rest of the city is still catching up to — the Chiado flagship remains unmissable.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-11-01",
    verification_source: "admin",
  },
  {
    name: "Copenhagen Coffee Lab Lisbon",
    slug: "copenhagen-coffee-lab-lisbon",
    lat: 38.7178,
    lng: -9.1470,
    city: "Lisbon",
    country: "Portugal",
    address: "Rua Nova da Piedade 10, 1200-298 Lisbon",
    roaster: "Copenhagen Coffee Lab",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "copenhagencoffeelab",
    editorial_blurb: "Danish precision transplanted to Príncipe Real — Scandinavian sourcing and technique in one of Lisbon's best-looking cafés.",
    featured_in: ["sprudge", "monocle"],
    verified: true,
    last_verified_at: "2024-10-18",
    verification_source: "admin",
  },
  {
    name: "Hello, Kristof",
    slug: "hello-kristof-lisbon",
    lat: 38.7230,
    lng: -9.1342,
    city: "Lisbon",
    country: "Portugal",
    address: "Largo do Intendente Pina Manique 1, 1100-285 Lisbon",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "hellokristof",
    editorial_blurb: "Natural wines and natural-process coffees at Intendente — the most exciting pairing in Lisbon's rapidly evolving drinks scene.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-25",
    verification_source: "admin",
  },
  {
    name: "Toma Café",
    slug: "toma-cafe-lisbon",
    lat: 38.7134,
    lng: -9.1487,
    city: "Lisbon",
    country: "Portugal",
    address: "Rua da Imprensa Nacional 56C, 1250-127 Lisbon",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "tomacafe",
    editorial_blurb: "Príncipe Real's finest specialty café — a compact space with a rotating European roaster program and staff who have clearly done the work.",
    featured_in: ["sprudge", "standart"],
    verified: true,
    last_verified_at: "2024-10-28",
    verification_source: "admin",
  },
  {
    name: "Wish Slow Coffee House",
    slug: "wish-coffee-lisbon",
    lat: 38.7126,
    lng: -9.1439,
    city: "Lisbon",
    country: "Portugal",
    address: "Rua do Século 26, 1200-433 Lisbon",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "wishslowcoffee",
    editorial_blurb: "Bairro Alto slow coffee bar where the name is the mission — unhurried, considerate service and beans sourced with genuine care.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-12",
    verification_source: "admin",
  },
  {
    name: "Comoba",
    slug: "comoba-lisbon",
    lat: 38.7122,
    lng: -9.1441,
    city: "Lisbon",
    country: "Portugal",
    address: "Rua do Século 39, 1200-433 Lisbon",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "comoba_lisbon",
    editorial_blurb: "Bairro Alto all-day café with a specialty coffee program that keeps pace with the food — a reliable neighborhood anchor in one of Lisbon's best streets.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-20",
    verification_source: "community",
  },
  {
    name: "Café Tati",
    slug: "cafe-tati-lisbon",
    lat: 38.7068,
    lng: -9.1462,
    city: "Lisbon",
    country: "Portugal",
    address: "Rua da Ribeira Nova 36, 1200-371 Lisbon",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "cafetati",
    editorial_blurb: "Cais do Sodré terrace institution where the riverside people-watching is as good as the espresso — exactly what Lisbon mornings were invented for.",
    featured_in: ["sprudge", "timeout"],
    verified: true,
    last_verified_at: "2024-10-05",
    verification_source: "admin",
  },
  {
    name: "Dear Breakfast",
    slug: "dear-breakfast-lisbon",
    lat: 38.7100,
    lng: -9.1479,
    city: "Lisbon",
    country: "Portugal",
    address: "Calçada do Combro 82, 1200-083 Lisbon",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "dearbreakfastlisbon",
    editorial_blurb: "Santa Catarina hillside café where the avocado toast comes with a properly pulled shot — Lisbon's specialty-meets-brunch formula at its most enjoyable.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-15",
    verification_source: "community",
  },
  {
    name: "Garagem Lisboa",
    slug: "garagem-lisboa",
    lat: 38.7175,
    lng: -9.1356,
    city: "Lisbon",
    country: "Portugal",
    address: "Rua da Mouraria 4, 1100-340 Lisbon",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "garagemlisboa",
    editorial_blurb: "Mouraria converted garage turned specialty café — a sign of how far Lisbon's coffee scene has traveled in just a few years.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-08",
    verification_source: "community",
  },
  {
    name: "Slow",
    slug: "slow-lisbon",
    lat: 38.7103,
    lng: -9.1430,
    city: "Lisbon",
    country: "Portugal",
    address: "Rua do Loreto 53, 1200-117 Lisbon",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "slow.coffee.bar",
    editorial_blurb: "Name-as-manifesto coffee bar in Bairro Alto — unhurried pour-overs and a quiet interior that runs counter to the neighborhood's usual energy.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-02",
    verification_source: "community",
  },

  // ── BARCELONA (11) ───────────────────────────────────────────────────────────
  {
    name: "Nomad Coffee",
    slug: "nomad-coffee-barcelona",
    lat: 41.4037,
    lng: 2.1972,
    city: "Barcelona",
    country: "Spain",
    address: "Passatge Sert 12, 08003 Barcelona",
    roaster: "Nomad Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "nomadcoffee",
    website: "https://nomadcoffee.es/",
    editorial_blurb: "Competition pedigree meets Poblenou industrial — the roastery behind Spain's most decorated specialty program is worth crossing Barcelona for.",
    featured_in: ["sprudge", "standart"],
    verified: true,
    last_verified_at: "2024-11-05",
    verification_source: "admin",
  },
  {
    name: "Syra Coffee",
    slug: "syra-coffee-barcelona",
    lat: 41.3930,
    lng: 2.1570,
    city: "Barcelona",
    country: "Spain",
    address: "Carrer de Enric Granados 36, 08008 Barcelona",
    roaster: "Syra Coffee",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "syracoffee",
    website: "https://syracoffee.com/",
    editorial_blurb: "Eixample minimalism done right — clean design and excellent filter coffee make Syra the neighborhood anchor Barcelona needed.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-20",
    verification_source: "admin",
  },
  {
    name: "Right Side Coffee Bar",
    slug: "right-side-coffee-barcelona",
    lat: 41.3853,
    lng: 2.1822,
    city: "Barcelona",
    country: "Spain",
    address: "Carrer del Parlament 33, 08015 Barcelona",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "rightsidecoffee",
    editorial_blurb: "Aussie-influenced El Born bar with a strong espresso program and the kind of relaxed confidence Barcelona's specialty scene needed.",
    featured_in: ["sprudge", "timeout"],
    verified: true,
    last_verified_at: "2024-10-08",
    verification_source: "admin",
  },
  {
    name: "Satan's Coffee Corner",
    slug: "satans-coffee-barcelona",
    lat: 41.3918,
    lng: 2.1841,
    city: "Barcelona",
    country: "Spain",
    address: "Arc de Triomf, Carrer de l'Arc de Triomf 12, 08018 Barcelona",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["minimalist", "standing-bar"],
    instagram_handle: "satanscoffee",
    editorial_blurb: "The name is a provocation; the espresso is an argument — Satan's tiny Arc de Triomf counter is one of Barcelona's most opinionated coffee stops.",
    featured_in: ["sprudge", "standart"],
    verified: true,
    last_verified_at: "2024-10-22",
    verification_source: "admin",
  },
  {
    name: "Espai Joliu",
    slug: "espai-joliu-barcelona",
    lat: 41.3909,
    lng: 2.1695,
    city: "Barcelona",
    country: "Spain",
    address: "Carrer de Bailèn 54, 08009 Barcelona",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "espaijoliu",
    editorial_blurb: "Eixample light-filled workspace-café where the filter coffee is reliably excellent and the natural-light interior makes afternoon work sessions feel civilized.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-15",
    verification_source: "admin",
  },
  {
    name: "Federal Café",
    slug: "federal-cafe-barcelona",
    lat: 41.3790,
    lng: 2.1589,
    city: "Barcelona",
    country: "Spain",
    address: "Carrer del Parlament 39, 08015 Barcelona",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "federalcafe",
    website: "https://federalcafe.es/",
    editorial_blurb: "Australian-style all-day café that showed Sant Antoni what brunch-with-serious-coffee could look like — the terrace queue on Sunday mornings proves it worked.",
    featured_in: ["sprudge", "timeout"],
    verified: true,
    last_verified_at: "2024-10-18",
    verification_source: "admin",
  },
  {
    name: "Cafés El Magnífico",
    slug: "cafes-el-magnifico-barcelona",
    lat: 41.3839,
    lng: 2.1817,
    city: "Barcelona",
    country: "Spain",
    address: "Carrer de l'Argenteria 64, 08003 Barcelona",
    roaster: "Cafés El Magnífico",
    brew_methods: ["pour-over", "espresso", "chemex", "french-press"],
    vibe_tags: ["roastery-on-site", "no-laptop"],
    instagram_handle: "cafeselmagnificobcn",
    editorial_blurb: "Barcelona's oldest specialty roaster and still the most essential — El Born institution since 1919, still sourcing and roasting with the same exacting standards.",
    featured_in: ["sprudge", "standart", "guardian"],
    verified: true,
    last_verified_at: "2024-11-05",
    verification_source: "admin",
  },
  {
    name: "Dr. Stramm",
    slug: "dr-stramm-barcelona",
    lat: 41.3845,
    lng: 2.1793,
    city: "Barcelona",
    country: "Spain",
    address: "Carrer de Lluís el Petit 2, 08003 Barcelona",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["minimalist", "standing-bar"],
    instagram_handle: "drstramm",
    editorial_blurb: "El Born standing bar where the shots are always dialed in and the space is smaller than the reputation — a necessary stop on any Barcelona coffee tour.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-10",
    verification_source: "community",
  },
  {
    name: "Butler Coffee",
    slug: "butler-coffee-barcelona",
    lat: 41.3779,
    lng: 2.1576,
    city: "Barcelona",
    country: "Spain",
    address: "Carrer del Parlament 1, 08015 Barcelona",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "butlercoffee",
    editorial_blurb: "Sant Antoni specialty bar doing precise filter work and well-sourced espresso without the attitude — the morning regulars know exactly what they're doing here.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-25",
    verification_source: "community",
  },
  {
    name: "Blackbird Coffee",
    slug: "blackbird-coffee-barcelona",
    lat: 41.4018,
    lng: 2.1589,
    city: "Barcelona",
    country: "Spain",
    address: "Carrer de Verdi 27, 08012 Barcelona",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "blackbirdcoffeebcn",
    editorial_blurb: "Gràcia neighborhood café where the specialty coffee landed quietly and stayed permanently — the Verdi street terrace is one of Barcelona's nicest coffee stops.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-18",
    verification_source: "community",
  },
  {
    name: "Garage Coffee",
    slug: "garage-coffee-barcelona",
    lat: 41.3898,
    lng: 2.1669,
    city: "Barcelona",
    country: "Spain",
    address: "Carrer de la Diputació 238, 08007 Barcelona",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "garagecoffeebcn",
    editorial_blurb: "Eixample roastery café where the industrial bones and the specialty program are both doing serious work — a strong addition to Barcelona's increasingly competitive scene.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-10",
    verification_source: "community",
  },

  // ── ISTANBUL (12) ─────────────────────────────────────────────────────────────
  {
    name: "Kronotrop",
    slug: "kronotrop-istanbul",
    lat: 41.0326, lng: 28.9828,
    city: "Istanbul", country: "Turkey",
    address: "Sıraselviler Cad. 69, Cihangir, 34433 Istanbul",
    roaster: "Kronotrop",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "kronotrop",
    website: "https://kronotrop.com.tr/",
    editorial_blurb: "Istanbul's most respected specialty roaster set in Cihangir's creative hub — the filter coffee here challenges everything you thought you knew about Turkish coffee.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2024-11-04", verification_source: "admin",
  },
  {
    name: "Petra Roasting Co.",
    slug: "petra-roasting-istanbul",
    lat: 41.0233, lng: 28.9748,
    city: "Istanbul", country: "Turkey",
    address: "Kemankeş Karamustafa Paşa Mah., Karaköy, Istanbul",
    roaster: "Petra Roasting Co.",
    brew_methods: ["espresso", "pour-over", "chemex"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "petraroasting",
    editorial_blurb: "Karaköy roastery with Bosphorus views and a bean programme worth navigating Istanbul's hills for — specialty coffee with an unmissable setting.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-15", verification_source: "admin",
  },
  {
    name: "MOC Coffee",
    slug: "moc-coffee-istanbul",
    lat: 41.0472, lng: 28.9944,
    city: "Istanbul", country: "Turkey",
    address: "Abdi İpekçi Cad., Nişantaşı, Istanbul",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "moccoffeetr",
    editorial_blurb: "Japanese-influenced minimalism in Nişantaşı — the focused pour-over menu and quiet interior are the antidote to Istanbul's sensory overload.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-30", verification_source: "admin",
  },
  {
    name: "Brew Lab Istanbul",
    slug: "brew-lab-istanbul",
    lat: 41.0261, lng: 28.9762,
    city: "Istanbul", country: "Turkey",
    address: "Galata, Beyoğlu, 34421 Istanbul",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress", "syphon"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "brewlabistanbul",
    editorial_blurb: "Galata's most technically focused specialty bar — the rotating international guest roaster programme brings the world's best lots to a neighbourhood already full of wonders.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-22", verification_source: "admin",
  },
  {
    name: "Lot Coffee",
    slug: "lot-coffee-istanbul",
    lat: 41.0241, lng: 28.9752,
    city: "Istanbul", country: "Turkey",
    address: "Kemankeş Cad., Karaköy, 34425 Istanbul",
    roaster: "Lot Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "minimalist"],
    instagram_handle: "lotcoffee",
    editorial_blurb: "Karaköy corner roastery where the Bosphorus breeze and the single-origin filter menu make an argument that Istanbul is one of the world's great coffee cities.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-12", verification_source: "admin",
  },
  {
    name: "Norm Coffee",
    slug: "norm-coffee-istanbul",
    lat: 41.0435, lng: 29.0063,
    city: "Istanbul", country: "Turkey",
    address: "Beşiktaş, Istanbul",
    roaster: "Norm Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "normcoffee",
    editorial_blurb: "Beşiktaş specialty roastery built on the conviction that Turkish coffee culture and third-wave precision belong in the same room — and proving it with every batch.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-08", verification_source: "admin",
  },
  {
    name: "Paper Cup",
    slug: "paper-cup-istanbul",
    lat: 41.0331, lng: 28.9813,
    city: "Istanbul", country: "Turkey",
    address: "Cihangir Mah., Beyoğlu, Istanbul",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "papercupist",
    editorial_blurb: "Cihangir neighbourhood café that the local creative community treats as a second living room — the guest roaster espresso is an honest daily ritual.",
    featured_in: ["timeout"],
    verified: false, last_verified_at: "2024-09-20", verification_source: "community",
  },
  {
    name: "GAIA Coffee Roasters",
    slug: "gaia-coffee-kadikoy",
    lat: 40.9904, lng: 29.0241,
    city: "Istanbul", country: "Turkey",
    address: "Moda, Kadıköy, Istanbul",
    roaster: "GAIA Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "gaiacoffeeroasters",
    editorial_blurb: "Kadıköy's leading specialty roastery on the Asian side — GAIA proves the Bosphorus is not a barrier to exceptional coffee, it's just a short ferry ride.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-28", verification_source: "admin",
  },
  {
    name: "Arkaoda",
    slug: "arkaoda-kadikoy",
    lat: 40.9912, lng: 29.0253,
    city: "Istanbul", country: "Turkey",
    address: "Moda Cad. 109, Kadıköy, 34710 Istanbul",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "arkaoda",
    website: "https://www.arkaoda.com/",
    editorial_blurb: "Kadıköy's beloved cultural venue by day serves specialty coffee on a terrace that doubles as the Asian side's most sociable morning spot.",
    featured_in: ["timeout", "guardian"],
    verified: true, last_verified_at: "2024-10-05", verification_source: "admin",
  },
  {
    name: "Coffee Department",
    slug: "coffee-department-istanbul",
    lat: 41.0348, lng: 28.9862,
    city: "Istanbul", country: "Turkey",
    address: "İstiklal Cad., Beyoğlu, Istanbul",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "coffeedeptist",
    editorial_blurb: "İstiklal Street specialty bar that filters out the tourist noise — the single-origin pour-over and standing counter are a deliberate contrast to everything outside the door.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2024-09-15", verification_source: "community",
  },
  {
    name: "Totem Coffee",
    slug: "totem-coffee-istanbul",
    lat: 41.0481, lng: 28.9930,
    city: "Istanbul", country: "Turkey",
    address: "Nişantaşı, Şişli, Istanbul",
    roaster: "Totem Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "totemcoffee",
    editorial_blurb: "Nişantaşı's most polished new-wave espresso bar — precise, spare, and popular with the neighbourhood's fashion and design crowd for exactly those reasons.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2024-09-10", verification_source: "community",
  },
  {
    name: "Nar Kahve",
    slug: "nar-kahve-istanbul",
    lat: 41.0264, lng: 28.9773,
    city: "Istanbul", country: "Turkey",
    address: "Galata, Beyoğlu, Istanbul",
    roaster: "Nar Kahve",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["outdoor-seating", "minimalist"],
    instagram_handle: "narkahve",
    editorial_blurb: "Galata roastery that honours Turkish coffee tradition while running one of the city's best specialty programmes — the only bar in Istanbul where both orders are equally correct.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2024-09-05", verification_source: "community",
  },
];
