import type { Cafe } from '@/types';

export const OCEANIA_RAW_CAFES: (Omit<Cafe, 'id' | 'created_at' | 'third_wave_score' | 'overall_rating' | 'review_count' | 'permanently_closed'> & { permanently_closed?: boolean })[] = [

  // ── MELBOURNE (39) ────────────────────────────────────────────────────────────
  {
    name: "St Ali",
    slug: "st-ali-melbourne",
    lat: -37.8312, lng: 144.9604,
    google_place_id: "ChIJJ5bS6P9n1moRx76U3LjtN1A",
    city: "Melbourne", country: "Australia",
    address: "12-18 Yarra Place, South Melbourne VIC 3205",
    roaster: "St Ali",
    roaster_family: true,
    brew_methods: ["espresso", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "stalicoffee",
    website: "https://stali.com.au/",
    editorial_blurb: "The roastery that helped define Melbourne's coffee identity — still the best introduction to why this city takes coffee so seriously.",
    featured_in: ["sprudge", "broadsheet", "timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Patricia Coffee Brewers",
    slug: "patricia-coffee-brewers",
    lat: -37.8147, lng: 144.9582,
    google_place_id: "ChIJn1FUnktd1moRgZCDC6aPCcw",
    city: "Melbourne", country: "Australia",
    address: "493-495 Little Bourke St, Melbourne VIC 3000",
    roaster: "Patricia Coffee Roasters",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["standing-bar", "no-laptop"],
    instagram_handle: "patriciacoffeebrewers",
    website: "https://patriciacoffee.com.au/",
    editorial_blurb: "Standing room only, zero compromise — Patricia runs the tightest espresso programme in the CBD and everyone knows it.",
    featured_in: ["sprudge", "timeout", "broadsheet"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Market Lane Coffee",
    slug: "market-lane-coffee",
    lat: -37.8458, lng: 144.9933,
    google_place_id: "ChIJlZ5XDiZo1moRV7DQNGNXi2I",
    city: "Melbourne", country: "Australia",
    address: "Prahran Market, Shop 13/163 Commercial Rd, South Yarra VIC 3141",
    roaster: "Market Lane",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["outdoor-seating"],
    instagram_handle: "marketlanecoffee",
    website: "https://marketlane.com.au/",
    editorial_blurb: "Market-stall origins, world-class roasting — their seasonal single-origins are worth building a Melbourne morning around.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Proud Mary",
    slug: "proud-mary-melbourne",
    lat: -37.8023, lng: 144.9852,
    google_place_id: "ChIJQZ-aOeBC1moRuuo3eAh3hGE",
    city: "Melbourne", country: "Australia",
    address: "172 Oxford St, Collingwood VIC 3066",
    roaster: "Proud Mary",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["outdoor-seating"],
    instagram_handle: "proudmarycoffee",
    website: "https://www.proudmarycoffee.com.au/",
    editorial_blurb: "Collingwood roastery-café ranked among the World's 100 Best Coffee Shops — still one of Melbourne's most acclaimed coffee addresses.",
    featured_in: ["sprudge", "worlds_100_best", "timeout", "broadsheet", "barista_magazine"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Seven Seeds",
    slug: "seven-seeds-melbourne",
    lat: -37.8030, lng: 144.9590,
    google_place_id: "ChIJvdx3kjJd1moRHnjYhByshFo",
    city: "Melbourne", country: "Australia",
    address: "114 Berkeley St, Carlton VIC 3053",
    roaster: "Seven Seeds",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "sevenseedscoffee",
    website: "https://sevenseeds.com.au/",
    editorial_blurb: "Carlton roastery-café roasting since 2007 and ranked among the World's 100 Best Coffee Shops in 2025 — still central to how Melbourne drinks coffee.",
    featured_in: ["sprudge", "worlds_100_best", "broadsheet", "timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Dukes Coffee Roasters",
    slug: "dukes-coffee-melbourne",
    lat: -37.8168, lng: 144.9662,
    google_place_id: "ChIJyaNNI7RC1moRQcMRU8Ucz8o",
    city: "Melbourne", country: "Australia",
    address: "247 Flinders Lane, Melbourne VIC 3000",
    roaster: "Dukes Coffee Roasters",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "dukescoffeeroasters",
    website: "https://www.dukescoffee.com.au/",
    editorial_blurb: "Flinders Lane basement bar that turns the CBD lunch rush into an exercise in precision — the espresso programme here runs at a different pace to everywhere else.",
    featured_in: ["sprudge", "timeout", "broadsheet", "barista_magazine"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Axil Coffee Roasters",
    slug: "axil-coffee-roasters-melbourne",
    lat: -37.8226, lng: 145.0343,
    google_place_id: "ChIJ2-ShXzFC1moRFSFI9lFKM7c",
    city: "Melbourne", country: "Australia",
    address: "322 Burwood Rd, Hawthorn VIC 3122",
    roaster: "Axil Coffee Roasters",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "axilcoffeeroasters",
    website: "https://axilcoffee.com.au/",
    editorial_blurb: "Hawthorn roastery-café with genuine barista-competition pedigree — still a benchmark address for direct-trade coffee in Melbourne's eastern suburbs.",
    featured_in: ["broadsheet"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Brother Baba Budan",
    slug: "brother-baba-budan-melbourne",
    lat: -37.8135, lng: 144.9621,
    google_place_id: "ChIJ6VLiOLVC1moRUX_Qgb0CEyU",
    city: "Melbourne", country: "Australia",
    address: "359 Little Bourke St, Melbourne VIC 3000",
    roaster: "Seven Seeds",
    brew_methods: ["espresso"],
    vibe_tags: ["standing-bar", "no-laptop", "minimalist"],
    instagram_handle: "brotherbababudan",
    website: "https://sevenseeds.com.au/pages/brother-baba-budan",
    editorial_blurb: "Seven Seeds' CBD sibling — chairs suspended from the ceiling, zero pretension, and the same exacting espresso in a space the size of a hallway.",
    featured_in: ["sprudge", "timeout", "broadsheet"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Wide Open Road",
    slug: "wide-open-road-brunswick",
    lat: -37.7763, lng: 144.9612,
    google_place_id: "ChIJt_EqLTVD1moRpkK9XYJ9y4A",
    city: "Melbourne", country: "Australia",
    address: "274 Blyth St, Brunswick VIC 3056",
    roaster: "Wide Open Road",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "wideopenroadcoffee",
    editorial_blurb: "Brunswick roastery-café included in Broadsheet's Melbourne best-cafes guide — a long-standing specialty address north of the city.",
    featured_in: ["broadsheet"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Higher Ground",
    slug: "higher-ground-melbourne",
    lat: -37.8157, lng: 144.9530,
    google_place_id: "ChIJ-R8fAE9d1moR3yFuI2x1z00",
    city: "Melbourne", country: "Australia",
    address: "650 Little Bourke St, Melbourne VIC 3000",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "highergroundmelb",
    website: "https://highergroundmelbourne.com.au/",
    editorial_blurb: "Converted power station with soaring ceilings and a coffee programme that matches the architecture — Melbourne's most spectacular all-day café.",
    featured_in: ["timeout", "infatuation"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Top Paddock",
    slug: "top-paddock-richmond",
    lat: -37.8328, lng: 144.9964,
    google_place_id: "ChIJ1fFuWYVC1moRoaV3KOybEQQ",
    city: "Melbourne", country: "Australia",
    address: "658 Church St, Richmond VIC 3121",
    roaster: "Market Lane",
    brew_methods: ["espresso"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "toppaddockmelbourne",
    website: "https://thetoppaddock.com/",
    editorial_blurb: "Richmond's neighbourhood café elevated by Market Lane's roasting — the weekend brunch crowd and the flat white devotees share the same excellent cup.",
    featured_in: ["sprudge", "timeout", "infatuation"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Allpress Espresso Melbourne",
    slug: "allpress-espresso-melbourne",
    lat: -37.8066, lng: 144.9894,
    google_place_id: "ChIJ97GV_uNC1moRTHYYvdZInGk",
    city: "Melbourne", country: "Australia",
    address: "80 Rupert St, Collingwood VIC 3066, Australia",
    roaster: "Allpress Espresso",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "allpressespresso",
    website: "https://allpressespresso.com/",
    editorial_blurb: "Trans-Tasman roastery institution's Collingwood headquarters — the open roastery and the espresso bar run in parallel, and the breakfast crowd arrives before the doors open.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Padre Coffee",
    slug: "padre-coffee-brunswick",
    lat: -37.7641, lng: 144.9733,
    google_place_id: "ChIJYeSX8llD1moReVgb27XXvqY",
    city: "Melbourne", country: "Australia",
    address: "438-440 Lygon St, Brunswick East VIC 3057",
    roaster: "Padre Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly"],
    instagram_handle: "padrecoffee",
    website: "https://www.padrecoffee.com.au/",
    editorial_blurb: "Brunswick East roastery-café on Lygon Street — Padre's own-roasted, direct-trade coffee anchors one of Melbourne's most consistent addresses.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Monk Bodhi Dharma",
    slug: "monk-bodhi-dharma-melbourne",
    lat: -37.8680, lng: 144.9909,
    google_place_id: "ChIJDwqU2kRo1moRZGwNnv7-xPs",
    city: "Melbourne", country: "Australia",
    address: "202 Carlisle St, Balaclava VIC 3183",
    roaster: "Disciple Roasters",
    brew_methods: ["espresso"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "monkbodhi",
    website: "https://www.monkbodhidharmacafe.com.au/",
    editorial_blurb: "Balaclava's plant-based specialty cafe — an all-vegetarian, vegan-friendly menu paired with multi-origin coffee from Disciple Roasters.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Hardware Société",
    slug: "hardware-societe-melbourne",
    lat: -37.8121, lng: 144.9604,
    google_place_id: "ChIJ22hhMyVd1moRhP7ARjsyWc8",
    city: "Melbourne", country: "Australia",
    address: "123 Hardware St, Melbourne VIC 3000, Australia",
    roaster: "Market Lane",
    brew_methods: ["espresso"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "hardwaresociete",
    website: "https://www.hardwaresociete.com/",
    editorial_blurb: "Hardware Street brunch institution with French-leaning food and all-day coffee — a laneway favourite named in Broadsheet's Melbourne CBD guide.",
    featured_in: ["broadsheet"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Aunty Peg's",
    slug: "aunty-pegs-collingwood",
    lat: -37.8028, lng: 144.9870,
    google_place_id: "ChIJOc2VxeFC1moR7HgPdWw5KME",
    city: "Melbourne", country: "Australia",
    address: "200 Wellington St, Collingwood VIC 3066",
    roaster: "Proud Mary",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "auntypegsbar",
    website: "https://www.proudmarycoffee.com.au/pages/aunty-pegs",
    editorial_blurb: "Proud Mary's upstairs cupping and filter bar — a quieter, more focused counterpoint to the bustling café below, where the pour-over menu goes deeper.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Everyday Coffee",
    slug: "everyday-coffee-fitzroy",
    lat: -37.7982, lng: 144.9859,
    google_place_id: "ChIJhb8hqx9D1moREUdvGRuSNic",
    city: "Melbourne", country: "Australia",
    address: "36-38 Sackville St, Collingwood VIC 3066",
    roaster: "Everyday Coffee",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "everydaycoffee",
    website: "https://everyday-coffee.com/",
    editorial_blurb: "Collingwood in-house roaster that moved from Johnston Street in 2018 — reliable, honest specialty coffee, seven days a week.",
    featured_in: ["barista_magazine", "broadsheet"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Code Black Coffee",
    slug: "code-black-coffee-brunswick",
    lat: -37.7746, lng: 144.9625,
    google_place_id: "ChIJT3I-okpD1moRBNshH62Qt7Q",
    city: "Melbourne", country: "Australia",
    address: "15-17 Weston St, Brunswick VIC 3056",
    roaster: "Code Black Coffee",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["laptop-friendly"],
    instagram_handle: "codeblackcoffee",
    website: "https://www.codeblackcoffee.com.au/",
    editorial_blurb: "Brunswick's HQ roastery-cafe, roasting its own beans on site — Code Black's serious sourcing has made it one of the suburb's specialty landmarks.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Auction Rooms",
    slug: "auction-rooms-north-melbourne",
    lat: -37.8025, lng: 144.9495,
    google_place_id: "ChIJAYc1Djpd1moRmGwu2RuDrsk",
    city: "Melbourne", country: "Australia",
    address: "103-107 Errol St, North Melbourne VIC 3051",
    roaster: "St Ali",
    brew_methods: ["espresso", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "auctionroomsmelbourne",
    website: "https://auctionroomscafe.com.au/",
    editorial_blurb: "North Melbourne's destination cafe in a former auction house — a longtime Sprudge and Time Out pick with espresso, batch and cold brew.",
    featured_in: ["sprudge", "timeout", "barista_magazine"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Stagger Lee's",
    slug: "stagger-lees-fitzroy",
    lat: -37.7990, lng: 144.9785,
    google_place_id: "ChIJl0FJoSBD1moRFMiAZXRKHsc",
    city: "Melbourne", country: "Australia",
    address: "276 Brunswick St, Fitzroy VIC 3065",
    roaster: "Seven Seeds",
    brew_methods: ["espresso", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "stagga_lees",
    website: "https://staggerlees.com.au/",
    editorial_blurb: "Brunswick Street neighbourhood cafe with no pretension — an easy, unfussy spot for espresso and cold brew in the heart of Fitzroy.",
    featured_in: ["broadsheet"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },

  {
    name: "Industry Beans Fitzroy",
    slug: "industry-beans-fitzroy",
    lat: -37.7948, lng: 144.9781,
    google_place_id: "ChIJ_7ffMiFD1moR5NCnlSFhECk",
    city: "Melbourne", country: "Australia",
    address: "70-76 Westgarth St, Fitzroy VIC 3065, Australia",
    roaster: "Industry Beans",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "industrybeans",
    website: "https://industrybeans.com/",
    editorial_blurb: "Fitzroy's original warehouse roastery on Westgarth Street — Industry Beans roasts its own coffee for a seasonal, ever-changing menu.",
    featured_in: ["timeout", "broadsheet"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Industry Beans Lt Collins",
    slug: "industry-beans-cbd",
    lat: -37.8155, lng: 144.9633,
    google_place_id: "ChIJgRXO-rRC1moRwcB73rcSyIE",
    city: "Melbourne", country: "Australia",
    address: "345 Little Collins St, Melbourne VIC 3000, Australia",
    roaster: "Industry Beans",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["minimalist", "standing-bar"],
    instagram_handle: "industrybeans",
    website: "https://industrybeans.com/",
    editorial_blurb: "Industry Beans' Little Collins Street standing bar — the same in-house-roasted, seasonal coffee programme in a compact CBD format.",
    featured_in: ["timeout", "broadsheet"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Market Lane Collins Street",
    slug: "market-lane-collins-st",
    lat: -37.8133, lng: 144.9734,
    google_place_id: "ChIJYQxRN8ZC1moRZPYsVv8YrEQ",
    city: "Melbourne", country: "Australia",
    address: "8 Collins Street, Melbourne VIC 3000",
    roaster: "Market Lane",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "marketlanecoffee",
    website: "https://marketlane.com.au/",
    editorial_blurb: "Market Lane's Collins Street cafe brings the roastery's seasonal sourcing to the CBD lunch crowd — espresso and filter from one of Melbourne's best-known coffee companies.",
    featured_in: ["broadsheet"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Commonfolk Coffee",
    slug: "commonfolk-coffee-mornington",
    lat: -38.2349, lng: 145.0576,
    google_place_id: "ChIJWQmrSqje1WoRAHdFfPHU3gw",
    city: "Melbourne", country: "Australia",
    address: "14 Progress St, Mornington VIC 3931, Australia",
    roaster: "Commonfolk Coffee",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["outdoor-seating", "dog-friendly"],
    instagram_handle: "commonfolkcoffee",
    website: "https://www.commonfolkcoffee.com.au/",
    editorial_blurb: "Mornington Peninsula roastery-cafe worth the drive from the city — Commonfolk has roasted and served its own coffee here since 2013.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Axil Coffee Roasters CBD",
    slug: "axil-coffee-roasters-cbd",
    lat: -37.8169, lng: 144.9687,
    google_place_id: "ChIJgwgMg99D1moR4u3FR8Nq1x8",
    city: "Melbourne", country: "Australia",
    address: "180 Flinders St, Melbourne VIC 3000, Australia",
    roaster: "Axil Coffee Roasters",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["minimalist", "standing-bar"],
    instagram_handle: "axilcoffeeroasters",
    website: "https://axilcoffee.com.au/",
    editorial_blurb: "Axil's Flinders Lane cafe extends the roastery founded by two champion baristas — full-service coffee and kitchen for the CBD lunch crowd.",
    featured_in: ["broadsheet", "timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "ONA Coffee Brunswick",
    slug: "ona-coffee-melbourne",
    lat: -37.7649, lng: 144.9617,
    google_place_id: "ChIJ0Rw8XyND1moRlQ3nyEFLcqk",
    city: "Melbourne", country: "Australia",
    address: "22 Ovens St, Brunswick VIC 3056, Australia",
    roaster: "ONA Coffee",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "onacoffee",
    website: "https://onacoffee.com.au/",
    editorial_blurb: "ONA's Brunswick cafe is the Melbourne outpost of one of Australia's most competition-decorated coffee roasters — seasonal filter and espresso alike.",
    featured_in: ["broadsheet", "timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Traveller Coffee",
    slug: "traveller-coffee-melbourne",
    lat: -37.8115, lng: 144.9712,
    google_place_id: "ChIJcRZauchC1moRSvqNA1_Mgwk",
    city: "Melbourne", country: "Australia",
    address: "2/14 Crossley St, Melbourne VIC 3000",
    roaster: "Seven Seeds",
    brew_methods: ["espresso"],
    vibe_tags: ["standing-bar", "no-laptop", "minimalist"],
    instagram_handle: "travellercoffee",
    website: "https://sevenseeds.com.au/pages/traveller",
    editorial_blurb: "Seven Seeds' tucked-away Crossley Street laneway outpost — a compact bench-seat bar serving quick, quality espresso to CBD commuters.",
    featured_in: ["broadsheet"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Kettle Black",
    slug: "kettle-black-south-melbourne",
    lat: -37.8341, lng: 144.9713,
    google_place_id: "ChIJrVqwpwJo1moRJ5oA8Rm_SBY",
    city: "Melbourne", country: "Australia",
    address: "50 Albert Rd, South Melbourne VIC 3205",
    roaster: "Market Lane",
    brew_methods: ["espresso"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "thekettleblack",
    website: "https://thekettleblack.com.au/",
    editorial_blurb: "South Melbourne brunch icon on Albert Road — the ricotta hotcakes built the reputation, and the terrace remains one of the city's most popular breakfast spots.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Lune Croissanterie",
    slug: "lune-croissanterie-fitzroy",
    lat: -37.7960, lng: 144.9799,
    google_place_id: "ChIJ1zV4U_Zo1moR9MXOJ461Jd0",
    city: "Melbourne", country: "Australia",
    address: "119 Rose St, Fitzroy VIC 3065",
    roaster: "Small Batch Roasting Company",
    brew_methods: ["espresso"],
    vibe_tags: ["no-laptop", "minimalist"],
    instagram_handle: "lunecroissanterie",
    website: "https://lunecroissanterie.com/",
    editorial_blurb: "Kate Reid's Fitzroy croissanterie pairs its pastries with a serious coffee program — the morning queue is real, and the NYT once praised its croissants as world-class.",
    featured_in: ["sprudge", "ny_times", "broadsheet"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Market Lane Carlton",
    slug: "market-lane-carlton",
    lat: -37.7985, lng: 144.9685,
    google_place_id: "ChIJm6Hi8dZC1moRiZwOkU2VUgQ",
    city: "Melbourne", country: "Australia",
    address: "176 Faraday St, Carlton VIC 3053, Australia",
    roaster: "Market Lane",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "marketlanecoffee",
    website: "https://marketlane.com.au/",
    editorial_blurb: "Market Lane's Carlton café on Faraday Street near Argyle Square — this specialty roaster brews its own coffee at cafés across Melbourne.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },

  // ── SYDNEY (29) ───────────────────────────────────────────────────────────────
  {
    name: "Single O",
    slug: "single-o-surry-hills",
    lat: -33.8811, lng: 151.2096,
    google_place_id: "ChIJNUOUhSKuEmsRj2F2Arcx_OQ",
    city: "Sydney", country: "Australia",
    address: "60-64 Reservoir St, Surry Hills NSW 2010",
    roaster: "Single O",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "singleocoffee",
    website: "https://www.singleo.com.au/",
    editorial_blurb: "The Surry Hills roastery that defined Sydney specialty — their taps of batch brew and cold brew changed how the city drinks coffee.",
    featured_in: ["sprudge", "timeout", "broadsheet", "monocle", "worlds_100_best"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Sample Coffee",
    slug: "sample-coffee-sydney",
    lat: -33.8867, lng: 151.2091,
    google_place_id: "ChIJHUVSMyCuEmsRcOVnCCEwodc",
    city: "Sydney", country: "Australia",
    address: "118 Devonshire St, Surry Hills NSW 2010",
    roaster: "Sample Coffee",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "samplecoffeesydney",
    website: "https://samplecoffee.com.au/",
    editorial_blurb: "Surry Hills espresso bar where owner Reuben Mardan roasts every bean himself on vintage German roasters — the Pacemaker blend is the reason for the queue.",
    featured_in: ["timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Reuben Hills",
    slug: "reuben-hills-sydney",
    lat: -33.8829, lng: 151.2110,
    google_place_id: "ChIJm_F_mhiuEmsR3Ah4Quu1Odg",
    city: "Sydney", country: "Australia",
    address: "61 Albion St, Surry Hills NSW 2010",
    roaster: "Reuben Hills",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["outdoor-seating"],
    instagram_handle: "reubenhills",
    website: "https://reubenhills.com.au/",
    editorial_blurb: "South American bean focus and a roastery café that doubles as a proper brunch destination — the espresso programme is the real reason to visit.",
    featured_in: ["sprudge", "timeout", "broadsheet"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Mecca Coffee - Alexandria",
    slug: "mecca-coffee-surry-hills",
    lat: -33.9066, lng: 151.2000,
    google_place_id: "ChIJ92I17cexEmsRQMdkCcGReCI",
    city: "Sydney", country: "Australia",
    address: "26 Bourke Rd, Alexandria NSW 2015, Australia",
    roaster: "Mecca Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly"],
    instagram_handle: "meccacoffee",
    website: "https://www.mecca.coffee/",
    editorial_blurb: "Mecca's Alexandria roastery cafe pairs a dialed-in pour-over bar with ever-changing espresso — beans roasted on site make it Sydney's benchmark specialty address.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Artificer Coffee",
    slug: "artificer-coffee-sydney",
    lat: -33.8871, lng: 151.2151,
    google_place_id: "ChIJs4Lblh6uEmsRlGsK1tv6qY8",
    city: "Sydney", country: "Australia",
    address: "547 Bourke St, Surry Hills NSW 2010",
    roaster: "Artificer Coffee",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["standing-bar", "minimalist", "no-laptop"],
    instagram_handle: "artificercoffee",
    website: "https://artificercoffee.com/",
    editorial_blurb: "Surry Hills espresso bar that imports and roasts its own beans in-house — no food, no distractions, just extraction precise enough to draw off-duty baristas.",
    featured_in: ["sprudge", "infatuation"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Paramount Coffee Project",
    slug: "paramount-coffee-project-sydney",
    lat: -33.8793, lng: 151.2110,
    google_place_id: "ChIJHRwF-BeuEmsRRwfUQVNfsdU",
    city: "Sydney", country: "Australia",
    address: "80 Commonwealth St, Surry Hills NSW 2010",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "pcpsydney",
    website: "https://paramountcoffeeproject.com.au/",
    editorial_blurb: "Surry Hills cafe in the Paramount Building — Japanese and Korean flavours meet guest-roaster coffee brewed at its dedicated filter bar.",
    featured_in: ["sprudge", "timeout", "infatuation", "broadsheet"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Brewtown Newtown",
    slug: "brewtown-newtown-sydney",
    lat: -33.8939, lng: 151.1824,
    google_place_id: "ChIJExZmFTKwEmsReP_uIMPdOOI",
    city: "Sydney", country: "Australia",
    address: "6-8 O'Connell St, Newtown NSW 2042",
    roaster: "Single O",
    brew_methods: ["espresso"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "brewtownnewtown",
    website: "https://brewtownsydney.com.au/",
    editorial_blurb: "Newtown's specialty anchor in a converted warehouse — Single O beans, an open roastery floor, and the easy pace of Sydney's most interesting neighbourhood.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Toby's Estate",
    slug: "tobys-estate-sydney",
    lat: -33.8859, lng: 151.1944,
    google_place_id: "ChIJR-S-I9axEmsRGjjcmNfvx6k",
    city: "Sydney", country: "Australia",
    address: "32-36 City Rd, Chippendale NSW 2008, Australia",
    roaster: "Toby's Estate",
    roaster_family: true,
    brew_methods: ["espresso", "cold-brew"],
    vibe_tags: ["laptop-friendly"],
    instagram_handle: "tobysestate",
    website: "https://tobysestate.com.au/",
    editorial_blurb: "Chippendale flagship warehouse cafe that topped the inaugural World's 100 Best Coffee Shops Gala in 2025 — the roastery upstairs supplies cafes worldwide.",
    featured_in: ["timeout", "worlds_100_best"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Pablo & Rusty's",
    slug: "pablo-rustys-sydney",
    lat: -33.8724, lng: 151.2091,
    google_place_id: "ChIJlQzbPT6uEmsRdMutKU9hWds",
    city: "Sydney", country: "Australia",
    address: "161 Castlereagh St, Sydney NSW 2000",
    roaster: "Pablo & Rusty's",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["laptop-friendly", "standing-bar"],
    instagram_handle: "pabloandrustyss",
    website: "https://pabloandrustys.com.au/",
    editorial_blurb: "CBD roastery café that brought Surry Hills standards to the financial district — the office-hour espresso programme holds up to anything in the city.",
    featured_in: ["timeout", "broadsheet"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Gumption by Coffee Alchemy",
    slug: "gumption-coffee-sydney",
    lat: -33.8694, lng: 151.2075,
    google_place_id: "ChIJDycznj-uEmsRCrYS0ALQByk",
    city: "Sydney", country: "Australia",
    address: "Shop 11, The Strand Arcade, 412-414 George St, Sydney NSW 2000",
    roaster: "Coffee Alchemy",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["standing-bar", "no-laptop", "minimalist"],
    instagram_handle: "gumptioncoffee",
    website: "https://www.gumptioncoffee.com.au/",
    editorial_blurb: "Strand Arcade heritage shopfront turned specialty espresso bar — Sydney's most theatrical coffee address, where the marble counter and the precision are equally impressive.",
    featured_in: ["sprudge", "timeout", "broadsheet"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Coffee Alchemy",
    slug: "coffee-alchemy-marrickville",
    lat: -33.9110, lng: 151.1645,
    google_place_id: "ChIJ_YbDfEGwEmsRANEuZjL_uSI",
    city: "Sydney", country: "Australia",
    address: "2/87 Sydenham Rd, Marrickville NSW 2204, Australia",
    roaster: "Coffee Alchemy",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["laptop-friendly"],
    instagram_handle: "coffeealchemy",
    website: "https://www.coffeealchemy.com.au/",
    editorial_blurb: "Marrickville roastery cafe where owner Hazel de Los Reyes roasts everything on site — order it as espresso or one of the house sparkling filter coffees.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Edition Coffee Roasters",
    slug: "edition-coffee-roasters-sydney",
    lat: -33.8785, lng: 151.2012,
    google_place_id: "ChIJJeRjRtmvEmsRvku-OhXBVAI",
    city: "Sydney", country: "Australia",
    address: "60 Darling Dr, Darling Square, Haymarket NSW 2000",
    roaster: "Edition Coffee Roasters",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "aeropress", "cold-brew"],
    vibe_tags: ["minimalist"],
    instagram_handle: "edition_coffee",
    website: "https://editionroasters.com/",
    editorial_blurb: "Darling Square micro-roastery built on the premise that small batches roasted close to service is the only way to work — every cup proves the point.",
    featured_in: ["sprudge", "timeout", "broadsheet"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Will & Co",
    slug: "will-and-co-sydney",
    lat: -33.8798, lng: 151.1973,
    google_place_id: "ChIJQw3XQS-uEmsRWSAo6K-Jx28",
    city: "Sydney", country: "Australia",
    address: "103 Jones St, Ultimo NSW 2007",
    roaster: "Will & Co",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "willandco",
    website: "https://www.willandco.com.au/",
    editorial_blurb: "Bondi-born specialty coffee roaster with an espresso bar near UTS in Ultimo — Will & Co roasts every bean it serves.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "The Grounds of Alexandria",
    slug: "the-grounds-of-alexandria-sydney",
    lat: -33.9107, lng: 151.1941,
    google_place_id: "ChIJFbIJpLaxEmsRSrzMZif-DK8",
    city: "Sydney", country: "Australia",
    address: "7a/2 Huntley St, Alexandria NSW 2015, Australia",
    roaster: "The Grounds Roasters",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["outdoor-seating"],
    instagram_handle: "thegroundsofale",
    website: "https://thegrounds.com.au/",
    editorial_blurb: "Alexandria's café precinct calls itself one of the world's most Instagrammable spots — its coffee is roasted by the same company's Eveleigh Coffee Factory, not on site here.",
    featured_in: ["timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },

  {
    name: "Skittle Lane",
    slug: "skittle-lane-sydney",
    lat: -33.8685, lng: 151.2048,
    google_place_id: "ChIJpz8eTD-uEmsRIQrn3Y2wl6Q",
    city: "Sydney", country: "Australia",
    address: "40 King St, Sydney NSW 2000",
    roaster: "Skittle Lane",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["standing-bar", "minimalist", "no-laptop"],
    instagram_handle: "skittlelane",
    website: "https://skittlelane.com/",
    editorial_blurb: "CBD bar hidden in plain sight — the morning single-origin espresso here is the best-kept secret in Sydney's King Street precinct.",
    featured_in: ["timeout", "broadsheet"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Ona Coffee Sydney",
    slug: "ona-coffee-sydney",
    lat: -33.9073, lng: 151.1673,
    google_place_id: "ChIJ9--VtvaxEmsR7dk5e90VOLI",
    city: "Sydney", country: "Australia",
    address: "58/60 Smith St, Marrickville NSW 2204",
    roaster: "ONA Coffee",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["minimalist"],
    instagram_handle: "onacoffee",
    website: "https://www.onacoffeesydney.com/",
    editorial_blurb: "Australia's most competition-decorated roastery opens in Surry Hills — the seasonal lot programme and the World Barista Championship pedigree raise Sydney's ceiling considerably.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Cali Press Barrack Place",
    slug: "cali-press-newtown",
    lat: -33.8676, lng: 151.2048,
    google_place_id: "ChIJq4OpghmvEmsR1fD7JNpWfwk",
    city: "Sydney", country: "Australia",
    address: "Shop 8/151 Clarence St, Sydney NSW 2000, Australia",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "calipresscafes",
    website: "https://www.calipress.com.au/",
    editorial_blurb: "This CBD outpost of the Cali Press health-café chain pours single-origin cold brew alongside its smoothie-bowl menu, inside Barrack Place's Clarence Street arcade.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Axil Coffee Sydney",
    slug: "axil-coffee-sydney",
    lat: -33.8850, lng: 151.2139,
    google_place_id: "ChIJZT4fSgCvEmsRR2hQ499sqJ0",
    city: "Sydney", country: "Australia",
    address: "365 Crown St, Surry Hills NSW 2010, Australia",
    roaster: "Axil Coffee Roasters",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["standing-bar", "minimalist"],
    instagram_handle: "axilcoffeeroasters",
    website: "https://axilcoffee.com.au/",
    editorial_blurb: "Melbourne-founded Axil Coffee Roasters runs its only Sydney café from a Surry Hills standing bar — same self-roasted beans, same culture, on Crown Street.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Five Senses Espresso",
    slug: "five-senses-coffee-sydney",
    lat: -33.8967, lng: 151.1530,
    google_place_id: "ChIJx9uP5xewEmsRNT69oLXyORA",
    city: "Sydney", country: "Australia",
    address: "Shop 1/114 New Canterbury Rd, Petersham NSW 2049, Australia",
    roaster: "Five Senses Coffee",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["laptop-friendly"],
    instagram_handle: "fivesensescoffee",
    website: "https://www.fivesenses.com.au/",
    editorial_blurb: "Perth-founded Five Senses roasts its own coffee at this Petersham café, attached to the brand's barista academy — not the Surry Hills address once listed.",
    featured_in: ["timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Black Star Pastry",
    slug: "black-star-pastry-newtown",
    lat: -33.8972, lng: 151.1790,
    google_place_id: "ChIJgwF71jawEmsRWUOXoYpNxjM",
    city: "Sydney", country: "Australia",
    address: "1/325 King St, Newtown NSW 2042, Australia",
    roaster: "Single O",
    brew_methods: ["espresso"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "blackstarpastry",
    website: "https://www.blackstarpastry.com.au/",
    editorial_blurb: "The watermelon cake made it famous — this King Street bakery-café also pours espresso, though the coffee program itself isn't independently documented.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Room 10",
    slug: "room-10-potts-point",
    lat: -33.8724, lng: 151.2245,
    google_place_id: "ChIJVdZk1HKuEmsRn_UpO_K5Lag",
    city: "Sydney", country: "Australia",
    address: "10 Llankelly Place, Potts Point NSW 2011",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "cold-brew"],
    vibe_tags: ["no-laptop", "minimalist"],
    instagram_handle: "room10espresso",
    website: "https://www.roomtenpottspoint.com.au/",
    editorial_blurb: "Potts Point's minimalist Llankelly Place espresso bar and cold-brew stop — a long-running fixture of the laneway coffee scene, though its exact opening date isn't confirmed.",
    featured_in: ["timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Campos Coffee Newtown",
    slug: "campos-coffee-newtown",
    lat: -33.8930, lng: 151.1832,
    google_place_id: "ChIJ9QILdzKwEmsRIjQVzqIASrc",
    city: "Sydney", country: "Australia",
    address: "193 Missenden Rd, Newtown NSW 2042",
    roaster: "Campos Coffee",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "camposcoffee",
    website: "https://www.camposcoffee.com/",
    editorial_blurb: "The Missenden Road café is Campos Coffee's original Newtown roastery — one of Australia's best-known specialty coffee names, still pouring espresso from its home base.",
    featured_in: ["timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },

  // ── AUCKLAND (11) ──────────────────────────────────────────────────────────────
  {
    name: "Kokako Roastery Roller Door",
    slug: "kokako-auckland",
    lat: -36.8703, lng: 174.7512,
    google_place_id: "ChIJvbL4_qNHDW0RBAFCn-P9xSE",
    city: "Auckland", country: "New Zealand",
    address: "9 Charles Street, Mount Eden, Auckland 1024",
    roaster: "Kokako",
    roaster_family: true,
    brew_methods: [],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "kokako_organic",
    website: "https://www.kokako.co.nz/",
    editorial_blurb: "Kokako moved its retail roastery to Mt Eden — click-and-collect beans only now; the old Grey Lynn café that inspired this entry has closed.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Eighthirty Coffee Roasters",
    slug: "eighthirty-auckland",
    lat: -36.8703, lng: 174.7510,
    google_place_id: "ChIJafc9vv1HDW0RzfVoysWXu0k",
    city: "Auckland", country: "New Zealand",
    address: "9 Charles Street, Mount Eden, Auckland 1024, New Zealand",
    roaster: "Eighthirty Coffee Roasters",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "eighthirty",
    website: "https://www.eighthirty.com/",
    editorial_blurb: "Eighthirty began as two people roasting out of a small K Road shop in 2009 — the Wyndham St café now pours that same house espresso.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Allpress Espresso Auckland",
    slug: "allpress-espresso-auckland",
    lat: -36.8487, lng: 174.7556,
    google_place_id: "ChIJv0PWevJHDW0RtXr7A1vPYC4",
    city: "Auckland", country: "New Zealand",
    address: "8 Drake St, Freemans Bay, Auckland 1011",
    roaster: "Allpress Espresso",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "allpressespresso",
    website: "https://allpressespresso.com/",
    editorial_blurb: "The origin story — Allpress started in this building before taking their espresso gospel to Sydney, Melbourne, Tokyo, and London, and the Auckland roastery still earns the pilgrimage.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Atomic Coffee Roasters",
    slug: "atomic-coffee-auckland",
    lat: -36.8719, lng: 174.7461,
    google_place_id: "ChIJTTRWv7BHDW0RUjXyu15qbT0",
    city: "Auckland", country: "New Zealand",
    address: "420 New North Road, Kingsland, Auckland 1021, New Zealand",
    roaster: "Atomic Coffee Roasters",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["laptop-friendly"],
    instagram_handle: "atomiccoffeeroasters",
    website: "https://www.atomiccoffee.co.nz/",
    editorial_blurb: "Kingsland roastery Atomic Coffee has hand-roasted small-batch coffee for cafés and homes across Aotearoa since 1992 — one of Auckland's longest-running.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },

  {
    name: "Mojo Albert",
    slug: "mojo-coffee-queen-street",
    lat: -36.8466, lng: 174.7646,
    google_place_id: "ChIJG0nyq4NHDW0RdwaDg19LK0Q",
    city: "Auckland", country: "New Zealand",
    address: "50 Albert Street, Auckland CBD, Auckland 1010, New Zealand",
    roaster: "Mojo Coffee",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "mojocoffee",
    website: "https://mojo.coffee/",
    editorial_blurb: "Mojo Albert is this Wellington-founded roaster's (est. 2003) Auckland café — near Queen St, not on it, and roasting its own beans.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Ima Cuisine",
    slug: "ima-boutique-auckland",
    lat: -36.8465, lng: 174.7688,
    google_place_id: "ChIJ64UPbPxHDW0RDj_fTPmFQlk",
    city: "Auckland", country: "New Zealand",
    address: "53 Fort St, Auckland CBD, Auckland 1010",
    roaster: "Kokako",
    brew_methods: ["espresso"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "imaboutique",
    website: "https://www.imacuisine.co.nz/",
    editorial_blurb: "Fort Street's Ima Cuisine pairs Middle Eastern brunch platters and mezze with espresso — the house roaster on the machine isn't confirmed.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Kokako CBD",
    slug: "kokako-cbd-auckland",
    lat: -36.8435, lng: 174.7660,
    google_place_id: "ChIJ2fK_D-dHDW0RRDyC3Hbnr60",
    city: "Auckland", country: "New Zealand",
    address: "Level 1, 7/21 Queen St, Commercial Bay, Auckland CBD, Auckland 1010",
    roaster: "Kokako",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "kokako_organic",
    website: "https://www.kokako.co.nz/",
    editorial_blurb: "Kokako's Commercial Bay café is now the brand's only real sit-down café in Auckland — organic, Fairtrade-certified coffee, brewed to order.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Eighthirty Ponsonby",
    slug: "eighthirty-ponsonby",
    lat: -36.8561, lng: 174.7461,
    google_place_id: "ChIJ5SZ-k5ZHDW0RCyOtsdNNmsw",
    city: "Auckland", country: "New Zealand",
    address: "4 Brown Street, Ponsonby, Auckland 1010, New Zealand",
    roaster: "Eighthirty Coffee Roasters",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "eighthirty",
    website: "https://www.eighthirty.com/",
    editorial_blurb: "Ponsonby Central hosts Eighthirty — the Auckland roaster that began as two people roasting out of a K Road shop in 2009.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },

  // ── WELLINGTON (12) ────────────────────────────────────────────────────────────
  {
    name: "Flight Coffee",
    slug: "flight-coffee-wellington",
    lat: -41.2933, lng: 174.7739,
    google_place_id: "ChIJ3xu-jnKvOG0RBvB9vm-8aNM",
    city: "Wellington", country: "New Zealand",
    address: "30 Garrett Street, Te Aro, Wellington 6011, New Zealand",
    roaster: "Flight Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "aeropress", "chemex"],
    vibe_tags: ["laptop-friendly"],
    instagram_handle: "flightcoffee",
    website: "https://flightcoffee.co.nz/",
    editorial_blurb: "Wellington's defining specialty roastery — Flight's direct-trade Kenyan and Ethiopian lots set the standard for what New Zealand expects from filter coffee.",
    featured_in: ["sprudge", "barista_magazine", "broadsheet"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "People's Coffee",
    slug: "peoples-coffee-wellington",
    lat: -41.2936, lng: 174.7746,
    google_place_id: "ChIJPyf9odCvOG0RJp9wNd62Nlw",
    city: "Wellington", country: "New Zealand",
    address: "13 Garrett Street, Te Aro, Wellington 6011, New Zealand",
    roaster: "People's Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "peoplescoffee",
    website: "https://www.peoplescoffee.co.nz/",
    editorial_blurb: "Organic, ethically-traded specialty roaster with an espresso bar on Garrett Street, Te Aro — not the Newtown address previously listed.",
    featured_in: ["broadsheet"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Caffe L'affare",
    slug: "caffe-laffare-wellington",
    lat: -41.2962, lng: 174.7804,
    google_place_id: "ChIJrST1sNuvOG0R3vzcciiyQWc",
    city: "Wellington", country: "New Zealand",
    address: "27 College St, Te Aro, Wellington 6011",
    roaster: "L'affare",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "caffelaffare",
    website: "https://www.laffare.co.nz/",
    editorial_blurb: "Wellington roastery established in 1990 — a pioneer of the city's café culture, sourcing beans directly for its College Street café for over three decades.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Customs Brew Bar",
    slug: "customs-brew-bar-wellington",
    lat: -41.2936, lng: 174.7762,
    google_place_id: "ChIJLXv2zdmvOG0R6kwX9B7jFsQ",
    city: "Wellington", country: "New Zealand",
    address: "39 Ghuznee St, Te Aro, Wellington 6011",
    roaster: "Coffee Supreme",
    brew_methods: ["espresso", "pour-over", "chemex"],
    vibe_tags: ["minimalist", "standing-bar"],
    instagram_handle: "customsbrewbar",
    editorial_blurb: "Ghuznee Street specialty bar serving Te Aro's creative crowd a proper alternative to mediocrity — the rotating single-origin pour-over is the reason people walk past the chains.",
    featured_in: ["sprudge", "broadsheet"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Coffee Supreme Wellington",
    slug: "coffee-supreme-wellington",
    lat: -41.2994, lng: 174.7741,
    google_place_id: "ChIJhSaVZN-vOG0R3AzA3-xML_Y",
    city: "Wellington", country: "New Zealand",
    address: "35 Hopper Street, Mount Cook, Wellington 6011, New Zealand",
    roaster: "Coffee Supreme",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "coffeesupreme",
    website: "https://coffeesupreme.com/",
    editorial_blurb: "The Wellington mothership of Australasia's most influential roastery — this is where Coffee Supreme's ethos was formed, and it still pours the most consistent flat white in the city.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Golding's Free Dive",
    slug: "goldings-free-dive-wellington",
    lat: -41.2928, lng: 174.7771,
    google_place_id: "ChIJw6DRYdevOG0R78qgsoWJQ1I",
    city: "Wellington", country: "New Zealand",
    address: "Te Aro, Wellington 6011, New Zealand",
    roaster: "Unconfirmed — no roaster named on the venue's own site or in any press found this session",
    brew_methods: ["espresso"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "goldingsfreedive",
    website: "https://www.goldingsfreedive.co.nz/",
    editorial_blurb: "Te Aro bar loved for its beer, wine and Neapolitan pizza on the terrace — coffee is a secondary, low-key offering here.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Midnight Espresso",
    slug: "midnight-espresso-wellington",
    lat: -41.2946, lng: 174.7749,
    google_place_id: "ChIJpUeBQ9ivOG0RfJfyJsdczAo",
    city: "Wellington", country: "New Zealand",
    address: "178 Cuba St, Te Aro, Wellington 6011",
    roaster: "Unconfirmed — website is dead (midnightespresso.shop now 301-redirects to an unrelated domain, nanastoto.org) and no press found this session",
    brew_methods: ["espresso"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "midnightespresso",
    editorial_blurb: "Cuba Street's long-running 24-hour espresso bar — a late-night fixture for Wellington's musicians, students and insomniacs; its founding date is unconfirmed this session.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Havana Coffee Works",
    slug: "havana-coffee-works-wellington",
    lat: -41.2977, lng: 174.7790,
    google_place_id: "ChIJ20sF8divOG0RBSITJe-MJvY",
    city: "Wellington", country: "New Zealand",
    address: "163 Tory St, Te Aro, Wellington 6011",
    roaster: "Havana Coffee Works",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "havanacoffeeworks",
    website: "https://www.havana.co.nz/",
    editorial_blurb: "Wellington's storied independent roastery, roasting on Tory Street since 1989 — precise sourcing-region claims are unconfirmed this session.",
    featured_in: ["broadsheet"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Prefab Eatery",
    slug: "prefab-eatery-wellington",
    lat: -41.2955, lng: 174.7786,
    google_place_id: "ChIJD0GpgdmvOG0RGQbEr3JdPp4",
    city: "Wellington", country: "New Zealand",
    address: "14 Jessie St, Te Aro, Wellington 6011",
    roaster: "Acme & Co (on-site)",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "prefabwellington",
    website: "https://prefab.co.nz/",
    editorial_blurb: "Jessie Street eatery where Acme & Co. roasts the coffee on-site — a longtime fixture of Te Aro's specialty-coffee scene since at least 2014.",
    featured_in: ["sprudge", "broadsheet"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Mojo Coffee Wellington",
    slug: "mojo-coffee-wellington",
    lat: -41.2836, lng: 174.7775,
    google_place_id: "ChIJhZszj2evOG0RI6HQWDTYpzQ",
    city: "Wellington", country: "New Zealand",
    address: "10 Brandon Street, Wellington Central, Wellington 6011, New Zealand",
    roaster: "Mojo Coffee",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "mojocoffee",
    website: "https://mojo.coffee/",
    editorial_blurb: "Mojo Coffee's Brandon Street café — part of the roaster's chain spanning Auckland, Wellington and Christchurch, serving Wellington's CBD.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
];
