import type { Cafe } from '@/types';

export const NA_RAW_CAFES: Omit<Cafe, 'id' | 'created_at' | 'third_wave_score' | 'overall_rating' | 'review_count' | 'permanently_closed'>[] = [
  // NEW YORK CITY
  {
    name: "Devoción",
    slug: "devocion-nyc",
    lat: 40.7134, lng: -73.9634,
    city: "New York City", country: "United States",
    address: "69 Grand St, Brooklyn, NY 11249",
    roaster: "Devoción",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "laptop-friendly"],
    instagram_handle: "devocion",
    website: "https://www.devocion.com/",
    editorial_blurb: "Colombian-owned, Williamsburg-roasted — they ship beans farm to cup in 10 days, and you can taste the difference.",
    featured_in: ["sprudge", "ny_times", "infatuation"],
    verified: true, last_verified_at: "2024-11-08", verification_source: "admin",
  },
  {
    name: "Onyx Coffee Lab NYC",
    slug: "onyx-coffee-lab-nyc",
    lat: 40.7282, lng: -73.9942,
    city: "New York City", country: "United States",
    address: "85 Attorney St, New York, NY 10002",
    roaster: "Onyx Coffee Lab",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "onyxcoffeelab",
    website: "https://onyxcoffeelab.com/",
    editorial_blurb: "Arkansas roasters who conquered NYC — their competition-level pours are approachable enough for a Tuesday morning.",
    featured_in: ["sprudge", "eater"],
    verified: true, last_verified_at: "2024-10-12", verification_source: "admin",
  },
  {
    name: "Parlor Coffee",
    slug: "parlor-coffee-brooklyn",
    lat: 40.6950, lng: -73.9909,
    city: "New York City", country: "United States",
    address: "135 Atlantic Ave, Brooklyn, NY 11201",
    roaster: "Parlor Coffee",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "parlorcoffee",
    editorial_blurb: "Tucked inside a Boerum Hill barbershop, Parlor's espresso is worth the detour and the wait for a stool.",
    featured_in: ["sprudge", "ny_times"],
    verified: true, last_verified_at: "2024-09-15", verification_source: "admin",
  },
  {
    name: "Sey Coffee",
    slug: "sey-coffee-bushwick",
    lat: 40.7047, lng: -73.9374,
    city: "New York City", country: "United States",
    address: "18 Grattan St, Brooklyn, NY 11206",
    roaster: "Sey Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "minimalist", "laptop-friendly"],
    instagram_handle: "seycoffee",
    website: "https://www.seycoffee.com/",
    editorial_blurb: "Bushwick roastery chasing the lightest possible roasts — the fruit-forward naturals here taste unlike anything else in the borough.",
    featured_in: ["sprudge", "eater", "ny_times"],
    verified: true, last_verified_at: "2024-11-01", verification_source: "admin",
  },
  {
    name: "Toby's Estate Coffee",
    slug: "tobys-estate-williamsburg",
    lat: 40.7121, lng: -73.9605,
    city: "New York City", country: "United States",
    address: "125 N 6th St, Brooklyn, NY 11249",
    roaster: "Toby's Estate Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "tobysestatecoffee",
    website: "https://tobysestate.com/",
    editorial_blurb: "Australian specialty pedigree rooted in Williamsburg — the training program here has shaped half of Brooklyn's barista talent.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2024-10-20", verification_source: "admin",
  },
  {
    name: "Partners Coffee",
    slug: "partners-coffee-williamsburg",
    lat: 40.7159, lng: -73.9585,
    city: "New York City", country: "United States",
    address: "Main Williamsburg location, Brooklyn, NY 11211",
    roaster: "Partners Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "partnerscoffee",
    website: "https://www.partnerscoffee.com/",
    editorial_blurb: "Brooklyn-roasted, community-minded — the direct-trade single-origins and rotating guest espressos make Partners a perpetual neighborhood anchor.",
    featured_in: ["sprudge", "infatuation"],
    verified: true, last_verified_at: "2024-10-05", verification_source: "admin",
  },
  {
    name: "Joe Coffee",
    slug: "joe-coffee-west-village",
    lat: 40.7333, lng: -74.0037,
    city: "New York City", country: "United States",
    address: "141 Waverly Pl, New York, NY 10014",
    roaster: "Joe Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "joecoffeenyc",
    website: "https://www.joecoffee.com/",
    editorial_blurb: "The café that quietly introduced Manhattan to specialty espresso two decades ago — the West Village original still sets the neighborhood standard.",
    featured_in: ["sprudge", "ny_times"],
    verified: true, last_verified_at: "2024-10-18", verification_source: "admin",
  },
  {
    name: "Everyman Espresso",
    slug: "everyman-espresso-soho",
    lat: 40.7258, lng: -73.9940,
    city: "New York City", country: "United States",
    address: "301 W Broadway, New York, NY 10013",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["standing-bar", "no-laptop", "minimalist"],
    instagram_handle: "everymanespresso",
    editorial_blurb: "SoHo's tightest espresso program in the smallest possible footprint — the rotating single-origin shots reward the walk-in.",
    featured_in: ["sprudge", "infatuation"],
    verified: true, last_verified_at: "2024-09-28", verification_source: "admin",
  },
  {
    name: "Little Collins",
    slug: "little-collins-midtown",
    lat: 40.7575, lng: -73.9718,
    city: "New York City", country: "United States",
    address: "667 Lexington Ave, New York, NY 10022",
    roaster: "Multiple roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "littlecollinsnyc",
    editorial_blurb: "Melbourne transplant that brought proper flat whites to Midtown — the Vegemite toast is optional, the coffee is not.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2024-10-10", verification_source: "admin",
  },
  {
    name: "Cafe Grumpy",
    slug: "cafe-grumpy-chelsea",
    lat: 40.7455, lng: -74.0001,
    city: "New York City", country: "United States",
    address: "224 W 20th St, New York, NY 10011",
    roaster: "Cafe Grumpy",
    brew_methods: ["espresso", "pour-over", "aeropress", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "cafegrumpy",
    website: "https://cafegrumpy.com/",
    editorial_blurb: "NYC's most reliably good indie chain — Chelsea flagship serves Grumpy's own roast with the kind of consistency most multi-location cafés never achieve.",
    featured_in: ["sprudge", "ny_times"],
    verified: true, last_verified_at: "2024-10-25", verification_source: "admin",
  },
  {
    name: "La Cabra NYC",
    slug: "la-cabra-nyc",
    lat: 40.7227, lng: -73.9969,
    city: "New York City", country: "United States",
    address: "31 Bond St, New York, NY 10012",
    roaster: "La Cabra",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "lacabracoffee",
    website: "https://www.lacabra.dk/",
    editorial_blurb: "Copenhagen's most celebrated roastery arrived in Nolita with the same light-handed precision and quietly became essential.",
    featured_in: ["sprudge", "eater"],
    verified: true, last_verified_at: "2024-11-05", verification_source: "admin",
  },
  {
    name: "Stumptown Coffee Roasters NYC",
    slug: "stumptown-ace-hotel-nyc",
    lat: 40.7472, lng: -73.9916,
    city: "New York City", country: "United States",
    address: "18 W 29th St, New York, NY 10001",
    roaster: "Stumptown Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "stumptowncoffee",
    website: "https://www.stumptowncoffee.com/",
    editorial_blurb: "Portland's flagship roastery inside the Ace Hotel — the Flatiron corner that introduced serious filter coffee to a neighborhood that needed it.",
    featured_in: ["sprudge", "ny_times"],
    verified: true, last_verified_at: "2024-10-08", verification_source: "admin",
  },
  {
    name: "Birch Coffee",
    slug: "birch-coffee-flatiron",
    lat: 40.7434, lng: -73.9892,
    city: "New York City", country: "United States",
    address: "134 5th Ave, New York, NY 10011",
    roaster: "Birch Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly"],
    instagram_handle: "birchcoffee",
    website: "https://www.birchcoffee.com/",
    editorial_blurb: "NYC-roasted, phone-optional — Birch's laptop-encouraged, phone-discouraged philosophy produces the most focused café atmosphere in Flatiron.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2024-10-15", verification_source: "admin",
  },
  {
    name: "Oslo Coffee Roasters",
    slug: "oslo-coffee-williamsburg",
    lat: 40.7131, lng: -73.9559,
    city: "New York City", country: "United States",
    address: "328 Bedford Ave, Brooklyn, NY 11211",
    roaster: "Oslo Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "oslocoffee",
    editorial_blurb: "Bedford Ave institution with Scandinavian-influenced sourcing and a Williamsburg patio that becomes impossible to leave in summer.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-20", verification_source: "admin",
  },
  {
    name: "Blue Bottle Coffee Williamsburg",
    slug: "blue-bottle-williamsburg",
    lat: 40.7142, lng: -73.9607,
    city: "New York City", country: "United States",
    address: "160 Berry St, Brooklyn, NY 11249",
    roaster: "Blue Bottle Coffee",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "bluebottlecoffee",
    website: "https://bluebottlecoffee.com/",
    editorial_blurb: "The café that introduced New York to single-origin pour-overs — Williamsburg flagship still earns the pilgrimages it gets.",
    featured_in: ["sprudge", "ny_times"],
    verified: true, last_verified_at: "2024-10-30", verification_source: "admin",
  },
  {
    name: "Coffee Project New York",
    slug: "coffee-project-new-york",
    lat: 40.7259, lng: -73.9847,
    city: "New York City", country: "United States",
    address: "239 E 5th St, New York, NY 10003",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress", "syphon"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "coffeeprojectny",
    website: "https://www.coffeeprojectny.com/",
    editorial_blurb: "East Village geek bar serving syphons and deconstructed lattes alongside serious single-origins — the most technically adventurous café in Manhattan.",
    featured_in: ["sprudge", "infatuation"],
    verified: true, last_verified_at: "2024-10-22", verification_source: "admin",
  },
  {
    name: "Variety Coffee Roasters",
    slug: "variety-coffee-williamsburg",
    lat: 40.7190, lng: -73.9580,
    city: "New York City", country: "United States",
    address: "146 Wythe Ave, Brooklyn, NY 11249",
    roaster: "Variety Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "varietycoffeeroasters",
    website: "https://varietycoffeeroasters.com/",
    editorial_blurb: "Williamsburg roastery that grew out of a single Greenpoint café into Brooklyn's most consistent specialty program — the house blends and single-origins are both excellent.",
    featured_in: ["sprudge", "infatuation"],
    verified: true, last_verified_at: "2024-10-15", verification_source: "admin",
  },
  {
    name: "Round K",
    slug: "round-k-les",
    lat: 40.7200, lng: -73.9867,
    city: "New York City", country: "United States",
    address: "426 Amsterdam Ave, New York, NY 10024",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "roundkcoffee",
    editorial_blurb: "Korean-influenced minimalism with a rotating roster of world-class guest roasters — the most curatorially adventurous café program in the city.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-10", verification_source: "admin",
  },
  {
    name: "Prodigy Coffee",
    slug: "prodigy-coffee-harlem",
    lat: 40.8054, lng: -73.9476,
    city: "New York City", country: "United States",
    address: "33 W 125th St, New York, NY 10027",
    roaster: "Prodigy Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "prodigycoffee",
    editorial_blurb: "Harlem's specialty anchor — Prodigy brought serious coffee culture above 110th Street and made it a neighborhood institution.",
    featured_in: ["sprudge", "ny_times"],
    verified: true, last_verified_at: "2024-10-02", verification_source: "admin",
  },
  {
    name: "Variety Coffee Roasters",
    slug: "variety-coffee-roasters-greenpoint",
    lat: 40.7267, lng: -73.9569,
    city: "New York City", country: "United States",
    address: "146 Driggs Ave, Brooklyn, NY 11222",
    roaster: "Variety Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "varietycoffeeroasters",
    website: "https://www.varietycoffeeroasters.com/",
    editorial_blurb: "Greenpoint roastery with a neighborhood café feel and competition-winning Ethiopian naturals that punch well above the price point.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-25", verification_source: "admin",
  },

  // SAN FRANCISCO
  {
    name: "Sightglass Coffee",
    slug: "sightglass-coffee-sf",
    lat: 37.7749, lng: -122.4066,
    city: "San Francisco", country: "United States",
    address: "270 7th St, San Francisco, CA 94103",
    roaster: "Sightglass Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "sightglasscoffee",
    website: "https://sightglasscoffee.com/",
    editorial_blurb: "SOMA roastery flagship with soaring ceilings and a sourcing program that earns every inch of the hype.",
    featured_in: ["sprudge", "eater"],
    verified: true, last_verified_at: "2024-11-01", verification_source: "admin",
  },
  {
    name: "Ritual Coffee Roasters",
    slug: "ritual-coffee-hayes-valley",
    lat: 37.7762, lng: -122.4245,
    city: "San Francisco", country: "United States",
    address: "432B Octavia Blvd, San Francisco, CA 94102",
    roaster: "Ritual Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "ritualcoffee",
    website: "https://www.ritualroasters.com/",
    editorial_blurb: "The roastery that pioneered SF specialty — Hayes Valley flagship still serves as the city's benchmark for direct-trade espresso.",
    featured_in: ["sprudge", "ny_times"],
    verified: true, last_verified_at: "2024-10-15", verification_source: "admin",
  },
  {
    name: "Linea Caffe",
    slug: "linea-caffe-sf",
    lat: 37.7599, lng: -122.4148,
    city: "San Francisco", country: "United States",
    address: "3417 18th St, San Francisco, CA 94110",
    roaster: "Linea Caffe",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["standing-bar", "no-laptop", "minimalist"],
    instagram_handle: "lineacaffe",
    editorial_blurb: "Standing bar, no wifi, zero distraction — the serious espresso program here is reason enough to make the Mission pilgrimage.",
    featured_in: ["sprudge", "infatuation"],
    verified: true, last_verified_at: "2024-10-20", verification_source: "admin",
  },
  {
    name: "Blue Bottle Coffee",
    slug: "blue-bottle-mint-plaza",
    lat: 37.7785, lng: -122.4074,
    city: "San Francisco", country: "United States",
    address: "66 Mint St, San Francisco, CA 94103",
    roaster: "Blue Bottle Coffee",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "outdoor-seating"],
    instagram_handle: "bluebottlecoffee",
    website: "https://bluebottlecoffee.com/",
    editorial_blurb: "The Mint Plaza kiosk where Blue Bottle's pour-over obsession began — small, seasonal, and still the best introduction to the brand.",
    featured_in: ["sprudge", "ny_times"],
    verified: true, last_verified_at: "2024-10-28", verification_source: "admin",
  },
  {
    name: "Wrecking Ball Coffee Roasters",
    slug: "wrecking-ball-coffee-sf",
    lat: 37.7990, lng: -122.4344,
    city: "San Francisco", country: "United States",
    address: "2271 Union St, San Francisco, CA 94123",
    roaster: "Wrecking Ball Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "laptop-friendly"],
    instagram_handle: "wreckingballcoffee",
    website: "https://www.wreckingballcoffee.com/",
    editorial_blurb: "Cow Hollow roastery with a thoughtful approach to lighter roasts — their Nicaraguan and Ethiopian lots are consistently among SF's finest.",
    featured_in: ["sprudge", "guardian"],
    verified: true, last_verified_at: "2024-10-18", verification_source: "admin",
  },
  {
    name: "Andytown Coffee Roasters",
    slug: "andytown-coffee-outer-sunset",
    lat: 37.7608, lng: -122.4796,
    city: "San Francisco", country: "United States",
    address: "3655 Lawton St, San Francisco, CA 94122",
    roaster: "Andytown Coffee Roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "laptop-friendly"],
    instagram_handle: "andytowncoffee",
    website: "https://www.andytowncoffee.com/",
    editorial_blurb: "Outer Sunset roastery beloved by surfers and specialty nerds alike — the Snowy Plover (sparkling water, espresso, whipped cream) is the only valid SF invention.",
    featured_in: ["sprudge", "eater"],
    verified: true, last_verified_at: "2024-10-08", verification_source: "admin",
  },
  {
    name: "Equator Coffees",
    slug: "equator-coffees-ferry-building",
    lat: 37.7956, lng: -122.3936,
    city: "San Francisco", country: "United States",
    address: "Ferry Building Marketplace, San Francisco, CA 94111",
    roaster: "Equator Coffees",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating"],
    instagram_handle: "equatorcoffees",
    website: "https://www.equatorcoffees.com/",
    editorial_blurb: "Pioneering Marin roaster with a long-standing commitment to fair trade and direct relationships — the Ferry Building perch is the best place to drink them.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-22", verification_source: "admin",
  },
  {
    name: "Réveille Coffee",
    slug: "reveille-coffee-north-beach",
    lat: 37.7985, lng: -122.4078,
    city: "San Francisco", country: "United States",
    address: "200 Columbus Ave, San Francisco, CA 94133",
    roaster: "Réveille Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "reveillecoffee",
    website: "https://www.reveillecoffee.com/",
    editorial_blurb: "North Beach café with a serious roasting operation and a sunny patio that makes it hard to leave — the espresso tonic is a SF rite of passage.",
    featured_in: ["sprudge", "infatuation"],
    verified: true, last_verified_at: "2024-10-12", verification_source: "admin",
  },
  {
    name: "Mazarine Coffee",
    slug: "mazarine-coffee-sf",
    lat: 37.7902, lng: -122.4011,
    city: "San Francisco", country: "United States",
    address: "720 Market St, San Francisco, CA 94102",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "mazarinecoffee",
    editorial_blurb: "Financial District café with a rotating guest roaster program that makes it the most intellectually stimulating coffee stop in downtown SF.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-15", verification_source: "admin",
  },
  {
    name: "Flywheel Coffee Roasters",
    slug: "flywheel-coffee-haight",
    lat: 37.7700, lng: -122.4436,
    city: "San Francisco", country: "United States",
    address: "672 Stanyan St, San Francisco, CA 94117",
    roaster: "Flywheel Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "flywheelcoffee",
    editorial_blurb: "Haight-Ashbury neighborhood roastery operating since 2008 — the longevity says everything about the consistency of what's in the cup.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-30", verification_source: "admin",
  },
  {
    name: "Contraband Coffee Bar",
    slug: "contraband-coffee-sf",
    lat: 37.7836, lng: -122.4165,
    city: "San Francisco", country: "United States",
    address: "1415 Larkin St, San Francisco, CA 94109",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "contrabandcoffeebar",
    editorial_blurb: "Nob Hill café punching above its weight with a guest roaster rotation that features the best of the West Coast specialty scene.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-05", verification_source: "admin",
  },
  {
    name: "Verve Coffee Roasters SF",
    slug: "verve-coffee-sf-mission",
    lat: 37.7609, lng: -122.4148,
    city: "San Francisco", country: "United States",
    address: "2101 Mission St, San Francisco, CA 94110",
    roaster: "Verve Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "vervecoffee",
    website: "https://www.vervecoffee.com/",
    editorial_blurb: "Santa Cruz's acclaimed roastery hits the Mission with the same light-roast precision — the Ethiopia Yirgacheffe is a permanent fixture on the menu for good reason.",
    featured_in: ["sprudge", "eater"],
    verified: true, last_verified_at: "2024-10-25", verification_source: "admin",
  },

  // PORTLAND
  {
    name: "Stumptown Coffee Roasters",
    slug: "stumptown-portland",
    lat: 45.5143, lng: -122.6545,
    city: "Portland", country: "United States",
    address: "4525 SE Division St, Portland, OR 97206",
    roaster: "Stumptown Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "french-press", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "stumptowncoffee",
    website: "https://www.stumptowncoffee.com/",
    editorial_blurb: "The roastery that launched Portland's coffee revolution — the original Division location still feels like the center of something important.",
    featured_in: ["sprudge", "ny_times", "eater"],
    verified: true, last_verified_at: "2024-10-28", verification_source: "admin",
  },
  {
    name: "Water Avenue Coffee",
    slug: "water-avenue-coffee-portland",
    lat: 45.5168, lng: -122.6649,
    city: "Portland", country: "United States",
    address: "1028 SE Water Ave, Portland, OR 97214",
    roaster: "Water Avenue Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "wateravenuecoffee",
    website: "https://wateravenuecoffee.com/",
    editorial_blurb: "Eastside Portland's precision roastery — their long extraction pour-overs and obsessive sourcing make the Hawthorne Bridge detour worthwhile.",
    featured_in: ["sprudge", "guardian"],
    verified: true, last_verified_at: "2024-10-10", verification_source: "admin",
  },
  {
    name: "Coava Coffee Roasters",
    slug: "coava-coffee-portland",
    lat: 45.5170, lng: -122.6604,
    city: "Portland", country: "United States",
    address: "1300 SE Grand Ave, Portland, OR 97214",
    roaster: "Coava Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "coavacoffee",
    website: "https://coava.coffee/",
    editorial_blurb: "Roastery inside a repurposed basketball court on Grand Ave — the scale of the space matches the ambition of the single-origin sourcing program.",
    featured_in: ["sprudge", "eater"],
    verified: true, last_verified_at: "2024-10-28", verification_source: "admin",
  },
  {
    name: "Heart Coffee Roasters",
    slug: "heart-coffee-roasters-portland",
    lat: 45.5228, lng: -122.6466,
    city: "Portland", country: "United States",
    address: "2211 E Burnside St, Portland, OR 97214",
    roaster: "Heart Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "minimalist", "laptop-friendly"],
    instagram_handle: "heartroasters",
    website: "https://www.heartroasters.com/",
    editorial_blurb: "Nordic-influenced roasting in a Scandinavian-designed Burnside space — the lightest roasts in Portland with the cleanest possible expression of terroir.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2024-11-05", verification_source: "admin",
  },
  {
    name: "Barista",
    slug: "barista-pearl-portland",
    lat: 45.5252, lng: -122.6832,
    city: "Portland", country: "United States",
    address: "539 NW 13th Ave, Portland, OR 97209",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "baristapdx",
    website: "https://www.baristapdx.com/",
    editorial_blurb: "Pearl District multi-roaster bar that helped define what a curatorially adventurous espresso program looks like — still the best guest-roaster lineup in town.",
    featured_in: ["sprudge", "eater"],
    verified: true, last_verified_at: "2024-10-15", verification_source: "admin",
  },
  {
    name: "Spella Caffè",
    slug: "spella-caffe-portland",
    lat: 45.5195, lng: -122.6785,
    city: "Portland", country: "United States",
    address: "520 SW 5th Ave, Portland, OR 97204",
    roaster: "Spella Caffè",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["standing-bar", "minimalist", "no-laptop"],
    instagram_handle: "spellacaffe",
    editorial_blurb: "Downtown Portland's most old-school espresso operation — a tiny cart serving the city's best traditional-method shots with Italian conviction.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-20", verification_source: "admin",
  },
  {
    name: "Proud Mary Coffee",
    slug: "proud-mary-coffee-portland",
    lat: 45.5496, lng: -122.6699,
    city: "Portland", country: "United States",
    address: "2012 N Mississippi Ave, Portland, OR 97227",
    roaster: "Proud Mary Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "proudmarycoffee",
    website: "https://proudmarycoffee.com/",
    editorial_blurb: "Melbourne-born, Mississippi Ave-adopted — Proud Mary's Australian approach to hospitality and sourcing brought a new gear to Portland's already-excellent scene.",
    featured_in: ["sprudge", "eater"],
    verified: true, last_verified_at: "2024-10-22", verification_source: "admin",
  },
  {
    name: "Extracto Coffee Roasters",
    slug: "extracto-coffee-portland",
    lat: 45.5381, lng: -122.6453,
    city: "Portland", country: "United States",
    address: "2921 NE Alberta St, Portland, OR 97211",
    roaster: "Extracto Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "extractocoffee",
    website: "https://extractocoffee.com/",
    editorial_blurb: "Alberta Arts District roastery with a community-first ethos and single-origins that reward the walk off the beaten path.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-25", verification_source: "admin",
  },
  {
    name: "Ristretto Roasters",
    slug: "ristretto-roasters-portland",
    lat: 45.5452, lng: -122.6619,
    city: "Portland", country: "United States",
    address: "3808 N Williams Ave, Portland, OR 97227",
    roaster: "Ristretto Roasters",
    brew_methods: ["espresso", "pour-over", "chemex"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "laptop-friendly"],
    instagram_handle: "ristrettoroasters",
    website: "https://ristrettoroasters.com/",
    editorial_blurb: "N Williams roastery with a decades-long commitment to single-origin transparency — the roast notes on their bags tell you more than most baristas will.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-05", verification_source: "admin",
  },
  {
    name: "Sterling Coffee Roasters",
    slug: "sterling-coffee-roasters-portland",
    lat: 45.5261, lng: -122.6944,
    city: "Portland", country: "United States",
    address: "2120 NW Glisan St, Portland, OR 97210",
    roaster: "Sterling Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "sterlingcoffeeroasters",
    website: "https://www.sterlingcoffeeroasters.com/",
    editorial_blurb: "NW Portland's precision roastery with a restrained aesthetic and an unrestrained commitment to sourcing transparency.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-12", verification_source: "admin",
  },
  {
    name: "Courier Coffee Roasters",
    slug: "courier-coffee-portland",
    lat: 45.5220, lng: -122.6808,
    city: "Portland", country: "United States",
    address: "923 SW Oak St, Portland, OR 97205",
    roaster: "Courier Coffee Roasters",
    brew_methods: ["espresso", "pour-over", "french-press"],
    vibe_tags: ["minimalist", "no-laptop", "standing-bar"],
    instagram_handle: "couriercoffeeroasters",
    editorial_blurb: "Downtown Portland's smallest serious roastery — the Oak Street cart-turned-room serves the city's most singular espresso program with no distractions.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-08", verification_source: "admin",
  },
  {
    name: "Deadstock Coffee",
    slug: "deadstock-coffee-portland",
    lat: 45.5232, lng: -122.6738,
    city: "Portland", country: "United States",
    address: "408 NW Couch St, Portland, OR 97209",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "deadstockcoffee",
    website: "https://www.deadstockcoffee.com/",
    editorial_blurb: "Sneaker culture meets specialty coffee in Old Town — the rotating collabs, the drip, and the community it's built make Deadstock genuinely one-of-a-kind.",
    featured_in: ["sprudge", "eater"],
    verified: true, last_verified_at: "2024-10-18", verification_source: "admin",
  },
  {
    name: "Case Study Coffee",
    slug: "case-study-coffee-portland",
    lat: 45.5289, lng: -122.6596,
    city: "Portland", country: "United States",
    address: "802 N Alberta St, Portland, OR 97217",
    roaster: "Case Study Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "casestudycoffee",
    website: "https://casestudycoffee.com/",
    editorial_blurb: "Alberta Street multi-roaster with a relaxed, studious atmosphere and a filter program that takes its cue from the best of Portland's roasting scene.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-18", verification_source: "admin",
  },

  // CHICAGO
  {
    name: "Intelligentsia Coffee",
    slug: "intelligentsia-millennium-park",
    lat: 41.8820, lng: -87.6244,
    city: "Chicago", country: "United States",
    address: "53 W Jackson Blvd, Chicago, IL 60604",
    roaster: "Intelligentsia Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "intelligentsiacoffee",
    website: "https://www.intelligentsiacoffee.com/",
    editorial_blurb: "The seminal US third-wave roaster that redefined direct trade — every cup carries twenty-five years of hard-won sourcing relationships.",
    featured_in: ["sprudge", "ny_times"],
    verified: true, last_verified_at: "2024-11-01", verification_source: "admin",
  },
  {
    name: "Dark Matter Coffee",
    slug: "dark-matter-coffee-wicker-park",
    lat: 41.9086, lng: -87.6788,
    city: "Chicago", country: "United States",
    address: "738 N Western Ave, Chicago, IL 60622",
    roaster: "Dark Matter Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "darkmattercoffee",
    website: "https://www.darkmattercoffee.com/",
    editorial_blurb: "Punk-aesthetic roastery in Wicker Park that proves world-class beans and a loud personality are not mutually exclusive.",
    featured_in: ["sprudge", "eater"],
    verified: true, last_verified_at: "2024-10-18", verification_source: "admin",
  },
  {
    name: "Sawada Coffee",
    slug: "sawada-coffee-chicago",
    lat: 41.8834, lng: -87.6479,
    city: "Chicago", country: "United States",
    address: "112 N Green St, Chicago, IL 60607",
    roaster: "Intelligentsia Coffee",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["minimalist", "no-laptop", "standing-bar"],
    instagram_handle: "sawadacoffee",
    editorial_blurb: "Japanese precision in the West Loop — Hiroshi Sawada's military latte and immaculate espresso pull make this a non-negotiable Chicago stop.",
    featured_in: ["sprudge", "infatuation"],
    verified: true, last_verified_at: "2024-10-10", verification_source: "admin",
  },
  {
    name: "Metric Coffee Co.",
    slug: "metric-coffee-chicago",
    lat: 41.8847, lng: -87.6510,
    city: "Chicago", country: "United States",
    address: "2021 W Fulton St, Chicago, IL 60612",
    roaster: "Metric Coffee Co.",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "metriccoffee",
    website: "https://metriccoffee.com/",
    editorial_blurb: "Fulton Market roastery that straddles science and craft — the sourcing transparency and brewing precision attract serious coffee professionals on their days off.",
    featured_in: ["sprudge", "infatuation"],
    verified: true, last_verified_at: "2024-10-28", verification_source: "admin",
  },
  {
    name: "Gaslight Coffee Roasters",
    slug: "gaslight-coffee-roasters-chicago",
    lat: 41.9228, lng: -87.7002,
    city: "Chicago", country: "United States",
    address: "2385 N Milwaukee Ave, Chicago, IL 60647",
    roaster: "Gaslight Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "gaslightcoffeeroasters",
    website: "https://www.gaslightcoffeeroasters.com/",
    editorial_blurb: "Logan Square's neighborhood roastery with an honest, unpretentious approach to great beans — the kind of café a neighborhood builds itself around.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-05", verification_source: "admin",
  },
  {
    name: "Halfwit Coffee Roasters",
    slug: "halfwit-coffee-roasters-chicago",
    lat: 41.9142, lng: -87.6869,
    city: "Chicago", country: "United States",
    address: "2046 W Chicago Ave, Chicago, IL 60622",
    roaster: "Halfwit Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["roastery-on-site", "minimalist", "laptop-friendly"],
    instagram_handle: "halfwitcoffee",
    website: "https://www.halfwitcoffee.com/",
    editorial_blurb: "Wicker Park roastery with a self-deprecating name and a deadly-serious approach to light-roast Ethiopian and Colombian single-origins.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-20", verification_source: "admin",
  },
  {
    name: "Ipsento 606",
    slug: "ipsento-606-chicago",
    lat: 41.9064, lng: -87.6720,
    city: "Chicago", country: "United States",
    address: "2035 N Western Ave, Chicago, IL 60647",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "ipsento606",
    website: "https://www.ipsento.com/",
    editorial_blurb: "Named for the 606 trail it sits beside — the espresso drinks here are as adventurous as the neighborhood and the patio sees every kind of Chicagoan.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2024-10-02", verification_source: "admin",
  },
  {
    name: "Passion House Coffee Roasters",
    slug: "passion-house-coffee-chicago",
    lat: 41.9230, lng: -87.7048,
    city: "Chicago", country: "United States",
    address: "2356 W Fullerton Ave, Chicago, IL 60647",
    roaster: "Passion House Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "passionhousecoffee",
    website: "https://passionhousecoffee.com/",
    editorial_blurb: "Logan Square roastery with a thoughtful approach to medium-light roasts — the origin notes are specific enough to reward the curious and the casual drinker both.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-15", verification_source: "admin",
  },
  {
    name: "La Colombe Coffee",
    slug: "la-colombe-chicago-river-north",
    lat: 41.8952, lng: -87.6336,
    city: "Chicago", country: "United States",
    address: "955 W Randolph St, Chicago, IL 60607",
    roaster: "La Colombe Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "lacolombecoffee",
    website: "https://www.lacolombe.com/",
    editorial_blurb: "Philly-born roastery that brought its serious espresso program and beloved draft latte to Chicago's West Loop restaurant corridor.",
    featured_in: ["sprudge", "eater"],
    verified: true, last_verified_at: "2024-10-15", verification_source: "admin",
  },
  {
    name: "Understory",
    slug: "understory-chicago",
    lat: 41.8837, lng: -87.6532,
    city: "Chicago", country: "United States",
    address: "222 W Adams St, Chicago, IL 60606",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "understorychicago",
    editorial_blurb: "West Loop multi-roaster bar in a stunning subterranean space — the daily rotating filter selection and pristine espresso make it the best lunch-break café in the Loop.",
    featured_in: ["sprudge", "infatuation"],
    verified: true, last_verified_at: "2024-10-20", verification_source: "admin",
  },
  {
    name: "Big Shoulders Coffee",
    slug: "big-shoulders-coffee-chicago",
    lat: 41.9117, lng: -87.6388,
    city: "Chicago", country: "United States",
    address: "1105 W Chicago Ave, Chicago, IL 60642",
    roaster: "Big Shoulders Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "bigshoulderscoffee",
    website: "https://www.bigshoulderscoffee.com/",
    editorial_blurb: "Named for Sandburg's Chicago, built for the city's specialty drinkers — the West Town flagship serves the neighborhood's best single-origin espresso.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-28", verification_source: "admin",
  },
  {
    name: "Dayglow",
    slug: "dayglow-chicago",
    lat: 41.9093, lng: -87.6745,
    city: "Chicago", country: "United States",
    address: "1177 N Elston Ave, Chicago, IL 60622",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "outdoor-seating"],
    instagram_handle: "dayglow",
    editorial_blurb: "Wicker Park café with a fashion-forward aesthetic and a seriously curated guest roaster program — the kind of place that looks good and tastes better.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-10", verification_source: "admin",
  },

  // MONTREAL
  {
    name: "Café Myriade",
    slug: "cafe-myriade-montreal",
    lat: 45.4972, lng: -73.5773,
    city: "Montreal", country: "Canada",
    address: "1432 Rue Mackay, Montréal, QC H3G 2H7",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "cafemyriade",
    website: "https://cafemyriade.com/",
    editorial_blurb: "Montreal's specialty anchor — consistently excellent espresso and a rotating guest roaster program that keeps regulars coming back.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-05", verification_source: "admin",
  },
  {
    name: "Dispatch Coffee",
    slug: "dispatch-coffee-montreal",
    lat: 45.5231, lng: -73.5790,
    city: "Montreal", country: "Canada",
    address: "4231 Rue Saint-Denis, Montréal, QC H2J 2K9",
    roaster: "Dispatch Coffee",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "dispatchcoffee",
    editorial_blurb: "Plateau neighbourhood staple with a serious roasting operation — the natural-process Ethiopians here are among Canada's best.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2024-09-10", verification_source: "community",
  },
  {
    name: "Café Olimpico",
    slug: "cafe-olimpico-montreal",
    lat: 45.5196, lng: -73.5935,
    city: "Montreal", country: "Canada",
    address: "124 Rue Saint-Viateur O, Montréal, QC H2T 2L1",
    roaster: "Caffè San Simeon",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "cafeolimp",
    editorial_blurb: "Mile End icon since 1970 — the lineups outside on Saint-Viateur are proof that getting the basics exactly right never goes out of style.",
    featured_in: ["sprudge", "guardian"],
    verified: true, last_verified_at: "2024-10-20", verification_source: "admin",
  },
  {
    name: "Saint-Henri Micro-Torréfacteur",
    slug: "saint-henri-montreal",
    lat: 45.4799, lng: -73.5820,
    city: "Montreal", country: "Canada",
    address: "3632 Notre-Dame St W, Montréal, QC H4C 1P8",
    roaster: "Saint-Henri Micro-Torréfacteur",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "sainthenricafe",
    website: "https://www.sainthenri.ca/",
    editorial_blurb: "Named for its neighbourhood, rooted in it — the micro-roastery behind one of Montreal's most thoughtful direct-sourcing programs.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-12", verification_source: "admin",
  },
  {
    name: "Café Névé",
    slug: "cafe-neve-montreal",
    lat: 45.5270, lng: -73.5777,
    city: "Montreal", country: "Canada",
    address: "151 Rue Rachel E, Montréal, QC H2W 1C7",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "nevemtl",
    editorial_blurb: "Plateau-Mont-Royal's most neighborhood-perfect café — the terrace, the espresso drinks, and the rotation of guest roasters make it hard to find a flaw.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-25", verification_source: "admin",
  },
  {
    name: "Tommy Café",
    slug: "tommy-cafe-montreal",
    lat: 45.4917, lng: -73.5592,
    city: "Montreal", country: "Canada",
    address: "200 Notre-Dame St W, Montréal, QC H2Y 1T3",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "tommycafemtl",
    editorial_blurb: "Griffintown's design-forward specialty café — the rotating guest roasters and clean Scandinavian interior make it the neighbourhood's most aspirational work space.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-18", verification_source: "admin",
  },
  {
    name: "Pikolo Espresso Bar",
    slug: "pikolo-espresso-bar-montreal",
    lat: 45.5082, lng: -73.5744,
    city: "Montreal", country: "Canada",
    address: "3418 Ave du Parc, Montréal, QC H2X 2H5",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["standing-bar", "no-laptop"],
    instagram_handle: "pikolomontreal",
    editorial_blurb: "The tiniest serious espresso bar in the McGill neighbourhood — the two stools, the rotating single-origins, and the expert pulls make it worth the squeeze.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-05", verification_source: "admin",
  },
  {
    name: "Café Falco",
    slug: "cafe-falco-montreal",
    lat: 45.5460, lng: -73.5778,
    city: "Montreal", country: "Canada",
    address: "5605 Ave de Gaspé, Montréal, QC H2T 2A4",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "cafefalco",
    editorial_blurb: "Rosemont café inside a design studio building — where the city's creative class brings their laptops and the guest roaster list changes weekly.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-12", verification_source: "admin",
  },
  {
    name: "Crew Collective & Café",
    slug: "crew-collective-cafe-montreal",
    lat: 45.5085, lng: -73.5565,
    city: "Montreal", country: "Canada",
    address: "360 Rue Saint-Jacques, Montréal, QC H2Y 1P5",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "crewcollectivecafe",
    website: "https://crewcollectivecafe.com/",
    editorial_blurb: "A former Royal Bank interior turned co-working café — the Beaux-Arts banking hall is the most dramatic place to drink an espresso in Canada.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2024-10-30", verification_source: "admin",
  },
  {
    name: "Café Larue & Fils",
    slug: "cafe-larue-fils-montreal",
    lat: 45.5410, lng: -73.5803,
    city: "Montreal", country: "Canada",
    address: "3955 Rue Beaubien E, Montréal, QC H1X 1H4",
    roaster: "Larue & Fils",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "larueetfils",
    editorial_blurb: "Rosemont micro-roastery doubling as a serious pour-over bar — the house Colombian lots and the neighbourhood regulars give it an authenticity hard to manufacture.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-08", verification_source: "admin",
  },
  {
    name: "Café Replika",
    slug: "cafe-replika-montreal",
    lat: 45.5014, lng: -73.5723,
    city: "Montreal", country: "Canada",
    address: "252 Rue du Square-Victoria, Montréal, QC H2Z 1X5",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "replicamtl",
    editorial_blurb: "Turkish-influenced café design with a Montreal specialty coffee sensibility — the baklava and espresso pairing makes it the city's most unexpected pleasure.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-08-28", verification_source: "community",
  },

  // TORONTO
  {
    name: "Pilot Coffee Roasters",
    slug: "pilot-coffee-roasters-toronto",
    lat: 43.6503, lng: -79.3591,
    city: "Toronto", country: "Canada",
    address: "49 Camden St, Toronto, ON M5V 1V2",
    roaster: "Pilot Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "pilotcoffeeroasters",
    website: "https://www.pilotcoffeeroasters.com/",
    editorial_blurb: "Toronto's most respected roastery — the Camden St flagship is where the city's specialty scene goes to calibrate its standards.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-11-02", verification_source: "admin",
  },
  {
    name: "Sam James Coffee Bar",
    slug: "sam-james-coffee-bar-toronto",
    lat: 43.6609, lng: -79.4024,
    city: "Toronto", country: "Canada",
    address: "297 Harbord St, Toronto, ON M6G 1G7",
    roaster: "Sam James Coffee Bar",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["standing-bar", "no-laptop", "minimalist"],
    instagram_handle: "samjamescoffeebar",
    editorial_blurb: "Toronto's legendary standing-bar espresso institution — the lineup is the city's most reliable indicator of a genuinely great shot.",
    featured_in: ["sprudge", "guardian"],
    verified: true, last_verified_at: "2024-10-25", verification_source: "admin",
  },
  {
    name: "Neo Coffee Bar",
    slug: "neo-coffee-bar-toronto",
    lat: 43.6527, lng: -79.3971,
    city: "Toronto", country: "Canada",
    address: "181 University Ave, Toronto, ON M5H 3M7",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "neocoffeebar",
    website: "https://www.neocoffeebar.com/",
    editorial_blurb: "Financial District specialty café with a serious filter program — the Korean-influenced minimalism and rotating guest roasters make it the best work-call café in the core.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-18", verification_source: "admin",
  },
  {
    name: "Rooster Coffee",
    slug: "rooster-coffee-toronto",
    lat: 43.6614, lng: -79.3676,
    city: "Toronto", country: "Canada",
    address: "479 Parliament St, Toronto, ON M4X 1P4",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "roostercoffeehouse",
    editorial_blurb: "Cabbagetown neighbourhood staple with Parliament St patio energy and a reliable espresso program that's fed the neighbourhood for years.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2024-10-08", verification_source: "admin",
  },
  {
    name: "Boxcar Social",
    slug: "boxcar-social-summerhill-toronto",
    lat: 43.6825, lng: -79.3896,
    city: "Toronto", country: "Canada",
    address: "235 Summerhill Ave, Toronto, ON M4T 1B3",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "boxcarsocial",
    website: "https://boxcarsocial.ca/",
    editorial_blurb: "Whisky bar meets specialty café — the Summerhill rooftop and the rotating guest roaster program make Boxcar one of Toronto's most original concepts.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2024-10-22", verification_source: "admin",
  },
  {
    name: "Merchants of Green Coffee",
    slug: "merchants-of-green-coffee-toronto",
    lat: 43.6627, lng: -79.3348,
    city: "Toronto", country: "Canada",
    address: "2 Matilda St, Toronto, ON M4M 1X5",
    roaster: "Merchants of Green Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "french-press"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "laptop-friendly"],
    instagram_handle: "merchantsofgreencoffee",
    website: "https://merchantsofgreencoffee.com/",
    editorial_blurb: "Leslieville roastery and green coffee importer — the sourcing goes deeper than almost any café in Canada and the industrial space does justice to the beans.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-28", verification_source: "admin",
  },
  {
    name: "Propeller Coffee Co.",
    slug: "propeller-coffee-toronto",
    lat: 43.6628, lng: -79.4383,
    city: "Toronto", country: "Canada",
    address: "50 Wade Ave, Toronto, ON M6H 1A4",
    roaster: "Propeller Coffee Co.",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "propellercoffee",
    website: "https://www.propellercoffee.com/",
    editorial_blurb: "Bloordale roastery in a converted industrial space — the direct-trade program and community events make it West End Toronto's specialty anchor.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-12", verification_source: "admin",
  },
  {
    name: "Reunion Island Coffee",
    slug: "reunion-island-coffee-toronto",
    lat: 43.6573, lng: -79.4014,
    city: "Toronto", country: "Canada",
    address: "254 Kensington Ave, Toronto, ON M5T 2H8",
    roaster: "Reunion Island Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "reunionislandcoffee",
    website: "https://reunionislandcoffee.com/",
    editorial_blurb: "Kensington Market's specialty gem from one of Canada's most dedicated roasters — the fair-trade direct relationships show up in every pour.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-20", verification_source: "admin",
  },
  {
    name: "Jimmy's Coffee",
    slug: "jimmys-coffee-toronto",
    lat: 43.6499, lng: -79.4232,
    city: "Toronto", country: "Canada",
    address: "107 Portland St, Toronto, ON M5V 2N3",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "jimmyscoffee",
    editorial_blurb: "Toronto's most neighbourhood-loyal café group — each location feels genuinely local and the espresso program never coasts.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2024-10-05", verification_source: "admin",
  },
  {
    name: "De Mello Palheta Coffee",
    slug: "de-mello-palheta-toronto",
    lat: 43.6553, lng: -79.3967,
    city: "Toronto", country: "Canada",
    address: "699 Spadina Ave, Toronto, ON M5S 2J2",
    roaster: "De Mello Palheta",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "demellopalhatatoronto",
    editorial_blurb: "Singapore specialty roaster's Toronto outpost — the meticulous sourcing and execution set a standard the local scene is still rising to meet.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-15", verification_source: "admin",
  },
  {
    name: "Sense Appeal Coffee Roasters",
    slug: "sense-appeal-toronto",
    lat: 43.6439, lng: -79.4008,
    city: "Toronto", country: "Canada",
    address: "907 King St W, Toronto, ON M6K 1E4",
    roaster: "Sense Appeal Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "laptop-friendly"],
    instagram_handle: "senseappealcoffee",
    editorial_blurb: "King West roastery café with a sun-drenched terrace and a serious single-origin filter program — the most civilized way to start a Toronto morning.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-22", verification_source: "admin",
  },
  {
    name: "Te Aro Coffee",
    slug: "te-aro-coffee-toronto",
    lat: 43.6477, lng: -79.3805,
    city: "Toronto", country: "Canada",
    address: "7 King St E, Toronto, ON M5C 1N5",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "tearocoffee",
    editorial_blurb: "New Zealand-inspired specialty in the heart of the Financial District — the flat whites are a genuine benchmark for the entire city.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-01", verification_source: "admin",
  },
  {
    name: "Ezra's Pound",
    slug: "ezras-pound-toronto",
    lat: 43.6433, lng: -79.4490,
    city: "Toronto", country: "Canada",
    address: "238 Roncesvalles Ave, Toronto, ON M6R 2L8",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "ezraspound",
    editorial_blurb: "Roncesvalles neighbourhood institution — the literary name, the rotating single-origins, and the book shelves make it the West End's most comfortable long stay.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-10", verification_source: "admin",
  },

  // VANCOUVER
  {
    name: "Revolver Coffee",
    slug: "revolver-coffee-gastown",
    lat: 49.2831, lng: -123.1054,
    city: "Vancouver", country: "Canada",
    address: "325 Cambie St, Vancouver, BC V6B 2N4",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress", "chemex"],
    vibe_tags: ["no-laptop", "minimalist", "standing-bar"],
    instagram_handle: "revolvercoffee",
    editorial_blurb: "Gastown's most serious coffee destination — the daily rotating roster of world's best roasters and the no-laptop rule make it the city's most focused café.",
    featured_in: ["sprudge", "monocle", "standart"],
    verified: true, last_verified_at: "2024-11-05", verification_source: "admin",
  },
  {
    name: "49th Parallel Coffee Roasters",
    slug: "49th-parallel-coffee-kitsilano",
    lat: 49.2669, lng: -123.1544,
    city: "Vancouver", country: "Canada",
    address: "2198 W 4th Ave, Vancouver, BC V6K 1N8",
    roaster: "49th Parallel Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "49thcoffee",
    website: "https://49thcoffee.com/",
    editorial_blurb: "Kitsilano flagship of Vancouver's most celebrated roastery — the Lucky's Donuts counter inside is the greatest coffee-and-doughnut pairing in Canada.",
    featured_in: ["sprudge", "guardian"],
    verified: true, last_verified_at: "2024-10-28", verification_source: "admin",
  },
  {
    name: "Matchstick Coffee Roasters",
    slug: "matchstick-coffee-roasters-vancouver",
    lat: 49.2797, lng: -123.0963,
    city: "Vancouver", country: "Canada",
    address: "639 E 15th Ave, Vancouver, BC V5T 2S6",
    roaster: "Matchstick Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "matchstickcoffee",
    website: "https://www.matchstickcoffee.com/",
    editorial_blurb: "Mount Pleasant roastery with an obsessive approach to single-origin transparency — the tasting notes here are written by people who actually tasted them.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-20", verification_source: "admin",
  },
  {
    name: "Pallet Coffee Roasters",
    slug: "pallet-coffee-roasters-vancouver",
    lat: 49.2722, lng: -123.0697,
    city: "Vancouver", country: "Canada",
    address: "323 E Broadway, Vancouver, BC V5T 1W5",
    roaster: "Pallet Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "palletcoffee",
    website: "https://www.palletcoffee.com/",
    editorial_blurb: "East Broadway roastery known for accessible entry-level specialty and a team that treats first-timers as well as the serious coffee nerd.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-10", verification_source: "admin",
  },
  {
    name: "JJ Bean Coffee Roasters",
    slug: "jj-bean-coffee-main-street",
    lat: 49.2548, lng: -123.1011,
    city: "Vancouver", country: "Canada",
    address: "2206 Main St, Vancouver, BC V5T 3C3",
    roaster: "JJ Bean Coffee Roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "jjbeancoffee",
    website: "https://jjbeancoffee.com/",
    editorial_blurb: "Vancouver's most loved local chain, earned honestly — the Main Street flagship serves the city's most consistent espresso and raises the bar for every location after it.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-05", verification_source: "admin",
  },
  {
    name: "Timbertrain Coffee Roasters",
    slug: "timbertrain-coffee-gastown",
    lat: 49.2839, lng: -123.1056,
    city: "Vancouver", country: "Canada",
    address: "311 W Cordova St, Vancouver, BC V6B 1E5",
    roaster: "Timbertrain Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "minimalist"],
    instagram_handle: "timbertraincoffee",
    website: "https://www.timbertraincoffeeroasters.com/",
    editorial_blurb: "Gastown roastery with a Pacific Northwest-sourcing focus and the kind of industrial-wood interior that coffee shops have been imitating ever since.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-15", verification_source: "admin",
  },
  {
    name: "Bows & Arrows Coffee Roasters",
    slug: "bows-and-arrows-vancouver",
    lat: 49.2776, lng: -123.0892,
    city: "Vancouver", country: "Canada",
    address: "4905 Fraser St, Vancouver, BC V5W 3C6",
    roaster: "Bows & Arrows Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "bowsandarrowscoffee",
    editorial_blurb: "Fraser Street roastery that stays under the radar while producing some of Vancouver's most technically precise single-origin lots.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-25", verification_source: "admin",
  },
  {
    name: "Small Victory Bakery",
    slug: "small-victory-bakery-vancouver",
    lat: 49.2751, lng: -123.1206,
    city: "Vancouver", country: "Canada",
    address: "1088 Homer St, Vancouver, BC V6B 2X2",
    roaster: "49th Parallel Coffee Roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "smallvictorybakery",
    website: "https://www.smallvictory.ca/",
    editorial_blurb: "Yaletown's most beautiful café doubles as a serious bakery — 49th Parallel on espresso and pastries worth delaying any meeting for.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2024-10-25", verification_source: "admin",
  },
  {
    name: "Kafka's Coffee & Tea",
    slug: "kafkas-coffee-mount-pleasant",
    lat: 49.2640, lng: -123.1005,
    city: "Vancouver", country: "Canada",
    address: "2525 Main St, Vancouver, BC V5T 3E2",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "kafkascoffee",
    editorial_blurb: "Main Street's most eclectic specialty café — the rotating guest roasters, the dark corners, and the regulars make Kafka's feel like a neighbourhood secret even when it's full.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-18", verification_source: "admin",
  },
  {
    name: "Nelson the Seagull",
    slug: "nelson-the-seagull-gastown",
    lat: 49.2839, lng: -123.1019,
    city: "Vancouver", country: "Canada",
    address: "315 Carrall St, Vancouver, BC V6B 2J4",
    roaster: "49th Parallel Coffee Roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["no-laptop", "outdoor-seating", "minimalist"],
    instagram_handle: "nelsontheseagull",
    editorial_blurb: "Gastown café and bakery where the sourdough and the espresso are treated with equal seriousness — the no-laptop policy keeps the energy exactly right.",
    featured_in: ["sprudge", "guardian"],
    verified: true, last_verified_at: "2024-10-18", verification_source: "admin",
  },
  {
    name: "Elysian Coffee",
    slug: "elysian-coffee-west-end-vancouver",
    lat: 49.2882, lng: -123.1373,
    city: "Vancouver", country: "Canada",
    address: "1778 W 5th Ave, Vancouver, BC V6J 1P2",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "elysiancoffee",
    editorial_blurb: "West End café with a community-first ethos and a guest roaster program that showcases the best of BC and beyond — the most welcoming specialty café in the neighbourhood.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-12", verification_source: "admin",
  },
  {
    name: "East Van Roasters",
    slug: "east-van-roasters-vancouver",
    lat: 49.2811, lng: -123.0594,
    city: "Vancouver", country: "Canada",
    address: "101 E Hastings St, Vancouver, BC V6A 1N7",
    roaster: "East Van Roasters",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "eastvanroasters",
    website: "https://www.eastvanroasters.com/",
    editorial_blurb: "Social enterprise roastery providing employment to women in the Downtown Eastside — the coffee is excellent and the mission behind it makes every cup matter more.",
    featured_in: ["sprudge", "guardian"],
    verified: true, last_verified_at: "2024-10-02", verification_source: "admin",
  },

  // MIAMI
  {
    name: "Panther Coffee",
    slug: "panther-coffee-wynwood",
    lat: 25.8002, lng: -80.1993,
    city: "Miami", country: "United States",
    address: "2390 NW 2nd Ave, Miami, FL 33127",
    roaster: "Panther Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "laptop-friendly"],
    instagram_handle: "panthercoffee",
    website: "https://www.panthercoffee.com/",
    editorial_blurb: "Miami's flagship specialty roastery in the heart of Wynwood — the Cuban-influenced espresso service and rotating single-origins set the city's benchmark.",
    featured_in: ["sprudge", "eater", "infatuation"],
    verified: true, last_verified_at: "2024-11-01", verification_source: "admin",
  },
  {
    name: "Panther Coffee Coconut Grove",
    slug: "panther-coffee-coconut-grove",
    lat: 25.7344, lng: -80.2385,
    city: "Miami", country: "United States",
    address: "3407 Main Hwy, Miami, FL 33133",
    roaster: "Panther Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "panthercoffee",
    website: "https://www.panthercoffee.com/",
    editorial_blurb: "Panther's shaded Grove outpost — the banyan-tree canopy and the same impeccable roasting make it the more relaxed way to experience Miami's best beans.",
    featured_in: ["sprudge", "infatuation"],
    verified: true, last_verified_at: "2024-10-15", verification_source: "admin",
  },
  {
    name: "Eternity Coffee Roasters",
    slug: "eternity-coffee-roasters-miami",
    lat: 25.8163, lng: -80.1956,
    city: "Miami", country: "United States",
    address: "6645 NE 4th Ave, Miami, FL 33138",
    roaster: "Eternity Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "eternitycoffee",
    website: "https://www.eternitycoffeeroasters.com/",
    editorial_blurb: "Miami Shores roastery focused on traceable Colombian and Ethiopian lots — the sourcing program rivals any roastery in the Southeast.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-20", verification_source: "admin",
  },
  {
    name: "Threefold Café",
    slug: "threefold-cafe-coral-gables",
    lat: 25.7489, lng: -80.2735,
    city: "Miami", country: "United States",
    address: "141 Giralda Ave, Coral Gables, FL 33134",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "threefoldcafe",
    website: "https://www.threefoldcafe.com/",
    editorial_blurb: "Australian-style breakfast café in the Gables with a serious espresso program — the Giralda Ave terrace and the avocado toast are both required.",
    featured_in: ["sprudge", "infatuation"],
    verified: true, last_verified_at: "2024-10-08", verification_source: "admin",
  },
  {
    name: "Zak the Baker",
    slug: "zak-the-baker-miami",
    lat: 25.8013, lng: -80.1988,
    city: "Miami", country: "United States",
    address: "405 NW 26th St, Miami, FL 33127",
    roaster: "Panther Coffee",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "zakthebaker",
    website: "https://www.zakthebaker.com/",
    editorial_blurb: "Wynwood Jewish bakery where the sourdough is legendary and Panther Coffee's espresso program gives every loaf the send-off it deserves.",
    featured_in: ["sprudge", "eater"],
    verified: true, last_verified_at: "2024-09-22", verification_source: "admin",
  },
  {
    name: "Vice City Bean",
    slug: "vice-city-bean-miami",
    lat: 25.7780, lng: -80.1934,
    city: "Miami", country: "United States",
    address: "169 SE 1st St, Miami, FL 33131",
    roaster: "Vice City Bean",
    brew_methods: ["espresso", "pour-over", "cold-brew", "aeropress"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "vicecitybean",
    editorial_blurb: "Downtown Miami's specialty anchor serving micro-lot single-origins steps from Brickell — the most serious pour-over program the financial district has ever had.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-15", verification_source: "admin",
  },

  // LOS ANGELES
  {
    name: "Go Get Em Tiger",
    slug: "go-get-em-tiger-larchmont",
    lat: 34.0721, lng: -118.3244,
    city: "Los Angeles", country: "United States",
    address: "230 N Larchmont Blvd, Los Angeles, CA 90004",
    roaster: "Go Get Em Tiger",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "laptop-friendly"],
    instagram_handle: "gogetemtiger",
    website: "https://www.gget.com/",
    editorial_blurb: "LA's most celebrated specialty roaster — the Larchmont flagship serves a textbook filter menu and the most approachable single-origin espresso in the city.",
    featured_in: ["sprudge", "eater", "infatuation"],
    verified: true, last_verified_at: "2024-11-04", verification_source: "admin",
  },
  {
    name: "G&B Coffee",
    slug: "gb-coffee-grand-central-market",
    lat: 34.0521, lng: -118.2490,
    city: "Los Angeles", country: "United States",
    address: "317 S Broadway, Los Angeles, CA 90013",
    roaster: "Go Get Em Tiger",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["standing-bar", "no-laptop", "minimalist"],
    instagram_handle: "gandberla",
    editorial_blurb: "Standing bar inside Grand Central Market — the cult espresso program and the downtown foot traffic make it the most democratic specialty experience in LA.",
    featured_in: ["sprudge", "eater", "ny_times"],
    verified: true, last_verified_at: "2024-10-28", verification_source: "admin",
  },
  {
    name: "Intelligentsia Coffee Venice",
    slug: "intelligentsia-coffee-venice",
    lat: 33.9895, lng: -118.4734,
    city: "Los Angeles", country: "United States",
    address: "1331 Abbot Kinney Blvd, Venice, CA 90291",
    roaster: "Intelligentsia Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "intelligentsiacoffee",
    website: "https://www.intelligentsiacoffee.com/",
    editorial_blurb: "Abbot Kinney's specialty anchor — Intelligentsia's Venice location brought Chicago's third-wave seriousness to the most sun-drenched street in LA.",
    featured_in: ["sprudge", "eater"],
    verified: true, last_verified_at: "2024-10-20", verification_source: "admin",
  },
  {
    name: "Blue Bottle Coffee Arts District",
    slug: "blue-bottle-coffee-arts-district-la",
    lat: 34.0418, lng: -118.2327,
    city: "Los Angeles", country: "United States",
    address: "582 Mateo St, Los Angeles, CA 90013",
    roaster: "Blue Bottle Coffee",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "outdoor-seating"],
    instagram_handle: "bluebottlecoffee",
    website: "https://bluebottlecoffee.com/",
    editorial_blurb: "The Arts District outpost in a converted industrial space — Blue Bottle's LA flagship proves the brand is at its best in spaces with stories.",
    featured_in: ["sprudge", "eater"],
    verified: true, last_verified_at: "2024-10-15", verification_source: "admin",
  },
  {
    name: "Verve Coffee Roasters West Hollywood",
    slug: "verve-coffee-west-hollywood",
    lat: 34.0916, lng: -118.3614,
    city: "Los Angeles", country: "United States",
    address: "8925 Melrose Ave, West Hollywood, CA 90069",
    roaster: "Verve Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "vervecoffee",
    website: "https://www.vervecoffee.com/",
    editorial_blurb: "Santa Cruz's acclaimed roastery on Melrose — the outdoor seating and impeccable filter program make it the most desirable coffee stop in WeHo.",
    featured_in: ["sprudge", "infatuation"],
    verified: true, last_verified_at: "2024-10-25", verification_source: "admin",
  },
  {
    name: "Civil Coffee",
    slug: "civil-coffee-highland-park",
    lat: 34.1149, lng: -118.2050,
    city: "Los Angeles", country: "United States",
    address: "5629 N Figueroa St, Los Angeles, CA 90042",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating", "minimalist"],
    instagram_handle: "civilcoffee",
    editorial_blurb: "Highland Park's specialty anchor — the rotating guest roasters and the neighbourhood regulars make it the best argument for making the drive to the northeast side.",
    featured_in: ["sprudge", "eater"],
    verified: true, last_verified_at: "2024-10-12", verification_source: "admin",
  },
  {
    name: "Cognoscenti Coffee",
    slug: "cognoscenti-coffee-culver-city",
    lat: 34.0173, lng: -118.3907,
    city: "Los Angeles", country: "United States",
    address: "6114 Washington Blvd, Culver City, CA 90232",
    roaster: "Cognoscenti Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "cognoscenticoffee",
    editorial_blurb: "Culver City's pop-culture café with serious coffee roots — the guest roaster program and curated soundtrack pull from the same curatorial instinct.",
    featured_in: ["sprudge", "eater"],
    verified: true, last_verified_at: "2024-09-25", verification_source: "admin",
  },
  {
    name: "Demitasse",
    slug: "demitasse-little-tokyo-la",
    lat: 34.0497, lng: -118.2410,
    city: "Los Angeles", country: "United States",
    address: "135 S San Pedro St, Los Angeles, CA 90012",
    roaster: "Demitasse",
    brew_methods: ["espresso", "pour-over", "cold-brew", "aeropress"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "demitassela",
    website: "https://www.demitasse.com/",
    editorial_blurb: "Little Tokyo specialty roaster with a Japanese-influenced approach to extraction — the black sesame latte is the most copied drink in the LA specialty scene.",
    featured_in: ["sprudge", "infatuation"],
    verified: true, last_verified_at: "2024-10-18", verification_source: "admin",
  },
  {
    name: "Caffe Luxxe",
    slug: "caffe-luxxe-santa-monica",
    lat: 34.0195, lng: -118.4912,
    city: "Los Angeles", country: "United States",
    address: "925 Montana Ave, Santa Monica, CA 90403",
    roaster: "Caffe Luxxe",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "caffeluxxe",
    website: "https://www.caffeluxxe.com/",
    editorial_blurb: "Santa Monica's Italian-method espresso institution — the Synesso pours and the Montana Ave terrace have made this LA's benchmark for old-school technique done right.",
    featured_in: ["sprudge", "infatuation"],
    verified: true, last_verified_at: "2024-10-05", verification_source: "admin",
  },
  {
    name: "Groundwork Coffee",
    slug: "groundwork-coffee-venice",
    lat: 33.9905, lng: -118.4680,
    city: "Los Angeles", country: "United States",
    address: "671 Rose Ave, Venice, CA 90291",
    roaster: "Groundwork Coffee",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "groundworkcoffee",
    website: "https://www.groundworkcoffee.com/",
    editorial_blurb: "LA's original specialty roaster — Groundwork has been sourcing organic, direct-trade beans since before it was trendy, and the Rose Ave café shows the longevity of getting it right.",
    featured_in: ["sprudge", "guardian"],
    verified: true, last_verified_at: "2024-10-10", verification_source: "admin",
  },
  {
    name: "Jones Coffee Roasters",
    slug: "jones-coffee-roasters-pasadena",
    lat: 34.1453, lng: -118.1308,
    city: "Los Angeles", country: "United States",
    address: "537 S Raymond Ave, Pasadena, CA 91105",
    roaster: "Jones Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "laptop-friendly"],
    instagram_handle: "jonescoffeeroasters",
    website: "https://www.jonescoffee.com/",
    editorial_blurb: "Pasadena roastery that has quietly operated at the highest level for over two decades — the single-origin Chemex in the courtyard is the best reason to come to the Eastside.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-20", verification_source: "admin",
  },
  {
    name: "Go Get Em Tiger Los Feliz",
    slug: "go-get-em-tiger-los-feliz",
    lat: 34.1068, lng: -118.2920,
    city: "Los Angeles", country: "United States",
    address: "4630 Hollywood Blvd, Los Angeles, CA 90027",
    roaster: "Go Get Em Tiger",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "gogetemtiger",
    website: "https://www.gget.com/",
    editorial_blurb: "GGET's Hillhurst location with the same obsessive pour-over program and a terrace that captures Los Feliz at its most relaxed.",
    featured_in: ["sprudge", "eater"],
    verified: true, last_verified_at: "2024-10-22", verification_source: "admin",
  },
  {
    name: "Night Owl Coffee",
    slug: "night-owl-coffee-silver-lake",
    lat: 34.0869, lng: -118.2748,
    city: "Los Angeles", country: "United States",
    address: "2802 Sunset Blvd, Los Angeles, CA 90026",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "nightowlcoffeela",
    editorial_blurb: "Silver Lake's late-night specialty option — the rotating guest roasters and the Sunset Strip patio fill a gap no other LA café bothers to cover.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-15", verification_source: "admin",
  },
  {
    name: "Weird Wave Coffee",
    slug: "weird-wave-coffee-boyle-heights",
    lat: 34.0334, lng: -118.2029,
    city: "Los Angeles", country: "United States",
    address: "2118 E Cesar Chavez Ave, Los Angeles, CA 90033",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "weirdwavecoffee",
    editorial_blurb: "Boyle Heights specialty café that has become a genuine neighbourhood institution — the community investment and the guest roaster rotation make it as important as it is delicious.",
    featured_in: ["sprudge", "eater"],
    verified: true, last_verified_at: "2024-10-08", verification_source: "admin",
  },
];
