import type { Cafe } from '@/types';

export const ISTANBUL_RAW_CAFES: Omit<Cafe, 'id' | 'created_at' | 'third_wave_score' | 'overall_rating' | 'review_count' | 'permanently_closed'>[] = [

  // ── ISTANBUL (12) ─────────────────────────────────────────────────────────────
  {
    name: "Kronotrop",
    slug: "kronotrop-istanbul",
    lat: 41.0326, lng: 28.9828,
    city: "Istanbul", country: "Turkey",
    address: "Sıraselviler Cad. 69, Cihangir, 34433 Istanbul",
    roaster: "Kronotrop",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "kronotrop",
    website: "https://kronotrop.com.tr/",
    editorial_blurb: "Istanbul's most respected specialty roaster set in Cihangir's creative hub — the filter coffee here challenges everything you thought you knew about Turkish coffee.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2024-11-04", verification_source: "admin",
  },
  {
    name: "Petra Roasting Co.",
    slug: "petra-roasting-istanbul",
    lat: 41.0233, lng: 28.9748,
    city: "Istanbul", country: "Turkey",
    address: "Kemankeş Karamustafa Paşa Mah., Karaköy, Istanbul",
    roaster: "Petra Roasting Co.",
    brew_methods: ["espresso", "pour-over", "chemex"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "petraroasting",
    editorial_blurb: "Karaköy roastery with Bosphorus views and a bean programme worth navigating Istanbul's hills for — specialty coffee with an unmissable setting.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-15", verification_source: "admin",
  },
  {
    name: "MOC Coffee",
    slug: "moc-coffee-istanbul",
    lat: 41.0472, lng: 28.9944,
    city: "Istanbul", country: "Turkey",
    address: "Abdi İpekçi Cad., Nişantaşı, Istanbul",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "moccoffeetr",
    editorial_blurb: "Japanese-influenced minimalism in Nişantaşı — the focused pour-over menu and quiet interior are the antidote to Istanbul's sensory overload.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-30", verification_source: "admin",
  },
  {
    name: "Brew Lab Istanbul",
    slug: "brew-lab-istanbul",
    lat: 41.0261, lng: 28.9762,
    city: "Istanbul", country: "Turkey",
    address: "Galata, Beyoğlu, 34421 Istanbul",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress", "syphon"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "brewlabistanbul",
    editorial_blurb: "Galata's most technically focused specialty bar — the rotating international guest roaster programme brings the world's best lots to a neighbourhood already full of wonders.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-22", verification_source: "admin",
  },
  {
    name: "Lot Coffee",
    slug: "lot-coffee-istanbul",
    lat: 41.0241, lng: 28.9752,
    city: "Istanbul", country: "Turkey",
    address: "Kemankeş Cad., Karaköy, 34425 Istanbul",
    roaster: "Lot Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "minimalist"],
    instagram_handle: "lotcoffee",
    editorial_blurb: "Karaköy corner roastery where the Bosphorus breeze and the single-origin filter menu make an argument that Istanbul is one of the world's great coffee cities.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-12", verification_source: "admin",
  },
  {
    name: "Norm Coffee",
    slug: "norm-coffee-istanbul",
    lat: 41.0435, lng: 29.0063,
    city: "Istanbul", country: "Turkey",
    address: "Beşiktaş, Istanbul",
    roaster: "Norm Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "normcoffee",
    editorial_blurb: "Beşiktaş specialty roastery built on the conviction that Turkish coffee culture and third-wave precision belong in the same room — and proving it with every batch.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-08", verification_source: "admin",
  },
  {
    name: "Paper Cup",
    slug: "paper-cup-istanbul",
    lat: 41.0331, lng: 28.9813,
    city: "Istanbul", country: "Turkey",
    address: "Cihangir Mah., Beyoğlu, Istanbul",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "papercupist",
    editorial_blurb: "Cihangir neighbourhood café that the local creative community treats as a second living room — the guest roaster espresso is an honest daily ritual.",
    featured_in: ["timeout"],
    verified: false, last_verified_at: "2024-09-20", verification_source: "community",
  },
  {
    name: "GAIA Coffee Roasters",
    slug: "gaia-coffee-kadikoy",
    lat: 40.9904, lng: 29.0241,
    city: "Istanbul", country: "Turkey",
    address: "Moda, Kadıköy, Istanbul",
    roaster: "GAIA Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "gaiacoffeeroasters",
    editorial_blurb: "Kadıköy's leading specialty roastery on the Asian side — GAIA proves the Bosphorus is not a barrier to exceptional coffee, it's just a short ferry ride.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-28", verification_source: "admin",
  },
  {
    name: "Arkaoda",
    slug: "arkaoda-kadikoy",
    lat: 40.9912, lng: 29.0253,
    city: "Istanbul", country: "Turkey",
    address: "Moda Cad. 109, Kadıköy, 34710 Istanbul",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "arkaoda",
    website: "https://www.arkaoda.com/",
    editorial_blurb: "Kadıköy's beloved cultural venue by day serves specialty coffee on a terrace that doubles as the Asian side's most sociable morning spot.",
    featured_in: ["timeout", "guardian"],
    verified: true, last_verified_at: "2024-10-05", verification_source: "admin",
  },
  {
    name: "Coffee Department",
    slug: "coffee-department-istanbul",
    lat: 41.0348, lng: 28.9862,
    city: "Istanbul", country: "Turkey",
    address: "İstiklal Cad., Beyoğlu, Istanbul",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "coffeedeptist",
    editorial_blurb: "İstiklal Street specialty bar that filters out the tourist noise — the single-origin pour-over and standing counter are a deliberate contrast to everything outside the door.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2024-09-15", verification_source: "community",
  },
  {
    name: "Totem Coffee",
    slug: "totem-coffee-istanbul",
    lat: 41.0481, lng: 28.9930,
    city: "Istanbul", country: "Turkey",
    address: "Nişantaşı, Şişli, Istanbul",
    roaster: "Totem Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "totemcoffee",
    editorial_blurb: "Nişantaşı's most polished new-wave espresso bar — precise, spare, and popular with the neighbourhood's fashion and design crowd for exactly those reasons.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2024-09-10", verification_source: "community",
  },
  {
    name: "Nar Kahve",
    slug: "nar-kahve-istanbul",
    lat: 41.0264, lng: 28.9773,
    city: "Istanbul", country: "Turkey",
    address: "Galata, Beyoğlu, Istanbul",
    roaster: "Nar Kahve",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["outdoor-seating", "minimalist"],
    instagram_handle: "narkahve",
    editorial_blurb: "Galata roastery that honours Turkish coffee tradition while running one of the city's best specialty programmes — the only bar in Istanbul where both orders are equally correct.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2024-09-05", verification_source: "community",
  },
];
