import type { Cafe } from '@/types';

export const LATAM_RAW_CAFES: (Omit<Cafe, 'id' | 'created_at' | 'third_wave_score' | 'overall_rating' | 'review_count' | 'permanently_closed'> & { permanently_closed?: boolean })[] = [

  // ── MEXICO CITY (15) ──────────────────────────────────────────────────────────
  {
    name: "Café Nil",
    slug: "cafe-nil-mexico-city",
    lat: 19.4326, lng: -99.1676,
    city: "Mexico City", country: "Mexico",
    address: "Orizaba 101, Roma Norte, 06700 Ciudad de México",
    roaster: "Café Nil",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["outdoor-seating", "minimalist"],
    instagram_handle: "cafenilmx",
    editorial_blurb: "Roma Norte's best-kept secret — Mexican single-origins from Oaxaca and Veracruz brewed with the care they deserve.",
    featured_in: ["sprudge", "infatuation"],
    verified: true, last_verified_at: "2025-09-25", verification_source: "admin",
  },
  {
    name: "Buna Coffee",
    slug: "buna-coffee-mexico-city",
    lat: 19.4284, lng: -99.1607,
    city: "Mexico City", country: "Mexico",
    address: "Tonalá 10, Roma Norte, 06700 Ciudad de México",
    roaster: "Buna",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "bunacoffee",
    website: "https://buna.mx/",
    editorial_blurb: "Ethiopian coffee expertise meets CDMX warmth — the natural processes here taste like nowhere else in the city.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-08-30", verification_source: "community",
  },
  {
    name: "Quentin Café",
    slug: "quentin-cafe-mexico-city",
    lat: 19.4185, lng: -99.1576,
    city: "Mexico City", country: "Mexico",
    address: "Álvaro Obregón 64, Roma Norte, 06700 Ciudad de México",
    roaster: "Quentin Café",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "quentincafemx",
    website: "https://quentin.mx/",
    editorial_blurb: "Veracruz single-origins served from a serious pour-over bar in Roma Norte — the best argument for CDMX's homegrown specialty beans.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-15", verification_source: "admin",
  },
  {
    name: "Toma Café",
    slug: "toma-cafe-cdmx",
    lat: 19.4198, lng: -99.1634,
    city: "Mexico City", country: "Mexico",
    address: "Orizaba 42, Roma Norte, 06700 Ciudad de México",
    roaster: "Toma Café",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "tomacafe",
    website: "https://www.tomacafe.mx/",
    editorial_blurb: "Roma Norte's flagship third-wave destination — Toma's rotating seasonal single-origins and sun-drenched patio have made it CDMX's most beloved specialty stop.",
    featured_in: ["sprudge", "infatuation"],
    verified: true, last_verified_at: "2025-10-20", verification_source: "admin",
  },
  {
    name: "Blend Station",
    slug: "blend-station-roma",
    lat: 19.4162, lng: -99.1606,
    city: "Mexico City", country: "Mexico",
    address: "Álvaro Obregón 286, Roma Norte, 06700 Ciudad de México",
    roaster: "Blend Station",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "blendstation",
    website: "https://blendstation.com.mx/",
    editorial_blurb: "Consistent specialty across multiple Roma locations — the house espresso blend is CDMX commuter coffee done properly.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-09-18", verification_source: "admin",
  },
  {
    name: "Cardinal",
    slug: "cardinal-cafe-cdmx",
    lat: 19.4174, lng: -99.1581,
    city: "Mexico City", country: "Mexico",
    address: "Córdoba 132, Roma Norte, 06700 Ciudad de México",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "casacardinal",
    website: "https://cardinalcoffeehouse.shop/",
    editorial_blurb: "Stripped-back Roma Norte bar focused entirely on the cup — the rotating pour-over menu is the most intellectually serious in the city.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-08", verification_source: "admin",
  },
  {
    name: "Lalo!",
    slug: "lalo-cafe-cdmx",
    lat: 19.4154, lng: -99.1624,
    city: "Mexico City", country: "Mexico",
    address: "Zacatecas 173, Roma Norte, 06700 Ciudad de México",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "eatlalo",
    editorial_blurb: "Roma Norte's most photogenic café — the weekend brunch queue is worth it, and the espresso program keeps pace with the famous food.",
    featured_in: ["infatuation", "timeout"],
    verified: true, last_verified_at: "2025-10-25", verification_source: "admin",
  },
  {
    name: "Cibicafé",
    slug: "cibicafe-condesa",
    lat: 19.4093, lng: -99.1736,
    city: "Mexico City", country: "Mexico",
    address: "Ámsterdam 317, Hipódromo Condesa, 06100 Ciudad de México",
    roaster: "Cibicafé",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "cibicafe",
    editorial_blurb: "Condesa's quiet roastery champion — Mexican terroir takes centre stage in a neighbourhood that rewards those who walk past the chains.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-09-30", verification_source: "admin",
  },
  {
    name: "Café Avellaneda",
    slug: "cafe-avellaneda-coyoacan",
    lat: 19.3513, lng: -99.1616,
    city: "Mexico City", country: "Mexico",
    address: "Higuera 40, Barrio de Santa Catarina, Coyoacán, 04010 Ciudad de México",
    roaster: "Café Avellaneda",
    brew_methods: ["pour-over", "espresso", "syphon", "aeropress"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "minimalist"],
    instagram_handle: "cafeavellaneda",
    website: "https://cafeavellaneda.com/",
    editorial_blurb: "Coyoacán's best argument for leaving Roma for an afternoon — meticulous Oaxacan and Chiapan sourcing in a cobblestone neighbourhood setting.",
    featured_in: ["sprudge", "infatuation"],
    verified: true, last_verified_at: "2025-10-12", verification_source: "admin",
  },
  {
    name: "Tierra Garat",
    slug: "tierra-garat-polanco",
    lat: 19.4340, lng: -99.1991,
    city: "Mexico City", country: "Mexico",
    address: "Virgilio 8, Polanco, 11560 Ciudad de México",
    roaster: "Tierra Garat",
    brew_methods: ["espresso", "pour-over", "cold-brew", "french-press"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "tierragarat",
    website: "https://tierragarat.com.mx/",
    editorial_blurb: "Mexico's most recognised specialty roaster chain with genuine sourcing credentials — the Polanco flagship remains the reference point for the city's coffee scene.",
    featured_in: ["sprudge", "infatuation"],
    verified: true, last_verified_at: "2025-11-01", verification_source: "admin",
  },

  {
    name: "Almanegra Café",
    slug: "almanegra-cafe-cdmx",
    lat: 19.4270, lng: -99.1550,
    city: "Mexico City", country: "Mexico",
    address: "Orizaba 8, Roma Norte, 06700 Ciudad de México",
    roaster: "Almanegra Café",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "almanegracafe",
    website: "https://almanegra.cafe/",
    editorial_blurb: "Roma Norte roastery sourcing exclusively from Mexican producers — Chiapan and Veracruz lots brewed with deliberate, unhurried precision.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Dosis Café",
    slug: "dosis-cafe-cdmx",
    lat: 19.4189, lng: -99.1556,
    city: "Mexico City", country: "Mexico",
    address: "Álvaro Obregón 24, Roma Norte, 06700 Ciudad de México",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "dosiscafe",
    website: "https://www.dosiscafe.com/",
    editorial_blurb: "Roma Norte specialty bar delivering consistently precise espresso to a neighbourhood hungry for it — the rotating pour-over board changes weekly.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Hola Coffee",
    slug: "hola-coffee-condesa",
    lat: 19.4138, lng: -99.1748,
    city: "Mexico City", country: "Mexico",
    address: "Ámsterdam 200, Hipódromo, Condesa, 06100 Ciudad de México",
    roaster: "Hola Coffee",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["outdoor-seating", "minimalist"],
    instagram_handle: "holacoffeemx",
    editorial_blurb: "Condesa corner bar with a cheerful name and a serious approach — the house espresso blend and the shaded terrace are equally satisfying.",
    featured_in: ["infatuation"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Café Punta del Cielo",
    slug: "cafe-punta-del-cielo-polanco",
    lat: 19.4362, lng: -99.1975,
    city: "Mexico City", country: "Mexico",
    address: "Presidente Masaryk 390, Polanco, 11560 Ciudad de México",
    roaster: "Café Punta del Cielo",
    brew_methods: ["espresso", "pour-over", "chemex", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "puntadelcielo",
    website: "https://www.puntadelcielo.com.mx/",
    editorial_blurb: "Mexico's most recognisable specialty chain built around genuine Mexican-origin sourcing — the Polanco flagship shows the brand at its most polished.",
    featured_in: ["infatuation", "timeout"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Café Toscano",
    slug: "cafe-toscano-polanco",
    lat: 19.4358, lng: -99.1915,
    city: "Mexico City", country: "Mexico",
    address: "Temistocles 26, Polanco, 11560 Ciudad de México",
    roaster: "Café Toscano",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "cafetoscanomx",
    website: "https://cafetoscano.shop/",
    editorial_blurb: "Polanco's Italian-influenced specialty bar anchored by strong Mexican sourcing — the morning cortado and the tree-lined terrace are worth making the trip for.",
    featured_in: ["infatuation"],
    verified: true, last_verified_at: "2025-09-01", verification_source: "community",
  },
  {
    name: "Café Avellaneda Roma",
    slug: "cafe-avellaneda-roma",
    lat: 19.4200, lng: -99.1600,
    city: "Mexico City", country: "Mexico",
    address: "Durango 279, Roma Norte, 06700 Ciudad de México",
    roaster: "Café Avellaneda",
    brew_methods: ["pour-over", "espresso", "aeropress", "syphon"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "cafeavellaneda",
    website: "https://cafeavellaneda.com/",
    editorial_blurb: "Café Avellaneda's Roma Norte sister to the Coyoacán original — same meticulous Oaxacan sourcing, now closer to the city's specialty heartland.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2025-09-01", verification_source: "community",
  },
  {
    name: "Boicot Café",
    slug: "boicot-cafe-cdmx",
    lat: 19.4175, lng: -99.1580,
    city: "Mexico City", country: "Mexico",
    address: "Jalapa 99, Roma Norte, 06700 Ciudad de México",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "boicotcafe",
    website: "https://boicotcafe.com/",
    editorial_blurb: "Counter-cultural Roma Norte café that takes its coffee as seriously as its politics — Mexican single-origins served with genuine conviction.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-09-01", verification_source: "community",
  },

  // ── BUENOS AIRES (12) ─────────────────────────────────────────────────────────
  {
    name: "Café Registrado",
    slug: "cafe-registrado-buenos-aires",
    lat: -34.5884, lng: -58.4161,
    city: "Buenos Aires", country: "Argentina",
    address: "Humboldt 1542, C1414 CABA, Buenos Aires",
    roaster: "Café Registrado",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "caferegistrado",
    editorial_blurb: "The café that changed what Buenos Aires understood about coffee — their training program shaped the city's entire specialty scene.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-09-05", verification_source: "admin",
  },
  {
    name: "LAB Tostadores de Café",
    slug: "lab-tostadores-buenos-aires",
    lat: -34.5961, lng: -58.3928,
    city: "Buenos Aires", country: "Argentina",
    address: "Thames 1885, C1414 CABA, Buenos Aires",
    roaster: "LAB Tostadores",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "labtostadores",
    editorial_blurb: "Palermo's most focused roastery café — an ever-changing Colombian single-origin menu and baristas who love to explain the difference.",
    featured_in: ["sprudge", "infatuation"],
    verified: true, last_verified_at: "2025-08-20", verification_source: "community",
  },
  {
    name: "Lattente Coffee Roasters",
    slug: "lattente-coffee-buenos-aires",
    lat: -34.5838, lng: -58.4325,
    city: "Buenos Aires", country: "Argentina",
    address: "Fray Luis Beltrán 1180, Palermo, C1406 CABA, Buenos Aires",
    roaster: "Lattente Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "lattentecoffee",
    editorial_blurb: "Palermo roastery leading Buenos Aires out of the dark-roast era — their direct-trade Ethiopian and Colombian lots are the city's most technically precise.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-15", verification_source: "admin",
  },
  {
    name: "Birkin Coffee Bar",
    slug: "birkin-coffee-buenos-aires",
    lat: -34.5873, lng: -58.4232,
    city: "Buenos Aires", country: "Argentina",
    address: "El Salvador 4618, Palermo Soho, C1414 CABA, Buenos Aires",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "birkincoffeebar",
    editorial_blurb: "Palermo's most design-conscious specialty bar — the rotating guest roaster programme and impeccable milk pours draw a knowing crowd.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-05", verification_source: "admin",
  },
  {
    name: "Tres Monos",
    slug: "tres-monos-buenos-aires",
    lat: -34.5910, lng: -58.4189,
    city: "Buenos Aires", country: "Argentina",
    address: "Thames 878, Palermo, C1414 CABA, Buenos Aires",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "tresmonosbar",
    editorial_blurb: "Better known for cocktails but the daytime coffee programme is equally serious — Palermo's most stylish all-day stop.",
    featured_in: ["infatuation", "timeout"],
    verified: true, last_verified_at: "2025-09-20", verification_source: "admin",
  },
  {
    name: "Café Margot",
    slug: "cafe-margot-boedo",
    lat: -34.6291, lng: -58.4139,
    city: "Buenos Aires", country: "Argentina",
    address: "Av. Boedo 857, Boedo, C1218 CABA, Buenos Aires",
    roaster: "Café Margot",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "cafemargot",
    editorial_blurb: "Classic Boedo corner café that predates the third wave and survived it — the espresso is honest, the chairs are mismatched, and the neighbourhood loves it.",
    featured_in: ["guardian"],
    verified: true, last_verified_at: "2025-09-05", verification_source: "community",
  },

  {
    name: "Ninina Bakery & Café",
    slug: "ninina-bakery-palermo",
    lat: -34.5882, lng: -58.4267,
    city: "Buenos Aires", country: "Argentina",
    address: "Gorriti 4738, Palermo Soho, C1414 CABA, Buenos Aires",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "ninina.bakery",
    editorial_blurb: "Palermo's most beloved pastry café with a coffee programme that keeps pace with the baking — the afternoon flat white and the medialuna are non-negotiable.",
    featured_in: ["infatuation", "timeout"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Coffee Town",
    slug: "coffee-town-buenos-aires",
    lat: -34.5929, lng: -58.4128,
    city: "Buenos Aires", country: "Argentina",
    address: "Gorriti 4596, Palermo, C1414 CABA, Buenos Aires",
    roaster: "Coffee Town",
    brew_methods: ["espresso", "pour-over", "aeropress", "cold-brew"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "coffeetownbsas",
    editorial_blurb: "Palermo specialty roastery where the sourcing notes on the menu are worth reading as carefully as the brew — consistently the most traceable coffee in the neighbourhood.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Crudo Coffee",
    slug: "crudo-coffee-buenos-aires",
    lat: -34.5897, lng: -58.4211,
    city: "Buenos Aires", country: "Argentina",
    address: "Nicaragua 5985, Palermo, C1414 CABA, Buenos Aires",
    roaster: "Crudo Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "minimalist", "no-laptop"],
    instagram_handle: "crudocoffee",
    editorial_blurb: "Uncompromising Palermo roastery where raw material quality is the entire conversation — the anaerobic and natural-process lots here arrive weeks before anyone else has them.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Despuntevicio",
    slug: "despuntevicio-buenos-aires",
    lat: -34.5978, lng: -58.4331,
    city: "Buenos Aires", country: "Argentina",
    address: "Acevedo 302, Villa Crespo, C1414 CABA, Buenos Aires",
    roaster: "Despuntevicio",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "despuntevicio",
    editorial_blurb: "Villa Crespo's artisan roastery café that refuses to compete with anyone — the in-house micro-lots and the slow weekend pace are exactly what specialty was meant to feel like.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Gorilla Café Palermo",
    slug: "gorilla-cafe-palermo",
    lat: -34.5854, lng: -58.4243,
    city: "Buenos Aires", country: "Argentina",
    address: "Fitz Roy 1872, Palermo, C1414 CABA, Buenos Aires",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "gorillacafe_ar",
    editorial_blurb: "Palermo's original specialty anchor that started conversations about coffee quality in Buenos Aires — still busy, still excellent, and still the best patio in the neighbourhood.",
    featured_in: ["sprudge", "infatuation"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Pani Bakery",
    slug: "pani-bakery-buenos-aires",
    lat: -34.5868, lng: -58.4198,
    city: "Buenos Aires", country: "Argentina",
    address: "Av. Santa Fe 2997, Recoleta, C1425 CABA, Buenos Aires",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "panibakery",
    editorial_blurb: "Recoleta's most beautiful bakery café where the sourdough and the espresso programme are taken equally seriously — a Buenos Aires morning essential.",
    featured_in: ["infatuation", "timeout"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },

  // ── SÃO PAULO (15) ────────────────────────────────────────────────────────────
  {
    name: "Guilhotina Coffee",
    slug: "guilhotina-coffee-sao-paulo",
    lat: -23.5630, lng: -46.6920,
    city: "São Paulo", country: "Brazil",
    address: "Rua Harmonia 354, Vila Madalena, São Paulo, SP 05435-000",
    roaster: "Guilhotina Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "guilhotinacoffee",
    editorial_blurb: "Vila Madalena roastery championing Brazilian single-origins — the best argument for why the world should drink more coffee from São Paulo's backyard.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-20", verification_source: "admin",
  },
  {
    name: "Suplicy Cafés Especiais",
    slug: "suplicy-cafes-sao-paulo",
    lat: -23.5715, lng: -46.6628,
    city: "São Paulo", country: "Brazil",
    address: "Al. Lorena 1430, Jardins, São Paulo, SP 01424-001",
    roaster: "Suplicy Cafés Especiais",
    brew_methods: ["espresso", "pour-over", "chemex", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "suplicycafes",
    website: "https://www.suplicy.com.br/",
    editorial_blurb: "Premium Brazilian specialty done with Jardins elegance — the micro-lot menu showcases what makes this country the world's most interesting origin.",
    featured_in: ["sprudge", "infatuation"],
    verified: true, last_verified_at: "2025-10-30", verification_source: "admin",
  },
  {
    name: "Café Três",
    slug: "cafe-tres-sao-paulo",
    lat: -23.5604, lng: -46.6762,
    city: "São Paulo", country: "Brazil",
    address: "Rua Aspicuelta 474, Pinheiros, São Paulo, SP 05433-012",
    roaster: "Café Três",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "cafetres",
    editorial_blurb: "Pinheiros natural-process specialists who source from farms within driving distance — this is Brazilian coffee at its most transparent.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-09-18", verification_source: "admin",
  },
  {
    name: "Coffee Lab",
    slug: "coffee-lab-sao-paulo",
    lat: -23.5604, lng: -46.6830,
    city: "São Paulo", country: "Brazil",
    address: "Rua Fradique Coutinho 1340, Pinheiros, São Paulo, SP 05416-001",
    roaster: "Coffee Lab",
    brew_methods: ["pour-over", "espresso", "syphon", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "coffeelab",
    website: "https://www.coffeelab.com.br/",
    editorial_blurb: "Isabela Raposeiras' Pinheiros laboratory set the bar for Brazilian specialty — her direct sourcing and barista training programme remain the industry reference.",
    featured_in: ["sprudge", "standart", "guardian"],
    verified: true, last_verified_at: "2025-11-05", verification_source: "admin",
  },
  {
    name: "Octávio Café",
    slug: "octavio-cafe-sao-paulo",
    lat: -23.5652, lng: -46.6804,
    city: "São Paulo", country: "Brazil",
    address: "Rua Cardeal Arcoverde 1855, Pinheiros, São Paulo, SP 05407-001",
    roaster: "Octávio Café",
    brew_methods: ["espresso", "pour-over", "cold-brew", "chemex"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "octaviocafe",
    website: "https://www.octaviocafe.com.br/",
    editorial_blurb: "Pinheiros stalwart with a micro-lot programme that's been quietly world-class for a decade — the espresso bar draws SCAA judges on their São Paulo visits.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-28", verification_source: "admin",
  },
  {
    name: "Isso é Café",
    slug: "isso-e-cafe-sao-paulo",
    lat: -23.5622, lng: -46.6891,
    city: "São Paulo", country: "Brazil",
    address: "Rua Girassol 285, Vila Madalena, São Paulo, SP 05433-000",
    roaster: "Isso é Café",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "issouecafe",
    editorial_blurb: "Vila Madalena roastery making the case for Cerrado and Sul de Minas terroir — the most flavour-forward single-origins in the neighbourhood.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-10", verification_source: "admin",
  },
  {
    name: "Orfeu Cafés Especiais",
    slug: "orfeu-cafes-sao-paulo",
    lat: -23.5476, lng: -46.6522,
    city: "São Paulo", country: "Brazil",
    address: "Rua Maranhão 625, Higienópolis, São Paulo, SP 01240-001",
    roaster: "Orfeu Cafés Especiais",
    brew_methods: ["espresso", "pour-over", "french-press", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "orfeucafes",
    editorial_blurb: "Higienópolis' grand café and one of Brazil's most respected roasters — the fazenda-specific lots and shaded terrace make it a mandatory São Paulo stop.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-18", verification_source: "admin",
  },
  {
    name: "Moka Cafés Especiais",
    slug: "moka-cafes-sao-paulo",
    lat: -23.5491, lng: -46.6533,
    city: "São Paulo", country: "Brazil",
    address: "Rua Sergipe 609, Higienópolis, São Paulo, SP 01243-001",
    roaster: "Moka Cafés Especiais",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "mokacafes",
    editorial_blurb: "Higienópolis institution known for meticulous espresso preparation and one of the most loyal neighbourhoods followings in the city.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-09-25", verification_source: "admin",
  },
  {
    name: "Lucca Cafés Especiais",
    slug: "lucca-cafes-sao-paulo",
    lat: -23.5787, lng: -46.6567,
    city: "São Paulo", country: "Brazil",
    address: "Rua Joaquim Antunes 210, Itaim Bibi, São Paulo, SP 05415-001",
    roaster: "Lucca Cafés Especiais",
    brew_methods: ["espresso", "pour-over", "cold-brew", "chemex"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "luccacafes",
    website: "https://www.luccacafes.com.br/",
    editorial_blurb: "Curitiba's best-loved roastery with a polished Itaim Bibi outpost — their Sul de Minas single-origins arrive days off-roast.",
    featured_in: ["sprudge", "infatuation"],
    verified: true, last_verified_at: "2025-10-22", verification_source: "admin",
  },
  {
    name: "Companhia Brasileira de Café",
    slug: "companhia-brasileira-cafe-sp",
    lat: -23.5641, lng: -46.6880,
    city: "São Paulo", country: "Brazil",
    address: "Rua Wisard 551, Vila Madalena, São Paulo, SP 05434-080",
    roaster: "Companhia Brasileira de Café",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "cbcafe",
    editorial_blurb: "Vila Madalena roastery built around the premise that Brazil makes the world's greatest coffee — the evidence is in the cup.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-15", verification_source: "admin",
  },

  {
    name: "O Barista",
    slug: "o-barista-sao-paulo",
    lat: -23.5608, lng: -46.6558,
    city: "São Paulo", country: "Brazil",
    address: "Rua Oscar Freire 413, Jardins, São Paulo, SP 01426-001",
    roaster: "O Barista",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "obaristacafe",
    editorial_blurb: "Jardins specialty bar built by a barista-turned-owner who kept the focus entirely on the craft — the espresso extraction here sets the Jardins standard.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Armazém do Café",
    slug: "armazem-do-cafe-sao-paulo",
    lat: -23.5487, lng: -46.6389,
    city: "São Paulo", country: "Brazil",
    address: "Rua Antônio Carlos 431, Consolação, São Paulo, SP 01309-011",
    roaster: "Armazém do Café",
    brew_methods: ["espresso", "pour-over", "french-press", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "armazemdocafe",
    editorial_blurb: "Consolação warehouse café with decades of sourcing relationships across Minas Gerais — the fazenda-specific lots and the wood-clad interior make this São Paulo's most atmospheric specialty stop.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Unique Coffee Roasters",
    slug: "unique-coffee-roasters-sao-paulo",
    lat: -23.5771, lng: -46.6618,
    city: "São Paulo", country: "Brazil",
    address: "Rua da Consolação 3216, Jardins, São Paulo, SP 01416-001",
    roaster: "Unique Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "minimalist", "no-laptop"],
    instagram_handle: "uniquecoffeeroasters",
    editorial_blurb: "Jardins micro-roastery producing some of Brazil's most technically precise lots — the single-estate Cerrado and Mantiqueira coffees are worth crossing the city for.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Café Passagem",
    slug: "cafe-passagem-sao-paulo",
    lat: -23.5630, lng: -46.6802,
    city: "São Paulo", country: "Brazil",
    address: "Rua Harmonia 465, Vila Madalena, São Paulo, SP 05435-000",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "cafepassagem",
    editorial_blurb: "Vila Madalena passageway café that turns a thoroughfare into a destination — the rotating Brazilian roaster programme is São Paulo's most consistent guest showcase.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Velvet Café",
    slug: "velvet-cafe-sao-paulo",
    lat: -23.5698, lng: -46.6544,
    city: "São Paulo", country: "Brazil",
    address: "Rua Haddock Lobo 1626, Cerqueira César, São Paulo, SP 01414-003",
    roaster: "Velvet Café",
    brew_methods: ["pour-over", "espresso", "aeropress", "chemex"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "velvetcafesp",
    editorial_blurb: "Cerqueira César specialty roastery where Brazilian naturals and washed lots are discussed with the same vocabulary as fine wine — a formative address for the city's coffee culture.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Suplicy Cafés Especiais Vila Olímpia",
    slug: "suplicy-cafes-vila-olimpia",
    lat: -23.5956, lng: -46.6861,
    city: "São Paulo", country: "Brazil",
    address: "Rua Olimpíadas 205, Vila Olímpia, São Paulo, SP 04551-000",
    roaster: "Suplicy Cafés Especiais",
    brew_methods: ["espresso", "pour-over", "chemex", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "suplicycafes",
    website: "https://www.suplicy.com.br/",
    editorial_blurb: "Suplicy's Vila Olímpia outpost serving the financial district with the same Brazilian micro-lot programme as the flagship — the post-meeting espresso here holds up to anything.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2025-09-01", verification_source: "community",
  },

  // ── LIMA (8) ─────────────────────────────────────────────────────────────────
  {
    name: "Tostaduría Bisetti",
    slug: "tostaduria-bisetti-lima",
    lat: -12.0964, lng: -77.0359,
    city: "Lima", country: "Peru",
    address: "Jr. General Mendiburu 1073, Miraflores, Lima",
    roaster: "Tostaduría Bisetti",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "tostaduriabisettioficial",
    editorial_blurb: "Lima's most important roastery — Bisetti built Peru's specialty infrastructure almost single-handedly and still sources the best high-altitude Peruvian lots.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-22", verification_source: "admin",
  },
  {
    name: "Arabica Dispensario",
    slug: "arabica-dispensario-lima",
    lat: -12.1225, lng: -77.0301,
    city: "Lima", country: "Peru",
    address: "Av. Grau 424, Barranco, Lima 15063",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "arabicadispensario",
    editorial_blurb: "Barranco's most thoughtful specialty bar — the curated Peruvian roaster programme showcases a coffee geography the rest of the world is only beginning to discover.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-10", verification_source: "admin",
  },
  {
    name: "Neira Café Lab",
    slug: "neira-cafe-lab-lima",
    lat: -12.1178, lng: -77.0330,
    city: "Lima", country: "Peru",
    address: "Calle Martir Olaya 129, Miraflores, Lima 15074",
    roaster: "Neira Café Lab",
    brew_methods: ["pour-over", "espresso", "syphon"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "neiracafelab",
    editorial_blurb: "Competition pedigree café in Miraflores where altitude and varietal are the entire conversation — Lima's most technically exacting barista bar.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-09-28", verification_source: "admin",
  },
  {
    name: "Puku Puku Café",
    slug: "puku-puku-cafe-lima",
    lat: -12.1155, lng: -77.0349,
    city: "Lima", country: "Peru",
    address: "Av. Larco 1150, Miraflores, Lima 15074",
    roaster: "Puku Puku",
    brew_methods: ["pour-over", "espresso", "aeropress", "chemex"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "pukupukucafe",
    editorial_blurb: "Andean-rooted Miraflores café championing high-altitude Peruvian cultivation — the Cajamarca and Junín lots here taste like the altitude they were grown at.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Arabela Café",
    slug: "arabela-cafe-lima",
    lat: -12.1081, lng: -77.0412,
    city: "Lima", country: "Peru",
    address: "Av. Conquistadores 1005, San Isidro, Lima 15027",
    roaster: "Arabela Café",
    brew_methods: ["espresso", "pour-over", "cold-brew", "aeropress"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "arabelacafe",
    editorial_blurb: "San Isidro's specialty anchor for Lima's business district — the Peruvian single-origin programme and the sidewalk terrace are the neighbourhood's best daytime combination.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Sierra y Selva Café",
    slug: "sierra-y-selva-lima",
    lat: -12.1140, lng: -77.0290,
    city: "Lima", country: "Peru",
    address: "Calle Schell 237, Miraflores, Lima 15074",
    roaster: "Sierra y Selva",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "sierrayselva",
    editorial_blurb: "Mountain-to-jungle sourcing philosophy expressed in Miraflores — the elevation profiles on each bag explain why Peruvian coffee is the world's next great origin.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Tostaduría Bisetti Barranco",
    slug: "tostaduria-bisetti-barranco",
    lat: -12.1450, lng: -77.0196,
    city: "Lima", country: "Peru",
    address: "Pedro de Osma 116, Barranco, Lima 15063",
    roaster: "Tostaduría Bisetti",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "tostaduriabisettioficial",
    editorial_blurb: "Bisetti's Barranco outpost in Lima's arts district — the same benchmark Peruvian sourcing, now with a colonial courtyard and the creative community that it deserves.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-09-01", verification_source: "community",
  },
];
