import type { Cafe } from '@/types';
import { calculateScore } from './scoring';

const rawCafes: Omit<Cafe, 'id' | 'created_at' | 'third_wave_score' | 'overall_rating' | 'review_count' | 'permanently_closed'>[] = [
  // TOKYO (3 cafes)
  {
    name: "Fuglen Tokyo",
    slug: "fuglen-tokyo",
    lat: 35.6696,
    lng: 139.6916,
    city: "Tokyo",
    country: "Japan",
    address: "1-16-11 Tomigaya, Shibuya-ku, Tokyo",
    roaster: "Fuglen Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "no-laptop"],
    google_place_id: "ChIJN1-WT_KLGGARzMPs8sI9WBc",
    instagram_handle: "fuglentokyo",
    website: "https://www.fuglen.com/",
    editorial_blurb: "Oslo's cult café landed in Tokyo and raised the bar for the entire city — order the pour-over and stay for the vintage furniture.",
    featured_in: ["sprudge", "monocle"],
    verified: true,
    last_verified_at: "2024-11-01",
    verification_source: "admin",
  },
  {
    name: "Koffee Mameya",
    slug: "koffee-mameya",
    lat: 35.6654,
    lng: 139.7104,
    city: "Tokyo",
    country: "Japan",
    address: "4-15-3 Jingumae, Shibuya-ku, Tokyo",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso"],
    vibe_tags: ["standing-bar", "minimalist"],
    instagram_handle: "koffee_mameya",
    website: "https://koffee-mameya.com/",
    editorial_blurb: "No menu, no seating — just a barista asking what you want and delivering the precise cup you didn't know you needed.",
    featured_in: ["sprudge", "ny_times"],
    verified: true,
    last_verified_at: "2024-10-15",
    verification_source: "admin",
  },
  {
    name: "Switch Coffee Tokyo",
    slug: "switch-coffee-tokyo",
    lat: 35.6952,
    lng: 139.7049,
    city: "Tokyo",
    country: "Japan",
    address: "Minami-Aoyama 6-6-22, Minato-ku, Tokyo",
    roaster: "Switch Coffee",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "switchcoffeetokyo",
    editorial_blurb: "A quietly confident roastery café in Aoyama where single-origins rotate weekly and the staff genuinely wants to talk about terroir.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-20",
    verification_source: "admin",
  },
  // COPENHAGEN (3 cafes)
  {
    name: "The Coffee Collective",
    slug: "the-coffee-collective-copenhagen",
    lat: 55.6867,
    lng: 12.5611,
    city: "Copenhagen",
    country: "Denmark",
    address: "Jægersborggade 10, 2200 Copenhagen",
    roaster: "The Coffee Collective",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "coffeecollective",
    website: "https://coffeecollective.dk/",
    editorial_blurb: "Copenhagen's gold standard for specialty — their direct-trade relationships and obsessive roasting set the benchmark for Northern Europe.",
    featured_in: ["sprudge", "standart", "monocle"],
    verified: true,
    last_verified_at: "2024-11-10",
    verification_source: "admin",
  },
  {
    name: "Prolog Coffee Bar",
    slug: "prolog-coffee-bar",
    lat: 55.6761,
    lng: 12.5572,
    city: "Copenhagen",
    country: "Denmark",
    address: "Vesterbrogade 76, 1620 Copenhagen",
    roaster: "Prolog",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "standing-bar"],
    instagram_handle: "prologcoffee",
    editorial_blurb: "Vespa and concrete, espresso and natural wine — Prolog made the Copenhagen café look louder and the coffee just as good.",
    featured_in: ["sprudge", "guardian"],
    verified: true,
    last_verified_at: "2024-10-01",
    verification_source: "admin",
  },
  {
    name: "Original Coffee",
    slug: "original-coffee-copenhagen",
    lat: 55.6894,
    lng: 12.5529,
    city: "Copenhagen",
    country: "Denmark",
    address: "Nørrebrogade 23, 2200 Copenhagen",
    roaster: "Original Coffee",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "originalcoffeedk",
    editorial_blurb: "Relaxed, unpretentious, consistently excellent — the kind of neighborhood spot Copenhagen does better than anywhere.",
    featured_in: ["timeout"],
    verified: true,
    last_verified_at: "2024-08-15",
    verification_source: "community",
  },
  // MELBOURNE (3 cafes)
  {
    name: "St Ali",
    slug: "st-ali-melbourne",
    lat: -37.8067,
    lng: 144.9580,
    city: "Melbourne",
    country: "Australia",
    address: "12-18 Yarra Place, South Melbourne VIC 3205",
    roaster: "St Ali",
    brew_methods: ["espresso", "pour-over", "syphon", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "stalicoffee",
    website: "https://stali.com.au/",
    editorial_blurb: "The roastery that helped define Melbourne's coffee identity — still the best introduction to why this city takes coffee so seriously.",
    featured_in: ["sprudge", "guardian", "eater"],
    verified: true,
    last_verified_at: "2024-11-05",
    verification_source: "admin",
  },
  {
    name: "Patricia Coffee Brewers",
    slug: "patricia-coffee-brewers",
    lat: -37.8150,
    lng: 144.9608,
    city: "Melbourne",
    country: "Australia",
    address: "493-495 Little Bourke St, Melbourne VIC 3000",
    roaster: "Multiple roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["standing-bar", "no-laptop"],
    instagram_handle: "patriciacoffeebrewers",
    editorial_blurb: "Standing room only, zero compromise — Patricia runs the tightest espresso program in the CBD and everyone knows it.",
    featured_in: ["sprudge", "timeout"],
    verified: true,
    last_verified_at: "2024-10-20",
    verification_source: "admin",
  },
  {
    name: "Market Lane Coffee",
    slug: "market-lane-coffee",
    lat: -37.8083,
    lng: 144.9702,
    city: "Melbourne",
    country: "Australia",
    address: "Prahran Market, 163 Commercial Rd, Prahran VIC 3181",
    roaster: "Market Lane",
    brew_methods: ["pour-over", "espresso", "aeropress", "french-press"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "marketlanecoffee",
    website: "https://marketlane.com.au/",
    editorial_blurb: "Market-stall origins, world-class roasting — their seasonal single-origins are worth building a Melbourne morning around.",
    featured_in: ["sprudge", "standart"],
    verified: true,
    last_verified_at: "2024-09-30",
    verification_source: "admin",
  },
  // NEW YORK CITY (3 cafes)
  {
    name: "Devoción",
    slug: "devocion-nyc",
    lat: 40.7134,
    lng: -73.9634,
    city: "New York City",
    country: "United States",
    address: "69 Grand St, Brooklyn, NY 11249",
    roaster: "Devoción",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "laptop-friendly"],
    instagram_handle: "devocion",
    website: "https://www.devocion.com/",
    editorial_blurb: "Colombian-owned, Williamsburg-roasted — they ship beans from farm to cup in 10 days, and you can taste the difference.",
    featured_in: ["sprudge", "ny_times", "infatuation"],
    verified: true,
    last_verified_at: "2024-11-08",
    verification_source: "admin",
  },
  {
    name: "Onyx Coffee Lab NYC",
    slug: "onyx-coffee-lab-nyc",
    lat: 40.7282,
    lng: -73.9942,
    city: "New York City",
    country: "United States",
    address: "85 Attorney St, New York, NY 10002",
    roaster: "Onyx Coffee Lab",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "onyxcoffeelab",
    website: "https://onyxcoffeelab.com/",
    editorial_blurb: "Arkansas roasters who conquered NYC — their competition-level pours are approachable enough for a Tuesday morning.",
    featured_in: ["sprudge", "eater"],
    verified: true,
    last_verified_at: "2024-10-12",
    verification_source: "admin",
  },
  {
    name: "Parlor Coffee",
    slug: "parlor-coffee-brooklyn",
    lat: 40.6950,
    lng: -73.9909,
    city: "New York City",
    country: "United States",
    address: "135 Atlantic Ave, Brooklyn, NY 11201",
    roaster: "Parlor Coffee",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "parlorcoffee",
    editorial_blurb: "Tucked inside a Boerum Hill barbershop, Parlor's espresso is worth the detour and the wait for a stool.",
    featured_in: ["sprudge", "ny_times"],
    verified: true,
    last_verified_at: "2024-09-15",
    verification_source: "admin",
  },
  // LONDON (2 cafes)
  {
    name: "Monmouth Coffee",
    slug: "monmouth-coffee-london",
    lat: 51.5125,
    lng: -0.1237,
    city: "London",
    country: "United Kingdom",
    address: "27 Monmouth St, London WC2H 9EU",
    roaster: "Monmouth Coffee",
    brew_methods: ["pour-over", "espresso", "french-press"],
    vibe_tags: ["no-laptop", "outdoor-seating"],
    instagram_handle: "monmouthcoffee",
    website: "https://www.monmouthcoffee.co.uk/",
    editorial_blurb: "London's original specialty institution — the queue outside Borough Market moves fast and the cup at the end is always worth it.",
    featured_in: ["guardian", "timeout", "sprudge"],
    verified: true,
    last_verified_at: "2024-10-30",
    verification_source: "admin",
  },
  {
    name: "Square Mile Coffee Roasters",
    slug: "square-mile-london",
    lat: 51.5224,
    lng: -0.0864,
    city: "London",
    country: "United Kingdom",
    address: "Unit 4.1, The Tea Building, 56 Shoreditch High St, London E1 6JJ",
    roaster: "Square Mile Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "squaremilecoffee",
    website: "https://shop.squaremilecoffee.com/",
    editorial_blurb: "The roastery that trained a generation of London baristas — their Red Brick blend is a daily ritual for good reason.",
    featured_in: ["sprudge", "standart", "guardian"],
    verified: true,
    last_verified_at: "2024-11-02",
    verification_source: "admin",
  },
  // MONTREAL (2 cafes)
  {
    name: "Café Myriade",
    slug: "cafe-myriade-montreal",
    lat: 45.4972,
    lng: -73.5773,
    city: "Montreal",
    country: "Canada",
    address: "1432 Rue Mackay, Montréal, QC H3G 2H7",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "cafemyriade",
    website: "https://cafemyriade.com/",
    editorial_blurb: "Montreal's specialty anchor — consistently excellent espresso and a rotating guest roaster program that keeps regulars coming back.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-10-05",
    verification_source: "admin",
  },
  {
    name: "Dispatch Coffee",
    slug: "dispatch-coffee-montreal",
    lat: 45.5231,
    lng: -73.5790,
    city: "Montreal",
    country: "Canada",
    address: "4231 Rue Saint-Denis, Montréal, QC H2J 2K9",
    roaster: "Dispatch Coffee",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "dispatchcoffee",
    editorial_blurb: "Plateau neighbourhood staple with a serious roasting operation — the natural-process Ethiopians here are among Canada's best.",
    featured_in: ["sprudge", "timeout"],
    verified: true,
    last_verified_at: "2024-09-10",
    verification_source: "community",
  },
  // BERLIN (2 cafes)
  {
    name: "The Barn",
    slug: "the-barn-berlin",
    lat: 52.5289,
    lng: 13.3859,
    city: "Berlin",
    country: "Germany",
    address: "Auguststraße 58, 10119 Berlin",
    roaster: "The Barn",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "thebarnberlin",
    website: "https://thebarn.de/",
    editorial_blurb: "Berlin's most opinionated roaster — they'll tell you which brew method suits your chosen bean, and they'll be right.",
    featured_in: ["sprudge", "monocle", "standart"],
    verified: true,
    last_verified_at: "2024-10-25",
    verification_source: "admin",
  },
  {
    name: "Five Elephant",
    slug: "five-elephant-berlin",
    lat: 52.4994,
    lng: 13.4283,
    city: "Berlin",
    country: "Germany",
    address: "Reichenberger Str. 101, 10999 Berlin",
    roaster: "Five Elephant",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "fiveelephant",
    website: "https://www.fiveelephant.com/",
    editorial_blurb: "Kreuzberg coffee institution — the cheesecake has its own fanbase but the roasting is what put them on the world map.",
    featured_in: ["sprudge", "guardian"],
    verified: true,
    last_verified_at: "2024-10-18",
    verification_source: "admin",
  },
  // MEXICO CITY (2 cafes)
  {
    name: "Café Nil",
    slug: "cafe-nil-mexico-city",
    lat: 19.4326,
    lng: -99.1676,
    city: "Mexico City",
    country: "Mexico",
    address: "Orizaba 101, Roma Norte, 06700 Ciudad de México",
    roaster: "Café Nil",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["outdoor-seating", "minimalist"],
    instagram_handle: "cafenilmx",
    editorial_blurb: "Roma Norte's best-kept secret — Mexican single-origins from Oaxaca and Veracruz brewed with the care they deserve.",
    featured_in: ["sprudge", "infatuation"],
    verified: true,
    last_verified_at: "2024-09-25",
    verification_source: "admin",
  },
  {
    name: "Buna Coffee",
    slug: "buna-coffee-mexico-city",
    lat: 19.4284,
    lng: -99.1607,
    city: "Mexico City",
    country: "Mexico",
    address: "Tonalá 10, Roma Norte, 06700 Ciudad de México",
    roaster: "Buna",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "bunacoffee",
    editorial_blurb: "Ethiopian coffee expertise meets CDMX warmth — the natural processes here taste like nowhere else in the city.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-08-30",
    verification_source: "community",
  },
  // SEOUL (2 cafes)
  {
    name: "Fritz Coffee Company",
    slug: "fritz-coffee-seoul",
    lat: 37.5139,
    lng: 126.9931,
    city: "Seoul",
    country: "South Korea",
    address: "11-5 Mapo-daero 18-gil, Mapo-gu, Seoul",
    roaster: "Fritz Coffee",
    brew_methods: ["pour-over", "espresso", "syphon"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "fritzcoffeecompany",
    website: "https://www.fritzcoffee.co.kr/",
    editorial_blurb: "Seoul's most beloved roastery café — the Saturday morning queue is a pilgrimage and the single-origins justify every minute of it.",
    featured_in: ["sprudge", "standart"],
    verified: true,
    last_verified_at: "2024-11-06",
    verification_source: "admin",
  },
  {
    name: "Namusairo",
    slug: "namusairo-seoul",
    lat: 37.5796,
    lng: 126.9770,
    city: "Seoul",
    country: "South Korea",
    address: "21 Jahamun-ro 5-gil, Jongno-gu, Seoul",
    roaster: "Namusairo",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "namusairo",
    editorial_blurb: "Tucked in Bukchon Hanok Village, Namusairo pairs traditional architecture with technically immaculate pour-overs — a rare combination.",
    featured_in: ["sprudge", "monocle"],
    verified: true,
    last_verified_at: "2024-10-08",
    verification_source: "admin",
  },
  // CAPE TOWN (2 cafes)
  {
    name: "Truth Coffee Roasting",
    slug: "truth-coffee-cape-town",
    lat: -33.9249,
    lng: 18.4241,
    city: "Cape Town",
    country: "South Africa",
    address: "36 Buitenkant St, Cape Town City Centre, 8001",
    roaster: "Truth Coffee",
    brew_methods: ["espresso", "pour-over", "syphon", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "truthcoffee",
    website: "https://www.truthcoffee.com/",
    editorial_blurb: "Steampunk décor, serious roasting — Truth earned 'world's best coffee shop' headlines and still delivers on the hype.",
    featured_in: ["sprudge", "guardian", "timeout"],
    verified: true,
    last_verified_at: "2024-10-22",
    verification_source: "admin",
  },
  {
    name: "Origin Coffee Roasting",
    slug: "origin-coffee-cape-town",
    lat: -33.9173,
    lng: 18.4234,
    city: "Cape Town",
    country: "South Africa",
    address: "28 Hudson St, De Waterkant, Cape Town, 8001",
    roaster: "Origin Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "origincoffeeroasting",
    editorial_blurb: "Pan-African sourcing done right — Origin's direct relationships with East African farmers show up in every cup.",
    featured_in: ["sprudge", "standart"],
    verified: true,
    last_verified_at: "2024-09-18",
    verification_source: "admin",
  },
  // BUENOS AIRES (2 cafes)
  {
    name: "Café Registrado",
    slug: "cafe-registrado-buenos-aires",
    lat: -34.5884,
    lng: -58.4161,
    city: "Buenos Aires",
    country: "Argentina",
    address: "Humboldt 1542, C1414 CABA, Buenos Aires",
    roaster: "Café Registrado",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "caferegistrado",
    editorial_blurb: "The café that changed what Buenos Aires understood about coffee — their training program shaped the city's entire specialty scene.",
    featured_in: ["sprudge"],
    verified: true,
    last_verified_at: "2024-09-05",
    verification_source: "admin",
  },
  {
    name: "LAB Tostadores de Café",
    slug: "lab-tostadores-buenos-aires",
    lat: -34.5961,
    lng: -58.3928,
    city: "Buenos Aires",
    country: "Argentina",
    address: "Thames 1885, C1414 CABA, Buenos Aires",
    roaster: "LAB Tostadores",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "labtostadores",
    editorial_blurb: "Palermo's most focused roastery café — an ever-changing Colombian single-origin menu and baristas who love to explain the difference.",
    featured_in: ["sprudge", "infatuation"],
    verified: true,
    last_verified_at: "2024-08-20",
    verification_source: "community",
  },
  // PORTLAND, OR (2 cafes)
  {
    name: "Stumptown Coffee Roasters",
    slug: "stumptown-portland",
    lat: 45.5143,
    lng: -122.6545,
    city: "Portland",
    country: "United States",
    address: "4525 SE Division St, Portland, OR 97206",
    roaster: "Stumptown Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "french-press", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "stumptowncoffee",
    website: "https://www.stumptowncoffee.com/",
    editorial_blurb: "The roastery that launched Portland's coffee revolution — the original Division location still feels like the center of something important.",
    featured_in: ["sprudge", "ny_times", "eater"],
    verified: true,
    last_verified_at: "2024-10-28",
    verification_source: "admin",
  },
  {
    name: "Water Avenue Coffee",
    slug: "water-avenue-coffee-portland",
    lat: 45.5168,
    lng: -122.6649,
    city: "Portland",
    country: "United States",
    address: "1028 SE Water Ave, Portland, OR 97214",
    roaster: "Water Avenue Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "wateravenuecoffee",
    website: "https://wateravenuecoffee.com/",
    editorial_blurb: "Eastside Portland's precision roastery — their long extraction pour-overs and obsessive sourcing make the Hawthorne Bridge detour worthwhile.",
    featured_in: ["sprudge", "guardian"],
    verified: true,
    last_verified_at: "2024-10-10",
    verification_source: "admin",
  },
];

export const SEED_CAFES: Cafe[] = rawCafes.map((cafe, index) => {
  const scoreBreakdown = calculateScore({
    roaster: cafe.roaster,
    brew_methods: cafe.brew_methods,
    vibe_tags: cafe.vibe_tags,
    featured_in: cafe.featured_in,
    community_upvotes: Math.floor(Math.random() * 8),
  });
  return {
    ...cafe,
    id: `cafe-${index + 1}`,
    created_at: new Date().toISOString(),
    third_wave_score: scoreBreakdown.total,
    overall_rating: 4.2 + Math.random() * 0.7,
    review_count: 50 + Math.floor(Math.random() * 200),
    permanently_closed: false,
    flagged: false,
    sponsored: false,
  };
});

export const SEED_CITIES = [
  { id: 'city-1', name: 'Tokyo', country: 'Japan', lat: 35.6762, lng: 139.6503, slug: 'tokyo', cafe_count: 3, city_blurb: 'Tokyo has elevated coffee into an art form — precision brewing, flawless service, and a density of world-class cafés that rivals any city on earth.' },
  { id: 'city-2', name: 'Copenhagen', country: 'Denmark', lat: 55.6761, lng: 12.5683, slug: 'copenhagen', cafe_count: 3, city_blurb: 'Scandinavia\'s coffee capital leads Europe on sourcing ethics and light-roast technique — every cup here feels considered.' },
  { id: 'city-3', name: 'Melbourne', country: 'Australia', lat: -37.8136, lng: 144.9631, slug: 'melbourne', cafe_count: 3, city_blurb: 'Melbourne\'s café culture is a civic institution — world-class flat whites and a roasting scene that exports talent globally.' },
  { id: 'city-4', name: 'New York City', country: 'United States', lat: 40.7128, lng: -74.0060, slug: 'new-york-city', cafe_count: 3, city_blurb: 'New York\'s specialty coffee scene is borough-by-borough diverse — Brooklyn leads on craft, Manhattan on volume, and the competition makes everyone better.' },
  { id: 'city-5', name: 'London', country: 'United Kingdom', lat: 51.5074, lng: -0.1278, slug: 'london', cafe_count: 2, city_blurb: 'London transformed from espresso-resistant to one of the world\'s most exciting coffee cities in a single decade — the east side is still the epicenter.' },
  { id: 'city-6', name: 'Montreal', country: 'Canada', lat: 45.5017, lng: -73.5673, slug: 'montreal', cafe_count: 2, city_blurb: 'Montreal\'s bilingual café culture and Québécois identity produce some of North America\'s most distinctive specialty shops.' },
  { id: 'city-7', name: 'Berlin', country: 'Germany', lat: 52.5200, lng: 13.4050, slug: 'berlin', cafe_count: 2, city_blurb: 'Berlin\'s third wave arrived with characteristic intensity — precise roasting, opinionated baristas, and spaces that double as cultural institutions.' },
  { id: 'city-8', name: 'Mexico City', country: 'Mexico', lat: 19.4326, lng: -99.1332, slug: 'mexico-city', cafe_count: 2, city_blurb: 'CDMX is rewriting what Mexican coffee means — local Oaxacan and Veracruz single-origins are finally getting the treatment they deserve.' },
  { id: 'city-9', name: 'Seoul', country: 'South Korea', lat: 37.5665, lng: 126.9780, slug: 'seoul', cafe_count: 2, city_blurb: 'Seoul\'s café density is unmatched anywhere — specialty coffee thrives alongside traditional tea culture and the aesthetics are always exceptional.' },
  { id: 'city-10', name: 'Cape Town', country: 'South Africa', lat: -33.9249, lng: 18.4241, slug: 'cape-town', cafe_count: 2, city_blurb: 'Cape Town\'s proximity to East African origins gives it an unfair advantage — roasters here work with some of the freshest beans on earth.' },
  { id: 'city-11', name: 'Buenos Aires', country: 'Argentina', lat: -34.6037, lng: -58.3816, slug: 'buenos-aires', cafe_count: 2, city_blurb: 'Buenos Aires is in the middle of a specialty coffee awakening — Palermo\'s independent roasteries are making the city\'s traditional café culture look again.' },
  { id: 'city-12', name: 'Portland', country: 'United States', lat: 45.5051, lng: -122.6750, slug: 'portland', cafe_count: 2, city_blurb: 'Portland\'s coffee heritage runs deep — this is where the American third wave started, and the roasting culture it built still sets global standards.' },
];
