import type { Cafe } from '@/types';

export const AFRICA_RAW_CAFES: Omit<Cafe, 'id' | 'created_at' | 'third_wave_score' | 'overall_rating' | 'review_count' | 'permanently_closed'>[] = [

  // ── CAPE TOWN (12) ────────────────────────────────────────────────────────────
  {
    name: "Truth Coffee Roasting",
    slug: "truth-coffee-cape-town",
    lat: -33.9249, lng: 18.4241,
    city: "Cape Town", country: "South Africa",
    address: "36 Buitenkant St, Cape Town City Centre, 8001",
    roaster: "Truth Coffee",
    brew_methods: ["espresso", "pour-over", "syphon", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "truthcoffee",
    website: "https://www.truthcoffee.com/",
    editorial_blurb: "Steampunk décor, serious roasting — Truth earned 'world's best coffee shop' headlines and still delivers on the hype.",
    featured_in: ["sprudge", "guardian", "timeout"],
    verified: true, last_verified_at: "2024-10-22", verification_source: "admin",
  },
  {
    name: "Origin Coffee Roasting",
    slug: "origin-coffee-cape-town",
    lat: -33.9173, lng: 18.4234,
    city: "Cape Town", country: "South Africa",
    address: "28 Hudson St, De Waterkant, Cape Town, 8001",
    roaster: "Origin Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "origincoffeeroasting",
    editorial_blurb: "Pan-African sourcing done right — Origin's direct relationships with East African farmers show up in every cup.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2024-09-18", verification_source: "admin",
  },
  {
    name: "Rosetta Roastery",
    slug: "rosetta-roastery-cape-town",
    lat: -33.9361, lng: 18.4148,
    city: "Cape Town", country: "South Africa",
    address: "8 Kloof Nek Rd, Gardens, Cape Town, 8001",
    roaster: "Rosetta Roastery",
    brew_methods: ["espresso", "pour-over", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "rosettaroastery",
    website: "https://www.rosettaroastery.com/",
    editorial_blurb: "Cape Town's most beloved neighbourhood roastery — Kloof Street locals and travelling coffee professionals queue side by side for the same exceptional cup.",
    featured_in: ["sprudge", "standart", "guardian"],
    verified: true, last_verified_at: "2024-10-30", verification_source: "admin",
  },
  {
    name: "Deluxe Coffeeworks",
    slug: "deluxe-coffeeworks-cape-town",
    lat: -33.9240, lng: 18.4212,
    city: "Cape Town", country: "South Africa",
    address: "19 Church Square, Cape Town City Centre, 8001",
    roaster: "Deluxe Coffeeworks",
    brew_methods: ["espresso", "pour-over", "chemex"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "deluxecoffeeworks",
    website: "https://www.deluxecoffeeworks.com/",
    editorial_blurb: "Church Square CBD institution — Deluxe introduced Cape Town's office crowd to what espresso was supposed to taste like and never let standards slip.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2024-10-12", verification_source: "admin",
  },
  {
    name: "Espresso Lab Microroasters",
    slug: "espresso-lab-cape-town",
    lat: -33.9282, lng: 18.4411,
    city: "Cape Town", country: "South Africa",
    address: "Old Biscuit Mill, 373-375 Albert Rd, Woodstock, 7915",
    roaster: "Espresso Lab",
    brew_methods: ["espresso", "pour-over", "syphon", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "espressolabza",
    website: "https://www.espressolab.co.za/",
    editorial_blurb: "Woodstock's Old Biscuit Mill showpiece — the Saturday market crowd and the serious coffee traveller find equal satisfaction in the same roastery space.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2024-10-25", verification_source: "admin",
  },
  {
    name: "Tribe Coffee",
    slug: "tribe-coffee-cape-town",
    lat: -33.9274, lng: 18.4437,
    city: "Cape Town", country: "South Africa",
    address: "Woodstock Exchange, 66 Albert Rd, Woodstock, 7925",
    roaster: "Tribe Coffee",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "tribecoffeeroasters",
    website: "https://www.tribecoffee.co.za/",
    editorial_blurb: "Woodstock roastery run by barista champions who turned competition technique into everyday practice — the most technically consistent cup in Cape Town.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-08", verification_source: "admin",
  },
  {
    name: "Father Coffee",
    slug: "father-coffee-cape-town",
    lat: -33.9152, lng: 18.4148,
    city: "Cape Town", country: "South Africa",
    address: "133 Bree St, Cape Town City Centre, 8001",
    roaster: "Father Coffee",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "fathercoffee",
    editorial_blurb: "Bree Street's most focused espresso bar — stripped back to just the coffee, served by people who know exactly what they're doing.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2024-09-28", verification_source: "admin",
  },
  {
    name: "Bootlegger Coffee Company",
    slug: "bootlegger-coffee-cape-town",
    lat: -33.9112, lng: 18.4056,
    city: "Cape Town", country: "South Africa",
    address: "Regent Rd, Sea Point, Cape Town, 8060",
    roaster: "Bootlegger Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "bootleggercoffee",
    website: "https://www.bootleggercoffee.com/",
    editorial_blurb: "Sea Point fixture with a loyal neighbourhood following — not the purist destination but the most reliably enjoyable daily coffee stop on the Atlantic Seaboard.",
    featured_in: ["timeout"],
    verified: true, last_verified_at: "2024-09-15", verification_source: "admin",
  },
  {
    name: "TriBeCa Coffee",
    slug: "tribeca-coffee-cape-town",
    lat: -33.9348, lng: 18.4139,
    city: "Cape Town", country: "South Africa",
    address: "11 Kloof St, Gardens, Cape Town, 8001",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "tribecacoffeect",
    editorial_blurb: "Kloof Street all-day café that works harder than most — the pour-over programme rotates monthly and the patio is Cape Town's best working terrace.",
    featured_in: ["timeout"],
    verified: false, last_verified_at: "2024-09-10", verification_source: "community",
  },
  {
    name: "Haas Coffee Collective",
    slug: "haas-coffee-cape-town",
    lat: -33.9200, lng: 18.4183,
    city: "Cape Town", country: "South Africa",
    address: "38 Wale St, Cape Town City Centre, 8001",
    roaster: "Haas Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "haascoffee",
    editorial_blurb: "City Bowl specialty collective with a rotating guest roster and a loyal following of baristas, designers, and coffee professionals — one of Cape Town's best-kept secrets.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2024-09-05", verification_source: "community",
  },
  {
    name: "Honest Chocolate Café",
    slug: "honest-chocolate-cape-town",
    lat: -33.9233, lng: 18.4170,
    city: "Cape Town", country: "South Africa",
    address: "64A Wale St, Cape Town City Centre, 8001",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "honestchocolate",
    website: "https://www.honestchocolate.co.za/",
    editorial_blurb: "Bean-to-bar chocolate meets third-wave coffee on Wale Street — a pairing Cape Town made look effortless, with espresso that holds its own against the famous product.",
    featured_in: ["guardian", "timeout"],
    verified: true, last_verified_at: "2024-10-18", verification_source: "admin",
  },
  {
    name: "HQ Coffee",
    slug: "hq-coffee-cape-town",
    lat: -33.9252, lng: 18.4248,
    city: "Cape Town", country: "South Africa",
    address: "55 Church St, Cape Town City Centre, 8001",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "chemex"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "hqcoffeect",
    editorial_blurb: "Central Church Street café built for the serious coffee drinker — rotating guest roasters, methodical extraction, no shortcuts.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2024-08-28", verification_source: "community",
  },

  // ── NAIROBI (11) ──────────────────────────────────────────────────────────────
  {
    name: "Nairobi Coffee Exchange",
    slug: "nairobi-coffee-exchange",
    lat: -1.2836, lng: 36.8214,
    city: "Nairobi", country: "Kenya",
    address: "Mama Ngina St, Nairobi CBD, Nairobi",
    roaster: "Nairobi Coffee Exchange",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "nairobicoffeeexchange",
    editorial_blurb: "Origin-focused CBD café serving single-farm Kenyan lots you simply cannot find anywhere else — drinking here is a direct line to the source.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-11-01", verification_source: "admin",
  },
  {
    name: "Kikao Coffee",
    slug: "kikao-coffee-nairobi",
    lat: -1.2636, lng: 36.8008,
    city: "Nairobi", country: "Kenya",
    address: "Westlands, Nairobi",
    roaster: "Kikao Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "kikaocoffee",
    editorial_blurb: "East Africa's specialty pioneer with a Westlands roastery proving that great Kenyan coffee belongs in the cup, not the export container.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-12", verification_source: "admin",
  },
  {
    name: "Dormans Coffee",
    slug: "dormans-coffee-nairobi",
    lat: -1.3244, lng: 36.7139,
    city: "Nairobi", country: "Kenya",
    address: "Karen Shopping Centre, Karen, Nairobi",
    roaster: "Dormans Coffee",
    brew_methods: ["espresso", "pour-over", "french-press"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "dormanscoffee",
    website: "https://www.dormanscoffee.co.ke/",
    editorial_blurb: "Kenya's historic roaster reborn as a specialty champion — Karen flagship is the most reliable place in the city for traceable Kenyan lots.",
    featured_in: ["sprudge", "guardian"],
    verified: true, last_verified_at: "2024-10-05", verification_source: "admin",
  },
  {
    name: "42 Degrees Coffee",
    slug: "42-degrees-nairobi",
    lat: -1.2658, lng: 36.8022,
    city: "Nairobi", country: "Kenya",
    address: "Westlands, Nairobi",
    roaster: "42 Degrees Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "42degreescoffee",
    editorial_blurb: "Westlands specialty roastery named for coffee's ideal bloom temperature — the single-origin Kenyan programme is the most precise in the city.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-20", verification_source: "admin",
  },
  {
    name: "Brew Bistro & Lounge",
    slug: "brew-bistro-nairobi",
    lat: -1.2908, lng: 36.7826,
    city: "Nairobi", country: "Kenya",
    address: "Kilimani, Nairobi",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "brewbistro_ke",
    editorial_blurb: "Kilimani's specialty coffee anchor doubling as a craft cocktail bar — the daytime pour-over programme is every bit as serious as the evening menu.",
    featured_in: ["timeout"],
    verified: true, last_verified_at: "2024-10-08", verification_source: "admin",
  },
  {
    name: "Karo Coffee",
    slug: "karo-coffee-nairobi",
    lat: -1.2844, lng: 36.7847,
    city: "Nairobi", country: "Kenya",
    address: "Kilimani Rd, Kilimani, Nairobi",
    roaster: "Karo Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "karocoffee",
    editorial_blurb: "Small-batch Kilimani roastery sourcing exclusively from farms within 200 km — the traceability here is unmatched in East Africa's café scene.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-25", verification_source: "admin",
  },
  {
    name: "Cultured Roots Coffee",
    slug: "cultured-roots-nairobi",
    lat: -1.2628, lng: 36.7993,
    city: "Nairobi", country: "Kenya",
    address: "Westlands Ave, Westlands, Nairobi",
    roaster: "Cultured Roots Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "culturedrootscoffee",
    editorial_blurb: "Westlands roastery championing smallholder Kenyan farmers by name — the most compelling proof that traceability and great flavour travel together.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2024-09-18", verification_source: "community",
  },
  {
    name: "Jiko Coffee",
    slug: "jiko-coffee-nairobi",
    lat: -1.2780, lng: 36.8156,
    city: "Nairobi", country: "Kenya",
    address: "Upper Hill, Nairobi",
    roaster: "Jiko Coffee",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "jikocoffee",
    editorial_blurb: "Upper Hill specialty bar where Nairobi's finance crowd discovered what single-origin Kenyan AA really tastes like — and converted almost immediately.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2024-09-12", verification_source: "community",
  },
];
