import type { Cafe } from '@/types';

export const LATAM_RAW_CAFES: Omit<Cafe, 'id' | 'created_at' | 'third_wave_score' | 'overall_rating' | 'review_count' | 'permanently_closed'>[] = [

  // ── MEXICO CITY (15) ──────────────────────────────────────────────────────────
  {
    name: "Café Nil",
    slug: "cafe-nil-mexico-city",
    lat: 19.4326, lng: -99.1676,
    city: "Mexico City", country: "Mexico",
    address: "Orizaba 101, Roma Norte, 06700 Ciudad de México",
    roaster: "Café Nil",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["outdoor-seating", "minimalist"],
    instagram_handle: "cafenilmx",
    editorial_blurb: "Roma Norte's best-kept secret — Mexican single-origins from Oaxaca and Veracruz brewed with the care they deserve.",
    featured_in: ["sprudge", "infatuation"],
    verified: true, last_verified_at: "2024-09-25", verification_source: "admin",
  },
  {
    name: "Buna Coffee",
    slug: "buna-coffee-mexico-city",
    lat: 19.4284, lng: -99.1607,
    city: "Mexico City", country: "Mexico",
    address: "Tonalá 10, Roma Norte, 06700 Ciudad de México",
    roaster: "Buna",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "bunacoffee",
    editorial_blurb: "Ethiopian coffee expertise meets CDMX warmth — the natural processes here taste like nowhere else in the city.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-08-30", verification_source: "community",
  },
  {
    name: "Quentin Café",
    slug: "quentin-cafe-mexico-city",
    lat: 19.4017, lng: -99.1696,
    city: "Mexico City", country: "Mexico",
    address: "Insurgentes Sur 811, Colonia Nápoles, 03810 Ciudad de México",
    roaster: "Quentin Café",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "quentincafe",
    editorial_blurb: "Veracruz single-origins served from a serious pour-over bar in Nápoles — the best argument for CDMX's homegrown specialty beans.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-15", verification_source: "admin",
  },
  {
    name: "Toma Café",
    slug: "toma-cafe-cdmx",
    lat: 19.4198, lng: -99.1634,
    city: "Mexico City", country: "Mexico",
    address: "Orizaba 42, Roma Norte, 06700 Ciudad de México",
    roaster: "Toma Café",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "tomacafe",
    website: "https://www.tomacafe.mx/",
    editorial_blurb: "Roma Norte's flagship third-wave destination — Toma's rotating seasonal single-origins and sun-drenched patio have made it CDMX's most beloved specialty stop.",
    featured_in: ["sprudge", "infatuation"],
    verified: true, last_verified_at: "2024-10-20", verification_source: "admin",
  },
  {
    name: "Blend Station",
    slug: "blend-station-roma",
    lat: 19.4162, lng: -99.1606,
    city: "Mexico City", country: "Mexico",
    address: "Álvaro Obregón 286, Roma Norte, 06700 Ciudad de México",
    roaster: "Blend Station",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "blendstation",
    editorial_blurb: "Consistent specialty across multiple Roma locations — the house espresso blend is CDMX commuter coffee done properly.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-18", verification_source: "admin",
  },
  {
    name: "Cardinal",
    slug: "cardinal-cafe-cdmx",
    lat: 19.4192, lng: -99.1613,
    city: "Mexico City", country: "Mexico",
    address: "Querétaro 230, Roma Norte, 06700 Ciudad de México",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "cardinal.cdmx",
    editorial_blurb: "Stripped-back Roma Norte bar focused entirely on the cup — the rotating pour-over menu is the most intellectually serious in the city.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-08", verification_source: "admin",
  },
  {
    name: "Lalo!",
    slug: "lalo-cafe-cdmx",
    lat: 19.4212, lng: -99.1588,
    city: "Mexico City", country: "Mexico",
    address: "Zitácuaro 22, Roma Norte, 06700 Ciudad de México",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "lalo_cdmx",
    editorial_blurb: "Roma Norte's most photogenic café — the weekend brunch queue is worth it, and the espresso program keeps pace with the famous food.",
    featured_in: ["infatuation", "timeout"],
    verified: true, last_verified_at: "2024-10-25", verification_source: "admin",
  },
  {
    name: "Cibicafé",
    slug: "cibicafe-condesa",
    lat: 19.4093, lng: -99.1736,
    city: "Mexico City", country: "Mexico",
    address: "Ámsterdam 317, Hipódromo Condesa, 06100 Ciudad de México",
    roaster: "Cibicafé",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "cibicafe",
    editorial_blurb: "Condesa's quiet roastery champion — Mexican terroir takes centre stage in a neighbourhood that rewards those who walk past the chains.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-30", verification_source: "admin",
  },
  {
    name: "Café Avellaneda",
    slug: "cafe-avellaneda-coyoacan",
    lat: 19.3513, lng: -99.1616,
    city: "Mexico City", country: "Mexico",
    address: "Higuera 40, Barrio de Santa Catarina, Coyoacán, 04010 Ciudad de México",
    roaster: "Café Avellaneda",
    brew_methods: ["pour-over", "espresso", "syphon", "aeropress"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "minimalist"],
    instagram_handle: "cafeavellaneda",
    editorial_blurb: "Coyoacán's best argument for leaving Roma for an afternoon — meticulous Oaxacan and Chiapan sourcing in a cobblestone neighbourhood setting.",
    featured_in: ["sprudge", "infatuation"],
    verified: true, last_verified_at: "2024-10-12", verification_source: "admin",
  },
  {
    name: "Tierra Garat",
    slug: "tierra-garat-polanco",
    lat: 19.4340, lng: -99.1991,
    city: "Mexico City", country: "Mexico",
    address: "Virgilio 8, Polanco, 11560 Ciudad de México",
    roaster: "Tierra Garat",
    brew_methods: ["espresso", "pour-over", "cold-brew", "french-press"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "tierragarat",
    website: "https://www.tierragarat.com.mx/",
    editorial_blurb: "Mexico's most recognised specialty roaster chain with genuine sourcing credentials — the Polanco flagship remains the reference point for the city's coffee scene.",
    featured_in: ["sprudge", "infatuation"],
    verified: true, last_verified_at: "2024-11-01", verification_source: "admin",
  },
  {
    name: "Passmar",
    slug: "passmar-cafe-cdmx",
    lat: 19.4186, lng: -99.1647,
    city: "Mexico City", country: "Mexico",
    address: "Orizaba 161, Roma Norte, 06700 Ciudad de México",
    roaster: "Passmar",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "passmarcafe",
    editorial_blurb: "Tiny Roma Norte bar with outsized ambition — single-origin pour-overs and espresso served with the precision of a much larger operation.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2024-09-10", verification_source: "community",
  },
  {
    name: "Onze Café",
    slug: "onze-cafe-condesa",
    lat: 19.4108, lng: -99.1712,
    city: "Mexico City", country: "Mexico",
    address: "Sonora 171, Hipódromo, Condesa, 06100 Ciudad de México",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "oncecafe",
    editorial_blurb: "Condesa corner café that earns loyalty through consistency — the afternoon cortado on the terrace is a CDMX ritual worth adopting.",
    featured_in: ["timeout"],
    verified: false, last_verified_at: "2024-08-15", verification_source: "community",
  },

  // ── BUENOS AIRES (12) ─────────────────────────────────────────────────────────
  {
    name: "Café Registrado",
    slug: "cafe-registrado-buenos-aires",
    lat: -34.5884, lng: -58.4161,
    city: "Buenos Aires", country: "Argentina",
    address: "Humboldt 1542, C1414 CABA, Buenos Aires",
    roaster: "Café Registrado",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "caferegistrado",
    editorial_blurb: "The café that changed what Buenos Aires understood about coffee — their training program shaped the city's entire specialty scene.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-05", verification_source: "admin",
  },
  {
    name: "LAB Tostadores de Café",
    slug: "lab-tostadores-buenos-aires",
    lat: -34.5961, lng: -58.3928,
    city: "Buenos Aires", country: "Argentina",
    address: "Thames 1885, C1414 CABA, Buenos Aires",
    roaster: "LAB Tostadores",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "labtostadores",
    editorial_blurb: "Palermo's most focused roastery café — an ever-changing Colombian single-origin menu and baristas who love to explain the difference.",
    featured_in: ["sprudge", "infatuation"],
    verified: true, last_verified_at: "2024-08-20", verification_source: "community",
  },
  {
    name: "Lattente Coffee Roasters",
    slug: "lattente-coffee-buenos-aires",
    lat: -34.5838, lng: -58.4325,
    city: "Buenos Aires", country: "Argentina",
    address: "Fray Luis Beltrán 1180, Palermo, C1406 CABA, Buenos Aires",
    roaster: "Lattente Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "lattentecoffee",
    editorial_blurb: "Palermo roastery leading Buenos Aires out of the dark-roast era — their direct-trade Ethiopian and Colombian lots are the city's most technically precise.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-15", verification_source: "admin",
  },
  {
    name: "Birkin Coffee Bar",
    slug: "birkin-coffee-buenos-aires",
    lat: -34.5873, lng: -58.4232,
    city: "Buenos Aires", country: "Argentina",
    address: "El Salvador 4618, Palermo Soho, C1414 CABA, Buenos Aires",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "birkincoffeebar",
    editorial_blurb: "Palermo's most design-conscious specialty bar — the rotating guest roaster programme and impeccable milk pours draw a knowing crowd.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-05", verification_source: "admin",
  },
  {
    name: "Tres Monos",
    slug: "tres-monos-buenos-aires",
    lat: -34.5910, lng: -58.4189,
    city: "Buenos Aires", country: "Argentina",
    address: "Thames 878, Palermo, C1414 CABA, Buenos Aires",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "tresmonosbar",
    editorial_blurb: "Better known for cocktails but the daytime coffee programme is equally serious — Palermo's most stylish all-day stop.",
    featured_in: ["infatuation", "timeout"],
    verified: true, last_verified_at: "2024-09-20", verification_source: "admin",
  },
  {
    name: "Unión Tostadores de Café",
    slug: "union-tostadores-buenos-aires",
    lat: -34.6177, lng: -58.3689,
    city: "Buenos Aires", country: "Argentina",
    address: "Defensa 934, San Telmo, C1065 CABA, Buenos Aires",
    roaster: "Unión Tostadores",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "uniontostadores",
    editorial_blurb: "San Telmo roastery where cobblestones meet competition-grade sourcing — the most serious pour-over programme south of Palermo.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2024-09-10", verification_source: "community",
  },
  {
    name: "Negro Cueva de Café",
    slug: "negro-cueva-cafe-buenos-aires",
    lat: -34.6188, lng: -58.3723,
    city: "Buenos Aires", country: "Argentina",
    address: "Bolivar 1254, San Telmo, C1066 CABA, Buenos Aires",
    roaster: "Negro Cueva de Café",
    brew_methods: ["espresso", "pour-over", "french-press"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "negrocueva",
    editorial_blurb: "San Telmo basement roastery with a neighbourhood following that would walk past anything else to get here — reliable, honest specialty.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2024-08-25", verification_source: "community",
  },
  {
    name: "Felfort Café",
    slug: "felfort-cafe-villa-crespo",
    lat: -34.5969, lng: -58.4378,
    city: "Buenos Aires", country: "Argentina",
    address: "Murillo 725, Villa Crespo, C1414 CABA, Buenos Aires",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "felfortcafe",
    editorial_blurb: "Villa Crespo's neighbourhood answer to Palermo's specialty glut — friendlier prices, the same calibre of pour-over, and half the queue.",
    featured_in: ["timeout"],
    verified: false, last_verified_at: "2024-08-18", verification_source: "community",
  },
  {
    name: "Café Margot",
    slug: "cafe-margot-boedo",
    lat: -34.6291, lng: -58.4139,
    city: "Buenos Aires", country: "Argentina",
    address: "Av. Boedo 857, Boedo, C1218 CABA, Buenos Aires",
    roaster: "Café Margot",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "cafemargot",
    editorial_blurb: "Classic Boedo corner café that predates the third wave and survived it — the espresso is honest, the chairs are mismatched, and the neighbourhood loves it.",
    featured_in: ["guardian"],
    verified: false, last_verified_at: "2024-09-05", verification_source: "community",
  },
  {
    name: "Télamo Café",
    slug: "telamo-cafe-buenos-aires",
    lat: -34.5855, lng: -58.4271,
    city: "Buenos Aires", country: "Argentina",
    address: "Cabrera 5270, Palermo, C1414 CABA, Buenos Aires",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "telamocafe",
    editorial_blurb: "Understated Palermo café where the focus stays on the cup — the pour-over menu and precise extraction make it a reliable daily destination.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2024-09-15", verification_source: "community",
  },

  // ── SÃO PAULO (15) ────────────────────────────────────────────────────────────
  {
    name: "Guilhotina Coffee",
    slug: "guilhotina-coffee-sao-paulo",
    lat: -23.5630, lng: -46.6920,
    city: "São Paulo", country: "Brazil",
    address: "Rua Harmonia 354, Vila Madalena, São Paulo, SP 05435-000",
    roaster: "Guilhotina Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "guilhotinacoffee",
    editorial_blurb: "Vila Madalena roastery championing Brazilian single-origins — the best argument for why the world should drink more coffee from São Paulo's backyard.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-20", verification_source: "admin",
  },
  {
    name: "Suplicy Cafés Especiais",
    slug: "suplicy-cafes-sao-paulo",
    lat: -23.5715, lng: -46.6628,
    city: "São Paulo", country: "Brazil",
    address: "Al. Lorena 1430, Jardins, São Paulo, SP 01424-001",
    roaster: "Suplicy Cafés Especiais",
    brew_methods: ["espresso", "pour-over", "chemex", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "suplicycafes",
    website: "https://www.suplicycafes.com.br/",
    editorial_blurb: "Premium Brazilian specialty done with Jardins elegance — the micro-lot menu showcases what makes this country the world's most interesting origin.",
    featured_in: ["sprudge", "infatuation"],
    verified: true, last_verified_at: "2024-10-30", verification_source: "admin",
  },
  {
    name: "Café Três",
    slug: "cafe-tres-sao-paulo",
    lat: -23.5604, lng: -46.6762,
    city: "São Paulo", country: "Brazil",
    address: "Rua Aspicuelta 474, Pinheiros, São Paulo, SP 05433-012",
    roaster: "Café Três",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "cafetres",
    editorial_blurb: "Pinheiros natural-process specialists who source from farms within driving distance — this is Brazilian coffee at its most transparent.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-18", verification_source: "admin",
  },
  {
    name: "Coffee Lab",
    slug: "coffee-lab-sao-paulo",
    lat: -23.5604, lng: -46.6830,
    city: "São Paulo", country: "Brazil",
    address: "Rua Fradique Coutinho 1340, Pinheiros, São Paulo, SP 05416-001",
    roaster: "Coffee Lab",
    brew_methods: ["pour-over", "espresso", "syphon", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "coffeelab",
    website: "https://www.coffeelab.com.br/",
    editorial_blurb: "Isabela Raposeiras' Pinheiros laboratory set the bar for Brazilian specialty — her direct sourcing and barista training programme remain the industry reference.",
    featured_in: ["sprudge", "standart", "guardian"],
    verified: true, last_verified_at: "2024-11-05", verification_source: "admin",
  },
  {
    name: "Octávio Café",
    slug: "octavio-cafe-sao-paulo",
    lat: -23.5652, lng: -46.6804,
    city: "São Paulo", country: "Brazil",
    address: "Rua Cardeal Arcoverde 1855, Pinheiros, São Paulo, SP 05407-001",
    roaster: "Octávio Café",
    brew_methods: ["espresso", "pour-over", "cold-brew", "chemex"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "octaviocafe",
    website: "https://www.octaviocafe.com.br/",
    editorial_blurb: "Pinheiros stalwart with a micro-lot programme that's been quietly world-class for a decade — the espresso bar draws SCAA judges on their São Paulo visits.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2024-10-28", verification_source: "admin",
  },
  {
    name: "Isso é Café",
    slug: "isso-e-cafe-sao-paulo",
    lat: -23.5622, lng: -46.6891,
    city: "São Paulo", country: "Brazil",
    address: "Rua Girassol 285, Vila Madalena, São Paulo, SP 05433-000",
    roaster: "Isso é Café",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "issouecafe",
    editorial_blurb: "Vila Madalena roastery making the case for Cerrado and Sul de Minas terroir — the most flavour-forward single-origins in the neighbourhood.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-10", verification_source: "admin",
  },
  {
    name: "Orfeu Cafés Especiais",
    slug: "orfeu-cafes-sao-paulo",
    lat: -23.5476, lng: -46.6522,
    city: "São Paulo", country: "Brazil",
    address: "Rua Maranhão 625, Higienópolis, São Paulo, SP 01240-001",
    roaster: "Orfeu Cafés Especiais",
    brew_methods: ["espresso", "pour-over", "french-press", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "orfeucafes",
    website: "https://www.orfeucafes.com.br/",
    editorial_blurb: "Higienópolis' grand café and one of Brazil's most respected roasters — the fazenda-specific lots and shaded terrace make it a mandatory São Paulo stop.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2024-10-18", verification_source: "admin",
  },
  {
    name: "Moka Cafés Especiais",
    slug: "moka-cafes-sao-paulo",
    lat: -23.5491, lng: -46.6533,
    city: "São Paulo", country: "Brazil",
    address: "Rua Sergipe 609, Higienópolis, São Paulo, SP 01243-001",
    roaster: "Moka Cafés Especiais",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "mokacafes",
    editorial_blurb: "Higienópolis institution known for meticulous espresso preparation and one of the most loyal neighbourhoods followings in the city.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-25", verification_source: "admin",
  },
  {
    name: "Lucca Cafés Especiais",
    slug: "lucca-cafes-sao-paulo",
    lat: -23.5787, lng: -46.6567,
    city: "São Paulo", country: "Brazil",
    address: "Rua Joaquim Antunes 210, Itaim Bibi, São Paulo, SP 05415-001",
    roaster: "Lucca Cafés Especiais",
    brew_methods: ["espresso", "pour-over", "cold-brew", "chemex"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "luccacafes",
    website: "https://www.luccacafes.com.br/",
    editorial_blurb: "Curitiba's best-loved roastery with a polished Itaim Bibi outpost — their Sul de Minas single-origins arrive days off-roast.",
    featured_in: ["sprudge", "infatuation"],
    verified: true, last_verified_at: "2024-10-22", verification_source: "admin",
  },
  {
    name: "Companhia Brasileira de Café",
    slug: "companhia-brasileira-cafe-sp",
    lat: -23.5641, lng: -46.6880,
    city: "São Paulo", country: "Brazil",
    address: "Rua Wisard 551, Vila Madalena, São Paulo, SP 05434-080",
    roaster: "Companhia Brasileira de Café",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "cbcafe",
    website: "https://www.companhiabrasileiradecafe.com.br/",
    editorial_blurb: "Vila Madalena roastery built around the premise that Brazil makes the world's greatest coffee — the evidence is in the cup.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-15", verification_source: "admin",
  },
  {
    name: "Kaffa Torrefazione",
    slug: "kaffa-torrefazione-sao-paulo",
    lat: -23.5788, lng: -46.6710,
    city: "São Paulo", country: "Brazil",
    address: "Rua João Cachoeira 152, Itaim Bibi, São Paulo, SP 04535-010",
    roaster: "Kaffa Torrefazione",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "kaffa.torrefazione",
    editorial_blurb: "Italian-influenced torrefazione in Itaim Bibi with Brazilian soul — the best cortado in the financial district and no apologies for being serious about it.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2024-09-12", verification_source: "community",
  },
  {
    name: "Piu Caffè",
    slug: "piu-caffe-sao-paulo",
    lat: -23.5573, lng: -46.6811,
    city: "São Paulo", country: "Brazil",
    address: "Rua Mourato Coelho 1178, Pinheiros, São Paulo, SP 05417-002",
    roaster: "Piu Caffè",
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "piucaffe.sp",
    editorial_blurb: "Pinheiros all-day café balancing specialty coffee with a proper food menu — the afternoon espresso crowd know this is where the quality is.",
    featured_in: ["timeout"],
    verified: false, last_verified_at: "2024-09-08", verification_source: "community",
  },

  // ── LIMA (8) ─────────────────────────────────────────────────────────────────
  {
    name: "Tostaduría Bisetti",
    slug: "tostaduria-bisetti-lima",
    lat: -12.0964, lng: -77.0359,
    city: "Lima", country: "Peru",
    address: "Jr. General Mendiburu 1073, Miraflores, Lima",
    roaster: "Tostaduría Bisetti",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "tostaduriabisettioficial",
    website: "https://www.bisetti.pe/",
    editorial_blurb: "Lima's most important roastery — Bisetti built Peru's specialty infrastructure almost single-handedly and still sources the best high-altitude Peruvian lots.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2024-10-22", verification_source: "admin",
  },
  {
    name: "Arabica Dispensario",
    slug: "arabica-dispensario-lima",
    lat: -12.1225, lng: -77.0301,
    city: "Lima", country: "Peru",
    address: "Av. Grau 424, Barranco, Lima 15063",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "arabicadispensario",
    editorial_blurb: "Barranco's most thoughtful specialty bar — the curated Peruvian roaster programme showcases a coffee geography the rest of the world is only beginning to discover.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-10-10", verification_source: "admin",
  },
  {
    name: "Neira Café Lab",
    slug: "neira-cafe-lab-lima",
    lat: -12.1178, lng: -77.0330,
    city: "Lima", country: "Peru",
    address: "Calle Martir Olaya 129, Miraflores, Lima 15074",
    roaster: "Neira Café Lab",
    brew_methods: ["pour-over", "espresso", "syphon"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "neiracafelab",
    editorial_blurb: "Competition pedigree café in Miraflores where altitude and varietal are the entire conversation — Lima's most technically exacting barista bar.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2024-09-28", verification_source: "admin",
  },
  {
    name: "Café Verde",
    slug: "cafe-verde-miraflores",
    lat: -12.1248, lng: -77.0278,
    city: "Lima", country: "Peru",
    address: "Av. Reducto 1120, Miraflores, Lima 15074",
    roaster: "Café Verde",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "cafeverdeperu",
    editorial_blurb: "Miraflores specialty roastery committed to Peruvian origins — the single-estate lots from Cajamarca and Amazonas are poured with obvious pride.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2024-09-15", verification_source: "community",
  },
  {
    name: "Pergola",
    slug: "pergola-cafe-lima",
    lat: -12.1483, lng: -77.0224,
    city: "Lima", country: "Peru",
    address: "Jirón Ayacucho 681, Barranco, Lima 15063",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "pergolacafe.lima",
    editorial_blurb: "Barranco's art-district café where the colonial courtyard and single-origin pour-overs compete equally for your attention — and both win.",
    featured_in: ["timeout"],
    verified: false, last_verified_at: "2024-09-20", verification_source: "community",
  },
  {
    name: "Delirious",
    slug: "delirious-cafe-lima",
    lat: -12.1190, lng: -77.0312,
    city: "Lima", country: "Peru",
    address: "Calle Berlín 645, Miraflores, Lima 15074",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "aeropress", "cold-brew"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "deliriouslima",
    editorial_blurb: "Miraflores café that treats coffee with the same seriousness Lima's dining scene brings to food — the tasting flights are genuinely educational.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2024-09-12", verification_source: "community",
  },
  {
    name: "Bocca Coffee",
    slug: "bocca-coffee-san-isidro",
    lat: -12.0986, lng: -77.0412,
    city: "Lima", country: "Peru",
    address: "Av. Conquistadores 790, San Isidro, Lima 15027",
    roaster: "Bocca Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "boccacoffeelima",
    editorial_blurb: "San Isidro's specialty anchor for the business district crowd — Peruvian micro-lots roasted in-house and served with zero corporate compromise.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2024-09-05", verification_source: "community",
  },
  {
    name: "Alma Café",
    slug: "alma-cafe-lima",
    lat: -12.1094, lng: -77.0286,
    city: "Lima", country: "Peru",
    address: "Av. Angamos Oeste 408, Miraflores, Lima 15074",
    roaster: "Alma Café",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "almacafe.pe",
    editorial_blurb: "Miraflores roastery with soul — their Peruvian-only sourcing philosophy and open roasting setup make this the most transparent café in the city.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2024-08-30", verification_source: "community",
  },
];
