import type { Cafe } from '@/types';

export const ASIA_RAW_CAFES: (Omit<Cafe, 'id' | 'created_at' | 'third_wave_score' | 'overall_rating' | 'review_count' | 'permanently_closed'> & { permanently_closed?: boolean })[] = [
  // ── TOKYO (20) ───────────────────────────────────────────────────────────────
  {
    name: "Fuglen Tokyo",
    slug: "fuglen-tokyo",
    lat: 35.6666, lng: 139.6924,
    google_place_id: "ChIJrWB6lbKMGGARp0QB0mMSNe4",
    city: "Tokyo", country: "Japan",
    address: "1-16-11 Tomigaya, Shibuya-ku, Tokyo",
    roaster: "Fuglen Coffee Roasters",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "fuglentokyo",
    website: "https://fuglencoffee.jp/",
    editorial_blurb: "Oslo's cult café landed in Tokyo and raised the bar for the entire city — order the pour-over and stay for the vintage furniture.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Koffee Mameya",
    slug: "koffee-mameya",
    lat: 35.6684, lng: 139.7109,
    google_place_id: "ChIJB1oleKOMGGAR_10GNeoySkY",
    city: "Tokyo", country: "Japan",
    address: "4-15-3 Jingumae, Shibuya-ku, Tokyo",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["standing-bar", "minimalist"],
    instagram_handle: "koffee_mameya",
    website: "https://koffee-mameya.com/",
    editorial_blurb: "No menu, no seating — just a barista asking what you want and delivering the precise cup you didn't know you needed.",
    featured_in: ["sprudge", "barista_magazine", "monocle"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Glitch Coffee & Roasters",
    slug: "glitch-coffee-tokyo",
    lat: 35.6937, lng: 139.7613,
    google_place_id: "ChIJDxYKIhCMGGARScnqzc-T-TU",
    city: "Tokyo", country: "Japan",
    address: "3-16 Kanda Nishikicho, Chiyoda-ku, Tokyo",
    roaster: "Glitch Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["minimalist"],
    instagram_handle: "glitch_coffee",
    website: "https://glitchcoffee.com/",
    editorial_blurb: "Jimbocho café and roastery whose filter menu rotates with what's peaking — among the most technically serious coffee bars in Tokyo.",
    featured_in: ["sprudge", "daily_coffee_news"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Onibus Coffee",
    slug: "onibus-coffee-nakameguro",
    lat: 35.6432, lng: 139.6980,
    google_place_id: "ChIJvXUZEEmLGGARlC39ZdeJ06Q",
    city: "Tokyo", country: "Japan",
    address: "2-14-1 Kamimeguro, Meguro-ku, Tokyo",
    roaster: "Onibus Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating"],
    instagram_handle: "onibuscoffee",
    website: "https://onibuscoffee.com/",
    editorial_blurb: "Nakameguro roastery tucked off the canal — the Portuguese name (bus) fits a café built on movement, sourcing, and sharing.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Sarutahiko Coffee",
    slug: "sarutahiko-coffee-ebisu",
    lat: 35.6477, lng: 139.7109,
    google_place_id: "ChIJRaBmLUCLGGARbU1gw-zbId0",
    city: "Tokyo", country: "Japan",
    address: "1-6-6 Ebisu, Shibuya-ku, Tokyo",
    roaster: "Sarutahiko Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["standing-bar", "minimalist"],
    instagram_handle: "sarutahiko_coffee",
    website: "https://sarutahiko.co",
    editorial_blurb: "Ebisu standing bar with an obsessive drip culture and a compact menu that never wastes your time or your palate.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "About Life Coffee Brewers",
    slug: "about-life-coffee-shibuya",
    lat: 35.6567, lng: 139.6958,
    google_place_id: "ChIJXVNv51WLGGARAFLANNXRSoo",
    city: "Tokyo", country: "Japan",
    address: "1-19-8 Dogenzaka, Shibuya-ku, Tokyo",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["standing-bar", "minimalist"],
    instagram_handle: "aboutlifecoffee",
    editorial_blurb: "Shibuya standing counter with a rotating guest-roaster program — the name is a provocation, the coffee makes good on it.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Blue Bottle Coffee Kiyosumi",
    slug: "blue-bottle-kiyosumi-tokyo",
    lat: 35.6778, lng: 139.8006,
    google_place_id: "ChIJVVVp3BaJGGARfAgSR2yEybw",
    city: "Tokyo", country: "Japan",
    address: "1-4-8 Hirano, Koto-ku, Tokyo 135-0023",
    roaster: "Blue Bottle Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "cold-brew", "syphon"],
    vibe_tags: ["minimalist"],
    instagram_handle: "bluebottlejpn",
    website: "https://bluebottlecoffee.com/",
    editorial_blurb: "Blue Bottle's Tokyo flagship in a converted Kiyosumi warehouse — the roastery that announced specialty coffee's arrival in Japan to a global audience.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Bear Pond Espresso",
    slug: "bear-pond-espresso-tokyo",
    lat: 35.6640, lng: 139.6679,
    google_place_id: "ChIJ_6-SI2vzGGARTwHyOGabtyI",
    city: "Tokyo", country: "Japan",
    address: "2-36-12 Kitazawa, Setagaya-ku, Tokyo",
    roaster: "Bear Pond Espresso",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["standing-bar", "no-laptop"],
    instagram_handle: "bearpondespresso",
    website: "https://bearpondespresso.com",
    editorial_blurb: "Shimokitazawa espresso purist — a single counter, a single focus, and the most intensely discussed shot in Tokyo. Cash only, always worth it.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Streamer Coffee Company",
    slug: "streamer-coffee-shibuya",
    lat: 35.6635, lng: 139.7039,
    google_place_id: "ChIJJ-aF_6aMGGARfbFeJO3hQuU",
    city: "Tokyo", country: "Japan",
    address: "1-20-28 Shibuya, Shibuya-ku, Tokyo",
    roaster: "Streamer Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "streamercoffee",
    website: "https://streamer.coffee/",
    editorial_blurb: "Streamer's latte art championship roots are on the walls; the espresso program that won those titles is in the cup.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Coffee Supreme Tokyo",
    slug: "coffee-supreme-tokyo",
    lat: 35.6655, lng: 139.6923,
    google_place_id: "ChIJAcCIX62MGGARGEilMb3hpkQ",
    city: "Tokyo", country: "Japan",
    address: "Japan, 〒150-0047 Tokyo, Shibuya, Kamiyamachō, 42−３ 1F",
    roaster: "Coffee Supreme",
    brew_methods: ["espresso"],
    vibe_tags: ["outdoor-seating"],
    instagram_handle: "coffeesupreme",
    website: "https://coffeesupreme.com/",
    editorial_blurb: "New Zealand's Coffee Supreme runs its Shibuya café near Yoyogi Park — beans roasted in Melbourne, Antipodean irreverence intact.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Passage Coffee",
    slug: "passage-coffee-shiba",
    lat: 35.6485, lng: 139.7448,
    google_place_id: "ChIJNwVt9rCLGGAR_TvVpvAyhK8",
    city: "Tokyo", country: "Japan",
    address: "5-14-16 Shiba, Minato-ku, Tokyo 108-0014",
    roaster: "Passage Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "passagecoffee",
    website: "https://passagecoffee.com/",
    editorial_blurb: "Shiba roastery café from 2014 World Aeropress Champion Shuichi Sasaki — precise, unhurried single-origin pours on a quiet Minato-ku side street.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Paul Bassett",
    slug: "paul-bassett-shinjuku",
    lat: 35.6928, lng: 139.6951,
    google_place_id: "ChIJE6uvw9WMGGARBzGk1OSnj74",
    city: "Tokyo", country: "Japan",
    address: "1-26-2 Nishishinjuku, B1F Nomura Building, Shinjuku-ku, Tokyo 163-0590",
    roaster: "Paul Bassett",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "paulbassettcoffee",
    website: "https://www.paulbassett.jp/",
    editorial_blurb: "World barista champion Paul Bassett's Shinjuku flagship in the Nomura Building basement — the espresso-as-craft philosophy translates into one of Tokyo's most quietly excellent menus.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Café Kitsuné Aoyama",
    slug: "cafe-kitsune-aoyama-tokyo",
    lat: 35.6648, lng: 139.7153,
    google_place_id: "ChIJJ3xR02GLGGARQuKJA_ZJp-0",
    city: "Tokyo", country: "Japan",
    address: "3-17-1 Minami-Aoyama, Minato-ku, Tokyo",
    roaster: "Café Kitsuné (Okayama roastery)",
    roaster_family: true,
    brew_methods: ["espresso", "cold-brew"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "cafekitsune",
    website: "https://cafekitsune.com/",
    editorial_blurb: "Fashion house garden café in Aoyama where the design is exceptional and the specialty espresso is serious — both are reasons to visit.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Higuma Doughnuts × Coffee Wrights Omotesando",
    slug: "coffee-wrights-sendagaya",
    lat: 35.6678, lng: 139.7105,
    google_place_id: "ChIJB4nX_beNGGARcvfg36ImbP8",
    city: "Tokyo", country: "Japan",
    address: "4-9-13 Jingumae, Shibuya-ku, Tokyo (Minagawa Village)",
    roaster: "Coffee Wrights",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["minimalist", "outdoor-seating"],
    instagram_handle: "coffee_wrights",
    website: "https://coffee-wrights.jp",
    editorial_blurb: "A doughnut-and-coffee collab behind Omotesando and Harajuku — Coffee Wrights pulls the espresso while Higuma Doughnuts fries to order.",
    featured_in: ["timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },

  // ── SEOUL (15) ───────────────────────────────────────────────────────────────
  {
    name: "Fritz Coffee Company",
    slug: "fritz-coffee-seoul",
    lat: 37.5410, lng: 126.9490,
    google_place_id: "ChIJe1ONC6aYfDUR6IUAfWMCG44",
    city: "Seoul", country: "South Korea",
    address: "17 Saechang-ro 2-gil, Mapo-gu, Seoul, South Korea",
    roaster: "Fritz Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["laptop-friendly"],
    instagram_handle: "fritzcoffeecompany",
    website: "https://fritz.co.kr/",
    editorial_blurb: "Seoul's most beloved roastery café — the Saturday morning queue is a pilgrimage and the single-origins justify every minute of it.",
    featured_in: ["sprudge", "barista_magazine"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Namusairo",
    slug: "namusairo-seoul",
    lat: 37.5747, lng: 126.9709,
    google_place_id: "ChIJA3_W7JVrMhURUlozmc4p7yA",
    city: "Seoul", country: "South Korea",
    address: "21 Sajik-ro 8-gil, Jongno-gu, Seoul",
    roaster: "Namusairo",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "namusairo",
    website: "https://www.namusairo.com/",
    editorial_blurb: "A Sajik-dong hanok near Gyeongbokgung Palace — Namusairo has poured technically precise pour-overs since 2002.",
    featured_in: ["barista_magazine"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "% Arabica Seoul Hannam",
    slug: "arabica-seoul-hannam",
    lat: 37.5338, lng: 127.0021,
    google_place_id: "ChIJZ9ND8AajfDURu0hJFPJp5HA",
    city: "Seoul", country: "South Korea",
    address: "35 Daesagwan-ro, 2F, Yongsan-gu, Seoul 04420",
    roaster: "% Arabica",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "arabica.kr",
    website: "https://arabica.com/en/",
    editorial_blurb: "Kyoto's global minimalist icon in Hannam — the same quiet precision, the same exceptional espresso, the same insistence on doing one thing right.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Onion Anguk",
    slug: "onion-anguk-seoul",
    lat: 37.5776, lng: 126.9866,
    google_place_id: "ChIJLXL2BvijfDURmTrYFPQIGUc",
    city: "Seoul", country: "South Korea",
    address: "5 Gyedong-gil, Jongno District, Seoul, South Korea",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["no-laptop", "outdoor-seating"],
    instagram_handle: "onion.anguk",
    editorial_blurb: "Anguk's 1920s hanok turned bakery-café — cardamom croissants and quietly good coffee draw the daily queue.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Coffee Libre",
    slug: "coffee-libre-seoul",
    lat: 37.5636, lng: 126.9237,
    google_place_id: "ChIJK05lru6YfDUR22H8d3bQr58",
    city: "Seoul", country: "South Korea",
    address: "20-5 Seongmisan-ro 32-gil, Mapo-gu, Seoul, South Korea",
    roaster: "Coffee Libre",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["laptop-friendly"],
    instagram_handle: "coffeelibrekorea",
    website: "https://coffeelibre.kr/",
    editorial_blurb: "Yeonnam-dong roastery that built the Seoul specialty movement before it had a name — their Latin American sourcing program is still the city's best.",
    featured_in: ["timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Manufact Coffee Roasters",
    slug: "manufact-coffee-seoul",
    lat: 37.5678, lng: 126.9296,
    google_place_id: "ChIJC8mDVPKYfDURhxX_yE8bjPE",
    city: "Seoul", country: "South Korea",
    address: "29 Yeonhui-ro 11-gil, 2F, Seodaemun-gu, Seoul",
    roaster: "Manufact Coffee",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["minimalist"],
    instagram_handle: "manufactcoffee",
    website: "https://www.manufactcoffee.com/",
    editorial_blurb: "Yeonhui roastery café with a serious light-roast commitment and a filter program that's been shaping Seoul palates for years.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Terarosa Coffee Seoul",
    slug: "terarosa-coffee-seoul",
    lat: 37.5058, lng: 127.0562,
    google_place_id: "ChIJS617_xOkfDURPartP-Y2W7E",
    city: "Seoul", country: "South Korea",
    address: "440 Teheran-ro, POSCO Center, Gangnam-gu, Seoul 06194",
    roaster: "Terarosa Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["laptop-friendly"],
    instagram_handle: "terarosacoffee",
    website: "https://www.terarosa.com/",
    editorial_blurb: "Gangneung's legendary roastery in Seoul — Terarosa's POSCO Center outpost brings the same obsessive sourcing and light-roast conviction to the capital.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Lowkey Coffee Seongsu",
    slug: "lowkey-coffee-seongsu",
    lat: 37.5442, lng: 127.0516,
    google_place_id: "ChIJy-WONTylfDUR6nkYbwW0prg",
    city: "Seoul", country: "South Korea",
    address: "6 Yeonmujang 3-gil, Seongdong-gu, Seoul",
    roaster: "Lowkey Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "lowkey_coffee",
    website: "https://www.lowkeycoffee.com/",
    editorial_blurb: "Seongsu specialty bar where the name is the ethos — no flashy design, just excellent espresso and a rotating filter menu worth returning for.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Felt Coffee",
    slug: "felt-coffee-seoul",
    lat: 37.5687, lng: 126.9788,
    google_place_id: "ChIJRTb_hKOjfDURQhHwwxDLWOY",
    city: "Seoul", country: "South Korea",
    address: "77 Mugyo-dong, Jung District, Seoul, South Korea",
    roaster: "Felt Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "felt_seoul",
    website: "https://www.feltcoffee.com/",
    editorial_blurb: "Cheonggyecheon-side café with a warm atmosphere and a filter menu that changes more often than you'd expect — always worth the detour.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Café Layered",
    slug: "cafe-layered-anguk",
    lat: 37.5777, lng: 126.9859,
    google_place_id: "ChIJr1nKrsSifDURgg2lrxJlNZU",
    city: "Seoul", country: "South Korea",
    address: "2-3 Bukchon-ro 2-gil, Jongno-gu, Seoul",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "cafe_layered",
    editorial_blurb: "Bukchon multi-floor café known for towers of English scones and cakes — coffee is served, but the bakery case is the draw.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },

  // ── SINGAPORE (12) ───────────────────────────────────────────────────────────
  {
    name: "Nylon Coffee Roasters",
    slug: "nylon-coffee-singapore",
    lat: 1.2769, lng: 103.8400,
    google_place_id: "ChIJE7ZtOWwZ2jERFcasWYmljJQ",
    city: "Singapore", country: "Singapore",
    address: "4 Everton Park #01-40, Singapore 080004",
    roaster: "Nylon Coffee Roasters",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["minimalist"],
    instagram_handle: "nyloncoffee",
    website: "https://nylon.coffee/",
    editorial_blurb: "Tanjong Pagar institution that defined Singapore specialty — Everton Park HDB block setting is as iconic as the coffee itself.",
    featured_in: ["sprudge", "monocle", "timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Cata Coffee",
    slug: "cata-singapore",
    lat: 1.3134, lng: 103.9016,
    google_place_id: "ChIJ8Ye4_Z8b2jERtgHTeOD_xnw",
    city: "Singapore", country: "Singapore",
    address: "56 Joo Chiat Pl, Singapore 427780",
    roaster: "Cata Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "cata_sg",
    website: "https://catacoffee.com/",
    editorial_blurb: "Joo Chiat standing coffee bar from an independent Singapore roastery — a glass-walled roasting room anchors the space, serving single-origin espresso and filter coffee.",
    featured_in: ["monocle"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Chye Seng Huat Hardware",
    slug: "chye-seng-huat-singapore",
    lat: 1.3116, lng: 103.8603,
    google_place_id: "ChIJDVvGO8kZ2jERoThpnZ1p97s",
    city: "Singapore", country: "Singapore",
    address: "150 Tyrwhitt Rd, Singapore 207563",
    roaster: "PPP Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "cshhardware",
    website: "https://cshhcoffee.com/",
    editorial_blurb: "Converted hardware shop turned café flagship for PPP Coffee — the courtyard, the pour-overs, and the industrial bones are all reasons to visit.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Common Man Coffee Roasters",
    slug: "common-man-coffee-singapore",
    lat: 1.2919, lng: 103.8384,
    google_place_id: "ChIJT3fdLZwZ2jERJx-QGgPAoac",
    city: "Singapore", country: "Singapore",
    address: "22 Martin Rd, Singapore 239058",
    roaster: "Common Man Coffee Roasters",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "aeropress", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "commonmancoffeeroasters",
    website: "https://www.commonmancoffeeroasters.com/",
    editorial_blurb: "Robertson Quay roastery that made specialty coffee accessible without dumbing it down — the training academy and the café are both world-class.",
    featured_in: ["sprudge", "monocle", "timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Sarnies",
    slug: "sarnies-singapore",
    lat: 1.2816, lng: 103.8480,
    google_place_id: "ChIJC6Atrw0Z2jERJ8FHIn-pwz0",
    city: "Singapore", country: "Singapore",
    address: "136 Telok Ayer St, Singapore 068601",
    roaster: "Sarnies",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["no-laptop", "outdoor-seating"],
    instagram_handle: "sarniessg",
    website: "https://sarnies.com/",
    editorial_blurb: "Telok Ayer shophouse café where the Antipodean sandwich and the flat white are equally non-negotiable — CBD specialty coffee done right.",
    featured_in: ["timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "PPP Coffee New Bahru",
    slug: "ppp-coffee-singapore",
    lat: 1.2925, lng: 103.8394,
    google_place_id: "ChIJK5eVlz8Z2jERN7rAQvDJ6IA",
    city: "Singapore", country: "Singapore",
    address: "46 Kim Yam Rd, #01-06, Singapore 239351",
    roaster: "PPP Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly"],
    instagram_handle: "ppp.coffee",
    website: "https://pppcoffee.com/",
    editorial_blurb: "New Bahru café from PPP Coffee, the specialty roaster behind Chye Seng Huat Hardware — an all-day coffee menu plus a sit-down coffee-omakase experience.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Tiong Hoe Specialty Coffee",
    slug: "tiong-hoe-coffee-singapore",
    lat: 1.2910, lng: 103.8031,
    google_place_id: "ChIJJ9wWkzQa2jER1NZNUnhOfJw",
    city: "Singapore", country: "Singapore",
    address: "Blk 170 Stirling Rd, #01-1133, Singapore 140170",
    roaster: "Tiong Hoe",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["minimalist"],
    instagram_handle: "tionghoecoffee",
    website: "https://tionghoe.com/",
    editorial_blurb: "Queenstown roastery that's been quietly excellent for longer than most — the house roasts and the barista knowledge both reward the regular.",
    featured_in: ["timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },

  // ── TAIPEI (11) ──────────────────────────────────────────────────────────────
  {
    name: "Fika Fika Café",
    slug: "fika-fika-taipei",
    lat: 25.0505, lng: 121.5353,
    google_place_id: "ChIJEfselmGpQjQR7yaK-dqDBJ4",
    city: "Taipei", country: "Taiwan",
    address: "No. 33, Yitong St, Zhongshan District, Taipei 104",
    roaster: "Fika Fika",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["laptop-friendly"],
    instagram_handle: "fikafika_cafe",
    website: "https://www.fikafikacafe.com/",
    editorial_blurb: "Taiwan's first Scandinavian-style roastery brought light-roast competition culture to Taipei — and the city never looked back.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Simple Kaffa",
    slug: "simple-kaffa-taipei",
    lat: 25.0340, lng: 121.5645,
    google_place_id: "ChIJP5CF7pmrQjQRY1MyLg_GRrw",
    city: "Taipei", country: "Taiwan",
    address: "110, Taiwan, Taipei City, Xinyi District, Xicun Village, Section 5, Xinyi Rd, 7號88樓",
    roaster: "Simple Kaffa",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "simplekaffa",
    website: "https://simplekaffa.com/",
    editorial_blurb: "World Barista Champion Berg Wu's Simple Kaffa Sola — the same espresso technique that won world titles, poured 88 floors above Taipei.",
    featured_in: ["sprudge", "barista_magazine"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Rufous Coffee",
    slug: "rufous-coffee-taipei",
    lat: 25.0235, lng: 121.5437,
    google_place_id: "ChIJW03Z2y6qQjQRkIeeuqF3-mU",
    city: "Taipei", country: "Taiwan",
    address: "No. 339, Fuxing S Rd Sec 2, Da'an District, Taipei",
    roaster: "Rufous Coffee Roasters",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "cold-brew", "syphon"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "rufous_coffee",
    website: "https://www.rufous.com.tw/",
    editorial_blurb: "Da'an's serious single-origin program, self-roasted since 2007 — espresso, hand brew, cold drip and siphon, all built around one Q-grader's palate.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "% Arabica Taipei Roastery",
    slug: "arabica-taipei",
    lat: 25.0563, lng: 121.5208,
    google_place_id: "ChIJNZgvAwCpQjQRpJ-vpaxyW_0",
    city: "Taipei", country: "Taiwan",
    address: "Zhongshan District, Taipei",
    roaster: "% Arabica",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "arabica.taipei",
    website: "https://arabica.com/en/",
    editorial_blurb: "The Kyoto minimalist icon's first Taiwan roastery, tucked into Zhongshan — sleek architecture, single-origin espresso, the same calm intention.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Gabee Coffee",
    slug: "gabee-coffee-taipei",
    lat: 25.0593, lng: 121.5462,
    google_place_id: "ChIJl2thpeWrQjQR6-xtBFEkoHI",
    city: "Taipei", country: "Taiwan",
    address: "No.21, Lane 113, Sec 3, Minsheng E Rd, Songshan District, Taipei",
    roaster: "Gabee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["laptop-friendly"],
    instagram_handle: "gabeecoffee",
    website: "https://www.gabee-cafe.com/",
    editorial_blurb: "Songshan latte-art pioneer founded by Taiwan's first Coffee Master champion — still one of the city's essential café-roastery stops.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Goodman Roaster",
    slug: "goodman-roaster-taipei",
    lat: 25.1240, lng: 121.5318,
    google_place_id: "ChIJN7wFrX6uQjQR1-0jCcR-0Y4",
    city: "Taipei", country: "Taiwan",
    address: "No.110 Tianyu St, Shilin District, Taipei",
    roaster: "Goodman Roaster",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "goodmanroaster",
    website: "https://goodmanroaster.tw/",
    editorial_blurb: "Shilin roastery café from Kyoto coffee craftsman Atsuomi Itō — Diedrich-roasted beans and a precise Kalita pour-over recipe.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },

  // ── OSAKA (10) ───────────────────────────────────────────────────────────────
  {
    name: "Mel Coffee Roasters",
    slug: "mel-coffee-roasters-osaka",
    lat: 34.6768, lng: 135.4958,
    google_place_id: "ChIJn3HiogTnAGARILfkHrpMUGQ",
    city: "Osaka", country: "Japan",
    address: "1-20-4 Shinmachi, Nishi-ku, Osaka 550-0013",
    roaster: "Mel Coffee Roasters",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "french-press"],
    vibe_tags: ["minimalist"],
    instagram_handle: "melcoffeeroasters",
    website: "https://mel-coffee.jp/",
    editorial_blurb: "Shinmachi roastery serving its own light-to-medium-dark roasts — a self-roasted, natural-leaning program a few minutes from Namba.",
    featured_in: ["sprudge", "barista_magazine", "timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "LiLo Coffee Roasters",
    slug: "lilo-coffee-osaka",
    lat: 34.6741, lng: 135.4980,
    google_place_id: "ChIJ1T9unxrnAGARhtQGwQaaF-I",
    city: "Osaka", country: "Japan",
    address: "1-10-28 Nishishinsaibashi, Chuo-ku, Osaka",
    roaster: "LiLo Coffee Roasters",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "aeropress", "cold-brew", "syphon", "french-press"],
    vibe_tags: ["laptop-friendly"],
    instagram_handle: "lilocoffeeroasters",
    website: "https://coffee.liloinveve.com/",
    editorial_blurb: "Nishishinsaibashi roastery-café with an in-house roasting program and a rare-for-Osaka hand-brew menu — V60, syphon, cold brew and more across 20-plus single origins.",
    featured_in: ["sprudge", "barista_magazine", "timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Takamura Wine & Coffee Roasters",
    slug: "takamura-coffee-osaka",
    lat: 34.6873, lng: 135.4911,
    google_place_id: "ChIJb3Q3lfnmAGARP7CUdaGq3P8",
    city: "Osaka", country: "Japan",
    address: "2-2-18 Edobori, Nishi-ku, Osaka 550-0002",
    roaster: "Takamura",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["outdoor-seating"],
    instagram_handle: "takamura_coffee",
    website: "https://takamura-coffee.com",
    editorial_blurb: "Utsubo Park-adjacent roastery that pairs natural wine sourcing sensibility with serious coffee — the best of two obsessive worlds under one roof.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },

  // ── HO CHI MINH CITY (9) ─────────────────────────────────────────────────────
  {
    name: "The Workshop Coffee",
    slug: "the-workshop-coffee-hcmc",
    lat: 10.7735, lng: 106.7056,
    google_place_id: "ChIJdyfroEYvdTER2m7eTz44Bns",
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "27 Ngo Duc Ke, District 1, Ho Chi Minh City",
    roaster: "The Workshop Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "aeropress", "syphon", "chemex"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "theworkshopcoffee",
    editorial_blurb: "A long-running café up a flight of stairs on Ngo Duc Ke, District 1 — pour-over, syphon, Chemex and AeroPress sit alongside espresso.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Shin Coffee – Heritage",
    slug: "shin-coffee-hcmc",
    lat: 10.7732, lng: 106.6991,
    google_place_id: "ChIJnxOUdKcvdTER2q9wWsl22gE",
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "27 Lưu Văn Lang, Bến Thành, Hồ Chí Minh 700000, Vietnam",
    roaster: "Shin Coffee",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "shincoffee",
    website: "https://shincaphe.com/",
    editorial_blurb: "Shin's Heritage flagship in Bến Thành, District 1 — Vietnamese robusta and imported arabica share a menu built on third-wave technique.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "L'Usine",
    slug: "lusine-hcmc",
    lat: 10.7797, lng: 106.7040,
    google_place_id: "ChIJmSbv60gvdTER8Nqtg6Unzpw",
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "19 Lê Thánh Tôn, Sài Gòn, Hồ Chí Minh 700000, Vietnam",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "lusinespace",
    website: "https://www.lusinespace.com/",
    editorial_blurb: "French colonial architecture meets third-wave coffee in the heart of District 1 — the design alone is reason to linger over a second cup.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Bosgaurus Coffee Roasters",
    slug: "bosgaurus-coffee-hcmc",
    lat: 10.7890, lng: 106.7206,
    google_place_id: "ChIJFbNbZhkpdTEREnQAU62EGgY",
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "Biệt thự, 1D5 D5, Saigon Pearl, Thạnh Mỹ Tây, Hồ Chí Minh, Vietnam",
    roaster: "Bosgaurus Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "cold-brew", "syphon"],
    vibe_tags: ["laptop-friendly"],
    instagram_handle: "bosgaurus",
    website: "https://bosgauruscoffee.com",
    editorial_blurb: "Bosgaurus's original roastery in Saigon Pearl, Bình Thạnh — hand-drip and siphon bars alongside espresso and cold brew, all from its own roast.",
    featured_in: ["sprudge", "barista_magazine"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },

  // ── TOKYO NEW (30) ───────────────────────────────────────────────────────────
  {
    name: "Little Nap Coffee Stand",
    slug: "little-nap-coffee-yoyogi",
    lat: 35.6721, lng: 139.6906,
    google_place_id: "ChIJUyaS0ErzGGAR6_mFuqndQ9o",
    city: "Tokyo", country: "Japan",
    address: "5-65-4 Yoyogi, Shibuya-ku, Tokyo",
    roaster: "Little Nap Coffee Roasters",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["standing-bar", "outdoor-seating", "minimalist"],
    instagram_handle: "littlenapcoffeestand",
    website: "https://littlenap.jp",
    editorial_blurb: "Yoyogi Park corner stand with a devoted neighbourhood following — the seasonal espresso blends and park-facing counter are a Tokyo classic.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "The Roastery by Nozy Coffee",
    slug: "the-roastery-nozy-omotesando",
    lat: 35.6656, lng: 139.7048,
    google_place_id: "ChIJCS0wmqaMGGAR2h4xKb_ah8c",
    city: "Tokyo", country: "Japan",
    address: "5-17-13 Jingumae, Shibuya-ku, Tokyo (Cat Street)",
    roaster: "Nozy Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "french-press"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "theroastery_nozycoffee",
    website: "https://www.tysons.jp/roastery/en/",
    editorial_blurb: "Cat Street roastery café from Nozy Coffee and Tysons — single-origin beans roasted on site, poured as espresso, latte or French press.",
    featured_in: ["timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Onibus Coffee Jiyugaoka",
    slug: "onibus-coffee-jiyugaoka",
    lat: 35.6085, lng: 139.6718,
    google_place_id: "ChIJzzAJyMP1GGAR7ggMQoGxyFo",
    city: "Tokyo", country: "Japan",
    address: "Japan, 〒152-0034 Tokyo, Meguro City, Midorigaoka, 2-chōme−24−８ arbre自由が丘",
    roaster: "Onibus Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["outdoor-seating", "minimalist"],
    instagram_handle: "onibuscoffee",
    website: "https://onibuscoffee.com/",
    editorial_blurb: "One of several Onibus Coffee outposts around Tokyo — this Jiyugaoka café, opened in 2022, was the chain's first location with a full kitchen alongside the coffee bar.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Turret Coffee",
    slug: "turret-coffee-tsukiji",
    lat: 35.6680, lng: 139.7720,
    google_place_id: "ChIJW4Hi46OLGGARZVuuNeN6hxs",
    city: "Tokyo", country: "Japan",
    address: "2-12-6 Tsukiji, Chuo-ku, Tokyo",
    roaster: "Sawada Coffee",
    brew_methods: ["espresso"],
    vibe_tags: ["standing-bar", "minimalist", "no-laptop"],
    instagram_handle: "turretcoffee",
    editorial_blurb: "Tiny standing espresso bar named for the delivery mini-trucks that once zipped past — a Tsukiji fixture since 2013, its beans sourced from Hiroshi Sawada's coffee line.",
    featured_in: ["timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Maruyama Coffee Nishi-Azabu",
    slug: "maruyama-coffee-aoyama-tokyo",
    lat: 35.6576, lng: 139.7241,
    google_place_id: "ChIJ3SRJq3GLGGARmGHC8gGDBbk",
    city: "Tokyo", country: "Japan",
    address: "3-13-3 Nishiazabu, Minato-ku, Tokyo 106-0031",
    roaster: "Maruyama Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "french-press"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "maruyamacoffee",
    website: "https://www.maruyamacoffee.com/",
    editorial_blurb: "Nagano's Cup of Excellence dynasty's only Tokyo café, tucked into Nishi-Azabu — pour-over, French press and espresso built around competition-grade lots.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Blue Bottle Coffee Aoyama",
    slug: "blue-bottle-aoyama-tokyo",
    lat: 35.6652, lng: 139.7139,
    google_place_id: "ChIJ6VIU1J-MGGARbBb5g_Wg8Ec",
    city: "Tokyo", country: "Japan",
    address: "3-13-14 Minami-Aoyama, Minato-ku, Tokyo",
    roaster: "Blue Bottle Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "outdoor-seating"],
    instagram_handle: "bluebottlejpn",
    website: "https://bluebottlecoffee.com/",
    editorial_blurb: "Blue Bottle's Aoyama café tucked into the Omotesando side streets — a second-floor terrace space, not inside the neighbouring Nezu Museum garden.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Blue Bottle Coffee Shinjuku",
    slug: "blue-bottle-shinjuku-tokyo",
    lat: 35.6888, lng: 139.7021,
    google_place_id: "ChIJ_5TAt9qMGGARjg9wMPqgimo",
    city: "Tokyo", country: "Japan",
    address: "4-1-6 Shinjuku, NEWoMan 1F, Shinjuku-ku, Tokyo 160-0022",
    roaster: "Blue Bottle Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "bluebottlejpn",
    website: "https://bluebottlecoffee.com/",
    editorial_blurb: "Blue Bottle's NEWoMan Shinjuku location offers a rare moment of filter-coffee calm in the middle of Shinjuku's relentless energy.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Switch Coffee Meguro",
    slug: "switch-coffee-meguro",
    lat: 35.6363, lng: 139.7074,
    google_place_id: "ChIJR6vPKbaLGGARK0tbWrrM5u0",
    city: "Tokyo", country: "Japan",
    address: "2-chōme-3-9 Meguro, Meguro City, Tokyo 153-0063, Japan",
    roaster: "Switch Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "switchcoffeetokyo",
    website: "https://www.switchcoffeetokyo.com",
    editorial_blurb: "Meguro flagship where Switch Coffee's house roasts are on full display — the weekly single-origin rotation rewards the regular visitor.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Verve Coffee Roasters Tokyo",
    slug: "verve-coffee-tokyo",
    lat: 35.6615, lng: 139.7362,
    google_place_id: "ChIJg36gYPSLGGARlTI1efR23YQ",
    city: "Tokyo", country: "Japan",
    address: "5-16-7 Roppongi, Minato-ku, Tokyo 106-0032",
    roaster: "Verve Coffee Roasters",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "outdoor-seating"],
    instagram_handle: "vervecoffeeroasters",
    website: "https://vervecoffee.jp/",
    editorial_blurb: "Santa Cruz's acclaimed roastery reaches Roppongi, not Aoyama — the California directness and Japanese precision still make a coherent pairing.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Amameria Espresso",
    slug: "amameria-espresso-tokyo",
    lat: 35.6203, lng: 139.7061,
    google_place_id: "ChIJZfP7_tuKGGAR74GltzQCNh8",
    city: "Tokyo", country: "Japan",
    address: "Japan, 〒142-0062 Tokyo, Shinagawa City, Koyama, 3-chōme−6−１５ 1階",
    roaster: "Amameria Espresso",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["standing-bar", "minimalist", "no-laptop"],
    instagram_handle: "amameria_espresso",
    website: "https://www.amameria.com",
    editorial_blurb: "Musashi-Koyama espresso bar that roasts its own beans on a Loring machine — a single-minded shrine to the shot in Shinagawa, not Kiyosumi-Shirakawa.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Glitch Coffee Ginza",
    slug: "glitch-coffee-ginza",
    lat: 35.6689, lng: 139.7686,
    google_place_id: "ChIJE0xjRfqLGGARkLg8IUjcu2o",
    city: "Tokyo", country: "Japan",
    address: "Japan, 〒104-0061 Tokyo, Chuo City, Ginza, 4-chōme−14−８ VORT銀座イーストIII 1階",
    roaster: "Glitch Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["minimalist", "standing-bar"],
    instagram_handle: "glitch_coffee",
    website: "https://glitchcoffee.com/",
    editorial_blurb: "Glitch's Ginza outpost distils the Jimbocho competition ethos into a compact bar — the rotating filter menu is as serious as any in the city.",
    featured_in: ["timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Fuglen Tokyo Asakusa",
    slug: "fuglen-tokyo-asakusa",
    lat: 35.7145, lng: 139.7940,
    google_place_id: "ChIJzVXOw5SPGGAR7yVtRAihT7o",
    city: "Tokyo", country: "Japan",
    address: "2-6-15 Asakusa, Taito-ku, Tokyo 111-0032",
    roaster: "Fuglen Coffee Roasters",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "aeropress"],
    vibe_tags: ["minimalist", "outdoor-seating"],
    instagram_handle: "fuglentokyo",
    website: "https://fuglencoffee.jp/",
    editorial_blurb: "Fuglen's Asakusa outpost takes the Oslo-meets-Tokyo formula into the city's most traditional neighbourhood — a contrast that somehow works perfectly.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Coffee Valley",
    slug: "coffee-valley-ikebukuro",
    lat: 35.7277, lng: 139.7131,
    google_place_id: "ChIJOSGiQWiNGGARrnh2tSR6HW0",
    city: "Tokyo", country: "Japan",
    address: "2-26-3 Minami-Ikebukuro, Toshima-ku, Tokyo 171-0022",
    roaster: "Coffee Valley",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["laptop-friendly"],
    instagram_handle: "coffeevalley_jp",
    website: "https://coffeevalley.jp",
    editorial_blurb: "Coffee Valley roasts its own beans on site at its Ikebukuro 'Lab' — the 3PEAKS flight lets you compare espresso, macchiato and drip side by side.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Streamer Coffee Harajuku",
    slug: "streamer-coffee-harajuku",
    lat: 35.6722, lng: 139.7097,
    google_place_id: "ChIJVZU_zqKMGGARfsjU4BRZplE",
    city: "Tokyo", country: "Japan",
    address: "3-chōme-28-10 Jingūmae, Shibuya, Tokyo 150-0001, Japan",
    roaster: "Streamer Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "outdoor-seating"],
    instagram_handle: "streamercoffee",
    website: "https://streamer.coffee/",
    editorial_blurb: "Streamer's Harajuku location puts championship latte art in front of a street-fashion crowd — the espresso behind it is what keeps coffee people coming back.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Single O Hamacho",
    slug: "single-o-hamacho",
    lat: 35.6841, lng: 139.7893,
    google_place_id: "ChIJyRUIqI-JGGARO-v7FvoRgkw",
    city: "Tokyo", country: "Japan",
    address: "Japan, 〒103-0007 Tokyo, Chuo City, Nihonbashihamachō, 3-chōme−16−７ スプラウト日本橋浜町 1F",
    roaster: "Single O",
    roaster_family: true,
    brew_methods: ["espresso", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "singleojapan",
    website: "https://singleo.jp/",
    editorial_blurb: "Sydney-born Single O's first Tokyo café, in Hamacho — a six-tap Freepour bar for self-serve batch brew alongside a full espresso program.",
    featured_in: ["sprudge", "barista_magazine", "daily_coffee_news", "monocle"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },

  // ── SEOUL NEW (20) ───────────────────────────────────────────────────────────
  {
    name: "Fritz Coffee Company Yangjae",
    slug: "fritz-coffee-yangjae",
    lat: 37.4853, lng: 127.0322,
    google_place_id: "ChIJL9zyHkmhfDURwamGLjmKr68",
    city: "Seoul", country: "South Korea",
    address: "24-11 Gangnam-daero 37-gil, Seocho-gu, Seoul",
    roaster: "Fritz Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "fritzcoffeecompany",
    website: "https://fritz.co.kr/",
    editorial_blurb: "Fritz's Yangjae roastery is bigger than the Mapo original and just as precise — the weekend bread and coffee ritual here draws South Seoul's specialty faithful.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Anthracite Coffee Roasters Hapjeong",
    slug: "anthracite-coffee-hapjeong",
    lat: 37.5458, lng: 126.9184,
    google_place_id: "ChIJx6CwxdOYfDURcTPw_mx60ws",
    city: "Seoul", country: "South Korea",
    address: "10 Tojeong-ro 5-gil, Mapo-gu, Seoul",
    roaster: "Anthracite Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "anthracitecoffee",
    website: "https://www.anthracitecoffee.com/",
    editorial_blurb: "Hapjeong factory building turned multi-floor roastery showroom — the courtyard garden and the single-origins are equally worth the trip from anywhere in Seoul.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Café Onion Seongsu",
    slug: "cafe-onion-seongsu",
    lat: 37.5447, lng: 127.0582,
    google_place_id: "ChIJHb1ypJWkfDURb2d4XCjLluM",
    city: "Seoul", country: "South Korea",
    address: "8 Achasan-ro 9-gil, Seongdong-gu, Seoul",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["no-laptop", "outdoor-seating"],
    instagram_handle: "cafe_onion",
    editorial_blurb: "A 1970s factory turned bakery-café in Seongsu — bare concrete, exposed steel, and a queue for the pastries and coffee.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Coffee Han Jan",
    slug: "coffee-han-jan-seoul",
    lat: 37.5770, lng: 126.9679,
    google_place_id: "ChIJPQ7cl5CjfDURdSXmqQ9Lq-0",
    city: "Seoul", country: "South Korea",
    address: "16-1 Sajik-ro 9-gil, Jongno-gu, Seoul",
    roaster: "Coffee Han Jan (in-house, charcoal roast)",
    roaster_family: true,
    brew_methods: ["pour-over"],
    vibe_tags: ["standing-bar", "minimalist", "no-laptop"],
    instagram_handle: "coffeehanjanseoul",
    editorial_blurb: "Tiny Jongno standing bar where 'one cup of coffee' — the literal translation — is taken with utmost seriousness, brewed to order, and gone in minutes.",
    featured_in: ["timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Café de Muse",
    slug: "cafe-de-muse-seoul",
    lat: 37.5212, lng: 127.0198,
    google_place_id: "ChIJQXiM0aqjfDURbvkdZrHSOhk",
    city: "Seoul", country: "South Korea",
    address: "14-12 Apgujeong-ro 4-gil, Gangnam District, Seoul",
    roaster: "Multiple guest roasters",
    brew_methods: [],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "cafe.de.muse",
    editorial_blurb: "Apgujeong café confirmed open via Google Maps — its interior, roaster, and espresso program could not be independently verified.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "The Barn Sinsa",
    slug: "the-barn-seoul",
    lat: 37.5421, lng: 127.0576,
    google_place_id: "ChIJkbWaUuylfDUR73woH8IjnfU",
    city: "Seoul", country: "South Korea",
    address: "36 Dosan-daero 17-gil, Gangnam-gu, Seoul",
    roaster: "The Barn",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "thebarnberlin",
    website: "https://thebarnberlin.kr/",
    editorial_blurb: "Berlin's exacting light-roast roastery runs this Seongsu outpost — an espresso counter and hand-brew filter bar serving the same globally sourced lots as the original.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },

  // ── SINGAPORE NEW (12) ───────────────────────────────────────────────────────
  {
    name: "Liberty Coffee",
    slug: "liberty-coffee-singapore",
    lat: 1.2793, lng: 103.8537,
    google_place_id: "ChIJd0APPFMZ2jER_VX_CqRyP_o",
    city: "Singapore", country: "Singapore",
    address: "10 Marina Boulevard #01 - 04, Tower 2 Marina Bay Financial Centre, Singapore 018983",
    roaster: "Liberty Coffee",
    roaster_family: true,
    brew_methods: ["pour-over", "aeropress", "chemex", "french-press"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "libertycoffeesg",
    website: "https://www.libertycoffee.sg/",
    editorial_blurb: "Wholesale specialty roaster now run as a by-appointment brewing lab on Syed Alwi Road — the Jalan Besar café it once ran has closed.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Dutch Colony Coffee Co Fusionopolis",
    slug: "dutch-colony-coffee-fusionopolis",
    lat: 1.2989, lng: 103.7873,
    google_place_id: "ChIJhY0JzqIb2jERqFsfxj2ZcLA",
    city: "Singapore", country: "Singapore",
    address: "1 Fusionopolis Way, #01-01, Singapore 138632",
    roaster: "Dutch Colony Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "chemex", "cold-brew"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "dutchcolonycoffee",
    website: "https://www.dutchcolony.sg/",
    editorial_blurb: "One-north tech-hub location serving the research campus community with the same quality-first approach as the original — a specialist café in a specialist district.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },

  // ── TAIPEI NEW (11) ──────────────────────────────────────────────────────────
  {
    name: "Congrats Espresso",
    slug: "congrats-espresso-taipei",
    lat: 25.0330, lng: 121.5506,
    google_place_id: "ChIJeytXpc2rQjQRr5wP80LPwTQ",
    city: "Taipei", country: "Taiwan",
    address: "49 Wenchang St, Da'an District, Taipei",
    roaster: "Congrats Coffee Roasters",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["standing-bar", "minimalist", "no-laptop"],
    instagram_handle: "congratsespresso",
    editorial_blurb: "Da'an café pouring self-roasted single-origin blends and hand-drip coffee in a quietly wabi-sabi-inspired space.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Costumice Café",
    slug: "costumice-cafe-taipei",
    lat: 25.0438, lng: 121.5525,
    google_place_id: "ChIJ-UiJasSrQjQRU4T8FGqhO1E",
    city: "Taipei", country: "Taiwan",
    address: "1F, No.6, Aly. 71, Ln. 223, Sec. 4, Zhongxiao E Rd, Da'an District, Taipei",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "costumice",
    editorial_blurb: "Da'an boutique café near Zhongxiao Dunhua with a specialty program that matches its editorial aesthetic shot for shot.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Zhanlu Coffee Da'an",
    slug: "zhanlu-coffee-daan-taipei",
    lat: 25.0346, lng: 121.5333,
    google_place_id: "ChIJ2WvYcX-pQjQR62iQUsj5j6U",
    city: "Taipei", country: "Taiwan",
    address: "Da'an District, Taipei",
    roaster: "Zhanlu Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "syphon", "cold-brew"],
    vibe_tags: ["laptop-friendly"],
    instagram_handle: "zhanlucoffee",
    website: "https://www.zhanlu.com.tw/",
    editorial_blurb: "Self-roasting Da'an café from a longtime specialty-coffee pioneer — known for tableside siphon and hand-pour service, including washed Ethiopian origins.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },

  // ── OSAKA NEW (6) ────────────────────────────────────────────────────────────
  {
    name: "Unir Coffee Osaka",
    slug: "unir-coffee-osaka",
    lat: 34.7028, lng: 135.4985,
    google_place_id: "ChIJH8fTW5LmAGARsHx9xxu-ERI",
    city: "Osaka", country: "Japan",
    address: "8-7 Kakudacho, Kita-ku, Osaka 530-8350",
    roaster: "Unir Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["laptop-friendly"],
    instagram_handle: "unircoffee",
    website: "https://unir-coffee.com",
    editorial_blurb: "Kyoto/Nagaokakyo roaster Unir's standing-only counter inside Hankyu Umeda's 10F food hall — staffed by Japan Barista Championship winners.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Streamer Coffee Osaka",
    slug: "streamer-coffee-osaka",
    lat: 34.6736, lng: 135.4980,
    google_place_id: "ChIJF1BpCxDnAGARCRPr-HiBm1E",
    city: "Osaka", country: "Japan",
    address: "Shinsaibashi, Chuo-ku, Osaka",
    roaster: "Streamer Coffee",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["minimalist", "outdoor-seating"],
    instagram_handle: "streamercoffee",
    website: "https://streamer.coffee/",
    editorial_blurb: "Streamer's Osaka foothold in the Shinsaibashi shopping corridor — the championship latte art draws the crowds; the espresso underneath is the real attraction.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },

  // ── HO CHI MINH CITY NEW (7) ─────────────────────────────────────────────────
  {
    name: "Là Việt Coffee",
    slug: "la-viet-coffee-hcmc",
    lat: 10.7776, lng: 106.6837,
    google_place_id: "ChIJxQVb87wvdTERh0Bxgv1YYjo",
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "57A Tú Xương, Xuân Hòa, Hồ Chí Minh, Vietnam",
    roaster: "Là Việt Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["laptop-friendly"],
    instagram_handle: "lavietcoffee",
    website: "https://laviet.coffee/",
    editorial_blurb: "Đà Lạt's pioneering specialty roaster, with a Saigon branch in District 3 — farm-to-cup highland arabica from its own farms and roastery.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Cộng Cà Phê",
    slug: "cong-ca-phe-hcmc",
    lat: 10.7782, lng: 106.7011,
    google_place_id: "ChIJnQcpCkgvdTERcdzIzC0f9f0",
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "26 Lý Tự Trọng, District 1, Ho Chi Minh City",
    roaster: "Cộng Cà Phê",
    brew_methods: [],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "congcaphevietnam",
    website: "https://congcaphe.com/",
    editorial_blurb: "North Vietnamese army-chic aesthetic with a coconut cold brew that defines the genre — the communist nostalgia décor is very deliberate and very effective.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "The Café Apartment",
    slug: "the-cafe-apartment-hcmc",
    lat: 10.7741, lng: 106.7041,
    google_place_id: "ChIJP4LyNAAvdTERp2XLe0QvLeU",
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "42 Nguyen Hue, District 1, Ho Chi Minh City",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "thecafeapartment",
    editorial_blurb: "Nine floors of independent cafés inside a 1960s Nguyen Hue building — the rooftop views and the street-level espresso bars each reward a different floor stop.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Bosgaurus Coffee Roasters – The Opera House",
    slug: "bosgaurus-coffee-opera-house-hcmc",
    lat: 10.7795, lng: 106.7059,
    google_place_id: "ChIJf4AVMzovdTERJKVKdFF8NgI",
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "12 Nguyễn Siêu, Bến Nghé, District 1, Ho Chi Minh City",
    roaster: "Bosgaurus Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "cold-brew", "syphon"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "bosgaurus",
    website: "https://bosgauruscoffee.com",
    editorial_blurb: "Bosgaurus's Opera House outpost near Nguyen Sieu, District 1 — the same in-house-roasted specialty program as the Saigon Pearl original.",
    featured_in: ["sprudge", "barista_magazine"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  // ── BENGALURU (9) ────────────────────────────────────────────────────────
  {
    name: "Third Wave Coffee",
    slug: "third-wave-coffee-lavelle-road",
    lat: 12.9714, lng: 77.5979,
    google_place_id: "ChIJcTcsJ1sXrjsR4zBGxzA2Ae8",
    city: "Bengaluru", country: "India",
    address: "Corporation No 13, Old No 4/1, Ground Floor, Lavelle Road Junction, Walton, Bengaluru, Karnataka 560001",
    roaster: "Third Wave Coffee Roasters",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["laptop-friendly"],
    instagram_handle: "thirdwavecoffeeindia",
    website: "https://www.thirdwavecoffeeroasters.com",
    editorial_blurb: "Third Wave Coffee grew from a single Bengaluru roastery into the closest thing India has to a national specialty chain, and this Lavelle Road location — steps from UB City — is where the city's business crowd gets its microlot fix between meetings.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Araku Coffee",
    slug: "araku-coffee-indiranagar",
    lat: 12.9699, lng: 77.6392,
    google_place_id: "ChIJu3MeVd0XrjsRej9BlCg4hv4",
    city: "Bengaluru", country: "India",
    address: "968, 12th Main Road, HAL 2nd Stage, Doopanahalli, Indiranagar, Bengaluru, Karnataka 560008",
    roaster: "Araku Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "aeropress", "french-press", "chemex"],
    vibe_tags: ["minimalist"],
    instagram_handle: "arakucoffeein",
    website: "https://www.arakucoffee.in",
    editorial_blurb: "Araku's flagship folds roastery, café, and SCA training room into one Indiranagar address — the coffee traces back to a tribal-farmer cooperative in Andhra Pradesh's Eastern Ghats, organic and regenerative from soil to cup.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Maverick & Farmer Coffee",
    slug: "maverick-farmer-koramangala",
    lat: 12.9354, lng: 77.6284,
    google_place_id: "ChIJ-UMGCUQVrjsRTI-9SL-bEhk",
    city: "Bengaluru", country: "India",
    address: "163, 15th Main Rd, 4th Block, Koramangala, Bengaluru, Karnataka 560034, India",
    roaster: "Maverick & Farmer Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "aeropress", "cold-brew"],
    vibe_tags: ["laptop-friendly"],
    instagram_handle: "maverickandfarmer",
    website: "https://www.maverickandfarmer.com",
    editorial_blurb: "One of the few genuinely bean-to-cup operations in India — Maverick & Farmer grows its own arabica on a Coorg estate before roasting and hand-brewing it at this easygoing Koramangala outpost.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Black Baza Coffee Co.",
    slug: "black-baza-coffee-sahakara-nagar",
    lat: 13.0604, lng: 77.5791,
    google_place_id: "ChIJY13jtAQYrjsRaPdFiTowTUA",
    city: "Bengaluru", country: "India",
    address: "Shop 1933, 3rd Main, C Block, Sahakara Nagar, Bengaluru, Karnataka 560092",
    roaster: "Black Baza Coffee Co.",
    roaster_family: true,
    brew_methods: [],
    vibe_tags: [],
    instagram_handle: "blackbazacoffee",
    website: "https://www.blackbazacoffee.com",
    editorial_blurb: "Founded by an ecologist, Black Baza names its roasts after endangered Western Ghats species and pays farmers to keep shade canopy intact — activism you can taste, and a recent SCA Sustainability Award winner to prove the model works.",
    featured_in: ["barista_magazine"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Matteo Coffea",
    slug: "matteo-coffea-indiranagar",
    lat: 12.9782, lng: 77.6438,
    google_place_id: "ChIJEdVNhKQWrjsRIJkyIYIKY9s",
    city: "Bengaluru", country: "India",
    address: "Melmat Building, 508, Chinmaya Mission Hospital (CMH) Road, Defence Colony, Indiranagar, Bengaluru, Karnataka 560038",
    roaster: "Unknown — no named roaster or supplier found across menu, social, or directory sources",
    brew_methods: ["espresso"],
    vibe_tags: ["laptop-friendly"],
    editorial_blurb: "A long-running Indiranagar restaurant with a sprawling food-and-coffee menu — reliably busy, though no evidence backs the \"biggest specialty coffee\" claim.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "GB Roasters / TrueBrew Café",
    slug: "gb-roasters-truebrew-indiranagar",
    lat: 12.9693, lng: 77.6359,
    google_place_id: "ChIJwxQv6zvwvwoRJBl_Kskw4s4",
    city: "Bengaluru", country: "India",
    address: "3163, 12th A Main Road, HAL 2nd Stage, Indiranagar, Bengaluru, Karnataka 560008",
    roaster: "GB Roasters",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly"],
    instagram_handle: "gb.roasters",
    website: "https://www.gbroastery.com",
    editorial_blurb: "GB Roasters' micro-batches — rare microlots cupped and profiled by a certified Q Grader — get served fresh next door at TrueBrew Café, making this one of the few Bengaluru spots where the roaster and the cup share an address.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Nandan Coffee",
    slug: "nandan-coffee-ganganagar",
    lat: 13.0194, lng: 77.5843,
    google_place_id: "ChIJU1dFsHMXrjsR2dKrSKfYNZY",
    city: "Bengaluru", country: "India",
    address: "Embassy One, Pinnacle Tower, 8 Bellary Road, Dena Bank Colony, Ganganagar, Bengaluru, Karnataka 560032",
    roaster: "Nandan Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "french-press", "cold-brew"],
    vibe_tags: ["minimalist"],
    instagram_handle: "nandancoffee",
    website: "https://nandancoffee.com",
    editorial_blurb: "Nandan controls every link of the chain from its own Palani Hills estate to the marble bar here, and the dedicated filter kaapi station is a rare sight — full South Indian tradition served with third-wave polish.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  // ── MUMBAI (10) ──────────────────────────────────────────────────────────
  {
    name: "Subko Specialty Coffee Roasters & Bakehouse",
    slug: "subko-mary-lodge-bandra",
    lat: 19.053165, lng: 72.830114,
    city: "Mumbai", country: "India",
    address: "Ground Floor, Mary Lodge, 21A, Chapel Road, Ranwar, Bandra West, Mumbai 400050",
    roaster: "Subko",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "subko.coffee",
    website: "https://subko.coffee",
    editorial_blurb: "A restored 1920s Bandra bungalow turned roastery-bakehouse, Subko runs fermentation and direct-trade experiments on Indian beans ambitious enough to have drawn international attention — get the filter and a laminated bun.",
    featured_in: ["sprudge", "barista_magazine", "monocle"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Blue Tokai Coffee Roasters",
    slug: "blue-tokai-bandra",
    lat: 19.0604, lng: 72.8243,
    google_place_id: "ChIJq6pLrmvJ5zsR9C5yYxXM-Sc",
    city: "Mumbai", country: "India",
    address: "Shop No. 1, Mayflower Building, 33 New Kantwadi Lane, Perry Road, Bandra West, Mumbai 400050",
    roaster: "Blue Tokai Coffee Roasters",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "bluetokaicoffeeroasters",
    website: "https://bluetokaicoffee.com",
    editorial_blurb: "India's pioneering specialty-coffee chain built its name on transparent, farm-direct sourcing from Coorg and Chikmagalur estates — this Bandra outpost is a reliable, unpretentious pour-over stop amid the neighborhood's flashier newcomers.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Bombay Island Coffee Company",
    slug: "bombay-island-coffee-vikhroli",
    lat: 19.0931, lng: 72.9202,
    google_place_id: "ChIJazGfY4_H5zsR3azFNpD91Rc",
    city: "Mumbai", country: "India",
    address: "Godrej One, Shop #4, Tower C, Retail Street, The Trees, Pirojshanagar, Vikhroli East, Mumbai 400079",
    roaster: "Bombay Island Coffee Roasters",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["laptop-friendly"],
    instagram_handle: "bombayisland",
    website: "https://bombayisland.com",
    editorial_blurb: "Founded in 2018, this suburban roaster-café roasts its own beans on an in-house Probat — a destination-worthy pour deep in Mumbai's eastern office corridor.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Grey Soul Coffee Roasters",
    slug: "grey-soul-coffee-bandra",
    lat: 19.0648, lng: 72.8299,
    google_place_id: "ChIJP-8ZoO_J5zsR7s9oX3bVa54",
    city: "Mumbai", country: "India",
    address: "Dr Ambedkar Rd, next to Wellness Forever, opp. Zig Zag Road, Pali Village, Bandra West, Mumbai, Maharashtra 400050, India",
    roaster: "Grey Soul Coffee Roasters",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "aeropress", "chemex"],
    vibe_tags: ["outdoor-seating"],
    instagram_handle: "greysoulcoffee",
    website: "https://greysoul.coffee",
    editorial_blurb: "An in-house roastery with a slow bar — hand-brewed Chemex, V60 and Aeropress from single-origin Indian beans sourced across Chikmagalur, Coorg, Yercaud and Nagaland.",
    featured_in: ["barista_magazine"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Nandan Coffee",
    slug: "nandan-coffee-kala-ghoda",
    lat: 18.9315, lng: 72.8319,
    google_place_id: "ChIJwfDqG3rR5zsR78baavyjGns",
    city: "Mumbai", country: "India",
    address: "Mulla House, 34 Homi Modi Street, opposite Central Bank Head Office, Kala Ghoda, Fort, Mumbai 400001",
    roaster: "Nandan Coffee",
    roaster_family: true,
    brew_methods: ["espresso"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "nandancoffee",
    website: "https://nandancoffee.com",
    editorial_blurb: "A farm-to-cup operation running its own Kodaikanal estate at 4,500 feet, Nandan's white-walled Fort flagship is where South India's high-altitude arabica meets Kala Ghoda's gallery-district hush.",
    featured_in: ["barista_magazine"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Toise Coffee Roastery + Brewstudio",
    slug: "toise-coffee-worli",
    lat: 19.0125, lng: 72.8217,
    google_place_id: "ChIJHTMzagDP5zsRv6jp2HUqZiA",
    city: "Mumbai", country: "India",
    address: "Shop No. 1, Dr Annie Besant Road, Adarsh Nagar, Worli, Mumbai 400030",
    roaster: "Toise",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["coworking"],
    instagram_handle: "toise.coffee",
    website: "https://toise.coffee",
    editorial_blurb: "Part café, part hands-on brew lab, Toise lets Worli regulars pull their own shots and dial in pour-overs on a rare small-batch electric roaster — a slowed-down retreat born from its founder's V60 obsession.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Araku Coffee",
    slug: "araku-coffee-colaba",
    lat: 18.9222, lng: 72.8325,
    google_place_id: "ChIJG7wUJOLR5zsRcVkxt-Oev6Q",
    city: "Mumbai", country: "India",
    address: "Sunny House, Mandlik Road, Apollo Bandar, Colaba, Mumbai 400001",
    roaster: "Araku Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "arakucoffeein",
    website: "https://arakucoffee.in",
    editorial_blurb: "Set inside a century-old Colaba building, Araku pours its own regeneratively farmed Eastern Ghats coffee, pairing seed-to-cup purism with a bakery mezzanine and cocktail bar upstairs.",
    featured_in: ["barista_magazine"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Boojee Cafe",
    slug: "boojee-cafe-bandra",
    lat: 19.0607, lng: 72.8246,
    google_place_id: "ChIJpVgsOFDJ5zsRMi5Myvre6zE",
    city: "Mumbai", country: "India",
    address: "Shop No. 6, 29 New Kantwadi Road, off Perry Cross Road, Bandra West, Mumbai 400050",
    roaster: "Boojee",
    roaster_family: true,
    brew_methods: ["espresso", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "boojeecafe",
    website: "https://boojeecafe.com",
    editorial_blurb: "What started in 2019 as a fifteen-seat lane-side café has grown into a Bandra brunch landmark, roasting its own beans in-house and pouring an Espresso Chai Latte that's become a neighborhood signature.",
    featured_in: ["barista_magazine"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  // ── NEW DELHI (8) ────────────────────────────────────────────────────────
  {
    name: "Subko Coffee Roasters – LoCol",
    slug: "subko-lodhi-colony",
    lat: 28.5800, lng: 77.2214,
    google_place_id: "ChIJZYesSzDjDDkRRfYk-Q0QNyQ",
    city: "New Delhi", country: "India",
    address: "F/6, New Khanna Market, Lodhi Colony, Block D, Lodi Colony, New Delhi 110003",
    roaster: "Subko",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "subkocoffee",
    website: "https://subko.coffee",
    editorial_blurb: "Mumbai's cult roaster brought its design-forward, multi-species approach to a heritage Lodhi Colony building, turning South Indian filter coffee into a cocktail-bar-worthy \"SIF on the Rocks.\"",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Perch Wine & Coffee Bar",
    slug: "perch-khan-market",
    lat: 28.6000, lng: 77.2263,
    google_place_id: "ChIJO2trNejiDDkR_NfaZlpD-QU",
    city: "New Delhi", country: "India",
    address: "71, Khan Market, New Delhi 110003",
    roaster: "Kaffa Cerrado",
    brew_methods: ["espresso"],
    vibe_tags: ["laptop-friendly", "coworking"],
    instagram_handle: "perchindelhi",
    editorial_blurb: "Half wine bar, half coffee counter, Perch runs a rotating set of single-origins from Kenya to Indonesia by day and turns into a natural-wine haunt by night.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Savorworks Coffee & Chocolate Atelier",
    slug: "savorworks-chhatarpur",
    lat: 28.5010, lng: 77.1881,
    city: "New Delhi", country: "India",
    address: "D-86, 100 Feet Road, near Red Light Junction, Chhatarpur Enclave Phase 2, New Delhi 110074",
    roaster: "Savorworks",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["minimalist"],
    instagram_handle: "savorworksroasters",
    website: "https://savorworksroasters.com",
    editorial_blurb: "Part café, part working atelier — watch beans roast on one side and chocolate temper on the other, an only-in-Chhatarpur combination that's rare even by Delhi's ambitious standards.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Seven Seeds Coffee",
    slug: "seven-seeds-green-park",
    lat: 28.5592, lng: 77.2007,
    google_place_id: "ChIJg6OiO2rjDDkRSCm30REQsFs",
    city: "New Delhi", country: "India",
    address: "W-5, Arjun Nagar, Green Park, New Delhi 110016",
    roaster: "Seven Seeds Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "sevenseeds.coffee",
    editorial_blurb: "A South Delhi late-nighter that keeps its espresso machine running until 4am, Seven Seeds pairs gourmet brews with a leafy, Instagram-ready outdoor room built for long, unhurried nights.",
    featured_in: ["timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Common Time",
    slug: "common-time-khan-market",
    lat: 28.6005, lng: 77.2277,
    google_place_id: "ChIJBzmQHy3jDDkRhXXdJ46MzT0",
    city: "New Delhi", country: "India",
    address: "34, Khan Market (2nd floor), New Delhi 110003",
    roaster: "Common Time Coffee",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    editorial_blurb: "Tucked above a bookshop with a wall of vinyl and a balcony over Khan Market's trees, Common Time treats coffee as one part of a slower, record-shop kind of hangout.",
    featured_in: ["timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Blue Tokai Coffee Roasters",
    slug: "blue-tokai-saidulajab",
    lat: 28.5204, lng: 77.2023,
    city: "New Delhi", country: "India",
    address: "Khasra No. 258, Lane Number 3, Westend Marg, Saidulajab, New Delhi 110030",
    roaster: "Blue Tokai Coffee Roasters",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "cold-brew", "aeropress"],
    vibe_tags: ["outdoor-seating", "dog-friendly"],
    instagram_handle: "bluetokaicoffee",
    website: "https://bluetokaicoffee.com",
    editorial_blurb: "The roastery that kickstarted Delhi's specialty-coffee reckoning — this is the original factory-floor café where the beans that stock a dozen other addresses in the city actually get roasted.",
    featured_in: [],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
  {
    name: "Devan's",
    slug: "devans-lodhi-colony",
    lat: 28.5799, lng: 77.2220,
    google_place_id: "ChIJ922KgfTiDDkRPWI4k_Yjtok",
    city: "New Delhi", country: "India",
    address: "131, New Khanna Market, Lodhi Colony, Block D, Lodi Colony, New Delhi 110003",
    roaster: "Devan's",
    roaster_family: true,
    brew_methods: ["espresso", "pour-over", "aeropress", "french-press"],
    vibe_tags: ["no-laptop", "minimalist"],
    website: "https://devans.in",
    editorial_blurb: "Since 1962 this Malayali-run shop has sent the smell of toasting Arabica and Robusta drifting through Khanna Market — a living link between Delhi's South Indian filter-coffee culture and today's roasting scene.",
    featured_in: ["timeout"],
    verified: true, last_verified_at: "2026-09-13", verification_source: "admin",
  },
];
