import type { Cafe } from '@/types';

export const ASIA_RAW_CAFES: (Omit<Cafe, 'id' | 'created_at' | 'third_wave_score' | 'overall_rating' | 'review_count' | 'permanently_closed'> & { permanently_closed?: boolean })[] = [
  // ── TOKYO (20) ───────────────────────────────────────────────────────────────
  {
    name: "Fuglen Tokyo",
    slug: "fuglen-tokyo",
    lat: 35.6696, lng: 139.6916,
    city: "Tokyo", country: "Japan",
    address: "1-16-11 Tomigaya, Shibuya-ku, Tokyo",
    roaster: "Fuglen Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "fuglentokyo",
    website: "https://www.fuglen.com/",
    editorial_blurb: "Oslo's cult café landed in Tokyo and raised the bar for the entire city — order the pour-over and stay for the vintage furniture.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2025-11-01", verification_source: "admin",
  },
  {
    name: "Koffee Mameya",
    slug: "koffee-mameya",
    lat: 35.6654, lng: 139.7104,
    city: "Tokyo", country: "Japan",
    address: "4-15-3 Jingumae, Shibuya-ku, Tokyo",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso"],
    vibe_tags: ["standing-bar", "minimalist"],
    instagram_handle: "koffee_mameya",
    website: "https://koffee-mameya.com/",
    editorial_blurb: "No menu, no seating — just a barista asking what you want and delivering the precise cup you didn't know you needed.",
    featured_in: ["sprudge", "ny_times"],
    verified: true, last_verified_at: "2025-10-15", verification_source: "admin",
  },
  {
    name: "% Arabica Tokyo",
    slug: "arabica-tokyo-aoyama",
    lat: 35.6640, lng: 139.7099,
    city: "Tokyo", country: "Japan",
    address: "5-17-13 Minami-Aoyama, Minato-ku, Tokyo",
    roaster: "% Arabica",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "arabica.tokyo",
    website: "https://arabica.com/en/",
    editorial_blurb: "The Kyoto minimalist icon's Aoyama home — a white cube where the espresso is as considered as the architecture.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2025-11-08", verification_source: "admin",
  },
  {
    name: "Glitch Coffee & Roasters",
    slug: "glitch-coffee-tokyo",
    lat: 35.6963, lng: 139.7590,
    city: "Tokyo", country: "Japan",
    address: "3-16 Kanda Nishikicho, Chiyoda-ku, Tokyo",
    roaster: "Glitch Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "glitch_coffee",
    website: "https://glitchcoffee.com/",
    editorial_blurb: "Jimbocho roastery with a world-competition record and a filter menu that changes based on what's peaking — the most technically serious café in Tokyo.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-28", verification_source: "admin",
  },
  {
    name: "Onibus Coffee",
    slug: "onibus-coffee-nakameguro",
    lat: 35.6401, lng: 139.7004,
    city: "Tokyo", country: "Japan",
    address: "2-14-1 Kamimeguro, Meguro-ku, Tokyo",
    roaster: "Onibus Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "onibuscoffee",
    website: "https://onibuscoffee.com/",
    editorial_blurb: "Nakameguro roastery tucked off the canal — the Portuguese name (bus) fits a café built on movement, sourcing, and sharing.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-11-03", verification_source: "admin",
  },
  {
    name: "Woodberry Coffee Roasters",
    slug: "woodberry-coffee-tokyo",
    lat: 35.7122, lng: 139.7744,
    city: "Tokyo", country: "Japan",
    address: "1-19-8 Yanaka, Taito-ku, Tokyo",
    roaster: "Woodberry Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "laptop-friendly"],
    instagram_handle: "woodberrycoffee",
    website: "https://woodberrycoffee.com/",
    editorial_blurb: "Yanaka roastery in Tokyo's most atmospheric old neighborhood — Ethiopian and Central American lots roasted with uncommon clarity.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-18", verification_source: "admin",
  },
  {
    name: "Sarutahiko Coffee",
    slug: "sarutahiko-coffee-ebisu",
    lat: 35.6468, lng: 139.7099,
    city: "Tokyo", country: "Japan",
    address: "1-6-6 Ebisu, Shibuya-ku, Tokyo",
    roaster: "Sarutahiko Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["standing-bar", "minimalist"],
    instagram_handle: "sarutahiko_coffee",
    website: "https://sarutahiko.co",
    editorial_blurb: "Ebisu standing bar with an obsessive drip culture and a compact menu that never wastes your time or your palate.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-10", verification_source: "admin",
  },
  {
    name: "About Life Coffee Brewers",
    slug: "about-life-coffee-shibuya",
    lat: 35.6587, lng: 139.6979,
    city: "Tokyo", country: "Japan",
    address: "1-19-8 Dogenzaka, Shibuya-ku, Tokyo",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["standing-bar", "minimalist"],
    instagram_handle: "aboutlifecoffee",
    editorial_blurb: "Shibuya standing counter with a rotating guest-roaster program — the name is a provocation, the coffee makes good on it.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-05", verification_source: "admin",
  },
  {
    name: "Blue Bottle Coffee Kiyosumi",
    slug: "blue-bottle-kiyosumi-tokyo",
    lat: 35.6778, lng: 139.8052,
    city: "Tokyo", country: "Japan",
    address: "4-7-2 Hirano, Koto-ku, Tokyo",
    roaster: "Blue Bottle Coffee",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "bluebottlejpn",
    website: "https://bluebottlecoffee.com/",
    editorial_blurb: "Blue Bottle's Tokyo flagship in a converted Kiyosumi warehouse — the roastery that announced specialty coffee's arrival in Japan to a global audience.",
    featured_in: ["sprudge", "ny_times", "monocle"],
    verified: true, last_verified_at: "2025-11-02", verification_source: "admin",
  },
  {
    name: "Arise Coffee Entangle",
    slug: "arise-coffee-tokyo",
    lat: 35.6781, lng: 139.8044,
    city: "Tokyo", country: "Japan",
    address: "3-16-3 Shirakawa, Koto-ku, Tokyo",
    roaster: "Arise Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "arisecoffeeentangle",
    editorial_blurb: "Blue Bottle's neighbor in Kiyosumi-Shirakawa doing equally serious work in a fraction of the space — a local institution with a cult following.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-20", verification_source: "admin",
  },
  {
    name: "Bear Pond Espresso",
    slug: "bear-pond-espresso-tokyo",
    lat: 35.6615, lng: 139.6673,
    city: "Tokyo", country: "Japan",
    address: "2-36-12 Kitazawa, Setagaya-ku, Tokyo",
    roaster: "Bear Pond Espresso",
    brew_methods: ["espresso"],
    vibe_tags: ["standing-bar", "no-laptop"],
    instagram_handle: "bearpondespresso",
    website: "https://bearpondespresso.com",
    editorial_blurb: "Shimokitazawa espresso purist — a single counter, a single focus, and the most intensely discussed shot in Tokyo. Cash only, always worth it.",
    featured_in: ["sprudge", "guardian"],
    verified: true, last_verified_at: "2025-10-08", verification_source: "admin",
  },
  {
    name: "Streamer Coffee Company",
    slug: "streamer-coffee-shibuya",
    lat: 35.6597, lng: 139.6977,
    city: "Tokyo", country: "Japan",
    address: "1-20-28 Shibuya, Shibuya-ku, Tokyo",
    roaster: "Streamer Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "streamercoffee",
    website: "https://streamer.coffee/",
    editorial_blurb: "Streamer's latte art championship roots are on the walls; the espresso program that won those titles is in the cup.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-09-25", verification_source: "admin",
  },
  {
    name: "Nozy Coffee",
    slug: "nozy-coffee-sangenjaya",
    lat: 35.6439, lng: 139.6708,
    city: "Tokyo", country: "Japan",
    address: "5-17-13 Sangenjaya, Setagaya-ku, Tokyo",
    roaster: "Nozy Coffee",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "nozycoffee",
    website: "https://nozy-coffee.jp",
    editorial_blurb: "Sangenjaya roastery that helped define Tokyo's third-wave generation — the outdoor bench and a single-origin V60 are all you need here.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-09-15", verification_source: "admin",
  },
  {
    name: "Coffee Supreme Tokyo",
    slug: "coffee-supreme-tokyo",
    lat: 35.6690, lng: 139.7079,
    city: "Tokyo", country: "Japan",
    address: "6-12-6 Jingumae, Shibuya-ku, Tokyo",
    roaster: "Coffee Supreme",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "coffeesupreme",
    website: "https://coffeesupreme.com/",
    editorial_blurb: "New Zealand's most revered roastery in the heart of Harajuku — the Antipodean irreverence and the technical precision are both very real.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2025-10-22", verification_source: "admin",
  },
  {
    name: "Passage Coffee",
    slug: "passage-coffee-shiba",
    lat: 35.6535, lng: 139.7454,
    city: "Tokyo", country: "Japan",
    address: "5-14-16 Shiba, Minato-ku, Tokyo 108-0014",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "passagecoffee",
    website: "https://passagecoffee.com/",
    editorial_blurb: "Shiba roastery café where the guest-roaster list reads like a Tokyo specialty map — the kind of precise, unhurried bar that rewards a deliberate detour.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-09-28", verification_source: "admin",
  },
  {
    name: "Paul Bassett",
    slug: "paul-bassett-shinjuku",
    lat: 35.6900, lng: 139.6919,
    city: "Tokyo", country: "Japan",
    address: "1-26-2 Nishishinjuku, B1F Nomura Building, Shinjuku-ku, Tokyo 163-0590",
    roaster: "Paul Bassett",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "paulbassettcoffee",
    website: "https://www.paulbassett.com/",
    editorial_blurb: "World barista champion Paul Bassett's Shinjuku flagship in the Nomura Building basement — the espresso-as-craft philosophy translates into one of Tokyo's most quietly excellent menus.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-15", verification_source: "admin",
  },
  {
    name: "Café Kitsuné Aoyama",
    slug: "cafe-kitsune-aoyama-tokyo",
    lat: 35.6641, lng: 139.7121,
    city: "Tokyo", country: "Japan",
    address: "3-17-1 Minami-Aoyama, Minato-ku, Tokyo",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "cafekitsune",
    website: "https://cafekitsune.com/",
    editorial_blurb: "Fashion house garden café in Aoyama where the design is exceptional and the specialty espresso is serious — both are reasons to visit.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2025-11-06", verification_source: "admin",
  },
  {
    name: "Coffee Wrights Sendagaya",
    slug: "coffee-wrights-sendagaya",
    lat: 35.6810, lng: 139.7092,
    city: "Tokyo", country: "Japan",
    address: "4-3-4 Sendagaya, Shibuya-ku, Tokyo",
    roaster: "Coffee Wrights",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "outdoor-seating"],
    instagram_handle: "coffee_wrights",
    website: "https://coffee-wrights.jp",
    editorial_blurb: "Yoyogi Park-adjacent coffee stand that captures what Tokyo neighbourhood specialty does best — a small menu, rotating origins, and no fuss.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-09-18", verification_source: "community",
  },

  // ── SEOUL (15) ───────────────────────────────────────────────────────────────
  {
    name: "Fritz Coffee Company",
    slug: "fritz-coffee-seoul",
    lat: 37.5139, lng: 126.9931,
    city: "Seoul", country: "South Korea",
    address: "11-5 Mapo-daero 18-gil, Mapo-gu, Seoul",
    roaster: "Fritz Coffee",
    brew_methods: ["pour-over", "espresso", "syphon"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "fritzcoffeecompany",
    website: "https://www.fritzcoffee.co.kr/",
    editorial_blurb: "Seoul's most beloved roastery café — the Saturday morning queue is a pilgrimage and the single-origins justify every minute of it.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-11-06", verification_source: "admin",
  },
  {
    name: "Namusairo",
    slug: "namusairo-seoul",
    lat: 37.5796, lng: 126.9770,
    city: "Seoul", country: "South Korea",
    address: "21 Jahamun-ro 5-gil, Jongno-gu, Seoul",
    roaster: "Namusairo",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "namusairo",
    website: "https://en.namusairo.com",
    editorial_blurb: "Tucked in Bukchon Hanok Village, Namusairo pairs traditional architecture with technically immaculate pour-overs — a rare combination.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2025-10-08", verification_source: "admin",
  },
  {
    name: "% Arabica Seoul Hannam",
    slug: "arabica-seoul-hannam",
    lat: 37.5327, lng: 127.0014,
    city: "Seoul", country: "South Korea",
    address: "35 Daesagwan-ro, 2F, Yongsan-gu, Seoul 04420",
    roaster: "% Arabica",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "arabica.kr",
    website: "https://arabica.com/en/",
    editorial_blurb: "Kyoto's global minimalist icon in Hannam — the same quiet precision, the same exceptional espresso, the same insistence on doing one thing right.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-25", verification_source: "admin",
  },
  {
    name: "Onion Anguk",
    slug: "onion-anguk-seoul",
    lat: 37.5790, lng: 126.9869,
    city: "Seoul", country: "South Korea",
    address: "102 Gyedong-gil, Jongno-gu, Seoul",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["no-laptop", "outdoor-seating"],
    instagram_handle: "onion.anguk",
    editorial_blurb: "Bukchon heritage building turned brutalist bakery-café — the concrete interior and the cardamom croissants are both reasons to queue.",
    featured_in: ["sprudge", "guardian"],
    verified: true, last_verified_at: "2025-10-30", verification_source: "admin",
  },
  {
    name: "Coffee Libre",
    slug: "coffee-libre-seoul",
    lat: 37.5578, lng: 126.9266,
    city: "Seoul", country: "South Korea",
    address: "227-15 Yeonnam-dong, Mapo-gu, Seoul 03985",
    roaster: "Coffee Libre",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "coffeelibrekorea",
    website: "https://coffeelibre.kr/",
    editorial_blurb: "Yeonnam-dong roastery that built the Seoul specialty movement before it had a name — their Latin American sourcing program is still the city's best.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-18", verification_source: "admin",
  },
  {
    name: "Anthracite Coffee Roasters",
    slug: "anthracite-coffee-seoul",
    lat: 37.5435, lng: 126.9908,
    city: "Seoul", country: "South Korea",
    address: "131 Itaewon-ro, Yongsan-gu, Seoul",
    roaster: "Anthracite Coffee",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "anthracitecoffee",
    website: "https://www.anthracitecoffee.com/",
    editorial_blurb: "Itaewon industrial roastery in a converted shoe factory — the space is as compelling as the light-roast single-origins brewed inside it.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-11-01", verification_source: "admin",
  },
  {
    name: "Manufact Coffee Roasters",
    slug: "manufact-coffee-seoul",
    lat: 37.5675, lng: 126.9339,
    city: "Seoul", country: "South Korea",
    address: "29 Yeonhui-ro 11-gil, 2F, Seodaemun-gu, Seoul",
    roaster: "Manufact Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "manufactcoffee",
    website: "https://www.manufactcoffee.com/",
    editorial_blurb: "Yeonhui roastery café with a serious light-roast commitment and a filter program that's been shaping Seoul palates for years.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-12", verification_source: "admin",
  },
  {
    name: "Terarosa Coffee Seoul",
    slug: "terarosa-coffee-seoul",
    lat: 37.5091, lng: 127.0581,
    city: "Seoul", country: "South Korea",
    address: "440 Teheran-ro, POSCO Center, Gangnam-gu, Seoul 06194",
    roaster: "Terarosa Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "terarosacoffee",
    website: "https://www.terarosa.com/",
    editorial_blurb: "Gangneung's legendary roastery in Seoul — Terarosa's POSCO Center outpost brings the same obsessive sourcing and light-roast conviction to the capital.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-11-04", verification_source: "admin",
  },
  {
    name: "Lowkey Coffee Seongsu",
    slug: "lowkey-coffee-seongsu",
    lat: 37.5463, lng: 127.0555,
    city: "Seoul", country: "South Korea",
    address: "6 Yeonmujang 3-gil, Seongdong-gu, Seoul",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "lowkey_coffee",
    website: "https://en.lowkeycoffee.co.kr/",
    editorial_blurb: "Seongsu specialty bar where the name is the ethos — no flashy design, just excellent espresso and a rotating filter menu worth returning for.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-09-18", verification_source: "community",
  },
  {
    name: "Felt Coffee",
    slug: "felt-coffee-seoul",
    lat: 37.5696, lng: 126.9863,
    city: "Seoul", country: "South Korea",
    address: "14 Cheonggyecheon-ro, Jung-gu, Seoul",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "felt_seoul",
    website: "https://en.feltcoffee.com/",
    editorial_blurb: "Cheonggyecheon-side café with a warm atmosphere and a filter menu that changes more often than you'd expect — always worth the detour.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-09-10", verification_source: "community",
  },
  {
    name: "Café Layered",
    slug: "cafe-layered-anguk",
    lat: 37.5808, lng: 126.9843,
    city: "Seoul", country: "South Korea",
    address: "2-3 Bukchon-ro 2-gil, Jongno-gu, Seoul",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "cafe_layered",
    editorial_blurb: "Anguk multi-floor café where the specialty coffee is as considered as the layered Korean desserts — a neighborhood institution with staying power.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-09-15", verification_source: "community",
  },

  // ── SINGAPORE (12) ───────────────────────────────────────────────────────────
  {
    name: "Nylon Coffee Roasters",
    slug: "nylon-coffee-singapore",
    lat: 1.2796, lng: 103.8390,
    city: "Singapore", country: "Singapore",
    address: "4 Everton Park #01-40, Singapore 080004",
    roaster: "Nylon Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "nyloncoffee",
    website: "https://www.nyloncoffee.sg/",
    editorial_blurb: "Tanjong Pagar institution that defined Singapore specialty — Everton Park HDB block setting is as iconic as the coffee itself.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2025-11-06", verification_source: "admin",
  },
  {
    name: "Cata Coffee",
    slug: "cata-singapore",
    lat: 1.3068, lng: 103.9012,
    city: "Singapore", country: "Singapore",
    address: "56 Joo Chiat Pl, Singapore 427780",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "cata_sg",
    website: "https://catacoffee.com/",
    editorial_blurb: "Where Singapore's wine bar scene meets specialty coffee — the curated pairing menu in this Joo Chiat shophouse makes Cata one of the city's most original concepts.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-15", verification_source: "admin",
  },
  {
    name: "Chye Seng Huat Hardware",
    slug: "chye-seng-huat-singapore",
    lat: 1.3127, lng: 103.8644,
    city: "Singapore", country: "Singapore",
    address: "150 Tyrwhitt Rd, Singapore 207563",
    roaster: "PPP Coffee",
    brew_methods: ["pour-over", "espresso", "syphon", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "laptop-friendly"],
    instagram_handle: "cshhardware",
    website: "https://www.cshhardware.com/",
    editorial_blurb: "Converted hardware shop turned café flagship for PPP Coffee — the courtyard, the pour-overs, and the industrial bones are all reasons to visit.",
    featured_in: ["sprudge", "guardian"],
    verified: true, last_verified_at: "2025-10-28", verification_source: "admin",
  },
  {
    name: "Common Man Coffee Roasters",
    slug: "common-man-coffee-singapore",
    lat: 1.2888, lng: 103.8400,
    city: "Singapore", country: "Singapore",
    address: "22 Martin Rd, Singapore 239058",
    roaster: "Common Man Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "commonmancoffeeroasters",
    website: "https://www.commonmancoffeeroasters.com/",
    editorial_blurb: "Robertson Quay roastery that made specialty coffee accessible without dumbing it down — the training academy and the café are both world-class.",
    featured_in: ["sprudge", "standart", "monocle"],
    verified: true, last_verified_at: "2025-11-05", verification_source: "admin",
  },
  {
    name: "Sarnies",
    slug: "sarnies-singapore",
    lat: 1.2815, lng: 103.8480,
    city: "Singapore", country: "Singapore",
    address: "136 Telok Ayer St, Singapore 068601",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["no-laptop", "outdoor-seating"],
    instagram_handle: "sarniessg",
    website: "https://sarnies.com/",
    editorial_blurb: "Telok Ayer shophouse café where the Antipodean sandwich and the flat white are equally non-negotiable — CBD specialty coffee done right.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2025-10-20", verification_source: "admin",
  },
  {
    name: "PPP Coffee New Bahru",
    slug: "ppp-coffee-singapore",
    lat: 1.2970, lng: 103.8345,
    city: "Singapore", country: "Singapore",
    address: "46 Kim Yam Rd, #01-06, Singapore 239351",
    roaster: "PPP Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "ppp.coffee",
    website: "https://pppcoffee.com/",
    editorial_blurb: "PPP Coffee's New Bahru flagship — one of Singapore's most progressive specialty programs, with a sourcing philosophy that built a loyal following long before the café existed.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-10", verification_source: "admin",
  },
  {
    name: "Jewel Coffee",
    slug: "jewel-coffee-singapore",
    lat: 1.2792, lng: 103.8481,
    city: "Singapore", country: "Singapore",
    address: "1 Shenton Way, #01-07, Singapore 068803",
    roaster: "Jewel Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "jewelcoffeesg",
    website: "https://jewelcoffee.com/",
    editorial_blurb: "CBD specialty café serving some of the city's most consistent espresso to Singapore's finance district — the after-work filter crowd is loyal for a reason.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-09-25", verification_source: "admin",
  },
  {
    name: "Tiong Hoe Specialty Coffee",
    slug: "tiong-hoe-coffee-singapore",
    lat: 1.2889, lng: 103.8113,
    city: "Singapore", country: "Singapore",
    address: "Blk 170 Stirling Rd, #01-1133, Singapore 140170",
    roaster: "Tiong Hoe",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "tionghoecoffee",
    website: "https://tionghoe.com/",
    editorial_blurb: "Queenstown roastery that's been quietly excellent for longer than most — the house roasts and the barista knowledge both reward the regular.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-08", verification_source: "admin",
  },

  // ── TAIPEI (11) ──────────────────────────────────────────────────────────────
  {
    name: "Fika Fika Café",
    slug: "fika-fika-taipei",
    lat: 25.0611, lng: 121.5237,
    city: "Taipei", country: "Taiwan",
    address: "No. 33, Yitong St, Zhongshan District, Taipei 104",
    roaster: "Fika Fika",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "fikafika_cafe",
    website: "https://www.fikafikacafe.com/",
    editorial_blurb: "Taiwan's first Scandinavian-style roastery brought light-roast competition culture to Taipei — and the city never looked back.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-11-02", verification_source: "admin",
  },
  {
    name: "Simple Kaffa",
    slug: "simple-kaffa-taipei",
    lat: 25.0290, lng: 121.5434,
    city: "Taipei", country: "Taiwan",
    address: "No. 54, Lane 243, Sec 1, Dunhua S Rd, Da'an, Taipei",
    roaster: "Simple Kaffa",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "simplekaffa",
    website: "https://simplekaffa.com/",
    editorial_blurb: "World barista champion Berg Wu's Da'an flagship — technically flawless espresso from a café that's earned every accolade it carries.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2025-11-08", verification_source: "admin",
  },
  {
    name: "Rufous Coffee",
    slug: "rufous-coffee-taipei",
    lat: 25.0585, lng: 121.5224,
    city: "Taipei", country: "Taiwan",
    address: "No. 1, Lane 40, Xinsheng N Rd, Zhongshan, Taipei",
    roaster: "Rufous Coffee",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "rufous_coffee",
    website: "https://www.rufous.com.tw/",
    editorial_blurb: "Zhongshan's serious single-origin program draws the kind of crowd that wants to talk about altitude and processing — and the baristas are ready.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-05", verification_source: "admin",
  },
  {
    name: "% Arabica Taipei",
    slug: "arabica-taipei",
    lat: 25.0534, lng: 121.5249,
    city: "Taipei", country: "Taiwan",
    address: "Zhongshan District, Taipei",
    roaster: "% Arabica",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "arabica.taipei",
    website: "https://arabica.com/en/",
    editorial_blurb: "The Kyoto minimalist icon in Zhongshan — the same precision pour-over, the same calm intention, the same reason to stay for a second cup.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-20", verification_source: "admin",
  },
  {
    name: "Gabee Coffee",
    slug: "gabee-coffee-taipei",
    lat: 25.0546, lng: 121.5311,
    city: "Taipei", country: "Taiwan",
    address: "No. 8, Lane 96, Zhongshan N Rd, Zhongshan, Taipei",
    roaster: "Gabee",
    brew_methods: ["espresso", "pour-over", "syphon"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "gabeecoffee",
    website: "https://www.gabee-cafe.com/",
    editorial_blurb: "Zhongshan latte art pioneer that helped build Taiwan's barista culture — still one of Taipei's most essential café-roastery experiences.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-28", verification_source: "admin",
  },
  {
    name: "MJCOFFEE",
    slug: "mjcoffee-taipei",
    lat: 25.0503, lng: 121.5268,
    city: "Taipei", country: "Taiwan",
    address: "Zhongshan District, Taipei",
    roaster: "MJCOFFEE",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "mjcoffee.tw",
    editorial_blurb: "Progressive Zhongshan specialty café with one of Taipei's most forward-thinking filter programs — the sourcing notes are always worth reading.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-10", verification_source: "admin",
  },
  {
    name: "15g Specialty Coffee",
    slug: "15g-specialty-taipei",
    lat: 25.0307, lng: 121.5411,
    city: "Taipei", country: "Taiwan",
    address: "Da'an District, Taipei",
    roaster: "15g",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "15g_coffee",
    editorial_blurb: "Da'an roastery built on competition-level sourcing and a belief that every gram matters — the filter menu rewards the curious.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-09-28", verification_source: "community",
  },
  {
    name: "Goodman Roaster",
    slug: "goodman-roaster-taipei",
    lat: 25.0328, lng: 121.5659,
    city: "Taipei", country: "Taiwan",
    address: "Xinyi District, Taipei",
    roaster: "Goodman Roaster",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "goodmanroaster",
    website: "https://goodmanroaster.tw/",
    editorial_blurb: "Xinyi roastery café doing serious filter work in the shadow of Taipei 101 — the setting is dramatic, the coffee is the reason to come back.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-05", verification_source: "community",
  },
  {
    name: "WA Living Coffee",
    slug: "wa-living-taipei",
    lat: 25.0540, lng: 121.5299,
    city: "Taipei", country: "Taiwan",
    address: "Zhongshan District, Taipei",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "wa_living",
    editorial_blurb: "Japanese-influenced lifestyle café in Zhongshan where the ceramics, the coffee, and the calm are equally worth your time.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-09-15", verification_source: "community",
  },
  {
    name: "Zhi Xin Coffee",
    slug: "zhi-xin-coffee-taipei",
    lat: 25.0499, lng: 121.5316,
    city: "Taipei", country: "Taiwan",
    address: "Zhongshan District, Taipei",
    roaster: "Zhi Xin Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "zhixincoffee",
    editorial_blurb: "Zhongshan roastery focused on Taiwanese-adjacent origins from Southeast Asia — a sourcing philosophy that makes the filter menu distinctly different.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-09-10", verification_source: "community",
  },
  {
    name: "Hiyori Coffee",
    slug: "hiyori-coffee-taipei",
    lat: 25.0434, lng: 121.5432,
    city: "Taipei", country: "Taiwan",
    address: "Da'an District, Taipei",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "hiyori_coffee_tw",
    website: "https://hiyoricoffee.square.site/",
    editorial_blurb: "Da'an specialty café where the Japanese-minimalist aesthetic and the rotating pour-over menu both reward multiple visits.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-09-05", verification_source: "community",
  },

  // ── OSAKA (10) ───────────────────────────────────────────────────────────────
  {
    name: "% Arabica Osaka Kitahama",
    slug: "arabica-osaka-kitahama",
    lat: 34.6898, lng: 135.5101,
    city: "Osaka", country: "Japan",
    address: "1-1-1 Kitahama, Chuo-ku, Osaka",
    roaster: "% Arabica",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "outdoor-seating", "no-laptop"],
    instagram_handle: "arabica.osaka",
    website: "https://arabica.com/en/",
    editorial_blurb: "Iconic river-facing minimalist space where Kitahama's beauty meets specialty precision — the best Instagram backdrop in Osaka that actually earns it.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2025-11-07", verification_source: "admin",
  },
  {
    name: "Kurasu Osaka",
    slug: "kurasu-osaka-shinsaibashi",
    lat: 34.6724, lng: 135.5011,
    city: "Osaka", country: "Japan",
    address: "1-7-1 Shinsaibashisuji, Chuo-ku, Osaka",
    roaster: "Kurasu",
    brew_methods: ["pour-over", "espresso", "aeropress", "chemex"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "kurasucoffee",
    website: "https://kurasu.kyoto/",
    editorial_blurb: "Kyoto roastery's Osaka flagship bringing direct-trade beans and Shinsaibashi foot traffic together — the pour-over menu rewards the extra walk.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-22", verification_source: "admin",
  },
  {
    name: "Mel Coffee Roasters",
    slug: "mel-coffee-roasters-osaka",
    lat: 34.6654, lng: 135.5032,
    city: "Osaka", country: "Japan",
    address: "Namba, Chuo-ku, Osaka",
    roaster: "Mel Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "melcoffeeroasters",
    website: "https://mel.coffee",
    editorial_blurb: "Namba roastery with a natural-process focus that stands apart from Osaka's lighter-roast mainstream — complex and worth seeking out.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-08", verification_source: "admin",
  },
  {
    name: "LiLo Coffee Roasters",
    slug: "lilo-coffee-osaka",
    lat: 34.6715, lng: 135.4993,
    city: "Osaka", country: "Japan",
    address: "1-7-19 Minamisenba, Chuo-ku, Osaka",
    roaster: "LiLo Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "lilocoffeeroasters",
    website: "https://lilocoffee.com/",
    editorial_blurb: "Minamisenba roastery that's quietly become one of the Kansai region's most respected — the African-origin filter program has no equal in Osaka.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-11-04", verification_source: "admin",
  },
  {
    name: "Takamura Wine & Coffee Roasters",
    slug: "takamura-coffee-osaka",
    lat: 34.6853, lng: 135.4908,
    city: "Osaka", country: "Japan",
    address: "1-1-35 Nishi-ku, Osaka",
    roaster: "Takamura",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating"],
    instagram_handle: "takamura_coffee",
    website: "https://takamura-coffee.com",
    editorial_blurb: "Utsubo Park-adjacent roastery that pairs natural wine sourcing sensibility with serious coffee — the best of two obsessive worlds under one roof.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-11-02", verification_source: "admin",
  },
  {
    name: "Graph Coffee",
    slug: "graph-coffee-osaka",
    lat: 34.6748, lng: 135.5018,
    city: "Osaka", country: "Japan",
    address: "Shinsaibashi, Chuo-ku, Osaka",
    roaster: "Graph Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "standing-bar"],
    instagram_handle: "graphcoffee",
    editorial_blurb: "Shinsaibashi standing bar with an analytical approach to extraction and a pour-over program that changes based on what's at peak — Osaka's most precise coffee stop.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-15", verification_source: "admin",
  },
  {
    name: "Fuglen Osaka",
    slug: "fuglen-osaka",
    lat: 34.6699, lng: 135.5007,
    city: "Osaka", country: "Japan",
    address: "Namba, Chuo-ku, Osaka",
    roaster: "Fuglen Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "outdoor-seating"],
    instagram_handle: "fuglenOsaka",
    website: "https://www.fuglen.com/",
    editorial_blurb: "Oslo's vintage-furniture café in Namba — the same precision Nordic pour-overs that made Tokyo's Fuglen famous, now with Osaka's energy.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-25", verification_source: "admin",
  },
  {
    name: "% Arabica Osaka Nakanoshima",
    slug: "arabica-osaka-nakanoshima",
    lat: 34.6905, lng: 135.4975,
    city: "Osaka", country: "Japan",
    address: "Nakanoshima, Kita-ku, Osaka",
    roaster: "% Arabica",
    brew_methods: ["pour-over", "espresso"],
    vibe_tags: ["minimalist", "outdoor-seating", "no-laptop"],
    instagram_handle: "arabica.nakanoshima",
    website: "https://arabica.com/en/",
    editorial_blurb: "Island location on the Dojima River — the Nakanoshima setting for % Arabica's second Osaka outpost may be their most beautiful globally.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-18", verification_source: "admin",
  },
  {
    name: "Maruyama Coffee Osaka",
    slug: "maruyama-coffee-osaka",
    lat: 34.6760, lng: 135.5025,
    city: "Osaka", country: "Japan",
    address: "Shinsaibashi, Chuo-ku, Osaka",
    roaster: "Maruyama Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "maruyamacoffee",
    website: "https://www.maruyamacoffee.com/",
    editorial_blurb: "Matsumoto legend's Osaka outpost bringing their COE-trophy sourcing program and immaculate pour-over technique to Kansai's biggest city.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-11-03", verification_source: "admin",
  },

  // ── HO CHI MINH CITY (9) ─────────────────────────────────────────────────────
  {
    name: "The Workshop Coffee",
    slug: "the-workshop-coffee-hcmc",
    lat: 10.7769, lng: 106.7009,
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "27 Ngo Duc Ke, District 1, Ho Chi Minh City",
    roaster: "The Workshop Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "theworkshop_coffee",
    website: "https://www.theworkshop.com.sg/",
    editorial_blurb: "Rooftop industrial space in District 1 that reimagined what a Vietnamese café could be — the specialty program here sets the city's benchmark.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2025-11-03", verification_source: "admin",
  },
  {
    name: "Shin Coffee",
    slug: "shin-coffee-hcmc",
    lat: 10.7793, lng: 106.6866,
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "4/2 Nguyen Thi Minh Khai, District 3, Ho Chi Minh City",
    roaster: "Shin Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "shincoffee",
    website: "https://shincaphe.vn",
    editorial_blurb: "Vietnamese robusta meets specialty arabica in District 3 — Shin bridges the country's coffee heritage with third-wave technique in a single menu.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-18", verification_source: "admin",
  },
  {
    name: "L'Usine",
    slug: "lusine-hcmc",
    lat: 10.7760, lng: 106.7005,
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "151/5 Dong Khoi, District 1, Ho Chi Minh City",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "lusinespace",
    website: "https://www.lusinespace.com/",
    editorial_blurb: "French colonial architecture meets third-wave coffee in the heart of District 1 — the design alone is reason to linger over a second cup.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2025-10-25", verification_source: "admin",
  },
  {
    name: "Bosgaurus Coffee Roasters",
    slug: "bosgaurus-coffee-hcmc",
    lat: 10.7788, lng: 106.6881,
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "District 3, Ho Chi Minh City",
    roaster: "Bosgaurus Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "bosgaurus",
    website: "https://bosgauruscoffee.com",
    editorial_blurb: "District 3 roastery building Vietnam's most ambitious specialty program — the sourcing stories and the extraction quality are both exceptional.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-12", verification_source: "admin",
  },
  {
    name: "Windmills Coffee Roasters",
    slug: "windmills-coffee-hcmc",
    lat: 10.8024, lng: 106.7155,
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "Bình Thạnh District, Ho Chi Minh City",
    roaster: "Windmills Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "windmillscoffee",
    editorial_blurb: "Bình Thạnh roastery café with a pour-over focus and a bean program that leans heavily on Vietnam's own highland growing regions.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-05", verification_source: "community",
  },
  {
    name: "Kairo Coffee",
    slug: "kairo-coffee-hcmc",
    lat: 10.7740, lng: 106.7012,
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "District 1, Ho Chi Minh City",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "kairocoffee",
    editorial_blurb: "District 1 specialty bar with a stripped-back aesthetic and a filter menu that makes a clear argument for why Ho Chi Minh City is becoming a serious coffee city.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-09-25", verification_source: "community",
  },
  {
    name: "Hola Coffee",
    slug: "hola-coffee-hcmc",
    lat: 10.7805, lng: 106.6895,
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "District 3, Ho Chi Minh City",
    roaster: "Hola Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "holacoffeevn",
    editorial_blurb: "District 3 specialty café doing careful pour-overs and well-sourced espresso in a space that feels more neighborhood gem than urban showcase.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-09-18", verification_source: "community",
  },
  {
    name: "Gemma",
    slug: "gemma-hcmc",
    lat: 10.8091, lng: 106.7399,
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "Thảo Điền, District 2, Ho Chi Minh City",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "gemma_saigon",
    editorial_blurb: "Thảo Điền expat neighborhood café with a specialty espresso program that holds its own globally — the riverside setting doesn't hurt.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-09-10", verification_source: "community",
  },
  {
    name: "Yoko Coffee",
    slug: "yoko-coffee-hcmc",
    lat: 10.7810, lng: 106.6902,
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "District 3, Ho Chi Minh City",
    roaster: "Yoko Coffee",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "yokocoffeevn",
    editorial_blurb: "Japanese-influenced specialty café in District 3 where the pour-over menu and the clean aesthetic signal what the next chapter of HCMC coffee looks like.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-09-05", verification_source: "community",
  },

  // ── TOKYO NEW (30) ───────────────────────────────────────────────────────────
  {
    name: "Little Nap Coffee Stand",
    slug: "little-nap-coffee-yoyogi",
    lat: 35.6727, lng: 139.6940,
    city: "Tokyo", country: "Japan",
    address: "5-65-4 Yoyogi, Shibuya-ku, Tokyo",
    roaster: "Little Nap Coffee Roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["standing-bar", "outdoor-seating", "minimalist"],
    instagram_handle: "littlenapcoffeestand",
    website: "https://littlenap.jp",
    editorial_blurb: "Yoyogi Park corner stand with a devoted neighbourhood following — the seasonal espresso blends and park-facing counter are a Tokyo classic.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "The Roastery by Nozy Coffee",
    slug: "the-roastery-nozy-omotesando",
    lat: 35.6657, lng: 139.7079,
    city: "Tokyo", country: "Japan",
    address: "5-17-13 Jingumae, Shibuya-ku, Tokyo (Cat Street)",
    roaster: "Nozy Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "minimalist", "no-laptop"],
    instagram_handle: "theroastery_nozycoffee",
    website: "https://www.tysons.jp/roastery/en/",
    editorial_blurb: "Omotesando Cat Street flagship where Nozy's full roasting operation is on display and the single-origin filter menu reaches its most ambitious form.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Onibus Coffee Jiyugaoka",
    slug: "onibus-coffee-jiyugaoka",
    lat: 35.6079, lng: 139.6836,
    city: "Tokyo", country: "Japan",
    address: "9-13 Jiyugaoka, Meguro-ku, Tokyo",
    roaster: "Onibus Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["outdoor-seating", "minimalist"],
    instagram_handle: "onibuscoffee",
    website: "https://onibuscoffee.com/",
    editorial_blurb: "Second Onibus outpost in sleepy Jiyugaoka — the neighbourhood fits the café's unhurried sourcing philosophy better than anywhere else in Tokyo.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Turret Coffee",
    slug: "turret-coffee-tsukiji",
    lat: 35.6658, lng: 139.7698,
    city: "Tokyo", country: "Japan",
    address: "2-12-6 Tsukiji, Chuo-ku, Tokyo",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["standing-bar", "minimalist", "no-laptop"],
    instagram_handle: "turretcoffee",
    editorial_blurb: "Tsukiji market-side standing bar that opens before dawn and pours the best early-morning espresso in Tokyo — frequented by fish traders and coffee obsessives alike.",
    featured_in: ["sprudge", "guardian"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Maruyama Coffee Minami-Aoyama",
    slug: "maruyama-coffee-aoyama-tokyo",
    lat: 35.6648, lng: 139.7156,
    city: "Tokyo", country: "Japan",
    address: "5-3-6 Minami-Aoyama, Minato-ku, Tokyo",
    roaster: "Maruyama Coffee",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "maruyamacoffee",
    website: "https://www.maruyamacoffee.com/",
    editorial_blurb: "Nagano's Cup of Excellence dynasty in Aoyama — the competition-grade lots and the reverent pour-over technique reward any detour into the backstreets.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "% Arabica Tokyo Daikanyama",
    slug: "arabica-tokyo-daikanyama",
    lat: 35.6490, lng: 139.7024,
    city: "Tokyo", country: "Japan",
    address: "16-15 Daikanyama-cho, Shibuya-ku, Tokyo",
    roaster: "% Arabica",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "outdoor-seating", "no-laptop"],
    instagram_handle: "arabica.tokyo",
    website: "https://arabica.com/en/",
    editorial_blurb: "% Arabica's Daikanyama outpost in the boutique-lined streets — the outdoor terrace and the clean espresso pull a design-conscious crowd that takes coffee seriously.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Blue Bottle Coffee Aoyama",
    slug: "blue-bottle-aoyama-tokyo",
    lat: 35.6655, lng: 139.7138,
    city: "Tokyo", country: "Japan",
    address: "3-13-14 Minami-Aoyama, Minato-ku, Tokyo",
    roaster: "Blue Bottle Coffee",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "outdoor-seating"],
    instagram_handle: "bluebottlejpn",
    website: "https://bluebottlecoffee.com/",
    editorial_blurb: "Hidden inside Aoyama's Nezu Museum garden — the most architecturally beautiful Blue Bottle globally and a genuine reason to slow a museum visit down.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Blue Bottle Coffee Shinjuku",
    slug: "blue-bottle-shinjuku-tokyo",
    lat: 35.6879, lng: 139.7006,
    city: "Tokyo", country: "Japan",
    address: "4-1-6 Shinjuku, NEWoMan 1F, Shinjuku-ku, Tokyo 160-0022",
    roaster: "Blue Bottle Coffee",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "bluebottlejpn",
    website: "https://bluebottlecoffee.com/",
    editorial_blurb: "Blue Bottle's NEWoMan Shinjuku location offers a rare moment of filter-coffee calm in the middle of Shinjuku's relentless energy.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Switch Coffee Meguro",
    slug: "switch-coffee-meguro",
    lat: 35.6385, lng: 139.7063,
    city: "Tokyo", country: "Japan",
    address: "1-17-23 Meguro, Meguro-ku, Tokyo",
    roaster: "Switch Coffee",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "switchcoffeetokyo",
    website: "https://www.switchcoffeetokyo.com",
    editorial_blurb: "Meguro flagship where Switch Coffee's house roasts are on full display — the weekly single-origin rotation rewards the regular visitor.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Verve Coffee Roasters Tokyo",
    slug: "verve-coffee-tokyo",
    lat: 35.6655, lng: 139.7094,
    city: "Tokyo", country: "Japan",
    address: "5-9-18 Minami-Aoyama, Minato-ku, Tokyo",
    roaster: "Verve Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "outdoor-seating"],
    instagram_handle: "vervecoffeeroasters",
    website: "https://www.vervecoffee.com/",
    editorial_blurb: "Santa Cruz's acclaimed roastery in Aoyama — the California directness and the Japanese precision make an unexpectedly coherent combination.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Amameria Espresso",
    slug: "amameria-espresso-tokyo",
    lat: 35.6778, lng: 139.8046,
    city: "Tokyo", country: "Japan",
    address: "3-8-9 Kiyosumi, Koto-ku, Tokyo",
    roaster: "Amameria Espresso",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["standing-bar", "minimalist", "no-laptop"],
    instagram_handle: "amameria_espresso",
    website: "https://www.amameria.com",
    editorial_blurb: "Kiyosumi-Shirakawa espresso specialist with an extractionist's mindset and a single-minded commitment to the shot — one of the cluster's unsung standouts.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Glitch Coffee Ginza",
    slug: "glitch-coffee-ginza",
    lat: 35.6718, lng: 139.7665,
    city: "Tokyo", country: "Japan",
    address: "6-10-1 Ginza, Chuo-ku, Tokyo",
    roaster: "Glitch Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "standing-bar"],
    instagram_handle: "glitch_coffee",
    website: "https://glitchcoffee.com/",
    editorial_blurb: "Glitch's Ginza outpost distils the Jimbocho competition ethos into a compact bar — the rotating filter menu is as serious as any in the city.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Arise Coffee Roasters",
    slug: "arise-coffee-roasters-kiyosumi",
    lat: 35.6785, lng: 139.8048,
    city: "Tokyo", country: "Japan",
    address: "3-1-3 Kiyosumi, Koto-ku, Tokyo",
    roaster: "Arise Coffee",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "arisecoffeeroasters",
    website: "https://arisecoffee.jp",
    editorial_blurb: "Kiyosumi roastery flagship where Arise's sourcing decisions get made and the freshest lots land first — the spiritual centre of the neighbourhood's specialty cluster.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Koffee Mameya Kakeru",
    slug: "koffee-mameya-kakeru-tokyo",
    lat: 35.6651, lng: 139.7100,
    city: "Tokyo", country: "Japan",
    address: "4-14-2 Jingumae, Shibuya-ku, Tokyo",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "syphon", "aeropress"],
    vibe_tags: ["no-laptop", "minimalist"],
    instagram_handle: "koffee_mameya_kakeru",
    website: "https://koffee-mameya.com/kakeru/",
    editorial_blurb: "The pairing-menu evolution of Koffee Mameya — coffee served alongside food in a format that treats extraction as seriously as any restaurant treats its wine list.",
    featured_in: ["sprudge", "ny_times"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Woodberry Coffee Mejiro",
    slug: "woodberry-coffee-mejiro",
    lat: 35.7229, lng: 139.7095,
    city: "Tokyo", country: "Japan",
    address: "2-30-5 Mejiro, Toshima-ku, Tokyo",
    roaster: "Woodberry Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "woodberrycoffee",
    website: "https://woodberrycoffee.com/",
    editorial_blurb: "Woodberry's second roastery location in the quiet residential streets of Mejiro — the same high-clarity African lots in a calmer neighbourhood setting.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Fuglen Tokyo Asakusa",
    slug: "fuglen-tokyo-asakusa",
    lat: 35.7138, lng: 139.7956,
    city: "Tokyo", country: "Japan",
    address: "2-6-15 Asakusa, Taito-ku, Tokyo 111-0032",
    roaster: "Fuglen Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "outdoor-seating"],
    instagram_handle: "fuglentokyo",
    website: "https://www.fuglen.com/",
    editorial_blurb: "Fuglen's Asakusa outpost takes the Oslo-meets-Tokyo formula into the city's most traditional neighbourhood — a contrast that somehow works perfectly.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Coffee Valley",
    slug: "coffee-valley-ikebukuro",
    lat: 35.7299, lng: 139.7147,
    city: "Tokyo", country: "Japan",
    address: "2-26-3 Minami-Ikebukuro, Toshima-ku, Tokyo 171-0022",
    roaster: "Coffee Valley",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "coffeevalley_jp",
    website: "https://coffeevalley.jp",
    editorial_blurb: "Ikebukuro roastery that quietly operates one of the most technically rigorous filter programs on the east side — worth seeking out past the shopping bustle.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Streamer Coffee Harajuku",
    slug: "streamer-coffee-harajuku",
    lat: 35.6700, lng: 139.7041,
    city: "Tokyo", country: "Japan",
    address: "6-12 Jingumae, Shibuya-ku, Tokyo",
    roaster: "Streamer Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "outdoor-seating"],
    instagram_handle: "streamercoffee",
    website: "https://streamer.coffee/",
    editorial_blurb: "Streamer's Harajuku location puts championship latte art in front of a street-fashion crowd — the espresso behind it is what keeps coffee people coming back.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Single O Japan",
    slug: "single-o-hamacho",
    lat: 35.6837, lng: 139.7872,
    city: "Tokyo", country: "Japan",
    address: "2-6-4 Nihonbashi Hamacho, Chuo-ku, Tokyo",
    roaster: "Single O",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "singleojapan",
    website: "https://www.singleo.com.au/",
    editorial_blurb: "Sydney's Single O in a converted Hamacho warehouse — the Australian directness and the specialty roasting ethos both come through in every cup.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },

  // ── SEOUL NEW (20) ───────────────────────────────────────────────────────────
  {
    name: "Fritz Coffee Company Yangjae",
    slug: "fritz-coffee-yangjae",
    lat: 37.4746, lng: 127.0421,
    city: "Seoul", country: "South Korea",
    address: "20 Yangjaecheon-ro, Seocho-gu, Seoul",
    roaster: "Fritz Coffee",
    brew_methods: ["pour-over", "espresso", "syphon"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "outdoor-seating"],
    instagram_handle: "fritzcoffeecompany",
    website: "https://www.fritzcoffee.co.kr/",
    editorial_blurb: "Fritz's Yangjae roastery is bigger than the Mapo original and just as precise — the weekend bread and coffee ritual here draws South Seoul's specialty faithful.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Anthracite Coffee Roasters Hapjeong",
    slug: "anthracite-coffee-hapjeong",
    lat: 37.5507, lng: 126.9073,
    city: "Seoul", country: "South Korea",
    address: "96 Tojeong-ro, Mapo-gu, Seoul",
    roaster: "Anthracite Coffee",
    brew_methods: ["pour-over", "espresso", "cold-brew", "chemex"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "laptop-friendly"],
    instagram_handle: "anthracitecoffee",
    website: "https://www.anthracitecoffee.com/",
    editorial_blurb: "Hapjeong factory building turned multi-floor roastery showroom — the courtyard garden and the single-origins are equally worth the trip from anywhere in Seoul.",
    featured_in: ["sprudge", "standart", "monocle"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Café Onion Seongsu",
    slug: "cafe-onion-seongsu",
    lat: 37.5446, lng: 127.0572,
    city: "Seoul", country: "South Korea",
    address: "8 Achasan-ro 9-gil, Seongdong-gu, Seoul",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["no-laptop", "outdoor-seating"],
    instagram_handle: "cafe_onion",
    editorial_blurb: "Seongsu industrial space with the same concrete brutalism as Anguk but a younger, more electric crowd — the queue is long and the croissants justify it.",
    featured_in: ["sprudge", "guardian", "timeout"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Coffee Han Jan",
    slug: "coffee-han-jan-seoul",
    lat: 37.5662, lng: 126.9812,
    city: "Seoul", country: "South Korea",
    address: "16-1 Sajik-ro 7-gil, Sajik-dong, Jongno-gu, Seoul",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso"],
    vibe_tags: ["standing-bar", "minimalist", "no-laptop"],
    instagram_handle: "coffeehanjanseoul",
    editorial_blurb: "Tiny Jongno standing bar where 'one cup of coffee' — the literal translation — is taken with utmost seriousness, brewed to order, and gone in minutes.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Southside Parlor",
    slug: "southside-parlor-seoul",
    lat: 37.5343, lng: 126.9911,
    city: "Seoul", country: "South Korea",
    address: "Itaewon, Yongsan-gu, Seoul",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "southsideparlor",
    editorial_blurb: "Itaewon parlour with a specialty espresso program and a New York–influenced café energy — one of the neighbourhood's most reliably excellent stops.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Café Comma",
    slug: "cafe-comma-seoul",
    lat: 37.5218, lng: 127.0411,
    city: "Seoul", country: "South Korea",
    address: "Cheongdam-dong, Gangnam-gu, Seoul",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "cafecomma",
    website: "https://cafecomma.com",
    editorial_blurb: "Cheongdam boutique café taking a considered pause in Seoul's most fashion-forward district — the pour-over list changes weekly and is always worth checking.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Mannong Roastery",
    slug: "mannong-roastery-seoul",
    lat: 37.5585, lng: 126.9380,
    city: "Seoul", country: "South Korea",
    address: "Seodaemun-gu, Seoul",
    roaster: "Mannong Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "mannong_roastery",
    editorial_blurb: "Seodaemun roastery working quietly outside the Hongdae hype — the direct-trade lots and precise light roasts are among the most underrated in Seoul.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Coffee Grüp",
    slug: "coffee-grup-seoul",
    lat: 37.5486, lng: 126.9212,
    city: "Seoul", country: "South Korea",
    address: "Hapjeong-dong, Mapo-gu, Seoul",
    roaster: "Coffee Grüp",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "coffeegroup_",
    editorial_blurb: "Hapjeong specialty café with a Scandinavian-influenced light-roast approach and an ever-changing filter menu that rewards multiple return visits.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Café Sukkat",
    slug: "cafe-sukkat-seoul",
    lat: 37.5508, lng: 126.9148,
    city: "Seoul", country: "South Korea",
    address: "Hapjeong-dong, Mapo-gu, Seoul",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso"],
    vibe_tags: ["outdoor-seating", "no-laptop", "minimalist"],
    instagram_handle: "cafesukkat",
    editorial_blurb: "Hapjeong garden café where the specialty coffee and the leafy terrace create a retreat from the district's busier streets — always worth a detour.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Café de Muse",
    slug: "cafe-de-muse-seoul",
    lat: 37.5228, lng: 127.0372,
    city: "Seoul", country: "South Korea",
    address: "Apgujeong-dong, Gangnam-gu, Seoul",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "cafe.de.muse",
    editorial_blurb: "Apgujeong specialty bar with a refined minimalist interior and a serious espresso program — the Gangnam set's preferred alternative to chain coffee.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Namusairo Gahoe-dong",
    slug: "namusairo-gahoe-dong",
    lat: 37.5820, lng: 126.9830,
    city: "Seoul", country: "South Korea",
    address: "Gahoe-dong, Jongno-gu, Seoul",
    roaster: "Namusairo",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["minimalist", "no-laptop", "outdoor-seating"],
    instagram_handle: "namusairo",
    website: "https://en.namusairo.com",
    editorial_blurb: "Second Namusairo location deeper in Bukchon's hanok alleyways — the architectural setting and the single-origin pour-overs are both without equal in Seoul.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "The Barn Seoul",
    slug: "the-barn-seoul",
    lat: 37.5219, lng: 127.0224,
    city: "Seoul", country: "South Korea",
    address: "Gangnam-gu, Seoul",
    roaster: "The Barn",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "thebarnberlin",
    website: "https://www.thebarn.de/",
    editorial_blurb: "Berlin's pioneering light-roast roastery outpost in Seoul — the same exactingly sourced lots that reshaped European specialty coffee, now available in Gangnam.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },

  // ── SINGAPORE NEW (12) ───────────────────────────────────────────────────────
  {
    name: "Dutch Colony Coffee Co Chip Bee",
    slug: "dutch-colony-coffee-chip-bee",
    lat: 1.3097, lng: 103.7936,
    city: "Singapore", country: "Singapore",
    address: "34 Chip Bee Gardens, Holland Village, Singapore 278699",
    roaster: "Dutch Colony Coffee",
    brew_methods: ["pour-over", "espresso", "cold-brew", "chemex"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "dutchcolonycoffee",
    website: "https://www.dutchcolony.com/",
    editorial_blurb: "Holland Village heritage shophouse with a garden terrace that makes Sunday morning filter coffee feel like a genuine event — consistently well-sourced.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Oriole Coffee + Bar",
    slug: "oriole-coffee-bar-singapore",
    lat: 1.2932, lng: 103.8421,
    city: "Singapore", country: "Singapore",
    address: "96 Somerset Rd, #01-01, Singapore 238163",
    roaster: "Oriole Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "oriolecoffeebar",
    editorial_blurb: "Somerset specialty bar that doubled as a craft cocktail destination after dark — the espresso program was taken just as seriously as the spirit selection.",
    featured_in: ["sprudge", "timeout"],
    verified: false, permanently_closed: true,
  },
  {
    name: "Strangers' Reunion",
    slug: "strangers-reunion-singapore",
    lat: 1.3135, lng: 103.8662,
    city: "Singapore", country: "Singapore",
    address: "37 Tyrwhitt Rd, Singapore 207543",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "strangersreunion",
    website: "https://www.strangersreunion.com/",
    editorial_blurb: "Tyrwhitt Road all-day café with an exuberant character and a specialty espresso program that refuses to be overshadowed by the famous French toast.",
    featured_in: ["sprudge", "timeout"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Kith Café Robertson Quay",
    slug: "kith-cafe-robertson-quay",
    lat: 1.2901, lng: 103.8385,
    city: "Singapore", country: "Singapore",
    address: "80 Mohamed Sultan Rd, #01-14, Singapore 239013",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "laptop-friendly"],
    instagram_handle: "kithcafe",
    website: "https://kith.com.sg/",
    editorial_blurb: "Riverside Robertson Quay staple that mastered the Antipodean café formula — the flat white and the views of the Singapore River are both reliably excellent.",
    featured_in: ["sprudge", "timeout"],
    verified: false, permanently_closed: true,
  },
  {
    name: "Liberty Coffee",
    slug: "liberty-coffee-singapore",
    lat: 1.2803, lng: 103.8490,
    city: "Singapore", country: "Singapore",
    address: "6 Raffles Blvd, #02-130, Singapore 039594",
    roaster: "Liberty Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress", "cold-brew"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "libertycoffeesg",
    website: "https://www.libertycoffee.sg/",
    editorial_blurb: "CBD specialty roastery café with a progressive approach to both sourcing and extraction — a professional crowd of repeat visitors validates the quality.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "The Assembly Ground",
    slug: "the-assembly-ground-singapore",
    lat: 1.3009, lng: 103.8469,
    city: "Singapore", country: "Singapore",
    address: "21 Tan Quee Lan St, #01-01, Singapore 188108",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "theassemblyground",
    website: "https://www.theassemblyground.com/",
    editorial_blurb: "Bugis lifestyle space where the specialty coffee counter holds its own beside the fashion retail — the espresso is not an afterthought.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Habitat Coffee",
    slug: "habitat-coffee-singapore",
    lat: 1.3420, lng: 103.8452,
    city: "Singapore", country: "Singapore",
    address: "211 Upp Thomson Rd, Singapore 574364",
    roaster: "Habitat Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "laptop-friendly"],
    instagram_handle: "habitatcoffeesg",
    website: "https://habitatcoffee.com.sg/",
    editorial_blurb: "Upper Thomson roastery set in a colonial bungalow with a garden — the nature-adjacent setting and the direct-trade filter menu are equally transportive.",
    featured_in: ["sprudge", "timeout"],
    verified: false, permanently_closed: true,
  },
  {
    name: "PPP Coffee Outram Park",
    slug: "ppp-coffee-outram-park",
    lat: 1.2796, lng: 103.8376,
    city: "Singapore", country: "Singapore",
    address: "Outram Park, Singapore",
    roaster: "PPP Coffee",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "pppcoffee",
    website: "https://www.pppcoffee.com/",
    editorial_blurb: "PPP's Outram Park outpost bringing the same subscription-honed roasting program to the southern fringe of the CBD — a quieter alternative to the Tiong Bahru flagship.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Common Man Coffee Roasters Dempsey",
    slug: "common-man-coffee-dempsey",
    lat: 1.3046, lng: 103.8089,
    city: "Singapore", country: "Singapore",
    address: "Dempsey Hill, Singapore",
    roaster: "Common Man Coffee Roasters",
    brew_methods: ["pour-over", "espresso", "chemex", "cold-brew"],
    vibe_tags: ["roastery-on-site", "outdoor-seating", "laptop-friendly"],
    instagram_handle: "commonmancoffeeroasters",
    website: "https://www.commonmancoffeeroasters.com/",
    editorial_blurb: "Common Man's Dempsey outpost in the heritage barracks setting — the outdoor terrace and the consistent specialty program make it the most relaxed of their locations.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Dutch Colony Coffee Co Fusionopolis",
    slug: "dutch-colony-coffee-fusionopolis",
    lat: 1.2991, lng: 103.7870,
    city: "Singapore", country: "Singapore",
    address: "1 Fusionopolis Way, #01-01, Singapore 138632",
    roaster: "Dutch Colony Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "dutchcolonycoffee",
    website: "https://www.dutchcolony.com/",
    editorial_blurb: "One-north tech-hub location serving the research campus community with the same quality-first approach as the original — a specialist café in a specialist district.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },

  // ── TAIPEI NEW (11) ──────────────────────────────────────────────────────────
  {
    name: "Congrats Espresso",
    slug: "congrats-espresso-taipei",
    lat: 25.0524, lng: 121.5241,
    city: "Taipei", country: "Taiwan",
    address: "Zhongshan District, Taipei",
    roaster: "Congrats Coffee",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["standing-bar", "minimalist", "no-laptop"],
    instagram_handle: "congratsespresso",
    editorial_blurb: "Zhongshan standing espresso bar where every shot is treated as a culmination — the congratulatory name speaks to what a perfect extraction feels like.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Café Costumé",
    slug: "cafe-costume-xinyi-taipei",
    lat: 25.0374, lng: 121.5619,
    city: "Taipei", country: "Taiwan",
    address: "Xinyi District, Taipei",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "cafe_costume",
    editorial_blurb: "Xinyi boutique café taking the fashion-district setting seriously with a specialty program that matches its editorial aesthetic shot for shot.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Lobby of Simple Kaffa",
    slug: "lobby-of-simple-kaffa-taipei",
    lat: 25.0444, lng: 121.5465,
    city: "Taipei", country: "Taiwan",
    address: "Da'an District, Taipei",
    roaster: "Simple Kaffa",
    brew_methods: ["espresso", "pour-over", "aeropress", "cold-brew"],
    vibe_tags: ["laptop-friendly", "minimalist"],
    instagram_handle: "lobbyofsimplekaffa",
    editorial_blurb: "Berg Wu's more accessible sibling concept — the same world-champion sourcing and technique in a format that welcomes lingering and laptop work.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Thomas Tsai Coffee",
    slug: "thomas-tsai-coffee-taipei",
    lat: 25.0484, lng: 121.5388,
    city: "Taipei", country: "Taiwan",
    address: "Da'an District, Taipei",
    roaster: "Thomas Tsai Coffee",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "thomastcoffee",
    editorial_blurb: "Veteran barista Thomas Tsai's showcase — competition-circuit knowledge translated into a single-origin filter menu of uncommon depth and consistency.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Zhanlu Coffee Da'an",
    slug: "zhanlu-coffee-daan-taipei",
    lat: 25.0333, lng: 121.5446,
    city: "Taipei", country: "Taiwan",
    address: "Da'an District, Taipei",
    roaster: "Zhanlu Coffee",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "zhanlucoffee",
    website: "https://www.zhanlu.com.tw/",
    editorial_blurb: "Da'an roastery with a competition pedigree and a filter program built on meticulous sourcing from Ethiopia, Kenya, and Colombia — one of Taipei's most serious.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Barista Way Coffee Roaster",
    slug: "barista-way-coffee-taipei",
    lat: 25.0472, lng: 121.5420,
    city: "Taipei", country: "Taiwan",
    address: "Zhongshan District, Taipei",
    roaster: "Barista Way",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "baristawaycoffee",
    editorial_blurb: "Training-school roastery where the education ethos infuses the café experience — the staff explains, the coffee teaches, and the filter menu is a curriculum.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Goodman Roaster Da'an",
    slug: "goodman-roaster-daan-taipei",
    lat: 25.0298, lng: 121.5399,
    city: "Taipei", country: "Taiwan",
    address: "Da'an District, Taipei",
    roaster: "Goodman Roaster",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["roastery-on-site", "minimalist"],
    instagram_handle: "goodmanroaster",
    website: "https://goodmanroaster.tw/",
    editorial_blurb: "Goodman's Da'an roastery location — more intimate than the Xinyi flagship, with the same rigorous sourcing and a filter program that peaks with every new harvest.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Zhanlu Coffee Zhongshan",
    slug: "zhanlu-coffee-zhongshan-taipei",
    lat: 25.0522, lng: 121.5247,
    city: "Taipei", country: "Taiwan",
    address: "Zhongshan District, Taipei",
    roaster: "Zhanlu Coffee",
    brew_methods: ["pour-over", "espresso"],
    vibe_tags: ["minimalist", "standing-bar"],
    instagram_handle: "zhanlucoffee",
    website: "https://www.zhanlu.com.tw/",
    editorial_blurb: "Zhanlu's Zhongshan counter — a more compact expression of the competition-level roastery, best for a quick filter that punches above its surroundings.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Rufous Coffee Da'an",
    slug: "rufous-coffee-daan-taipei",
    lat: 25.0302, lng: 121.5440,
    city: "Taipei", country: "Taiwan",
    address: "Da'an District, Taipei",
    roaster: "Rufous Coffee",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "rufous_coffee",
    website: "https://www.rufous.com.tw/",
    editorial_blurb: "Rufous's Da'an outpost extending the Zhongshan single-origin program south — the neighbourhood's quieter pace suits the contemplative filter approach.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Simple Kaffa Xinyi",
    slug: "simple-kaffa-xinyi-taipei",
    lat: 25.0362, lng: 121.5647,
    city: "Taipei", country: "Taiwan",
    address: "Xinyi District, Taipei",
    roaster: "Simple Kaffa",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "simplekaffa",
    website: "https://simplekaffa.com/",
    editorial_blurb: "Simple Kaffa's Xinyi location brings Berg Wu's world-champion espresso to Taipei's commercial heart — precision at scale without compromise.",
    featured_in: ["sprudge", "monocle"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Fika Fika Café Songshan",
    slug: "fika-fika-songshan-taipei",
    lat: 25.0504, lng: 121.5562,
    city: "Taipei", country: "Taiwan",
    address: "Songshan District, Taipei",
    roaster: "Fika Fika",
    brew_methods: ["pour-over", "espresso", "chemex"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "fikafika_cafe",
    website: "https://www.fikafikacafe.com/",
    editorial_blurb: "Fika Fika's Songshan outpost in the cultural park district — the Scandinavian roasting ethos in a creative neighbourhood that was always a natural match.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },

  // ── OSAKA NEW (6) ────────────────────────────────────────────────────────────
  {
    name: "Triangle Coffee Stand",
    slug: "triangle-coffee-stand-osaka",
    lat: 34.6731, lng: 135.5024,
    city: "Osaka", country: "Japan",
    address: "Shinsaibashi area, Chuo-ku, Osaka",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over"],
    vibe_tags: ["standing-bar", "minimalist", "no-laptop"],
    instagram_handle: "trianglecoffeestand",
    editorial_blurb: "Shinsaibashi corner standing bar occupying a genuinely triangular space — the geometric constraints focus everything on the coffee, which is excellent.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Unir Coffee Osaka",
    slug: "unir-coffee-osaka",
    lat: 34.6943, lng: 135.5009,
    city: "Osaka", country: "Japan",
    address: "Umeda, Kita-ku, Osaka",
    roaster: "Unir Coffee",
    brew_methods: ["pour-over", "espresso", "chemex", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "unircoffee",
    website: "https://unir-coffee.com",
    editorial_blurb: "Kyoto roastery's Umeda outpost bringing a COE competition record and Nordic-influenced light-roast precision to Osaka's busiest transit hub.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "% Arabica Osaka Wharf",
    slug: "arabica-osaka-wharf",
    lat: 34.6567, lng: 135.4327,
    city: "Osaka", country: "Japan",
    address: "Sakishima Cosmo Tower, 2-1-10 Nankokita, Suminoe-ku, Osaka 559-0034",
    roaster: "% Arabica",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "outdoor-seating", "no-laptop"],
    instagram_handle: "arabica.osaka",
    website: "https://arabica.com/en/",
    editorial_blurb: "% Arabica at Osaka's waterfront — the bay views and the white minimalist design make it the chain's most unexpectedly dramatic location.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Streamer Coffee Osaka",
    slug: "streamer-coffee-osaka",
    lat: 34.6702, lng: 135.5010,
    city: "Osaka", country: "Japan",
    address: "Shinsaibashi, Chuo-ku, Osaka",
    roaster: "Streamer Coffee",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["minimalist", "outdoor-seating"],
    instagram_handle: "streamercoffee",
    website: "https://streamer.coffee/",
    editorial_blurb: "Streamer's Osaka foothold in the Shinsaibashi shopping corridor — the championship latte art draws the crowds; the espresso underneath is the real attraction.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "café murni",
    slug: "cafe-murni-osaka",
    lat: 34.7025, lng: 135.5055,
    city: "Osaka", country: "Japan",
    address: "Nakazaki-nishi, Kita-ku, Osaka",
    roaster: "café murni",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "outdoor-seating"],
    instagram_handle: "cafe_murni",
    editorial_blurb: "Nakazakicho specialty café with an Indonesian-inspired sourcing focus — rare island-specific lots from Sulawesi and Flores brewed with thoughtful precision.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },

  // ── HO CHI MINH CITY NEW (7) ─────────────────────────────────────────────────
  {
    name: "Là Việt Coffee",
    slug: "la-viet-coffee-hcmc",
    lat: 10.7812, lng: 106.6944,
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "167 Pasteur, District 3, Ho Chi Minh City",
    roaster: "Là Việt Coffee",
    brew_methods: ["pour-over", "espresso", "cold-brew", "aeropress"],
    vibe_tags: ["roastery-on-site", "laptop-friendly"],
    instagram_handle: "lavietcoffee",
    website: "https://laviet.coffee/",
    editorial_blurb: "Da Lat's most acclaimed specialty roastery in the city — the highland Vietnamese arabica lots and the immaculate pour-over technique belong in any serious city guide.",
    featured_in: ["sprudge", "standart"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Cộng Cà Phê",
    slug: "cong-ca-phe-hcmc",
    lat: 10.7760, lng: 106.6998,
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "26 Lý Tự Trọng, District 1, Ho Chi Minh City",
    roaster: "Cộng Cà Phê",
    brew_methods: ["espresso", "cold-brew"],
    vibe_tags: ["laptop-friendly", "outdoor-seating"],
    instagram_handle: "congcaphevietnam",
    website: "https://congcaphe.com/",
    editorial_blurb: "North Vietnamese army-chic aesthetic with a coconut cold brew that defines the genre — the communist nostalgia décor is very deliberate and very effective.",
    featured_in: ["sprudge", "guardian", "timeout"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "The Café Apartment",
    slug: "the-cafe-apartment-hcmc",
    lat: 10.7759, lng: 106.6992,
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "42 Nguyen Hue, District 1, Ho Chi Minh City",
    roaster: "Multiple guest roasters",
    brew_methods: ["espresso", "pour-over", "cold-brew"],
    vibe_tags: ["outdoor-seating", "no-laptop"],
    instagram_handle: "thecafeapartment",
    editorial_blurb: "Nine floors of independent cafés inside a 1960s Nguyen Hue building — the rooftop views and the street-level espresso bars each reward a different floor stop.",
    featured_in: ["sprudge", "timeout", "guardian"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Úp Café",
    slug: "up-cafe-hcmc",
    lat: 10.7885, lng: 106.6974,
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "Bình Thạnh District, Ho Chi Minh City",
    roaster: "Úp Café",
    brew_methods: ["pour-over", "espresso", "aeropress"],
    vibe_tags: ["minimalist", "laptop-friendly"],
    instagram_handle: "upcafevn",
    editorial_blurb: "Bình Thạnh specialty café focused on Vietnamese highlands arabica with a direct-sourcing model that makes every cup a transparent conversation about origin.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Hi Coffee",
    slug: "hi-coffee-hcmc",
    lat: 10.7800, lng: 106.6998,
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "District 1, Ho Chi Minh City",
    roaster: "Hi Coffee",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "outdoor-seating"],
    instagram_handle: "hicoffeevn",
    editorial_blurb: "District 1 specialty café with a cheerful name and a focused filter program that balances Vietnamese robusta heritage with third-wave arabica sourcing.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Specialty Coffee Store",
    slug: "specialty-coffee-store-hcmc",
    lat: 10.7834, lng: 106.6922,
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "District 3, Ho Chi Minh City",
    roaster: "Multiple guest roasters",
    brew_methods: ["pour-over", "espresso", "aeropress", "chemex"],
    vibe_tags: ["roastery-on-site", "laptop-friendly", "minimalist"],
    instagram_handle: "specialtycoffeestore",
    editorial_blurb: "District 3 multi-roaster concept carrying the best of Vietnam's growing domestic specialty scene — the guest-roaster rotation is the city's most curated.",
    featured_in: ["sprudge"],
    verified: true, last_verified_at: "2025-10-01", verification_source: "admin",
  },
  {
    name: "Bosgaurus Coffee Ben Thanh",
    slug: "bosgaurus-coffee-ben-thanh-hcmc",
    lat: 10.7726, lng: 106.6980,
    city: "Ho Chi Minh City", country: "Vietnam",
    address: "District 1, near Ben Thanh Market, Ho Chi Minh City",
    roaster: "Bosgaurus Coffee",
    brew_methods: ["pour-over", "espresso", "cold-brew"],
    vibe_tags: ["minimalist", "no-laptop"],
    instagram_handle: "bosgaurus",
    website: "https://bosgauruscoffee.com",
    editorial_blurb: "Bosgaurus second location closer to the tourist centre — the same ambitious specialty roasting, accessible without navigating into District 3.",
    featured_in: ["sprudge"],
    verified: false, last_verified_at: "2025-10-01", verification_source: "community",
  },
];
