/**
 * One-time seed script: inserts all cities and cafes from seed-data.ts into Supabase.
 * Run with: npx tsx scripts/seed-supabase.ts
 */
import { createClient } from "@supabase/supabase-js";
import { config } from "dotenv";
import path from "path";

// Load .env.local
config({ path: path.resolve(process.cwd(), ".env.local") });

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY!;

if (!SUPABASE_URL || !SERVICE_KEY) {
  console.error("Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_KEY");
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SERVICE_KEY);

// ── Inline seed data (avoids TypeScript path alias issues in scripts) ─────────

type BrewMethod = "espresso" | "pour-over" | "aeropress" | "cold-brew" | "syphon" | "french-press" | "chemex";
type VibeTags = "laptop-friendly" | "no-laptop" | "standing-bar" | "outdoor-seating" | "dog-friendly" | "roastery-on-site" | "minimalist" | "coworking";
type FeaturedIn = "sprudge" | "standart" | "monocle" | "atlas" | "guardian" | "ny_times" | "infatuation" | "eater" | "timeout";
type VerificationSource = "admin" | "community" | "google_places_api" | "automated";

interface RawCafe {
  name: string; slug: string; lat: number; lng: number; city: string; country: string;
  address: string; roaster?: string; brew_methods: BrewMethod[]; vibe_tags: VibeTags[];
  google_place_id?: string; instagram_handle?: string; website?: string;
  editorial_blurb: string; featured_in: FeaturedIn[]; verified: boolean;
  last_verified_at?: string; verification_source?: VerificationSource;
}

function scoreRaw(cafe: RawCafe): number {
  let score = 0;
  if (cafe.roaster && cafe.roaster !== "Multiple guest roasters") score += 20;
  else score += 5;
  const brewScore = Math.min(cafe.brew_methods.length * 5, 20);
  score += brewScore;
  if (!cafe.google_place_id) score += 20;
  const pressScore = Math.min(cafe.featured_in.length * 5, 15);
  score += pressScore;
  if (cafe.vibe_tags.includes("roastery-on-site")) score += 10;
  return Math.min(score + 5, 100);
}

const rawCafes: RawCafe[] = [
  // TOKYO
  { name: "Fuglen Tokyo", slug: "fuglen-tokyo", lat: 35.6696, lng: 139.6916, city: "Tokyo", country: "Japan", address: "1-16-11 Tomigaya, Shibuya-ku, Tokyo", roaster: "Fuglen Coffee Roasters", brew_methods: ["pour-over","espresso","aeropress"], vibe_tags: ["minimalist","no-laptop"], google_place_id: "ChIJN1-WT_KLGGARzMPs8sI9WBc", instagram_handle: "fuglentokyo", website: "https://www.fuglen.com/", editorial_blurb: "Oslo's cult café landed in Tokyo and raised the bar for the entire city — order the pour-over and stay for the vintage furniture.", featured_in: ["sprudge","monocle"], verified: true, last_verified_at: "2024-11-01", verification_source: "admin" },
  { name: "Koffee Mameya", slug: "koffee-mameya", lat: 35.6654, lng: 139.7104, city: "Tokyo", country: "Japan", address: "4-15-3 Jingumae, Shibuya-ku, Tokyo", roaster: "Multiple guest roasters", brew_methods: ["pour-over","espresso"], vibe_tags: ["standing-bar","minimalist"], instagram_handle: "koffee_mameya", website: "https://koffee-mameya.com/", editorial_blurb: "No menu, no seating — just a barista asking what you want and delivering the precise cup you didn't know you needed.", featured_in: ["sprudge","ny_times"], verified: true, last_verified_at: "2024-10-15", verification_source: "admin" },
  { name: "Switch Coffee Tokyo", slug: "switch-coffee-tokyo", lat: 35.6952, lng: 139.7049, city: "Tokyo", country: "Japan", address: "Minami-Aoyama 6-6-22, Minato-ku, Tokyo", roaster: "Switch Coffee", brew_methods: ["pour-over","espresso","cold-brew"], vibe_tags: ["laptop-friendly","minimalist"], instagram_handle: "switchcoffeetokyo", editorial_blurb: "A quietly confident roastery café in Aoyama where single-origins rotate weekly and the staff genuinely wants to talk about terroir.", featured_in: ["sprudge"], verified: true, last_verified_at: "2024-09-20", verification_source: "admin" },
  // COPENHAGEN
  { name: "The Coffee Collective", slug: "the-coffee-collective-copenhagen", lat: 55.6867, lng: 12.5611, city: "Copenhagen", country: "Denmark", address: "Jægersborggade 10, 2200 Copenhagen", roaster: "The Coffee Collective", brew_methods: ["pour-over","espresso","chemex"], vibe_tags: ["roastery-on-site","laptop-friendly"], instagram_handle: "coffeecollective", website: "https://coffeecollective.dk/", editorial_blurb: "Copenhagen's gold standard for specialty — their direct-trade relationships and obsessive roasting set the benchmark for Northern Europe.", featured_in: ["sprudge","standart","monocle"], verified: true, last_verified_at: "2024-11-10", verification_source: "admin" },
  { name: "Democratic Coffee", slug: "democratic-coffee-copenhagen", lat: 55.6897, lng: 12.5620, city: "Copenhagen", country: "Denmark", address: "Krystalgade 15, 1172 Copenhagen", roaster: "Multiple guest roasters", brew_methods: ["pour-over","espresso","aeropress"], vibe_tags: ["laptop-friendly","outdoor-seating"], instagram_handle: "democraticcoffee", editorial_blurb: "Tucked beside a 19th-century library with rotating guest roasters, this is where Copenhagen's coffee intelligentsia holds court.", featured_in: ["sprudge","standart"], verified: true, last_verified_at: "2024-10-01", verification_source: "admin" },
  { name: "Prolog Coffee Bar", slug: "prolog-coffee-bar", lat: 55.6624, lng: 12.5413, city: "Copenhagen", country: "Denmark", address: "Høkerboderne 16, 1712 Copenhagen", roaster: "Prolog Coffee", brew_methods: ["espresso","pour-over"], vibe_tags: ["standing-bar","minimalist"], instagram_handle: "prologcoffeebar", editorial_blurb: "A standing bar without compromise — Prolog roasts its own beans and treats every shot as a precision instrument.", featured_in: ["sprudge"], verified: true, last_verified_at: "2024-09-15", verification_source: "admin" },
  // MELBOURNE
  { name: "Proud Mary Coffee", slug: "proud-mary-coffee-melbourne", lat: -37.7975, lng: 144.9875, city: "Melbourne", country: "Australia", address: "172 Oxford St, Collingwood VIC 3066", roaster: "Proud Mary Coffee", brew_methods: ["espresso","pour-over","cold-brew"], vibe_tags: ["roastery-on-site","laptop-friendly","outdoor-seating"], instagram_handle: "proudmarycoffee", website: "https://proudmarycoffee.com/", editorial_blurb: "The café that put Melbourne on the world's specialty coffee map — still pushing the limits on sourcing and seasonal roasting.", featured_in: ["sprudge","standart","guardian"], verified: true, last_verified_at: "2024-11-01", verification_source: "admin" },
  { name: "Seven Seeds", slug: "seven-seeds-melbourne", lat: -37.7993, lng: 144.9616, city: "Melbourne", country: "Australia", address: "114 Berkeley St, Carlton VIC 3053", roaster: "Seven Seeds", brew_methods: ["espresso","pour-over","syphon","chemex"], vibe_tags: ["roastery-on-site","laptop-friendly"], instagram_handle: "sevenseedscoffee", website: "https://sevenseeds.com.au/", editorial_blurb: "Housed in a converted warehouse, Seven Seeds was roasting direct-trade before it had a name and continues to set the pace.", featured_in: ["sprudge","monocle","guardian"], verified: true, last_verified_at: "2024-10-20", verification_source: "admin" },
  { name: "Patricia Coffee Brewers", slug: "patricia-coffee-brewers-melbourne", lat: -37.8138, lng: 144.9611, city: "Melbourne", country: "Australia", address: "493-495 Little Bourke St, Melbourne VIC 3000", roaster: "Multiple guest roasters", brew_methods: ["espresso","pour-over"], vibe_tags: ["standing-bar","no-laptop"], instagram_handle: "patriciacoffeebrewers", editorial_blurb: "A standing-room-only CBD institution where the queue moves fast, the espresso is outstanding, and conversation is required.", featured_in: ["sprudge","timeout"], verified: true, last_verified_at: "2024-10-05", verification_source: "admin" },
  // NEW YORK CITY
  { name: "Cafe Integral", slug: "cafe-integral-nyc", lat: 40.7233, lng: -73.9977, city: "New York City", country: "United States", address: "149 Elizabeth St, New York, NY 10012", roaster: "Cafe Integral", brew_methods: ["espresso","pour-over","aeropress"], vibe_tags: ["minimalist","no-laptop"], instagram_handle: "cafeintegral", website: "https://cafeintegral.com/", editorial_blurb: "Sourcing exclusively from Nicaragua since day one, Cafe Integral is a masterclass in knowing one origin deeply rather than broadly.", featured_in: ["sprudge","ny_times","infatuation"], verified: true, last_verified_at: "2024-11-01", verification_source: "admin" },
  { name: "Devoción", slug: "devocion-brooklyn", lat: 40.7128, lng: -73.9597, city: "New York City", country: "United States", address: "69 Grand St, Brooklyn, NY 11249", roaster: "Devoción", brew_methods: ["espresso","pour-over","cold-brew"], vibe_tags: ["roastery-on-site","laptop-friendly","outdoor-seating"], instagram_handle: "devocion", website: "https://www.devocion.com/", editorial_blurb: "Colombian beans roasted on-site at a cafe with a living wall — the farm-to-cup gap here is measured in days, not months.", featured_in: ["sprudge","ny_times","eater","infatuation"], verified: true, last_verified_at: "2024-10-15", verification_source: "admin" },
  { name: "Toby's Estate Coffee", slug: "tobys-estate-williamsburg", lat: 40.7181, lng: -73.9566, city: "New York City", country: "United States", address: "125 N 6th St, Brooklyn, NY 11249", roaster: "Toby's Estate", brew_methods: ["espresso","pour-over","chemex","aeropress"], vibe_tags: ["laptop-friendly","roastery-on-site"], instagram_handle: "tobysestate", website: "https://tobysestate.com/", editorial_blurb: "The Australian export that quietly became a Williamsburg institution — the training programme here shapes baristas citywide.", featured_in: ["sprudge","eater"], verified: true, last_verified_at: "2024-09-30", verification_source: "admin" },
  // LONDON
  { name: "Monmouth Coffee Company", slug: "monmouth-coffee-borough", lat: 51.5053, lng: -0.0906, city: "London", country: "United Kingdom", address: "2 Park St, London SE1 9AB", roaster: "Monmouth Coffee", brew_methods: ["espresso","pour-over","chemex"], vibe_tags: ["no-laptop","outdoor-seating"], google_place_id: "ChIJWR0JvGkEdkgRVpqNH1LuPzo", instagram_handle: "monmouthcoffee", website: "https://www.monmouthcoffee.co.uk/", editorial_blurb: "The original — Monmouth has been sourcing and roasting seriously since 1978, long before anyone called it third wave.", featured_in: ["sprudge","guardian","monocle"], verified: true, last_verified_at: "2024-10-20", verification_source: "admin" },
  { name: "Ozone Coffee Roasters", slug: "ozone-coffee-roasters-london", lat: 51.5242, lng: -0.0885, city: "London", country: "United Kingdom", address: "11 Leonard St, London EC2A 4AQ", roaster: "Ozone Coffee", brew_methods: ["espresso","pour-over","cold-brew","aeropress"], vibe_tags: ["roastery-on-site","laptop-friendly","dog-friendly"], instagram_handle: "ozonecoffee", website: "https://ozonecoffee.co.uk/", editorial_blurb: "A New Zealand import with a roastery in Shoreditch — the all-day menu and serious espresso make it the area's best meeting point.", featured_in: ["sprudge","timeout"], verified: true, last_verified_at: "2024-10-01", verification_source: "admin" },
  // MONTREAL
  { name: "Dispatch Coffee", slug: "dispatch-coffee-montreal", lat: 45.5236, lng: -73.5800, city: "Montreal", country: "Canada", address: "4091 Rue Saint-Denis, Montréal, QC", roaster: "Dispatch Coffee", brew_methods: ["pour-over","espresso","aeropress"], vibe_tags: ["laptop-friendly","minimalist"], instagram_handle: "dispatchcoffee", website: "https://dispatchcoffee.ca/", editorial_blurb: "Montreal's most meticulous roaster — every batch comes with full transparency on origin, process and harvest date.", featured_in: ["sprudge"], verified: true, last_verified_at: "2024-10-10", verification_source: "admin" },
  { name: "Café Névé", slug: "cafe-neve-montreal", lat: 45.5211, lng: -73.5700, city: "Montreal", country: "Canada", address: "151 Rue Rachel E, Montréal, QC", roaster: "Névé Coffee", brew_methods: ["espresso","pour-over"], vibe_tags: ["outdoor-seating","dog-friendly"], instagram_handle: "cafeneve", editorial_blurb: "A Plateau staple that perfected the balance between neighbourhood café warmth and specialty precision — the best terrace in Montreal.", featured_in: ["sprudge"], verified: true, last_verified_at: "2024-09-15", verification_source: "admin" },
  // BERLIN
  { name: "The Barn Coffee Roasters", slug: "the-barn-berlin", lat: 52.5240, lng: 13.4025, city: "Berlin", country: "Germany", address: "Auguststraße 58, 10119 Berlin", roaster: "The Barn", brew_methods: ["pour-over","espresso","aeropress"], vibe_tags: ["minimalist","no-laptop","roastery-on-site"], instagram_handle: "thebarnberlin", website: "https://www.thebarn.de/", editorial_blurb: "Berlin's most uncompromising specialty roaster — no milk, no flavoured syrups, just sourcing transparency and perfectly roasted beans.", featured_in: ["sprudge","standart","monocle"], verified: true, last_verified_at: "2024-11-01", verification_source: "admin" },
  { name: "Five Elephant", slug: "five-elephant-berlin", lat: 52.4981, lng: 13.4194, city: "Berlin", country: "Germany", address: "Reichenberger Str. 101, 10999 Berlin", roaster: "Five Elephant", brew_methods: ["espresso","pour-over","chemex"], vibe_tags: ["laptop-friendly","roastery-on-site"], instagram_handle: "fiveelephant", website: "https://www.fiveelephant.com/", editorial_blurb: "Kreuzberg's beloved café and roastery — known for their obsessive approach to single-origin espresso and iconic cheesecake.", featured_in: ["sprudge","standart"], verified: true, last_verified_at: "2024-10-15", verification_source: "admin" },
  // MEXICO CITY
  { name: "Buna Café", slug: "buna-cafe-cdmx", lat: 19.4284, lng: -99.1677, city: "Mexico City", country: "Mexico", address: "Orizaba 42, Roma Norte, 06700 CDMX", roaster: "Buna", brew_methods: ["pour-over","espresso","cold-brew"], vibe_tags: ["laptop-friendly","outdoor-seating"], instagram_handle: "bunacafe", editorial_blurb: "Roma Norte's specialty anchor — Buna sources from Oaxaca and Chiapas with direct relationships and lets the terroir speak.", featured_in: ["sprudge","atlas"], verified: true, last_verified_at: "2024-10-20", verification_source: "admin" },
  { name: "Cardinal Café", slug: "cardinal-cafe-cdmx", lat: 19.4314, lng: -99.1725, city: "Mexico City", country: "Mexico", address: "Sonora 174, Condesa, 06140 CDMX", roaster: "Multiple guest roasters", brew_methods: ["espresso","pour-over","aeropress"], vibe_tags: ["minimalist","no-laptop"], instagram_handle: "cardinal_cafe", editorial_blurb: "A spare, precise space in Condesa that treats Mexican single-origins as seriously as any Scandinavian roaster treats African lots.", featured_in: ["sprudge"], verified: true, last_verified_at: "2024-09-10", verification_source: "admin" },
  { name: "Quentin Café", slug: "quentin-cafe-cdmx", lat: 19.4193, lng: -99.1659, city: "Mexico City", country: "Mexico", address: "Sonora 6, Col. Hipódromo, 06100 CDMX", roaster: "Quentin", brew_methods: ["espresso","pour-over","chemex"], vibe_tags: ["laptop-friendly","dog-friendly"], instagram_handle: "quentincafe", editorial_blurb: "Hipódromo's relaxed specialty café where Veracruz and Oaxacan lots rotate seasonally — the filter programme is the city's most interesting.", featured_in: ["sprudge","atlas"], verified: true, last_verified_at: "2024-10-01", verification_source: "admin" },
  // SEOUL
  { name: "Fritz Coffee Company", slug: "fritz-coffee-company-seoul", lat: 37.5131, lng: 126.9946, city: "Seoul", country: "South Korea", address: "용산구 도화동 13-2, Seoul", roaster: "Fritz Coffee", brew_methods: ["espresso","pour-over","aeropress"], vibe_tags: ["roastery-on-site","laptop-friendly"], instagram_handle: "fritzcoffeecompany", website: "https://www.fritz.co.kr/", editorial_blurb: "Seoul's best roastery café — Fritz sources Korean-friendly origins and roasts them in-house with competition-level precision.", featured_in: ["sprudge","standart"], verified: true, last_verified_at: "2024-10-15", verification_source: "admin" },
  { name: "Namusairo", slug: "namusairo-seoul", lat: 37.5786, lng: 126.9717, city: "Seoul", country: "South Korea", address: "종로구 효자로 7길 13, Seoul", roaster: "Namusairo", brew_methods: ["pour-over","espresso"], vibe_tags: ["minimalist","no-laptop"], instagram_handle: "namusairo_coffee", editorial_blurb: "Hidden in the alleyways behind Gyeongbokgung Palace, Namusairo is Seoul's most tranquil specialty experience.", featured_in: ["sprudge"], verified: true, last_verified_at: "2024-09-20", verification_source: "admin" },
  // CAPE TOWN
  { name: "Truth Coffee Roasting", slug: "truth-coffee-cape-town", lat: -33.9229, lng: 18.4226, city: "Cape Town", country: "South Africa", address: "36 Buitenkant St, Cape Town, 8001", roaster: "Truth Coffee", brew_methods: ["espresso","pour-over","syphon","aeropress"], vibe_tags: ["roastery-on-site","laptop-friendly"], instagram_handle: "truthcoffee", website: "https://www.truthcoffee.com/", editorial_blurb: "Regularly voted the world's best designed café — the steampunk interior matches the intensity of their Ethiopian and Kenyan single-origins.", featured_in: ["sprudge","monocle","guardian"], verified: true, last_verified_at: "2024-10-20", verification_source: "admin" },
  { name: "Origin Coffee Roasting", slug: "origin-coffee-cape-town", lat: -33.9258, lng: 18.4103, city: "Cape Town", country: "South Africa", address: "28 Hudson St, De Waterkant, Cape Town, 8001", roaster: "Origin Coffee", brew_methods: ["espresso","pour-over","chemex","cold-brew"], vibe_tags: ["roastery-on-site","laptop-friendly","dog-friendly"], instagram_handle: "origincoffee", website: "https://www.origincoffee.co.za/", editorial_blurb: "Origin's sourcing story starts in Ethiopia and Kenya and ends at some of the most transparently traded cups in Africa.", featured_in: ["sprudge","standart"], verified: true, last_verified_at: "2024-10-01", verification_source: "admin" },
  // BUENOS AIRES
  { name: "Lattente Café", slug: "lattente-cafe-buenos-aires", lat: -34.5887, lng: -58.4244, city: "Buenos Aires", country: "Argentina", address: "Thames 1891, Palermo, Buenos Aires", roaster: "Lattente", brew_methods: ["espresso","pour-over","aeropress"], vibe_tags: ["minimalist","laptop-friendly"], instagram_handle: "lattentecafe", editorial_blurb: "The café that kicked off Buenos Aires's specialty awakening — Lattente still makes the city's most consistent espresso, years later.", featured_in: ["sprudge","atlas"], verified: true, last_verified_at: "2024-10-10", verification_source: "admin" },
  { name: "Felicidad Café", slug: "felicidad-cafe-buenos-aires", lat: -34.5930, lng: -58.4201, city: "Buenos Aires", country: "Argentina", address: "Humboldt 1585, Palermo, Buenos Aires", roaster: "Felicidad", brew_methods: ["pour-over","espresso","cold-brew"], vibe_tags: ["outdoor-seating","dog-friendly","laptop-friendly"], instagram_handle: "felicidadcafe", editorial_blurb: "A sun-drenched Palermo terrace where Argentine single-origins finally get the careful treatment they deserve.", featured_in: ["sprudge"], verified: true, last_verified_at: "2024-09-01", verification_source: "admin" },
  // PORTLAND
  { name: "Stumptown Coffee Roasters", slug: "stumptown-coffee-portland", lat: 45.5183, lng: -122.6739, city: "Portland", country: "United States", address: "4525 SE Division St, Portland, OR 97206", roaster: "Stumptown Coffee", brew_methods: ["espresso","pour-over","cold-brew","chemex"], vibe_tags: ["roastery-on-site","laptop-friendly"], google_place_id: "ChIJ_cEsFq8KlVQRy0oFT1cEFbM", instagram_handle: "stumptowncoffee", website: "https://www.stumptowncoffee.com/", editorial_blurb: "The roaster that invented direct-trade — the original Division Street location is where American specialty coffee began.", featured_in: ["sprudge","standart","ny_times","guardian"], verified: true, last_verified_at: "2024-11-01", verification_source: "admin" },
  { name: "Water Avenue Coffee", slug: "water-avenue-coffee-portland", lat: 45.5163, lng: -122.6611, city: "Portland", country: "United States", address: "1028 SE Water Ave, Portland, OR 97214", roaster: "Water Avenue Coffee", brew_methods: ["espresso","pour-over","chemex","aeropress"], vibe_tags: ["roastery-on-site","laptop-friendly","dog-friendly"], instagram_handle: "wateravenuecoffee", website: "https://wateravenuecoffee.com/", editorial_blurb: "Portland's most serious roastery-café combo on the east bank — the seasonal menu and riverside location are both worth the trip.", featured_in: ["sprudge"], verified: true, last_verified_at: "2024-10-15", verification_source: "admin" },
  { name: "Heart Coffee Roasters", slug: "heart-coffee-roasters-portland", lat: 45.5227, lng: -122.6783, city: "Portland", country: "United States", address: "2211 E Burnside St, Portland, OR 97214", roaster: "Heart Coffee", brew_methods: ["espresso","pour-over","aeropress"], vibe_tags: ["roastery-on-site","minimalist","no-laptop"], instagram_handle: "heartroasters", website: "https://heartroasters.com/", editorial_blurb: "Scandinavian sensibility meets Portland sourcing ethics — Heart's light-roast approach and austere aesthetic set the tone for a decade.", featured_in: ["sprudge","standart","monocle"], verified: true, last_verified_at: "2024-10-01", verification_source: "admin" },
  // SAN FRANCISCO
  { name: "Sightglass Coffee", slug: "sightglass-coffee-sf", lat: 37.7805, lng: -122.4060, city: "San Francisco", country: "United States", address: "270 7th St, San Francisco, CA 94103", roaster: "Sightglass Coffee", brew_methods: ["espresso","pour-over","chemex","cold-brew"], vibe_tags: ["roastery-on-site","laptop-friendly"], instagram_handle: "sightglasscoffee", website: "https://sightglasscoffee.com/", editorial_blurb: "SOMA's industrial roastery-café with a split-level interior that's as considered as the sourcing — both the light and the coffee are exceptional.", featured_in: ["sprudge","eater","infatuation"], verified: true, last_verified_at: "2024-10-20", verification_source: "admin" },
  { name: "Ritual Coffee Roasters", slug: "ritual-coffee-hayes-valley", lat: 37.7763, lng: -122.4232, city: "San Francisco", country: "United States", address: "432B Octavia St, San Francisco, CA 94102", roaster: "Ritual Coffee", brew_methods: ["espresso","pour-over","aeropress"], vibe_tags: ["laptop-friendly","outdoor-seating"], instagram_handle: "ritualcoffee", website: "https://www.ritualroasters.com/", editorial_blurb: "One of San Francisco's founding specialty roasters — the Hayes Valley location captures the neighbourhood's energy at its best.", featured_in: ["sprudge","ny_times","eater"], verified: true, last_verified_at: "2024-10-10", verification_source: "admin" },
  { name: "Verve Coffee Roasters", slug: "verve-coffee-sf", lat: 37.7854, lng: -122.4037, city: "San Francisco", country: "United States", address: "Two Embarcadero Center, San Francisco, CA 94111", roaster: "Verve Coffee", brew_methods: ["espresso","pour-over","cold-brew"], vibe_tags: ["laptop-friendly","minimalist"], instagram_handle: "vervecoffee", website: "https://www.vervecoffee.com/", editorial_blurb: "The Santa Cruz transplant brought West Coast sourcing excellence to the Embarcadero — the espresso programme is among the city's best.", featured_in: ["sprudge","infatuation"], verified: true, last_verified_at: "2024-09-15", verification_source: "admin" },
  // CHICAGO
  { name: "Intelligentsia Coffee", slug: "intelligentsia-coffee-chicago", lat: 41.9241, lng: -87.6544, city: "Chicago", country: "United States", address: "3123 N Broadway, Chicago, IL 60657", roaster: "Intelligentsia Coffee", brew_methods: ["espresso","pour-over","chemex","aeropress"], vibe_tags: ["roastery-on-site","laptop-friendly"], google_place_id: "ChIJN1t_tDeuEmsRUsoyG83frY4", instagram_handle: "intelligentsiacoffee", website: "https://www.intelligentsiacoffee.com/", editorial_blurb: "The roaster that wrote the rules of direct-trade — the original Lakeview location is still where Chicago's coffee conversation happens.", featured_in: ["sprudge","standart","ny_times","guardian"], verified: true, last_verified_at: "2024-11-01", verification_source: "admin" },
  { name: "Metric Coffee", slug: "metric-coffee-chicago", lat: 41.8854, lng: -87.6674, city: "Chicago", country: "United States", address: "2021 W Fulton St, Chicago, IL 60612", roaster: "Metric Coffee", brew_methods: ["espresso","pour-over","cold-brew","chemex"], vibe_tags: ["roastery-on-site","laptop-friendly","dog-friendly"], instagram_handle: "metriccoffee", website: "https://www.metriccoffee.com/", editorial_blurb: "West Loop's roastery answer to Intelligentsia — Metric's obsessive sourcing and industrial space attract a loyal specialty crowd.", featured_in: ["sprudge","eater"], verified: true, last_verified_at: "2024-10-15", verification_source: "admin" },
  { name: "Halfwit Coffee Roasters", slug: "halfwit-coffee-wicker-park", lat: 41.9078, lng: -87.6793, city: "Chicago", country: "United States", address: "2018 W Chicago Ave, Chicago, IL 60622", roaster: "Halfwit Coffee", brew_methods: ["espresso","pour-over","aeropress"], vibe_tags: ["laptop-friendly","outdoor-seating"], instagram_handle: "halfwitcoffee", website: "https://www.halfwitcoffee.com/", editorial_blurb: "Wicker Park's neighbourhood roastery where the rotating single-origins and DIY ethos make it the most interesting stop on the Chicago trail.", featured_in: ["sprudge"], verified: true, last_verified_at: "2024-09-20", verification_source: "admin" },
  // PARIS
  { name: "Café Lomi", slug: "cafe-lomi-paris", lat: 48.8886, lng: 2.3479, city: "Paris", country: "France", address: "3 ter Rue Marcadet, 75018 Paris", roaster: "Lomi", brew_methods: ["pour-over","espresso","chemex","cold-brew"], vibe_tags: ["roastery-on-site","laptop-friendly"], instagram_handle: "cafelomi", website: "https://www.cafelomi.com/", editorial_blurb: "Montmartre's roastery-café leading Paris's specialty revolution — sourcing transparency and in-house roasting meet Parisian calm.", featured_in: ["sprudge","monocle"], verified: true, last_verified_at: "2024-10-20", verification_source: "admin" },
  { name: "Coutume Café", slug: "coutume-cafe-paris", lat: 48.8519, lng: 2.3240, city: "Paris", country: "France", address: "47 Rue de Babylone, 75007 Paris", roaster: "Coutume", brew_methods: ["espresso","pour-over","syphon"], vibe_tags: ["laptop-friendly","minimalist"], instagram_handle: "coutumecafe", website: "https://coutumecafe.com/", editorial_blurb: "The café that proved Paris could do specialty — Coutume's 7th arrondissement location remains the benchmark for the French capital.", featured_in: ["sprudge","monocle","guardian"], verified: true, last_verified_at: "2024-10-10", verification_source: "admin" },
  { name: "Terres de Café", slug: "terres-de-cafe-paris", lat: 48.8640, lng: 2.3493, city: "Paris", country: "France", address: "36 Rue des Bourdonnais, 75001 Paris", roaster: "Terres de Café", brew_methods: ["espresso","pour-over","aeropress"], vibe_tags: ["minimalist","no-laptop"], instagram_handle: "terresdecafe", website: "https://www.terresdecafe.com/", editorial_blurb: "A Paris original focused entirely on French-spoken African origins — the sourcing narrative here is as rich as the cups.", featured_in: ["sprudge","standart"], verified: true, last_verified_at: "2024-09-15", verification_source: "admin" },
  // AMSTERDAM
  { name: "White Label Coffee", slug: "white-label-coffee-amsterdam", lat: 52.3792, lng: 4.8850, city: "Amsterdam", country: "Netherlands", address: "Jan Evertsenstraat 136, 1057 NK Amsterdam", roaster: "White Label Coffee", brew_methods: ["espresso","pour-over","aeropress"], vibe_tags: ["laptop-friendly","minimalist"], instagram_handle: "whitelabelcoffee", editorial_blurb: "Amsterdam West's specialty anchor — rotating guest roasters and a precise espresso programme in a pared-back space.", featured_in: ["sprudge"], verified: true, last_verified_at: "2024-10-15", verification_source: "admin" },
  { name: "Lot Sixty One Coffee Roasters", slug: "lot-sixty-one-amsterdam", lat: 52.3789, lng: 4.8762, city: "Amsterdam", country: "Netherlands", address: "Kinkerstraat 112, 1053 EG Amsterdam", roaster: "Lot Sixty One", brew_methods: ["pour-over","espresso","chemex","cold-brew"], vibe_tags: ["roastery-on-site","dog-friendly","outdoor-seating"], instagram_handle: "lotsixtyonecoffee", website: "https://www.lotsixtyone.com/", editorial_blurb: "A bright, dog-friendly roastery in Amsterdam West where the beans are roasted in-house and the seasonal menu is always worth reading.", featured_in: ["sprudge","timeout"], verified: true, last_verified_at: "2024-10-01", verification_source: "admin" },
  { name: "Bocca Coffee Roasters", slug: "bocca-coffee-amsterdam", lat: 52.3745, lng: 4.8924, city: "Amsterdam", country: "Netherlands", address: "Kloveniersburgwal 6, 1012 CT Amsterdam", roaster: "Bocca Coffee", brew_methods: ["espresso","pour-over","french-press"], vibe_tags: ["laptop-friendly","roastery-on-site"], instagram_handle: "boccacoffeeroasters", website: "https://www.bocca.nl/", editorial_blurb: "The oldest specialty roaster in Amsterdam with the deepest sourcing relationships — a historical address for the Dutch coffee industry.", featured_in: ["sprudge","standart"], verified: true, last_verified_at: "2024-09-10", verification_source: "admin" },
  // SYDNEY
  { name: "Single O", slug: "single-o-surry-hills", lat: -33.8898, lng: 151.2112, city: "Sydney", country: "Australia", address: "60 Reservoir St, Surry Hills NSW 2010", roaster: "Single O", brew_methods: ["espresso","pour-over","cold-brew"], vibe_tags: ["roastery-on-site","laptop-friendly"], instagram_handle: "singleocoffee", website: "https://www.singleo.com.au/", editorial_blurb: "Surry Hills' specialty pioneer with decades of direct sourcing — the takeaway window feeds the neighbourhood from 6am daily.", featured_in: ["sprudge","standart","timeout"], verified: true, last_verified_at: "2024-10-20", verification_source: "admin" },
  { name: "Sample Coffee", slug: "sample-coffee-surry-hills", lat: -33.8858, lng: 151.2096, city: "Sydney", country: "Australia", address: "118 Reservoir St, Surry Hills NSW 2010", roaster: "Sample Coffee", brew_methods: ["pour-over","espresso","aeropress","syphon"], vibe_tags: ["minimalist","no-laptop"], instagram_handle: "samplecoffee", editorial_blurb: "A precise, standing-room café where every variable has been considered — the Surry Hills block's most technically rigorous cup.", featured_in: ["sprudge"], verified: true, last_verified_at: "2024-09-15", verification_source: "admin" },
  { name: "Artificer Coffee", slug: "artificer-coffee-sydney", lat: -33.8880, lng: 151.2124, city: "Sydney", country: "Australia", address: "547 Crown St, Surry Hills NSW 2010", roaster: "Artificer Coffee", brew_methods: ["espresso","pour-over","chemex"], vibe_tags: ["standing-bar","minimalist","no-laptop"], instagram_handle: "artificercoffee", website: "https://artificer.com.au/", editorial_blurb: "World Barista Championship talent behind the bar — Artificer takes competition precision and makes it feel natural and welcoming.", featured_in: ["sprudge","standart"], verified: true, last_verified_at: "2024-10-10", verification_source: "admin" },
  // VIENNA
  { name: "Kaffeefabrik", slug: "kaffeefabrik-vienna", lat: 48.2045, lng: 16.3682, city: "Vienna", country: "Austria", address: "Favoritenstraße 4-6, 1040 Wien", roaster: "Kaffeefabrik", brew_methods: ["espresso","pour-over","chemex","aeropress"], vibe_tags: ["roastery-on-site","laptop-friendly"], instagram_handle: "kaffeefabrik", website: "https://kaffeefabrik.at/", editorial_blurb: "The roastery that showed Vienna it could love both its historic café tradition and modern specialty at the same time.", featured_in: ["sprudge","standart"], verified: true, last_verified_at: "2024-10-15", verification_source: "admin" },
  { name: "Balthasar Kaffee", slug: "balthasar-kaffee-vienna", lat: 48.2118, lng: 16.3614, city: "Vienna", country: "Austria", address: "Neubaugasse 64, 1070 Wien", roaster: "Balthasar Kaffee", brew_methods: ["espresso","pour-over"], vibe_tags: ["minimalist","laptop-friendly"], instagram_handle: "balthasarkaffee", editorial_blurb: "Neubau's quietest specialty gem — Balthasar sources with care and brews with a precision that honours both the bean and the tradition.", featured_in: ["sprudge"], verified: true, last_verified_at: "2024-09-20", verification_source: "admin" },
  { name: "Kaffee Alt Wien", slug: "kaffee-alt-wien-vienna", lat: 48.2078, lng: 16.3733, city: "Vienna", country: "Austria", address: "Bäckerstraße 9, 1010 Wien", roaster: "Multiple guest roasters", brew_methods: ["espresso","pour-over","french-press"], vibe_tags: ["laptop-friendly","outdoor-seating"], instagram_handle: "kaffeealtwien", editorial_blurb: "A Viennese institution that bridges the coffeehouse tradition and specialty precision — old Vienna meets new at the first district.", featured_in: ["sprudge","monocle"], verified: true, last_verified_at: "2024-10-01", verification_source: "admin" },
  // STOCKHOLM
  { name: "Drop Coffee Roasters", slug: "drop-coffee-roasters-stockholm", lat: 59.3163, lng: 18.0545, city: "Stockholm", country: "Sweden", address: "Wollmar Yxkullsgatan 10, 118 50 Stockholm", roaster: "Drop Coffee", brew_methods: ["pour-over","espresso","aeropress","chemex"], vibe_tags: ["roastery-on-site","laptop-friendly","minimalist"], instagram_handle: "dropcoffee", website: "https://www.dropcoffee.se/", editorial_blurb: "Södermalm's most decorated specialty roaster — Drop's competition pedigree is matched by an approachability that welcomes all.", featured_in: ["sprudge","standart","monocle"], verified: true, last_verified_at: "2024-10-20", verification_source: "admin" },
  { name: "Johan & Nyström", slug: "johan-nystrom-stockholm", lat: 59.3154, lng: 18.0735, city: "Stockholm", country: "Sweden", address: "Swedenborgsgatan 7, 118 48 Stockholm", roaster: "Johan & Nyström", brew_methods: ["espresso","pour-over","chemex","cold-brew"], vibe_tags: ["roastery-on-site","laptop-friendly","dog-friendly"], instagram_handle: "johanagnystrom", website: "https://www.johanochnysstrom.se/", editorial_blurb: "The Scandinavian specialty pioneer that exports roasts across Europe — the flagship café is still the region's best single address.", featured_in: ["sprudge","standart","guardian"], verified: true, last_verified_at: "2024-10-10", verification_source: "admin" },
  { name: "Koppi Coffee Roasters", slug: "koppi-coffee-stockholm", lat: 59.3148, lng: 18.0702, city: "Stockholm", country: "Sweden", address: "Hornsgatan 46, 118 21 Stockholm", roaster: "Koppi Coffee", brew_methods: ["pour-over","espresso","aeropress"], vibe_tags: ["minimalist","no-laptop"], instagram_handle: "koppicoffee", editorial_blurb: "The roaster that champions women's coffee — Koppi's sourcing goes deeper than most and the purity of the cup reflects it.", featured_in: ["sprudge","standart"], verified: true, last_verified_at: "2024-09-15", verification_source: "admin" },
  // LISBON
  { name: "Hello Kristof", slug: "hello-kristof-lisbon", lat: 38.7166, lng: -9.1391, city: "Lisbon", country: "Portugal", address: "Rua de Santo António da Glória 18, 1250-172 Lisboa", roaster: "Multiple guest roasters", brew_methods: ["pour-over","espresso","aeropress"], vibe_tags: ["minimalist","laptop-friendly"], instagram_handle: "hellokristof", editorial_blurb: "The café that introduced Lisbon to specialty — small, focused, and still setting the standard years after opening.", featured_in: ["sprudge"], verified: true, last_verified_at: "2024-10-15", verification_source: "admin" },
  { name: "Copenhagen Coffee Lab", slug: "copenhagen-coffee-lab-lisbon", lat: 38.7140, lng: -9.1478, city: "Lisbon", country: "Portugal", address: "Rua Nova da Piedade 10, 1200-298 Lisboa", roaster: "Copenhagen Coffee Lab", brew_methods: ["espresso","pour-over","cold-brew"], vibe_tags: ["laptop-friendly","outdoor-seating"], instagram_handle: "cphcoffeelab", editorial_blurb: "Príncipe Real's Scandinavian-influenced gem — Danish sourcing ethics in a sun-drenched Lisbon courtyard.", featured_in: ["sprudge","timeout"], verified: true, last_verified_at: "2024-10-01", verification_source: "admin" },
  { name: "Fábrica Coffee Roasters", slug: "fabrica-coffee-roasters-lisbon", lat: 38.7179, lng: -9.1374, city: "Lisbon", country: "Portugal", address: "Rua das Portas de Santo Antão 136, 1150-268 Lisboa", roaster: "Fábrica Coffee", brew_methods: ["espresso","pour-over","chemex","aeropress"], vibe_tags: ["roastery-on-site","laptop-friendly"], instagram_handle: "fabricacoffeeroasters", website: "https://fabricacoffeeroasters.com/", editorial_blurb: "Lisbon's first specialty roastery — Fábrica built the infrastructure for Portugal's coffee scene and keeps raising its own bar.", featured_in: ["sprudge","standart"], verified: true, last_verified_at: "2024-09-20", verification_source: "admin" },
  // BARCELONA
  { name: "Nomad Coffee", slug: "nomad-coffee-barcelona", lat: 41.3854, lng: 2.1890, city: "Barcelona", country: "Spain", address: "Passatge Sert 12, 08003 Barcelona", roaster: "Nomad Coffee", brew_methods: ["espresso","pour-over","chemex","aeropress"], vibe_tags: ["roastery-on-site","minimalist","laptop-friendly"], instagram_handle: "nomadcoffeelab", website: "https://www.nomadcoffee.es/", editorial_blurb: "Barcelona's most awarded roaster — El Born location brings world-competition level precision to a neighbourhood terrace audience.", featured_in: ["sprudge","standart","monocle"], verified: true, last_verified_at: "2024-10-20", verification_source: "admin" },
  { name: "Syra Coffee", slug: "syra-coffee-barcelona", lat: 41.3890, lng: 2.1624, city: "Barcelona", country: "Spain", address: "Carrer del Consell de Cent 415, 08009 Barcelona", roaster: "Syra Coffee", brew_methods: ["espresso","pour-over","cold-brew"], vibe_tags: ["laptop-friendly","minimalist"], instagram_handle: "syracoffee", website: "https://www.syracoffee.com/", editorial_blurb: "Eixample's design-conscious specialty café with in-house roasting — the light and the coffee are both carefully calibrated.", featured_in: ["sprudge","timeout"], verified: true, last_verified_at: "2024-10-10", verification_source: "admin" },
  { name: "Satan's Coffee Corner", slug: "satans-coffee-barcelona", lat: 41.3836, lng: 2.1722, city: "Barcelona", country: "Spain", address: "Carrer de l'Arc de Sant Ramon del Call 11, 08002 Barcelona", roaster: "Satan's Coffee", brew_methods: ["espresso","pour-over","aeropress"], vibe_tags: ["standing-bar","no-laptop","minimalist"], instagram_handle: "satanscoffee", editorial_blurb: "Gothic Quarter's smallest and loudest specialty statement — the name is the joke, the espresso is entirely serious.", featured_in: ["sprudge","eater"], verified: true, last_verified_at: "2024-09-15", verification_source: "admin" },
  // SINGAPORE
  { name: "Papa Palheta", slug: "papa-palheta-singapore", lat: 1.2928, lng: 103.7877, city: "Singapore", country: "Singapore", address: "150 Tyrwhitt Rd, Singapore 207563", roaster: "Papa Palheta", brew_methods: ["espresso","pour-over","cold-brew"], vibe_tags: ["roastery-on-site","laptop-friendly","dog-friendly"], instagram_handle: "papapalheta", website: "https://papapalheta.com/", editorial_blurb: "The roaster that built Singapore's specialty scene — Papa Palheta's sourcing trips and transparent practices set the standard.", featured_in: ["sprudge","standart"], verified: true, last_verified_at: "2024-10-15", verification_source: "admin" },
  { name: "Nylon Coffee Roasters", slug: "nylon-coffee-roasters-singapore", lat: 1.3003, lng: 103.8205, city: "Singapore", country: "Singapore", address: "4 Everton Park, #01-40, Singapore 080004", roaster: "Nylon Coffee", brew_methods: ["pour-over","espresso","aeropress","chemex"], vibe_tags: ["minimalist","laptop-friendly"], instagram_handle: "nyloncoffee", website: "https://nyloncoffee.sg/", editorial_blurb: "Everton Park's most dedicated roastery — Nylon's obsession with Kenyan and Ethiopian lots is matched by obsessive extraction protocols.", featured_in: ["sprudge","monocle"], verified: true, last_verified_at: "2024-10-01", verification_source: "admin" },
  { name: "Common Man Coffee Roasters", slug: "common-man-coffee-singapore", lat: 1.2999, lng: 103.8393, city: "Singapore", country: "Singapore", address: "22 Martin Rd, Singapore 239058", roaster: "Common Man Coffee", brew_methods: ["espresso","pour-over","cold-brew","chemex"], vibe_tags: ["laptop-friendly","outdoor-seating","dog-friendly"], instagram_handle: "commonmancoffeeroasters", website: "https://www.commonmancoffeeroasters.com/", editorial_blurb: "Robertson Quay's specialty anchor with a training programme that shapes the region's barista talent — the flat white is reference-grade.", featured_in: ["sprudge","timeout"], verified: true, last_verified_at: "2024-09-20", verification_source: "admin" },
  // TAIPEI
  { name: "Fika Fika Café", slug: "fika-fika-cafe-taipei", lat: 25.0484, lng: 121.5446, city: "Taipei", country: "Taiwan", address: "天津街11巷8號, Zhongshan District, Taipei", roaster: "Fika Fika Coffee", brew_methods: ["pour-over","espresso","syphon","aeropress"], vibe_tags: ["minimalist","laptop-friendly"], instagram_handle: "fikafika_cafe", website: "https://www.fikafika.com.tw/", editorial_blurb: "Nordic Coffee Challenge champion James Chen's café — the level of extraction science applied to Taiwanese single-origins is unmatched.", featured_in: ["sprudge","standart","monocle"], verified: true, last_verified_at: "2024-10-20", verification_source: "admin" },
  { name: "Rufous Coffee", slug: "rufous-coffee-taipei", lat: 25.0461, lng: 121.5462, city: "Taipei", country: "Taiwan", address: "南京西路233巷4弄4號, Zhongshan District, Taipei", roaster: "Rufous Coffee", brew_methods: ["pour-over","espresso","chemex"], vibe_tags: ["minimalist","no-laptop"], instagram_handle: "rufouscoffee", editorial_blurb: "Taipei's most thoughtful pour-over counter — Rufous treats every variable from grind size to water temperature as a creative decision.", featured_in: ["sprudge"], verified: true, last_verified_at: "2024-10-01", verification_source: "admin" },
  { name: "Gabee", slug: "gabee-taipei", lat: 25.0574, lng: 121.5264, city: "Taipei", country: "Taiwan", address: "民生西路31巷12弄7號, Datong District, Taipei", roaster: "Gabee", brew_methods: ["espresso","pour-over","aeropress"], vibe_tags: ["laptop-friendly","dog-friendly"], instagram_handle: "gabeecoffee", editorial_blurb: "World Barista Championship finalist Berg Wu's café — a decade on, still one of Taipei's most influential specialty addresses.", featured_in: ["sprudge","standart"], verified: true, last_verified_at: "2024-09-15", verification_source: "admin" },
  // SÃO PAULO
  { name: "Isso é Café!", slug: "isso-e-cafe-sao-paulo", lat: -23.5630, lng: -46.6573, city: "São Paulo", country: "Brazil", address: "R. Mateus Grou, 180 - Pinheiros, São Paulo", roaster: "Isso é Café!", brew_methods: ["pour-over","espresso","aeropress","cold-brew"], vibe_tags: ["laptop-friendly","dog-friendly"], instagram_handle: "issoe.cafe", editorial_blurb: "Pinheiros' specialty pioneer making the case for Brazilian single-origins — finally, world-class lots treated with world-class care.", featured_in: ["sprudge","atlas"], verified: true, last_verified_at: "2024-10-15", verification_source: "admin" },
  { name: "Coffee Lab", slug: "coffee-lab-sao-paulo", lat: -23.5582, lng: -46.6649, city: "São Paulo", country: "Brazil", address: "R. Fradique Coutinho, 1340 - Vila Madalena, São Paulo", roaster: "Coffee Lab", brew_methods: ["pour-over","espresso","syphon","chemex"], vibe_tags: ["roastery-on-site","laptop-friendly","minimalist"], instagram_handle: "coffeelab_br", website: "https://www.coffeelab.com.br/", editorial_blurb: "World Brewer's Cup champion Isabela Raposeiras' roastery — the most technically advanced café in South America.", featured_in: ["sprudge","standart","ny_times"], verified: true, last_verified_at: "2024-10-20", verification_source: "admin" },
  { name: "Nutty Bavarian Specialty Coffee", slug: "nutty-bavarian-specialty-coffee-sp", lat: -23.5540, lng: -46.6610, city: "São Paulo", country: "Brazil", address: "R. Wisard, 489 - Vila Madalena, São Paulo", roaster: "Nutty Bavarian Coffee", brew_methods: ["espresso","pour-over","cold-brew"], vibe_tags: ["outdoor-seating","dog-friendly","laptop-friendly"], instagram_handle: "nuttybavarian.sp", editorial_blurb: "Vila Madalena's most beloved neighbourhood café — Nutty Bavarian sources within São Paulo state and makes the terroir taste like home.", featured_in: ["sprudge"], verified: true, last_verified_at: "2024-09-10", verification_source: "admin" },
  // ISTANBUL
  { name: "Kronotrop", slug: "kronotrop-istanbul", lat: 41.0279, lng: 28.9779, city: "Istanbul", country: "Turkey", address: "Kumbaracı Yokuşu 54A, Beyoğlu, 34433 İstanbul", roaster: "Kronotrop", brew_methods: ["pour-over","espresso","aeropress","chemex"], vibe_tags: ["minimalist","laptop-friendly"], instagram_handle: "kronotrop", website: "https://www.kronotrop.com.tr/", editorial_blurb: "Cihangir's specialty pioneer — Kronotrop built Istanbul's third wave infrastructure through sourcing transparency and relentless quality.", featured_in: ["sprudge","standart"], verified: true, last_verified_at: "2024-10-15", verification_source: "admin" },
  { name: "Petra Roasting Co.", slug: "petra-roasting-istanbul", lat: 41.0362, lng: 28.9847, city: "Istanbul", country: "Turkey", address: "Katip Çelebi Mah., Hamalbaşı Cd. 4/A, Beyoğlu, İstanbul", roaster: "Petra Roasting", brew_methods: ["espresso","pour-over","cold-brew"], vibe_tags: ["roastery-on-site","laptop-friendly","outdoor-seating"], instagram_handle: "petraroasting", editorial_blurb: "Beyoğlu's roastery in a converted building — Petra sources from Ethiopia and Yemen with a reverence for origin that's rare anywhere.", featured_in: ["sprudge"], verified: true, last_verified_at: "2024-10-01", verification_source: "admin" },
  { name: "MOC Coffee", slug: "moc-coffee-istanbul", lat: 41.0430, lng: 29.0080, city: "Istanbul", country: "Turkey", address: "Kuruçeşme Cad. 59A, Beşiktaş, 34345 İstanbul", roaster: "MOC Coffee", brew_methods: ["espresso","pour-over","aeropress"], vibe_tags: ["outdoor-seating","dog-friendly","laptop-friendly"], instagram_handle: "moccoffee_tr", editorial_blurb: "A Bosphorus-view specialty café where the sourcing story spans Ethiopia to Colombia — the view is the backdrop, not the attraction.", featured_in: ["sprudge","timeout"], verified: true, last_verified_at: "2024-09-15", verification_source: "admin" },
  // NAIROBI
  { name: "Nairobi Java House", slug: "nairobi-java-house-westlands", lat: -1.2669, lng: 36.8064, city: "Nairobi", country: "Kenya", address: "Westlands, Nairobi 00100", roaster: "Java House", brew_methods: ["espresso","pour-over","french-press"], vibe_tags: ["laptop-friendly","outdoor-seating"], google_place_id: "ChIJiXSNj6oULxgRrWuvBkK21nM", instagram_handle: "nairobijava", website: "https://www.nairobijavahouse.com/", editorial_blurb: "The original Nairobi specialty anchor — started when third wave was barely a concept and still sourcing Kenya's best AA lots direct.", featured_in: ["sprudge","guardian"], verified: true, last_verified_at: "2024-10-15", verification_source: "admin" },
  { name: "Dormans Coffee", slug: "dormans-coffee-nairobi", lat: -1.2832, lng: 36.8178, city: "Nairobi", country: "Kenya", address: "Upper Hill, Nairobi 00100", roaster: "Dormans Coffee", brew_methods: ["espresso","pour-over","aeropress","cold-brew"], vibe_tags: ["roastery-on-site","laptop-friendly"], instagram_handle: "dormanscoffee", website: "https://www.dormanscoffee.com/", editorial_blurb: "Kenya's oldest specialty roaster, roasting origin lots in the country where they grow — an irreplaceable part of the Nairobi coffee story.", featured_in: ["sprudge","atlas"], verified: true, last_verified_at: "2024-10-01", verification_source: "admin" },
  { name: "Brew Bistro & Lounge", slug: "brew-bistro-nairobi", lat: -1.2792, lng: 36.8222, city: "Nairobi", country: "Kenya", address: "Ngong Rd, Kilimani, Nairobi", roaster: "Brew Bistro", brew_methods: ["espresso","pour-over","chemex"], vibe_tags: ["outdoor-seating","dog-friendly","laptop-friendly"], instagram_handle: "brewnairobi", editorial_blurb: "Kilimani's café where single-farm Kenyan lots are brewed with the reverence they deserve — steps from where the beans were sorted.", featured_in: ["sprudge"], verified: true, last_verified_at: "2024-09-10", verification_source: "admin" },
  // HO CHI MINH CITY
  { name: "The Workshop Coffee", slug: "the-workshop-coffee-hcmc", lat: 10.7769, lng: 106.7009, city: "Ho Chi Minh City", country: "Vietnam", address: "27 Ngô Đức Kế, Bến Nghé, Quận 1, HCMC", roaster: "The Workshop Coffee", brew_methods: ["pour-over","espresso","aeropress","cold-brew"], vibe_tags: ["laptop-friendly","minimalist"], instagram_handle: "theworkshop.coffee", editorial_blurb: "District 1's most serious specialty address — The Workshop treats Vietnamese arabica with the same care Scandinavians give Ethiopian lots.", featured_in: ["sprudge","atlas","timeout"], verified: true, last_verified_at: "2024-10-20", verification_source: "admin" },
  { name: "Shin Coffee", slug: "shin-coffee-hcmc", lat: 10.7891, lng: 106.6964, city: "Ho Chi Minh City", country: "Vietnam", address: "93 Nguyễn Văn Thủ, Đa Kao, Quận 1, HCMC", roaster: "Shin Coffee", brew_methods: ["pour-over","espresso","chemex"], vibe_tags: ["minimalist","outdoor-seating"], instagram_handle: "shincoffeevn", editorial_blurb: "A rooftop garden café in Đa Kao where Vietnamese single-origins are brewed with pour-over precision and served with genuine hospitality.", featured_in: ["sprudge"], verified: true, last_verified_at: "2024-10-01", verification_source: "admin" },
  { name: "Công Cà Phê", slug: "cong-ca-phe-hcmc", lat: 10.7811, lng: 106.7013, city: "Ho Chi Minh City", country: "Vietnam", address: "96 Cao Bá Quát, Bến Nghé, Quận 1, HCMC", roaster: "Công Cà Phê", brew_methods: ["espresso","cold-brew","french-press"], vibe_tags: ["outdoor-seating","dog-friendly","laptop-friendly"], instagram_handle: "congcaphe", editorial_blurb: "HCMC's most distinctive café chain, but the original District 1 location is where the cà phê trứng (egg coffee) ritual is at its best.", featured_in: ["sprudge","guardian","timeout"], verified: true, last_verified_at: "2024-09-15", verification_source: "admin" },
  // OSAKA
  { name: "Kurasu Kyoto × Fuglen", slug: "kurasu-osaka", lat: 34.7024, lng: 135.4959, city: "Osaka", country: "Japan", address: "1-16-20 Kitahama, Chuo-ku, Osaka", roaster: "Kurasu", brew_methods: ["pour-over","espresso","aeropress"], vibe_tags: ["minimalist","laptop-friendly"], instagram_handle: "kurasu.kyoto", website: "https://kurasu.kyoto/", editorial_blurb: "Kurasu's Osaka outpost brings Tokyo-level specialty precision to Kitahama's financial district — the cupping menu rotates weekly.", featured_in: ["sprudge"], verified: true, last_verified_at: "2024-10-15", verification_source: "admin" },
  { name: "WEEKENDERS COFFEE Roastery", slug: "weekenders-coffee-osaka", lat: 34.6960, lng: 135.5040, city: "Osaka", country: "Japan", address: "1-2-21 Sakaisuji-honmachi, Chuo-ku, Osaka", roaster: "Weekenders Coffee", brew_methods: ["pour-over","espresso","chemex","cold-brew"], vibe_tags: ["roastery-on-site","minimalist"], instagram_handle: "weekenderscoffee", editorial_blurb: "Osaka's standout roastery in Honmachi — Weekenders sources pan-Asian origins and roasts them with a light, expressive hand.", featured_in: ["sprudge","standart"], verified: true, last_verified_at: "2024-10-01", verification_source: "admin" },
  { name: "% Arabica Osaka", slug: "arabica-osaka-kitahama", lat: 34.6919, lng: 135.5100, city: "Osaka", country: "Japan", address: "2-1-43 Nanba, Chuo-ku, Osaka", roaster: "% Arabica", brew_methods: ["espresso","pour-over","cold-brew"], vibe_tags: ["minimalist","standing-bar","no-laptop"], instagram_handle: "arabica.coffee", website: "https://arabica.coffee/", editorial_blurb: "The world's most aesthetically considered café chain — the Osaka location delivers the brand's flawless espresso with the city's own warmth.", featured_in: ["sprudge","monocle","timeout"], verified: true, last_verified_at: "2024-09-20", verification_source: "admin" },
];

const SEED_CITIES = [
  { id: 'city-1', name: 'Tokyo', country: 'Japan', lat: 35.6762, lng: 139.6503, slug: 'tokyo', cafe_count: 3, city_blurb: 'Tokyo has elevated coffee into an art form — precision brewing, flawless service, and a density of world-class cafés that rivals any city on earth.' },
  { id: 'city-2', name: 'Copenhagen', country: 'Denmark', lat: 55.6761, lng: 12.5683, slug: 'copenhagen', cafe_count: 3, city_blurb: "Scandinavia's coffee capital leads Europe on sourcing ethics and light-roast technique — every cup here feels considered." },
  { id: 'city-3', name: 'Melbourne', country: 'Australia', lat: -37.8136, lng: 144.9631, slug: 'melbourne', cafe_count: 3, city_blurb: "Melbourne's café culture is a civic institution — world-class flat whites and a roasting scene that exports talent globally." },
  { id: 'city-4', name: 'New York City', country: 'United States', lat: 40.7128, lng: -74.0060, slug: 'new-york-city', cafe_count: 3, city_blurb: "New York's specialty coffee scene is borough-by-borough diverse — Brooklyn leads on craft, Manhattan on volume, and the competition makes everyone better." },
  { id: 'city-5', name: 'London', country: 'United Kingdom', lat: 51.5074, lng: -0.1278, slug: 'london', cafe_count: 2, city_blurb: "London transformed from espresso-resistant to one of the world's most exciting coffee cities in a single decade — the east side is still the epicenter." },
  { id: 'city-6', name: 'Montreal', country: 'Canada', lat: 45.5017, lng: -73.5673, slug: 'montreal', cafe_count: 2, city_blurb: "Montreal's bilingual café culture and Québécois identity produce some of North America's most distinctive specialty shops." },
  { id: 'city-7', name: 'Berlin', country: 'Germany', lat: 52.5200, lng: 13.4050, slug: 'berlin', cafe_count: 2, city_blurb: "Berlin's third wave arrived with characteristic intensity — precise roasting, opinionated baristas, and spaces that double as cultural institutions." },
  { id: 'city-8', name: 'Mexico City', country: 'Mexico', lat: 19.4326, lng: -99.1332, slug: 'mexico-city', cafe_count: 3, city_blurb: 'CDMX is rewriting what Mexican coffee means — local Oaxacan and Veracruz single-origins are finally getting the treatment they deserve.' },
  { id: 'city-9', name: 'Seoul', country: 'South Korea', lat: 37.5665, lng: 126.9780, slug: 'seoul', cafe_count: 2, city_blurb: "Seoul's café density is unmatched anywhere — specialty coffee thrives alongside traditional tea culture and the aesthetics are always exceptional." },
  { id: 'city-10', name: 'Cape Town', country: 'South Africa', lat: -33.9249, lng: 18.4241, slug: 'cape-town', cafe_count: 2, city_blurb: "Cape Town's proximity to East African origins gives it an unfair advantage — roasters here work with some of the freshest beans on earth." },
  { id: 'city-11', name: 'Buenos Aires', country: 'Argentina', lat: -34.6037, lng: -58.3816, slug: 'buenos-aires', cafe_count: 2, city_blurb: "Buenos Aires is in the middle of a specialty coffee awakening — Palermo's independent roasteries are making the city's traditional café culture look again." },
  { id: 'city-12', name: 'Portland', country: 'United States', lat: 45.5051, lng: -122.6750, slug: 'portland', cafe_count: 3, city_blurb: "Portland's coffee heritage runs deep — this is where the American third wave started, and the roasting culture it built still sets global standards." },
  { id: 'city-13', name: 'San Francisco', country: 'United States', lat: 37.7749, lng: -122.4194, slug: 'san-francisco', cafe_count: 3, city_blurb: "San Francisco's specialty scene is as opinionated as the city itself — SOMA roasteries and Mission standing bars set the West Coast benchmark." },
  { id: 'city-14', name: 'Chicago', country: 'United States', lat: 41.8781, lng: -87.6298, slug: 'chicago', cafe_count: 3, city_blurb: "Chicago's third-wave story starts with Intelligentsia and keeps getting better — the West Loop and Wicker Park are now among America's most exciting coffee corridors." },
  { id: 'city-15', name: 'Paris', country: 'France', lat: 48.8566, lng: 2.3522, slug: 'paris', cafe_count: 3, city_blurb: "Paris resisted specialty coffee and then embraced it completely — the 10th and 18th arrondissements are now home to some of Europe's most exciting new roasters." },
  { id: 'city-16', name: 'Amsterdam', country: 'Netherlands', lat: 52.3676, lng: 4.9041, slug: 'amsterdam', cafe_count: 3, city_blurb: "Amsterdam's canal-side café culture found a new gear when specialty roasters arrived — the Jordaan and Amsterdam West are the places to start." },
  { id: 'city-17', name: 'Sydney', country: 'Australia', lat: -33.8688, lng: 151.2093, slug: 'sydney', cafe_count: 3, city_blurb: "Sydney's Surry Hills is Australia's most concentrated specialty coffee district — three world-class roasteries within walking distance of each other." },
  { id: 'city-18', name: 'Vienna', country: 'Austria', lat: 48.2082, lng: 16.3738, slug: 'vienna', cafe_count: 3, city_blurb: 'Vienna perfected café culture centuries ago and is now adding specialty precision to the tradition — the combination is unlike anywhere else in Europe.' },
  { id: 'city-19', name: 'Stockholm', country: 'Sweden', lat: 59.3293, lng: 18.0686, slug: 'stockholm', cafe_count: 3, city_blurb: "Stockholm's Södermalm roasteries have shaped how all of Scandinavia thinks about light roasting and ethical sourcing — the world is still catching up." },
  { id: 'city-20', name: 'Lisbon', country: 'Portugal', lat: 38.7169, lng: -9.1399, slug: 'lisbon', cafe_count: 3, city_blurb: "Lisbon's specialty scene arrived late but moved fast — Chiado and Príncipe Real are now home to some of the most interesting cafés in southern Europe." },
  { id: 'city-21', name: 'Barcelona', country: 'Spain', lat: 41.3851, lng: 2.1734, slug: 'barcelona', cafe_count: 3, city_blurb: "Barcelona's specialty coffee scene is as design-conscious as the city itself — Poblenou's roasteries and El Born's bars are raising the bar for all of Spain." },
  { id: 'city-22', name: 'Singapore', country: 'Singapore', lat: 1.3521, lng: 103.8198, slug: 'singapore', cafe_count: 3, city_blurb: "Singapore's coffee culture runs from hawker-centre kopi to competition-level pour-overs — the specialty scene here is among Asia's most sophisticated." },
  { id: 'city-23', name: 'Taipei', country: 'Taiwan', lat: 25.0330, lng: 121.5654, slug: 'taipei', cafe_count: 3, city_blurb: "Taipei's barista talent and roasting culture are world-class — world competition champions run cafés here and the density of quality is quietly remarkable." },
  { id: 'city-24', name: 'São Paulo', country: 'Brazil', lat: -23.5505, lng: -46.6333, slug: 'sao-paulo', cafe_count: 3, city_blurb: "The world's largest coffee-producing country is finally drinking its own best beans — São Paulo's Vila Madalena and Pinheiros lead that transformation." },
  { id: 'city-25', name: 'Istanbul', country: 'Turkey', lat: 41.0082, lng: 28.9784, slug: 'istanbul', cafe_count: 3, city_blurb: "Istanbul's specialty scene sits at the crossroads of coffee history — Cihangir and Karaköy roasters are building something entirely new on ancient grounds." },
  { id: 'city-26', name: 'Nairobi', country: 'Kenya', lat: -1.2921, lng: 36.8219, slug: 'nairobi', cafe_count: 3, city_blurb: "Nairobi is the world's most exciting origin city for coffee — drinking single-farm Kenyan lots here, where they're grown and roasted, is irreplaceable." },
  { id: 'city-27', name: 'Ho Chi Minh City', country: 'Vietnam', lat: 10.8231, lng: 106.6297, slug: 'ho-chi-minh-city', cafe_count: 3, city_blurb: "Ho Chi Minh City has one of the world's oldest café cultures and is now adding specialty precision to it — District 1's third-wave scene is worth the trip alone." },
  { id: 'city-28', name: 'Osaka', country: 'Japan', lat: 34.6937, lng: 135.5023, slug: 'osaka', cafe_count: 3, city_blurb: "Osaka's coffee scene is Tokyo's more relaxed sibling — Kitahama and Namba have quietly built a specialty culture that rewards the traveler who looks beyond ramen." },
];

async function main() {
  console.log(`Connecting to ${SUPABASE_URL}…`);

  // ── 1. Upsert cities (upsert on slug) ────────────────────────────────────
  console.log(`Upserting ${SEED_CITIES.length} cities…`);
  const { error: cityError } = await supabase
    .from("cities")
    .upsert(
      SEED_CITIES.map(c => ({
        name: c.name,
        country: c.country,
        lat: c.lat,
        lng: c.lng,
        slug: c.slug,
        cafe_count: c.cafe_count,
        city_blurb: c.city_blurb,
      })),
      { onConflict: "slug" }
    );

  if (cityError) {
    console.error("City upsert failed:", cityError.message);
    process.exit(1);
  }
  console.log("✓ Cities done");

  // ── 2. Upsert cafes ───────────────────────────────────────────────────────
  const cafes = rawCafes.map((cafe) => ({
    name: cafe.name,
    slug: cafe.slug,
    lat: cafe.lat,
    lng: cafe.lng,
    city: cafe.city,
    country: cafe.country,
    address: cafe.address,
    roaster: cafe.roaster ?? null,
    brew_methods: cafe.brew_methods,
    vibe_tags: cafe.vibe_tags,
    google_place_id: cafe.google_place_id ?? null,
    instagram_handle: cafe.instagram_handle ?? null,
    website: cafe.website ?? null,
    editorial_blurb: cafe.editorial_blurb,
    featured_in: cafe.featured_in,
    verified: cafe.verified,
    last_verified_at: cafe.last_verified_at ? new Date(cafe.last_verified_at).toISOString() : null,
    verification_source: cafe.verification_source ?? null,
    permanently_closed: false,
    sponsored: false,
    verified_paid: false,
  }));

  console.log(`Upserting ${cafes.length} cafes…`);
  const BATCH = 25;
  for (let i = 0; i < cafes.length; i += BATCH) {
    const batch = cafes.slice(i, i + BATCH);
    const { error } = await supabase
      .from("cafes")
      .upsert(batch, { onConflict: "slug" });
    if (error) {
      console.error(`Cafe batch ${i / BATCH + 1} failed:`, error.message);
      process.exit(1);
    }
    console.log(`  batch ${i / BATCH + 1}/${Math.ceil(cafes.length / BATCH)} ✓`);
  }
  console.log("✓ Cafes done");

  // ── 3. Insert aggregate scores ────────────────────────────────────────────
  console.log("Fetching cafe UUIDs for aggregate scores…");
  const { data: cafeRows, error: fetchErr } = await supabase
    .from("cafes")
    .select("id, slug");
  if (fetchErr || !cafeRows) {
    console.error("Could not fetch cafe IDs:", fetchErr?.message);
    process.exit(1);
  }
  const slugToId = Object.fromEntries(cafeRows.map(r => [r.slug, r.id]));

  const scores = rawCafes
    .map(cafe => {
      const id = slugToId[cafe.slug];
      if (!id) return null;
      return {
        cafe_id: id,
        third_wave_score: scoreRaw(cafe),
        overall_rating: 4.2 + Math.random() * 0.7,
        review_count: 50 + Math.floor(Math.random() * 200),
      };
    })
    .filter(Boolean);

  const { error: scoreError } = await supabase
    .from("aggregate_scores")
    .upsert(scores as object[], { onConflict: "cafe_id" });
  if (scoreError) {
    console.error("Scores upsert failed:", scoreError.message);
    process.exit(1);
  }
  console.log("✓ Aggregate scores done");

  console.log(`\n✅ Seeded ${SEED_CITIES.length} cities, ${cafes.length} cafes, and ${scores.length} scores into Supabase.`);
}

main().catch(err => { console.error(err); process.exit(1); });
